Received: from F29.Tymnet by D35.Tymnet; Mon, 24 Aug 87 17:30:09 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 24 Aug 87 14:28:15 PDT
Return-path: <TYMPLN.HQ@EMSTXS.Ontyme.Tymnet> 
From: TYMPLN.HQ@EMSTXS.Ontyme.Tymnet 
Date: 24 AUG 87 19:56:15 
To: TXSSUP@D35.Tymnet 
Message-id: M14190@Ontyme.Tymnet 
Subject: ACCESS CHARGE SEMINAR 

                           T Y M N E T

           MC DONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                       M E M O R A N D U M


   DATE:  AUGUST 24, 1987

     TO:  ALL TYMNET MANAGERS & ALL SALES

   FROM:  JO AN COUCHE

SUBJECT:  ACCESS CHARGE SEMINAR
__________________________________________________________________




               * * ACCESS CHARGE UPDATE * *



Access charges -

  What are they?

  Why does the FCC want to impose them on Tymnet?

  How will they impact our business?

  What can we do to stop the FCC from imposing these charges?


These  questions  and  many more will be answered at  the  Access
Charge  Seminar  on  Thursday,  August 27 9:00-11:00  AM  in  the
Training Room at Valley Green Drive

Please plan to attend.  Contact Jo An Couche at (408) 446-7154 if
you have questions.
Received: from F29.Tymnet by D35.Tymnet; Mon, 31 Aug 87 11:44:10 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 31 Aug 87 11:36:15 PDT
Return-path: <IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet> 
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 31 AUG 87 19:34:00 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A07141@Ontyme.Tymnet 
Subject: System D-27 Memo 
D-27UserMove: 

   Date:  August 31, 1987
     
     To:  All INTERNAL D-27 User's 
     
   From:  Resource Planning & Management
          Jan Krivanec   
     
Subject:  D-27 User Move 
     
 Reason:  System D-27 Shutdown
     
-------------------------------------------------------------------------  
     
     
System D-27 will be permanently shutdown on September 31, 1987. RPM   
has chosen to route all D-27 User's to System D-34 by September 26, 1987.  
     
If you are valid on D-27 and D-34 you are requested to move your own  
files and tapes to D-34. You are to be completed by September 26, 1987.    
     
If you are valid only on D-27, RPM and Operations will move your files
and tapes to D-34. This request will begin September 25, 1987 beginning    
at 1800 pst.   
     
If you have any questions, please call me at (415) 498-2556 or ontyme 
IPC.J/KRIVANEC.


Thank you,
Jan Krivanec
Received: from F29.Tymnet by D35.Tymnet; Wed, 2 Sep 87 7:47:33 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 2 Sep 87 7:45:26 PDT
Return-path: <ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet> 
From: ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet 
Date: 02 SEP 87 15:31:10 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: J11985@Ontyme.Tymnet 
Subject: "ADMINISTRATIVE NO: DIS-87-012"... 




                                ADMINISTRATIVE          NO:    DIS-87-012
                                    BULLETIN            DATE:  02 SEP 87

         MCDONNELL DOUGLAS DIVERSIFIED INFORMATION SYSTEMS COMPANY



To:                ISG St. Louis Tract III Lists A - H

Subject:           EXPRESS SHIPPING SERVICES



Effective September 1, 1987, the processing of expedite/express parcels
previously handled by Production Services, Information Processing Company
has been transferred to the Metropolitan Services Organization.  The
function and the receiving window has been relocated from Building 307,
1 West to Building 307, 1 East.

The basic services previously provided will continue at the new location.
Hours of operation will be changed effective September 7, 1987 to
8:30 a.m. to 4:30 p.m., Monday through Friday.  Therefore, all parcels
must be to the MSO before 4:30 p.m.

We continue to look forward to being of service to you in this area of
responsibility.


(Original signed by M. J. Daniels)

M. J. Daniels, Manager
Branch Center Tract III
Metropolitan Services Organization - St. Louis


(Original signed by R. W. Brown)

R. W. Brown, Manager
Production Services
Information Processing Services


(Original signed by R. D. Windsor)

R. D. Windsor, Director
Metropolitan Services Organization - St. Louis
Received: from F29.Tymnet by D35.Tymnet; Fri, 4 Sep 87 17:16:08 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 4 Sep 87 17:15:41 PDT
Return-path: <ACS.W/PARSONS@EMSTXS.Ontyme.Tymnet> 
From: ACS.W/PARSONS@EMSTXS.Ontyme.Tymnet 
Date: 05 SEP 87 01:10:53 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A09336@Ontyme.Tymnet 
Subject: WHO'S THE SUP!!! 
WHO'STHESUP!!: 

                      APPLIED COMMUNICATIONS SYSTEMS
 
                           M E M O R A N D U M
 
 
                                                      []  ISG     
 
DATE>      04 SEP 87  17:07

TO>        INTERNAL ONTYME ACCOUNT SUPERVISORS

COPIES>    LES METOUR
           ROBERT LEVRINI
           PHILIPPE DES HORTES

FROM>      WENDY PARSONS


SUBJECT>   WHO'S THE SUP!!


-----------------------------------------------------------------------



ACS is currently updating the DIR.SUPERVISORS file which identifies each
internal OnTyme Account Supervisor and their respective address and telephone
number.
 
Attached you will find the current directory.  Among other benefits, this
directory reduces the amount of time your users may spend trying to locate you.
 
As you will see, some information is incomplete.  That's why we need your
help!  Please send an OnTyme to ACS.SUP with any additions, deletions, or
changes by September 25, 1987.
 
We appreciate you cooperation and look forward to hearing from you.
 
 
*******************************************************************************
 
 
 
*** DIR.SUPERVISORS
UPDATED:  8-6-87
BY: Wendy Parsons
 
                                                                Page  2

 
ACCOUNT        ADDRESS/TELEPHONE*              ACCOUNT SUPERVISOR
=======     =========================         ====================
 
 ACS        SJ: C22 - X6172                      Wendy Parsons
 
 APD                                             Dave Weaver
 
 ARC                                             Richard Goodwin
 
 ATE                                             Marian Del Russo
 
 AUGMENT                                         Bill Daul
 
 CANCSC     4211 Yonge St., Suite 230            Michael Gallant
            Willowdale, Ontario,
            M2P 2A9 Canada
            [   ]
 
 CNS        STL:                                 ?
 
 CREDIT     CUP:                                 Karyn Jenson
 
 CSUK                                            Cherril Foster
 
 CTG        CUP:                                 Nancy Vittum
 
 DBSD       CUP:                                 ?
 
 DSCHQ      STL:                                 ?
 
 DSS        IRV:                                 Cathy Polichetti
 
 ENS        SJ :                                 Laurie Caesar
 
 FAI        STL: L927/303/2E                     Val Wadlington
                 [314] 232-9401
 
 FEDSYS     STL: M614/Bldg 281/Level 4           Gene Weeke
                 [314] 234-3102
 
 FIN        CUP: VG1-B14                         Anita Giluso
                 [408] 446-7778
 
 FSC                                             ?
 
 HRD        CUP: VG1-A08                         Jeri McGoughey
 
 HSD        STL: N519/270/D-1/Post E-2           Nancy Ake
                 [314] 234-3997
 
 IBIS                                            Norm Comite
 
 INTL                                            Laurie Caesar
 
 IPC        STL: L237/306/3/C6                   Bev Martin
                 [314] 232-6943
 
                                                                Page  3

 IS                                              Linn Scoggins
 
 ISGFM      STL: LO69/306/2W/250                 Kathy Waddell
                 [314] 233-5116
 
 ISGHQ      STL: I210/301/3D/392                 Mary Spencer
                 [314] 212-1354
 
 ISGHR      STL:                                 Carolyn Patton
 
 ISID                                            Richard Krahn
 
 ISIGB                                           J. Millward
 
 ISIPR                                           ?
 
 ISITPR                                          Julie Erdman
 
 MAG        CUP:                                 ?
 
 MDACTVL                                         Brad Schuette
 
 MDAIS      STL: W255/306/3E                     Rich Brauer
                 [314] 233-8372
 
 MDCHQ      STL: H351/HQ/5S/572                  Jan Schneider
                 [314] 233-9060
 
 MDCSC      IRV: 99410/TWR/T907                  Jeff Christie
                 [714] 250-1000 x2148
 
 MDCSS      COL: D320/                           Phil Estrem
                 [303] 695-1500
 
 MDISB                                           Jean Van Waterschoot
 
 MDISF                                           Phil Costes
 
 MDISS                                           Eduardo Mancisidor
 
 MDSGP                                           J. Burek, Pollyn
 
 MFG                                             Bob Bockman
 
 MISCO      STL: I386/305/3E/251                 Tom Whelan
                 [314] 232-5895
 
 
 NAD                                             ?
 
 NETS                                            Susan Voth
                       432-5399
 
 NIS                                             Koniyoshi Kamoi
 
 NSCHQ      CUP:                                 Carolee Neff
                [408] 446-7682
 
                                                                Page  4

 NSMS       SJ: Orchard Parkway                  Julia Reuscher
                [408] 942-
 
 NSS        SJ: Orchard Parkway                  Linda Kypke
                [408] 942-5213
 
 NTD        SJ:                                  Gail Cone
 
 NTS        SJ:                                  Kimberly Holland
 
 OPERA      FR:                                  Rick Daniels
 
 PMTS       39100 Liberty Street                 Anne Downard
            Fremont, CA 94538
                [415] 794-2554
 
 PSB        STL:
 
 PSD                                             ?
 
 QSATS      SJ: Orchard Parkway                  Linda Kypke
 
 RCS                                             ?
 
 REMS                                            Lora Brading
 
 SLI                                             Henri Tocheport
 
 TBS                                             Bill French
 
 TCHECK                                          Jan Mueller
 
 TNAD                                            Fran Zapala
 
 TNS                                             Corinne Zerbib
 
 TOC                                             Debbie Hill
 
 TT                                              Irene Fischer-Uhrig
 
 TUK                                             Peter Boraston
 
 TXS                                             Carl Baltrunas
 
 TYM                                             Pat Relfe
 
 TYMHQ                                           Terri Osteen
 
 TYMOPS      SJ:  Orchard Parkway                Rose Doolittle
                  [408] 432-5202
 
 TYMPLN                                          ?
 
 TYMVEND                                         ?
 
 UKCS                                            H.B. Wallace
 
 UKNS                                            H.B. Wallace
                                                                Page  5

 
 UTX                                             Judith Smith
 
 
The following is a list of international internals.  (This list may be
redundant to this list above)
 
 
 ISIGB
 
 ISIPR
 
 ISID
 
 TNS
 
 MDICUST
 
 UKNS
 
 SUPS
 
 SUP
 
 MDISB
 
 TUK
 
 OPERS
 
 CMCSA
 
 ISIAHS
 
 MDINET
 
 MDISES
 
 UKCS
 
 MDISF
 
 OTSUPS
 
 MDI
 
 ISIAPR
 
 ISITPR
Received: from F29.Tymnet by D35.Tymnet; Tue, 8 Sep 87 9:04:19 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 8 Sep 87 8:54:23 PDT
Return-path: <ACS.ONTYME@EMSTXS.Ontyme.Tymnet> 
From: ACS.ONTYME@EMSTXS.Ontyme.Tymnet 
Date: 08 SEP 87 16:48:13 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A09530@Ontyme.Tymnet 
Subject: FOR DISTRIBUTION 
TELLAGRAF&DISSPLAUSAGE: 

                      R E M O T E   C O M P U T I N G
                              S E R V I C E S


                                                                  [MDC-ISG]

DATE>      04 SEP 87  10:18

TO>        TELLAGRAF AND DISSPLA USERS

COPIES>    

FROM>      CHERYL SCHREODER
           PROCESSING SERVICES


SUBJECT>   TELLAGRAF & DISSPLA USAGE


-----------------------------------------------------------------------


BECAUSE OF THE RESPONSE WE RECEIVED FROM THE MEMO REGARDING
CANCELLATION OF TELLAGRAF AND DISSPLA, WE HAVE DECIDED NOT TO 
CANCEL THE PRODUCTS .

WE WILL CONTINUE TO MAINTAIN THE TELLAGRAF AND DISSPLA
PRODUCTS TILL USAGE IS SUCH THAT WE CAN NO LONGER JUSTIFY 
KEEPING THE PRODUCTS.


ANY QUESTIONS CAN BE DIRECTED TO ME AT RCS.C/SCHROEDER.
Received: from F29.Tymnet by D35.Tymnet; Fri, 11 Sep 87 16:44:26 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 11 Sep 87 16:25:30 PDT
Return-path: <QSATS.G/KOLEK@EMSTXS.Ontyme.Tymnet> 
From: QSATS.G/KOLEK@EMSTXS.Ontyme.Tymnet 
Date: 11 SEP 87 23:46:27 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M18544@Ontyme.Tymnet 
Subject: NEW ADDRESS AND PHONE NUMBERS FOR QSATS 
NEWADDRESS/TELEPHONENUMBERS: 

                                     MEMORANDUM
                               NETWORK SYSTEMS COMPANY
                       QUALITY SERVICES AND TECHNICAL SUPPORT

          TO:       DISTRIBUTION                       CC:  DON JOHNSON
          FROM:     GLORIA KOLEK                            GARY WALKER
          DATE:     11 SEPTEMBER 1987                       ROURKE McCUSKER
          SUBJECT:  NEW ADDRESS/TELEPHONE NUMBERS:
                    (QSATS) N.T.S., S.T.S, Q.A.
          _________________________________________________________________

          NEW ADDRESS FOR U.S. MAIL DELIVERY:
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-2
          2560 N. FIRST STREET
          P. O. BOX 49019
          SAN JOSE, CA 95161-9019

          NEW ADDRESS FOR PRIVATE DELIVERY SERVICE (UPS, FED-EX, DHL, ETC)
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-2
          2560 N. FIRST STREET
          SAN JOSE, CA 95131

          TELEPHONE LISTING FOR QSATS (HTS, STS, QA):
          AREA CODE: 408      PREFIX NUMBER FOR ALL EXTENSIONS: 922

          NAME________________     DEPARTMENT__________________  EXTENSION
          AKELLA, RAM              QUALITY ASSURANCE             7461
          ARNETT, MARY             QUALITY ASSURANCE             7462
          BUBSEY, GAIL             STS (INTERFACE SUPPORT)       7463
          BURROUGH, JOHN           STS (INTERFACE SUPPORT)       7464
          CATTANEO, AUGUST         NTS (H/W TECH. SUPPORT)       7466
          CHEN, BEN                STS (NETWORK SUPPORT)         7468
          CHENG, HENRY             QUALITY ASSURANCE             7470
          CHIANG, SHIRLEY          STS (INTERFACE SUPP, MGR)     7471
          CHU, PING                STS (INTERFACE SUPPORT)       7472
          CLARIDGE, JON            QUALITY ASSURANCE             7473
          CURRI, LOUISE            STS (STS TECH. ANALYST)       7477
          DIAS, LARRY              QUALITY ASSURANCE             7478
          ELLENBERG, DOUG          STS (APPLICATIONS SUPP, MGR)  7480
          FISTE, TOD               STS (INTERFACE SUPPORT)       7484
          HO, RICHARD              STS (INTERFACE SUPPORT)       7486
          HOUGE, DIANA             QUALITY ASSURANCE             7487
          HUSSEY, DAVE             QUALITY ASSURANCE             7489
          JOHNSON, DON             QSATS (NTS, QA, MANAGER       6222
          KOCHMANN, TIM            NTS (H/W TECH. SUPPORT)       7493
          KOLEK, GLORIA            QSATS (NTS, STS, QA, SECY)    7495
          KRUMVIEDE, PAUL          NTS (H/W, S/W DIAG. SUPPORT)  7496
          LANGDON, CARL            STS (NETWORK SUPP, MGR)       7497
          LIU, JEFF                STS (APPLICATIONS SUPPORT)    7498
          LUCAS, JERRY             STS (NETWORK SUPPORT)         7499
          MATUCHA, DEAN            QUALITY ASSURANCE             7500
          McKIERNAN, JOHN          STS (INTERFACE SUPPORT)       7501












          MISTRY, PRAVIN           QUALITY ASSURANCE             7502
          MOORING, ED              NTS (H/W, S/W, DIAG. SUPPORT) 7504
          NARAYAN, KRISHNAN        STS (APPLICATIONS SUPPORT)    7507
          NELSON, PHIL             NTS (H/W TECH. SUPPORT)       7508
          NILLUKA, SANDRA          STS (NETWORK SUPPORT)         7510
          REILLY, JOHN             STS (NETWORK SUPPORT)         7447
          RICHARDS, STAN           NTS (H/W TECH. SUPPORT)       7513
          ROWE, CLIVE              STS (NETWORK SUPPORT)         7514
          SHARMA, ALOK             STS (INTERFACE SUPPORT)       7516
          SHEPHERD, BRUCE          NTS (H/W TECH. SUPPORT)       7517
          SHUTICH, JOHN            NTS (H/W TECH. SUPPORT)       7069
          STEIN, JIM               NTS (H/W TECH. SUPPORT, MGR)  7518
          TURNER, TOM              QUALITY ASSURANCE             7520
          VIVIER, RON              NTS (H/W S/W DIAG SUPP, MGR)  7521
          WALKER, GARY             STS (APPL,NW,INTERFACE, MGR)  7523
          WANG, JAMES              STS (NETWORK SUPPORT)         7524
          WARNER, RUTH             QUALITY ASSURANCE             7525
          YEH, TED                 STS (APPLICATIONS SUPPORT)    7528


          NOTE #1:
          FIELD ENGINEERING HANDBOOK IS COMPLETE AND AVAILABLE TOR.
          PLEASE CONTACT YOUR MANAGER FOR FURTHER DETAILS.


          NOTE #2:
          DUE TO "CIRCUMSTANCES BEYOND OUR CONTROL", OUR MOVE HAS BEEN
          DELAYED FOR ONE WEEK.  WE WERE ORIGINALLY SCHEDULED TO MOVE ON
          FRIDAY, 11 SEPTEMBER 1987; OUR NEW MOVING DATE IS TARGETED FOR
          FRIDAY, 18 SEPTEMBER 1987.  ANY AIL BY U.S. POSTAL SERVICE OR
          PRIVATE MAIL CARRIER WILL BE DELIVERED TO NEW MAILING ADDRESS
          AND REROUTED TO ORCHARD PARKWAY.

          PRESENT TELEPHONE NUMBERS FOR NTS,  STS AND QA  ARE  STILL  VALID
          UNTIL FURTHER NOTICE.

          WHEN  TELEPHONE  NUMBERS  ARE  CHANGED,  AND  YOU  PHONE  OUR OLD
          NUMBERS, THERE WILL BE A RECORDED MESSAGE STATING THAT THESE
          NUMBERS HAVE BEEN DISCONNECTED AND YOU WILL BE GIVEN A NEW NUMBER
          TO USE.

          VOICE MAIL WILL REMAIN ACTIVATED ON OLD TELEPHONE NUMBERS FOR ONE
         WEEK AFTER TELEPHONE NUMBERS ARE CHANGED.

          IF IN DOUBT, PLEASE CALL CORPORATE TELEPHONE OPERATOR AT
          (408) 922-0250.
Received: from F29.Tymnet by D35.Tymnet; Tue, 15 Sep 87 16:44:13 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 15 Sep 87 16:41:44 PDT
Return-path: <FIN.SUP@EMSTXS.Ontyme.Tymnet> 
From: FIN.SUP@EMSTXS.Ontyme.Tymnet 
Date: 16 SEP 87 00:24:21 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A12372@Ontyme.Tymnet 
Subject: AMERICAN EXPRESS 



                             MCDONNELL DOUGLAS
                          NETWORK SYSTEMS COMPANY
                          INTEROFFICE MEMORANDUM



     TO:       ALL MDC CORP AMERICAN EXPRESS CARD HOLDERS

     FROM:     LINDA SERVELLO

     SUBJECT:  ISSUANCE OF NEW AMERICAN EXPRESS CARDS
                                                                     



     WE ARE IN THE PROCESS OF CONSOLIDATING OUR AMERICAN EXPRESS
     CARDS INTO ONE BILLING CYCLE.  SOME EMPLOYEES WILL BE RECEIVING
     A NEW AMERICAN EXPRESS CARD IN THE NEAR FUTURE.

     UNTIL THEN PLEASE CONTINUE TO USE YOUR CURRENT CARD AS NORMAL.
     PLEASE DISREGARD ANY MESSAGES ON YOUR MONTHLY STATEMENTS
     REGARDING CANCELLATION OF YOUR CARD.  YOUR CARD HAS NOT BEEN
     CANCELLED.

     IF YOU HAVE ANY QUESTIONS, PLEASE CALL PAM SUTER AT (408)
     922-6617.  WE ARE SORRY FOR ANY INCONVENIENCE YOU MAY HAVE BEEN
     CAUSED.
Received: from F29.Tymnet by D35.Tymnet; Wed, 16 Sep 87 13:44:15 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 16 Sep 87 13:43:41 PDT
Return-path: <TYMOPS.TOMASI@EMSTXS.Ontyme.Tymnet> 
From: TYMOPS.TOMASI@EMSTXS.Ontyme.Tymnet 
Date: 16 SEP 87 21:04:32 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M19373@Ontyme.Tymnet 
Subject: JACK SNAVELY NEW POSITION 
DISTRIBUTIONOFMSG.RE: JACK SNAVELY

                 MCDONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                     T Y M N E T    O P E R A T I O N S

                            M E M O R A N D U M



DATE>      16 SEP 87  13:03

TO>        ALL SUPERVISORS

COPIES>    

FROM>      ANNE M. GUERIN


SUBJECT>   DISTRIBUTION OF MSG. RE: JACK SNAVELY


-----------------------------------------------------------------------


PLEASE DISTRIBUTE THE FOLLOWING MESSAGE TO ALL YOUR MANAGERS.

                 MCDONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                     T Y M N E T    O P E R A T I O N S

                            M E M O R A N D U M



DATE>      16 SEP 87  12:26

TO>        ALL MANAGERS

COPIES>    

FROM>      BOB TOMASI


SUBJECT>   JACK SNAVELY NEW POSITION


-----------------------------------------------------------------------



 
 
          AS MOST OF YOU KNOW,  MR.  JACK SNAVELY,  MANAGER OF NETWORK
          RESOURCES,  HAS  ACCEPTED A MANAGEMENT CHAIR POSITION IN THE
          MANAGEMENT TRAINING AND PROFESSIONAL  DEVELOPMENT  GROUP  IN
          ST.  LOUIS.  THIS TRANSFER WILL BE EFFECTIVE SEPTEMBER 28TH,
          1987.
 
          I WISH TO TAKE THIS OPPORTUNITY  TO  RECOGNIZE  JACK'S  OUT-
          STANDING CONTRIBUTIONS TO THE NETWORK SYSTEMS COMPANY, ESPE-
          CIALLY IN HIS MOST RECENT ASSIGNMENT IN  NETWORK  RESOURCES.
          JACK  FIRST  ASSUMED THIS RESPONSIBILITY IN JANUARY OF 1984,
          IN THE MIDST OF THE BREAKUP  OF  A.T.  &  T.  AND  MCDONNELL
          DOUGLAS' ACQUISITION OF TYMSHARE.   AT THAT TIME,  OUR ORDER
          PROCESSING CAPABILITIES,  ALTHOUGH IMPROVED,  WERE LESS THAN
          ADEQUATE.    HIS  LEADERSHIP  AND  DIRECTION  OF  THE  ORDER
          PROCESSING GROUPS RESULTED IN AN AVERAGE  INSTALLATION  TIME
          REDUCTION FROM 120 DAYS TO 42 DAYS.
 
          IN THE PROCESS OF BUILDING THE ORDER PROCESSING SYSTEM, JACK
          HAS ALSO ASSEMBLED AN OUTSTANDING TEAM  OF  TALENTED,  DEDI-
          CATED INDIVIDUALS TO CONTINUE IMPROVING THE ORDER PROCESSING
                                                                Page  2

          SYSTEM.  WHILE THERE IS STILL MUCH WORK TO BE DONE, JACK HAS
          PROVIDED  A  SOLID  FOUNDATION  AND  HAS  MADE  THE  NETWORK
          RESOURCES GROUP A VITAL CONTRIBUTING MEMBER OF  THE  NETWORK
          SYSTEMS COMPANY TEAM.
 
          I WOULD LIKE YOU TO JOIN ME IN TAKING THE TIME TO THANK JACK
          FOR PUTTING THE ORDER PROCESSING SYSTEM ON THE RIGHT  TRACK.
          ALSO,  WE CONGRATULATE HIM ON HIS NEW POSITION IN MANAGEMENT
          TRAINING AND PROFESSIONAL DEVELOPMENT,  AND LOOK FORWARD  TO
          HIS  RETURN  TO NETWORK SYSTEMS COMPANY WHEN HIS NEW ASSIGN-
          MENT IS COMPLETED.
Received: from F29.Tymnet by D35.Tymnet; Thu, 17 Sep 87 14:04:20 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Thu, 17 Sep 87 13:59:17 PDT
Return-path: <QSATS.G/KOLEK@EMSTXS.Ontyme.Tymnet> 
From: QSATS.G/KOLEK@EMSTXS.Ontyme.Tymnet 
Date: 17 SEP 87 21:31:14 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M19699@Ontyme.Tymnet 
Subject: 2ND PHONE LIST FOR QSATS, CORRECTED 
NEWADDRESS/TELEPHONENUMBERS: 

                                   MEMORANDUM
                               NETWORK SYSTEMS COMPANY
                       QUALITY SERVICES AND TECHNICAL SUPPORT

          TO:       DISTRIBUTION                       CC:  DON JOHNSON
          FROM:     GLORIA KOLEK                            GARY WALKER
          DATE:     11 SEPTEMBER 1987                       ROURKE McCUSKER
          SUBJECT:  NEW ADDRESS/TELEPHONE NUMBERS:
                    (QSATS) N.T.S., S.T.S, Q.A.
          _________________________________________________________________

          NEW ADDRESS FOR U.S. MAIL DELIVERY:
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-21
          2560 N. FIRST STREET
          P. O. BOX 49019
          SAN JOSE, CA 95161-9019

          NEW ADDRESS FOR PRIVATE DELIVERY SERVICE (UPS, FED-EX, DHL, ETC)
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-21
          2560 N. FIRST STREET
          SAN JOSE, CA 95131

          TELEPHONE LISTING FOR QSATS (HTS, STS, QA):
          AREA CODE: 408      PREFIX NUMBER FOR ALL EXTENSIONS: 922

          NAME________________     DEPARTMENT__________________  EXTENSION
          AKELLA, RAM              QUALITY ASSURANCE             7461
          ARNETT, MARY             QUALITY ASSURANCE             7462
          BUBSEY, GAIL             STS (INTERFACE SUPPORT)       7463
          BURROUGH, JOHN           STS (INTERFACE SUPPORT)       7464
          CATTANEO, AUGUST         NTS (H/W TECH. SUPPORT)       7466
          CHANG, VERA              QUALITY ASSURANCE             7469
          CHEN, BEN                STS (NETWORK SUPPORT)         7468
          CHEN, CATHY              QUALITY ASSURANCE             7469
          CHENG, HENRY             QUALITY ASSURANCE             7470
          CHIANG, SHIRLEY          STS (INTERFACE SUPP, MGR)     7471
          CHU, PING                STS (INTERFACE SUPPORT)       7472
          CLARIDGE, JON            QUALITY ASSURANCE             7473
          CURRI, LOUISE            STS (STS TECH. ANALYST)       7477
          DAZZI, ALAIN             NTS (H/W SUPPORT)             7669
          DIAS, LARRY              QUALITY ASSURANCE             7478
          ELLENBERG, DOUG          STS (APPLICATIONS SUPP, MGR)  7480
          FANG, DAN                STS (INTERFACE SUPPORT)       7481
          FISTE, TOD               STS (INTERFACE SUPPORT)       7484
          HEALY, ANGELA            STS (NETWORK SUPPORT)         6741
          HO, RICHARD              STS (INTERFACE SUPPORT)       7486
          HOUGE, DIANA             QUALITY ASSURANCE             7487
          HUSSEY, DAVE             QUALITY ASSURANCE             7489
          JOHNSON, DON             QSATS (MANAGER: NTS & QA)     6222
          KOCHMANN, TIM            NTS (H/W TECH. SUPPORT)       7493
          KOLEK, GLORIA            QSATS (NTS, STS, QA, SECY)    7495
          KRUMVIEDE, PAUL          NTS (H/W, S/W DIAG. SUPPORT)  7496












          LANGDON, CARL            STS (NETWORK SUPP, MGR)       7497
          LIU, JEFF                STS (APPLICATIONS SUPPORT)    7498
          LUCAS, JERRY             STS (NETWORK SUPPORT)         7499
          MATUCHA, DEAN            QUALITY ASSURANCE             7500
          McCUSKER, ROURKE         QUALITY ASSURANCE (MANAGER)   7576
          McKIERNAN, JOHN          STS (INTERFACE SUPPORT)       7501
          MISTRY, PRAVIN           QUALITY ASSURANCE             7502
          MOORING, ED              NTS (H/W, S/W, DIAG. SUPP)    7504
          MORDEN, JEFF             STS (INTERFACE SUPPORT)       7506
          NARAYAN, KRISHNAN        STS (APPLICATIONS SUPPORT)    7507
          NELSON, PHIL             NTS (H/W TECH. SUPPORT)       7508
          NILLUKA, SANDRA          STS (NETWORK SUPPORT)         7510
          REILLY, JOHN             STS (NETWORK SUPPORT)         7447
          RICHARDS, STAN           NTS (H/W TECH. SUPPORT)       7513
          ROWE, CLIVE              STS (NETWORK SUPPORT)         7514
          SHARMA, ALOK             STS (INTERFACE SUPPORT)       7516
          SHEPHERD, BRUCE          NTS (H/W TECH. SUPPORT)       7517
          SHUTICH, JOHN            NTS (H/W TECH. SUPPORT)       7069
          STEIN, JIM               NTS (H/W TECH. SUPPORT, MGR)  7518
          TURNER, TOM              QUALITY ASSURANCE             7520
          VIVIER, RON              NTS (H/W S/W DIAG SUPP, MGR)  7521
          WALKER, GARY             STS (MANAGER: APPL,N/W,I/F)   7523
          WANG, JAMES              STS (NETWORK SUPPORT)         7524
          WARNER, RUTH             QUALITY ASSURANCE             7525
          YEH, TED                 STS (APPLICATIONS SUPPORT)    7528

          ONTYME LISTINGS WILL REMAIN THE SAME: QSATS.-/----


          NOTE #1:
          FIELD ENGINEERING HANDBOOK IS COMPLETE AND AVAILABLE TO ORDER.
          PLEASE CONTACT YOUR MANAGER FOR FURTHER DETAILS.


          NOTE #2:
          DUE TO "CIRCUMSTANCES BEYOND OUR CONTROL",  OUR MOVE WAS  DELAYED
          FOR ONE WEEK.  WE WERE ORIGINALLY SCHEDULED TO MOVE ON FRIDAY, 11
          SEPTEMBER 1987;  OUR NEW MOVING DATE IS TARGETED FOR  FRIDAY,  18
          SEPTEMBER 1987.   ANY MAIL BY U.S. POSTAL SERVICE OR PRIVATE MAIL
          CARRIER WILL BE DELIVERED TO NEW MAILING ADDRESS AND REROUTED  TO
          ORCHARD PARKWAY.

          PRESENT  TELEPHONE  NUMBERS  FOR NTS,  STS AND QA ARE STILL VALID
          UNTIL FURTHER NOTICE.

          WHEN TELEPHONE  NUMBERS  ARE  CHANGED,  AND  YOU  PHONE  OUR  OLD
          NUMBERS, THERE WILL BE A RECORDED MESSAGE STATING THAT THESE
          NUMBERS HAVE BEEN DISCONNECTED AND YOU WILL BE GIVEN A NEW NUMBER
          TO USE.

          IF IN DOUBT, PLEASE CALL CORPORATE TELEPHONE OPERATOR AT
          (408) 922-0250.
Received: from F29.Tymnet by D35.Tymnet; Fri, 18 Sep 87 7:04:12 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 18 Sep 87 6:45:28 PDT
Return-path: <IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet> 
From: IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet 
Date: 18 SEP 87 14:39:41 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A13456@Ontyme.Tymnet 
Subject: CONVERSION SERVICE 



TO:       ALL ISG BUSINESS UNITS

SUBJECT:  ISG WORD PROCESSING CONVERSION SERVICE


    ISG is now offering Word Processing Document conversions.  This
service is being performed in the St. Louis Computer Center.  Current
software conversions include the following:

                    WANG 8" to MULTIMATE
                    WANG 8" to IBM DISPLAYWRITER
                    WANG 8" to DISPLAYWRITE III
                    WANG 5 1/4" to MULTIMATE
                    MULTIMATE to WANG 8"
                    MULTIMATE to IBM DISPLAYWRITER
                    MULTIMATE to XEROX 860
                    IBM DISPLAYWRITER to WANG 8"
                    IBM DISPLAYWRITER to MULTIMATE


   Software pairings (single-direction-links between incompatibles)
are readily available for virtually all major Word Processing
packages and dedicated systems on the market today.  Additional
pairings will be ordered as needed.  A total list of the available
software pairings for conversions can be aquired from the location
below.


    For further information reguarding the conversion service,  you
may contact:

                         ISG CONVERSION SERVICE
                         MAIL STOP: 307/2E/L237/D15
                         Phone:  314-233-8250
Received: from F29.Tymnet by D35.Tymnet; Mon, 21 Sep 87 16:53:59 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 21 Sep 87 16:45:25 PDT
Return-path: <TYMOPS.TOMASI@EMSTXS.Ontyme.Tymnet> 
From: TYMOPS.TOMASI@EMSTXS.Ontyme.Tymnet 
Date: 22 SEP 87 00:08:47 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M20248@Ontyme.Tymnet 
Subject: NETWORK RESOURCES 

TO ALL SUPERVISORS:  PLEASE DISTRIBUTE THE FOLLOWING MESSAGE TO 
ONLY MANAGERS.  THANK YOU.

                 MCDONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                     T Y M N E T    O P E R A T I O N S

                            M E M O R A N D U M



DATE>      21 SEP 87  15:50

TO>        ALL OPERATIONS PERSONNEL/TYMNET MANAGERS

COPIES>    P. KRETER  W. PRINCE

FROM>      BOB TOMASI


SUBJECT>   NETWORK RESOURCES


-----------------------------------------------------------------------



          I AM PLEASED TO ANNOUNCE THE APPOINTMENT OF THOM  KELLEY  TO  THE

          POSITION OF MANAGER,  NETWORK RESOURCES,  REPLACING JACK SNAVELY.

          THIS APPOINTMENT IS EFFECTIVE MONDAY, SEPTEMBER 28TH, 1987.


          WITH THOM'S APPOINTMENT,  SEVERAL CHANGES WILL BE TAKING PLACE IN

          THE  NETWORK  RESOURCES  GROUP.    FIRST,  THE LOGISTICS PLANNING

          FUNCTION, UNDER FRANK TROGLIONE,  WILL BE MERGED INTO THE NETWORK

          RESOURCES  GROUP AND WILL CONTINUE TO REPORT TO THOM.   THE ORDER

          PROCESSING GROUP, UNDER KATHERINE GOODWIN,  THE PROJECT IMPLEMEN-

          TATION GROUP,  UNDER BERYL AGUA, AND THE RESOURCE CENTER UNDER JO

          HANNAH, WILL ALSO REPORT TO THOM.   THIS COMBINATION OF FUNCTIONS

          WILL BETTER ENABLE US TO ADDRESS THE MATERIAL SUPPORT CONCERNS AS
                                                                Page  2


          THEY RELATE TO ORDER PROCESSING.   PEGGY MACDONALD,  SECRETARY TO

          JACK SNAVELY, WILL ALSO REPORT TO THOM.


          THIS  NEW  NETWORK RESOURCES GROUP WILL THEN REPORT INTACT TO DR.

          A.  S.  (RAJA) RAJARAMAN,  DIRECTOR OF NETWORK  PLANNING.    THIS

          CHANGE  IS  BEING  MADE  TO  CONSOLIDATE  REPORTING FUNCTIONS AND

          PROVIDE  A  MORE  COHESIVE  APPROACH  TO  NETWORK  PLANNING   AND

          IMPLEMENTATION.


          I  TRUST  THAT I CAN COUNT ON YOUR SUPPORT FOR BOTH THOM AND RAJA

          AS THEY ASSUME THEIR NEW ASSIGNMENTS.
Received: from F29.Tymnet by D35.Tymnet; Thu, 24 Sep 87 15:44:19 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Thu, 24 Sep 87 15:25:33 PDT
Return-path: <HRD.TRNG@EMSTXS.Ontyme.Tymnet> 
From: HRD.TRNG@EMSTXS.Ontyme.Tymnet 
Date: 24 SEP 87 23:12:41 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A15625@Ontyme.Tymnet 
Subject: M&PD-San Jose address/phone 

                     Management & Professional Development

                              M E M O R A N D U M


  TO:       All Employees (Please post)

  FROM:     Stephen Reynolds, Manager
            Management & Professional Development (M&PD) San Jose

  SUBJECTS: .4Q87 M&PD-San Jose Training Schedule
            .New M&PD-San Jose Address and Phone Numbers

  DATE:     September 24, 1987

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - 
  BAY AREA EMPLOYEES   
  -4Q87 M&PD-San Jose schedules, enrollment forms, and course descriptions
  were sent to all A-F managers (Sr. Section Manager and above) on 
  September 11.  See your manager for a copy.
      -Registrations are due back to M&PD-San Jose by September 28.

  EMPLOYEES OUTSIDE THE BAY AREA
  -4Q87 M&PD San Jose schedule, enrollment forms and course desctiptions
  will be sent to all District Managers and above during the week of
  September 28 for courses in San Jose, Vienna/Rockville,
  Rosemont/Mt. Prospect, and San Diego.  See your manager for a copy.
      -Registrations are due back to M&PD-San Jose by October 12.

  FOR INFORMATION:
  - Tymnet Training & Education, call Cheryl McGowan at 408/922-7617
      (408/432-5042 until Oct. 5).

  - M&PD-St. Louis, call Linda Zink at 314/232-9304.

  - M&PD-Irvine, call Bonnie Watkins at 714/250-1000 ext.7486.

  - Denver (MDCIS) programs, call Kathy Padus at 303/220-6044.

*************  NEW M&PD-SAN JOSE ADDRESS  **************************

  Mail:  McDonnell Douglas Training Center
         2665 North First Street
         San Jose, CA  95134

  Interoffice:  CA59 Bldg T

  Ontyme:  HRD.TRNG

  Phone:  Name                      After 10/6/87              Until 10/6/87
          Stephen Reynolds..........408/922-7654............... 408/435-7742
          Kathleen Corcoran.........408/922-7651................408/432-5068
          LaVonne Hage..............408/922-7652................408/432-5292
          Belinda Quesada...........408/922-7653................408/435-7740
Received: from F29.Tymnet by D35.Tymnet; Mon, 2 Nov 87 10:03:16 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 2 Nov 87 9:58:05 PST
Return-path: <NETS.TTE@EMSTXS.Ontyme.Tymnet> 
From: NETS.TTE@EMSTXS.Ontyme.Tymnet 
Date: 02 NOV 87 17:32:54 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I06734@Ontyme.Tymnet 
Subject: TTE 1st Qtr Schedule 
TTE1stQuarter88Schedule: 

                            M E M O R A N D U M

                          NETWORK SYSTEMS COMPANY
                         NETWORK SYSTEMS MARKETING


DATE>      30 OCT 87  13:17

TO>        The World

COPIES>    

FROM>      Tymnet Training and Education


SUBJECT>   TTE 1st Quarter 88 Schedule


-----------------------------------------------------------------------


The Tymnet Training and Education schedule for the 1st quarter '88
is now available via ontyme  :EXEC *** TTE.ENROLL

As a result of your feedback after class and the recommendations of the
training advisory task forces we have made some changes in our
courses.

  1.  The length of  TTE 455 Utilities Code Generation has been
      increased to 8 days to provide more time for hands-on labs.

  2.  SmarTym has been added to the TTE 230 Tymnet 3270/CMT/SmarTym
      course and the length has been extended to 8 days.

  3.  The name of TTE 260 has been changed to Async Error Correction, we
      now cover X.PC, Network Server, Menu Server and 2 new
      protocols - MNP & AFT

  4.  The CPU III, MAC III and Nano engine were added to the TTE 330
      TYMNET Hardware Maintenance and Troubleshooting.

  5.  The requirement for either TTE 455 or TTE 445 as a prerequisite 
      for TTE 450 has been revised.

The enrollment procedure remains the same - use  :EXEC *** TTE.ENROLL
In the last quarter we had some students show up who were not on our
roster.  Please be sure to send an enrollment form at least 5 weeks 
before your class.  That way we will be sure we have enough materials
and lab equipment available for you.  You should receive confirmation of
your enrollment within 2 days of your registration.

We look forward to seeing you in class next quarter.  If you have any
questions about the schedule or prerequisite courses, please give us a
call.  Our new phone number is (408) 922-7620


Sincerely,

Robert C. Grandey
Received: from F29.Tymnet by D35.Tymnet; Tue, 17 Nov 87 14:04:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 17 Nov 87 13:56:23 PST
Return-path: <ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet> 
From: ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet 
Date: 17 NOV 87 21:31:26 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: J40902@Ontyme.Tymnet 
Subject: "ADMINISTRATIVE NO: DIS-87-019"... 



                                ADMINISTRATIVE          NO:    DIS-87-019
                                    BULLETIN            DATE:  17 NOV 87

         MCDONNELL DOUGLAS DIVERSIFIED INFORMATION SYSTEMS COMPANY



To:                ISG Lists B - E

Subject:           NEW ORGANIZATION FOR MDIPS PRODUCTION SERVICES,
                   ST. LOUIS



Effective immediately, the following organization is in place within
Production Services, St. Louis.

Ron Brown is Manager of IBM Processing Services, with responsibility for
mainframe and tape operations, print operations and distribution,
production job management, storage management, validations and security
management.

Gene Stephens is Manager of Specialized Processing Services, with
responsibility for Tandem, DEC, VAX and KL10 operations, ULTRIX
processing, and other special processing support activities requested by
MDISG business units.

Alice Diehl is Senior Section Manager in charge of St. Louis Processing
Change Management with responsibility for change control, daily planning,
hardware planning, problem management and hardware maintenance management.

Alice, Gene and Ron will report to the undersigned.  Your support of them
in their assignments will be appreciated.





Luke R. Abkemeier, Director
Production Services, St. Louis


CONCURRENCE:





Karen S. Gedera, Director
Information Processing
Received: from F29.Tymnet by D35.Tymnet; Mon, 7 Dec 87 15:44:10 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 7 Dec 87 15:37:15 PST
Return-path: <HRD.PERSMAIL@EMSTXS.Ontyme.Tymnet> 
From: HRD.PERSMAIL@EMSTXS.Ontyme.Tymnet 
Date: 07 DEC 87 23:21:15 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A40199@Ontyme.Tymnet 
Subject: HOLIDAYS 

TO:           ALL NSC EMPLOYEES

FROM:         KAY CHILDS
              HUMAN RESOURCES



PAID HOLIDAYS FOR DECEMBER ARE:  THURSDAY, DECEMBER 24 AND 
FRIDAY, DECEMBER 25 AND FOR JANUARY - ONLY JANUARY 1, 1988.

DECEMBER 23 IS A WORK DAY, BUT MAY  BE TAKEN AS A VACATION
DAY OR UNPAID PERSONAL LEAVE WITH SUPERVISORY APPROVAL.
Received: from F29.Tymnet by D35.Tymnet; Mon, 21 Dec 87 10:04:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 21 Dec 87 9:51:49 PST
Return-path: <TYMOPS.K/LEONGUERRERO@EMSTXS.Ontyme.Tymnet> 
From: TYMOPS.K/LEONGUERRERO@EMSTXS.Ontyme.Tymnet 
Date: 21 DEC 87 17:35:46 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M37795@Ontyme.Tymnet 
Subject: 39238.WEB 
39238.WEB: 


TO:  WNFE
FR:  KATHY LEON GUERRERO
RE:  39238.WEB

ON MONDAY, DECEMBER 28TH, CODE WILL BE LOADED TO CANCEL (1) LSI-11 WITH ITS
(3) CSO HOSTS (617, 62, AND 4525) AND (1) 9.6 HW TO NODE 3143/TYMNET IN 
FREMONT, CA.  HARDWARE WAS COMPLETED AUGUST 28, 1987 AND CODE FOR 
10115 WAS COMPLETED BY FSC.

DEAD-ENDED NODES:  NONE

FOR DETAILS, TYPE (DBSCHED:38)39238W.EB

HAVE A SHORT WEEK, KATHY
Received: from F29.Tymnet by D35.Tymnet; Tue, 5 Jan 88 14:34:00 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 5 Jan 88 14:29:07 PST
Return-path: <TYM.F/BARKER@EMSTXS.Ontyme.Tymnet> 
From: TYM.F/BARKER@EMSTXS.Ontyme.Tymnet 
Date: 05 JAN 88 21:59:31 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I31514@Ontyme.Tymnet 
Subject: EASTERN TECH SERVICES ORGANIZATION 

 
 
                        M E M O R A N D U M
 
 
 
 
 
DATE:       January 5, 1988
 
 
TO:         All Tech/All Sales
 
CC:         Jerry Edgerton
            Rob Ritchie
            Mark Lonergan
            Andy Price
            Bruce Smith
 
FROM:       Frank Barker
 
 
SUBJECT:    EASTERN TECH SERVICES ORGANIZATION
                                                                 
 
I am pleased to announce that Mr. Ken Dulabhan will assume 
responsibility of the Eastern Tech Services organization as 
Regional Technical Manager effective October 12, 1987.
 
The Eastern Tech Services organization is chartered with support 
of the eastern private networks as well as the eastern technical 
specialist group.
 
Ken brings with him a proven track record in the folds of data 
processing and networking along with his success as project 
manager of FTS-2000.
 
Please join me in wishing Ken well in his new position.
Received: from F29.Tymnet by D35.Tymnet; Mon, 11 Jan 88 14:16:02 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 11 Jan 88 14:15:10 PST
Return-path: <IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet> 
From: IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet 
Date: 11 JAN 88 21:49:32 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A49530@Ontyme.Tymnet 
Subject: ISG CONVERSION SERVICE 



TO:       ALL ISG BUSINESS UNITS

SUBJECT:  ISG WORD PROCESSING CONVERSION SERVICE


    ISG is now offering Word Processing Document conversions.  This
service is being performed in the St. Louis Computer Center.  Current
software conversions include the following:

                    WANG 8" to MULTIMATE
                    WANG 8" to IBM DISPLAYWRITER
                    WANG 8" to DISPLAYWRITE III
                    WANG 5 1/4" to MULTIMATE
                    MULTIMATE to WANG 8"
                    MULTIMATE to IBM DISPLAYWRITER
                    MULTIMATE to XEROX 860
                    IBM DISPLAYWRITER to WANG 8"
                    IBM DISPLAYWRITER to MULTIMATE


   Software pairings (single-direction-links between incompatibles)
are readily available for virtually all major Word Processing
packages and dedicated systems on the market today.  Additional
pairings will be ordered as needed.  A total list of the available
software pairings for conversions can be aquired from the location
below.


    For further information reguarding the conversion service,  you
may contact:

                         ISG CONVERSION SERVICE
                         MAIL STOP: 307/2E/L237/D15
                         Phone:  314-233-8250
Received: from F29.Tymnet by D35.Tymnet; Mon, 8 Feb 88 17:04:10 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 8 Feb 88 17:01:05 PST
Return-path: <HRD.TRNG@EMSTXS.Ontyme.Tymnet> 
From: HRD.TRNG@EMSTXS.Ontyme.Tymnet 
Date: 09 FEB 88 00:46:58 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A59609@Ontyme.Tymnet 
Subject: M&PD Schedule Changes 


 
                                M E M O R A N D U M
                                   (PLEASE POST)


                                                           February 8, 1988

     TO:           All U.S. MDNSC Employees
                   All U.S. MDPSC Employees
                   All Other ISG Bay Area Employees

     FROM:         Stephen Reynolds, Manager
                   Management & Professional Development (M&PD)-San Jose

     SUBJECT:      Changes in M&PD Staffing and Programs


     It is with both pleasure and regret that I have decided to leave
     McDonnell Douglas, effective February 11, 1988.  I have accepted the
     position of Domestic Training Manager for Seagate Technology, in Scotts
     Valley, California.  

     I am extremely pleased to announce that Kathleen Corcoran, formerly
     Senior Training Specialist in M&PD-San Jose, has been appointed to fill
     my position.  Please join me in congratulating Kathleen on her new
     assignment, which reflects her outstanding accomplishments over the
     last year in a variety of M&PD programs.

     I am also pleased to announce that Becky Spencer has taken the position
     as Department Secretary of M&PD.  Becky was previously an MDC employee
     with Douglas Aircraft in Long Beach.

     Kathleen's former Training Specialist position is currently available.
     Interested candidates should contact Kathleen at (408)922-7651.

     Questions about M&PD programs and services can be directed as follows:

         Kathleen Corcoran (408)922-7651 -- Questions on program content of
         M&PD programs.

         Becky Spencer (408)922-7653 -- Questions on enrollment in M&PD
         programs; borrowing films and tapes; ordering Ethical Decision
         Making supplies.

         LaVonne Hage (408)922-7652 -- Educational Reimbursement questions
         and forms.

     The following is a listing of M&PD-San Jose programs scheduled for the
     next two months and their status.  (The 2Q88 M&PD-San Jose schedule
     will be published in early March.)  Employees wishing to enroll in any
     of the following programs should see their senior section manager for
     an enrollment form.  If additional enrollment forms are needed, contact
     Becky Spencer.

 
 
                                                           Memorandum
                                                           February 8, 1988
                                                           Page 2



         MDNSC CONSTRUCTIVE EMPLOYEE RELATIONS --- Two courses will be held
         as scheduled on March 3 and 24.

         FRONTLINE LEADERSHIP --- The series will be held as scheduled
         February 17, 24 and March 2, 9 and 16.

         SO YOU WANT TO BE A MANAGER --- (originally scheduled for March 8)
         Will be postponed to April 28.

         POSITIVE NEGOTIATION SKILLS --- Will be held as scheduled March
         21-23 in San Jose.

         COUNSELOR SELLING SKILLS --- The March 8-11 seminar will not be
         held.  Dates of future programs will be determined following the
         meeting of regional sales managers in early March.

         VERSATILE SALES PERSON --- The April 6-7 seminar will not be held.
         The dates of future programs will be determined following the
         meeting of regional sales managers in early March.

         TIME MANAGER --- Will be held as scheduled:

                                Feb. 23-24 Atlanta
                                Mar. 15-16 New York
                               Mar. 17-18 Vienna, VA
                                Apr. 12-13 San Jose
                              Apr. 19-20 Rosemont, IL

         PEAK PERFORMANCE --- Will be held as scheduled March 2 and 3.

         BUSINESS WRITING SKILLS --- The two series currently being
         conducted will be continued to their conclusion.

         ADMINISTRATIVE PROFESSIONALISM --- Will be held as scheduled on
         February 26 and March 4 and 11.

         EXCEPTIONAL CUSTOMER SATISFACTION --- Will be held as scheduled on
         March 29-30.

         MANAGEMENT SKILLS PROFILE --- Forms will be distributed by the end
         of February to all enrollees.  After the forms have been returned
         and compiled, a feedback session will be scheduled in April.

     SLR:ras
Received: from F29.Tymnet by D35.Tymnet; Fri, 19 Feb 88 19:34:41 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 19 Feb 88 19:25:50 PST
Return-path: <ACS.K/FISHER@EMSTXS.Ontyme.Tymnet> 
From: ACS.K/FISHER@EMSTXS.Ontyme.Tymnet 
Date: 20 FEB 88 02:58:20 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A63915@Ontyme.Tymnet 
Subject: ACCOUNT SUP INFO- PLEASE READ AS SOON AS POSSIBLE 

Dear Account Supervisor,
 
     Hello!  We need to update our records on our foreign OnTyme acccounts
AS SOON AS POSSIBLE.  Please send me an OnTyme AS SOON AS POSSIBLE telling
the name, address and phone of the account supervisor for this OnTyme account!
If this is not an account outside of the United States, please make that
clear.  Your cooperation is much appreciated.
 
     My OnTyme ID is ACS.K/FISHER.
 
                                                            THANK YOU!
From: Tymcom-X Supervisor <TXSSUP> 
Date: Sat, 20 Feb 88 1:35:35 CST 
To: <ACS.K/FISHER@EMSTXS.Ontyme.Tymnet> 
Subject: Re: ACCOUNT SUP INFO- PLEASE READ AS SOON AS POSSIBLE 
In-reply-to: A63915@Ontyme.Tymnet of 20 FEB 88 02:58:20

TXS.SUP is the account supervisor for the Tymcom-X Support Group.
The group is located at McDonnell Douglas Center in San Jose.
We support all the PDP-10 systems, including the TYMNET code generation
systems on hosts 25, 54, and 33.  TXS is most definitely not a foreign account.

Craig Fletcher, Carl Baltrunas, Osman Guven, and Joe Smith.
(408)922-6224.
Received: from F29.Tymnet by D35.Tymnet; Tue, 1 Mar 88 15:43:20 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Mar 88 15:35:39 PST
Return-path: <TYM.J/EDGERTON@EMSTXS.Ontyme.Tymnet> 
From: TYM.J/EDGERTON@EMSTXS.Ontyme.Tymnet 
Date: 01 MAR 88 23:26:05 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I57852@Ontyme.Tymnet 
Subject: OPEN SYSTEMS ENGINEER POSITION 
OPENSYSTEMSENGINEERPOSITION: 

                         M E M O R A N D U M 
 
                          FEDERAL OPERATIONS
                     ADVANCED PROGRAMS DEPARTMENT
 
 
 
DATE:     MARCH 1, 1988
 
TO:       ALL TECH
          ALL SALES
 
COPY:     JERRY EDGERTON
 
 
FROM:     GEORGE WRIGHT
 
SUBJ:     OPEN SYSTEMS ENGINEER POSITION
----------------------------------------------------------------------
 
 
The Federal Operations' Advanced Programs Department, located in 
Vienna, Virginia has an opening for the position of Systems Engineer.  
Following  are the requirements for the position:
 
 
                           SYSTEMS ENGINEER
 
    - Basic understanding of the Tymnet product line and a solid 
      understanding of basic communication.
 
    - Experience with alternate technologies (i.e. Satellite, etc.) and 
      other vendors IBM, DEC, etc.  Specific knowledge of IBM hardware 
      and software (NET VIEW) highly desireable.
 
    - Oral presentation and writing skills are a critical requirement.  
      Please provide samples of documents which demonstrate writing 
      ability.
 
    - Experience in proposal preparation is a plus.
 
    - Ability to work independantly and as part of a group.
 
Interested individuals should notify their managers prior to applying 
for this position.  Please send your resume and letter of application 
to:
 
TYMNET/McDonnell Douglas
 Network Systems Company
ATTN:  George Wright
Suite 200
2070 Chain Bridge Road
Vienna,  Virginia  22180
 
Phone:  (703) 556-3234
Received: from F29.Tymnet by D35.Tymnet; Sat, 30 Apr 88 14:05:51 PDT
Received: from D35.Tymnet by F29.Tymnet; Sat, 30 Apr 88 14:05:02 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 30 Apr 88 14:00:25 PDT
Return-path: <IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet> 
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 29 APR 88 22:55:38 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A91364@Ontyme.Tymnet 
Subject: "Date: April 29, 1988 To: All System"... 

Date:  April 29, 1988    
     
  To:  All System F-40 Users  
     
Copy:
     
From:  Resource Planning & Management   
     
------------------------------------------------------------------------   
     
     
System 40 at our Fremont Data Center is leaving tymsharing effective  
June 30, 1988. 
     
All Users will be moved to our Dallas Data Center - Host 43 or 47. A  
memo will be sent to your managers with details of the move.
     
If you have any questions, please escalate them to your manager, as we
will be in touch with them during the closure of F-40. 
     
Thank you,
     
Jan Krivanec   
RPM
Received: from F29.Tymnet by D35.Tymnet; Sat, 30 Apr 88 14:05:54 PDT
Received: from D35.Tymnet by F29.Tymnet; Sat, 30 Apr 88 14:05:05 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Sat, 30 Apr 88 14:00:32 PDT
Return-path: <IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet> 
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 29 APR 88 22:59:40 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A91366@Ontyme.Tymnet 
Subject: "TO: SUPERVISOR FR: JAN KRIVANEC"... 

TO:  SUPERVISOR
FR:  JAN KRIVANEC


A ontyme was sent to you message number A91364. Please distribute to all
ontyme users assigned to you by the closing date of May 2, 1988.

If you have any questions, please call me at (415)498-2556. 

Thank you,
Jan
Received: from F29.Tymnet by D35.Tymnet; Wed, 4 May 88 14:04:58 PDT
Received: from D35.Tymnet by F29.Tymnet; Wed, 4 May 88 14:04:19 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 4 May 88 14:00:28 PDT
Return-path: <IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet> 
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 04 MAY 88 18:51:12 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, TXS.SUP@Ontyme.Tymnet 
Message-id: A93145@Ontyme.Tymnet 
Subject: sys 40 shutdown 
SystemF-40Shutdown: 

Date:  May 4, 1988  
     
  To:  Carl Baltrunas    
     
Copy:  FSC System 40 Users    
     
From:  Jan Krivanec 
     
Subj:  System F-40 Shutdown   
     
------------------------------------------------------------------------   
     
     
The following is a list of FSC Internal Ids valid on F-40, which is   
scheduled to shutdown on June 30, 1988. 
     
Many of the ids are only valid on F-40. If they are needed on an 
IBM host, please let me know by May 20th, so that I can validate 
their id's on D-43. On June 3rd, I will then move files for them.
If there are id's that are not needed, please let me know by May 
20th, too. I will remove them from F-40 on that date, or as I    
receive them.  
     
Ids that are valid on other IBM hosts, are responsible for moving
their files to the alternate host by the closing of June 30th.   
If more storage is required to accomodate F-40 files, please call me  
for more resources. 
     
Our IBM hosts (D43) already running successfully on CP Version 4.2    
and (D47) expected to run on CP Version 4.2 beginning on May 7th,
is different from F40, which is running on CP Version 3.2. If you
want to test your application against 4.2, please let me know right   
away. I will setup your id for the test on D43 (if you are not already
there).   
     
  CID   USERNAME      HOST Where Valid  
  ---   --------      ----------------  
     
    8   1213MGR       40 43   
    8   ABELE         40 
    8   AGTDMS        40 
    8   BAIGENT       40 
    8   BSTRONG       40 
    8   CSS1          40 
    8   CSS10         40 
    8   CSS11         40 
    8   CSS5          40 
    8   CSS6          40 
    8   CSS7          40 
    8   CSS8          40 
    8   CSS9          40 
    8   CUSTIN        40 
    8   DEPUY         40 
    8   FINNEGAN      40 
    8   JACKT         40 
    8   LARRYB        40 
    8   MAINTFSC      40 
    8   MIKEA         40 
    8   MORTON        40 
    8   TDFOCUS       40 
    8   TDMS          40 
    8   TDMSDB        40 
   16   DOC2          40 
   16   NDT           40 
   16   OSMAN         40 43   
   16   OSU           40 
   16   TXSDOC        40 43 47
     
If you have any questions or concerns, please give me a call at  
(415)498-2556 or ontyme IPC.J/KRIVANEC. 
     
Thank you,
Jan
Received: from F29.Tymnet by D35.Tymnet; Tue, 10 May 88 14:07:53 PDT
Received: from D35.Tymnet by F29.Tymnet; Tue, 10 May 88 14:06:46 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Tue, 10 May 88 14:00:47 PDT
Return-path: <IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet> 
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 10 MAY 88 21:33:12 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Cc: FSC.SUP@Ontyme.Tymnet, TXS.SUP@Ontyme.Tymnet 
Message-id: A95639@Ontyme.Tymnet 
Subject: "M E M O R A N D U M DATE 9 May"... 

                 M E M O R A N D U M                                            
                                                                                
DATE     9 May 1988                                                             
                                                                                
TO       All F40 Users Moving to D43/D47                                        
                                                                                
FROM     RPM                                                                    
                                                                                
RE       Transferring Files                                                     
                                                                                
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -               
                                                                                
At the request of numerous users, we have outlined the two best ways            
of transferring files between hosts.  In both descriptions, D43 is              
used as the example system; substitute D47 where appropriate.                   
                                                                                
We have used brackets < > to denote special or variable words.                  
Do not type these brackets when entering your command line.                     
                                                                                
If you have any questions, contact Ingrid Lopes (415-498-2564) or Jan           
Krivanec (415-498-2558).                                                        
                                                                                
HOW TO TELECOPY FILES BETWEEN HOSTS                                             
                                                                                
This method works best when your files are small (less than 15 blocks           
each) and the total number of files is less than 50.  If you exceed             
either, you should use the tape procedure described below.                      
                                                                                
1.  Login to your F40 userid.                                                   
                                                                                
2.  Connect to your D43 userid by entering:                                     
          TELECOPY TALK 43                                                      
                                                                                
3.  You will now be in your D43 userid.  Do you have any files here?            
    Check by entering:   LIST * * A                                             
    If there are no files, continue with step 4.  If there are files,           
    do any have the same filenames as those on F40?  If so, decide              
    whether or not you want to keep these duplicate files.  If not,             
    then erase them:                                                            
          ERASE <fn> <ft> A                                                     
    To save a file, rename it:                                                  
          RENAME <oldfn> <oldft> A <newfn> <newft> A                            
    (Another solution is to erase or rename any duplicates on F40.)             
                                                                                
4.  Return to F40 by entering:                                                  
          %%F                                                                   
                                                                                
5.  You can either send each file individually to D43:                          
          TELECOPY SEND <fn> <ft>                                               
                                                                                
    or you can send the files as a group.  First list them in a                 
    group file:                                                                 
          LIST * * A (EXEC                                                      
    Send the group of files:                                                    
          CMS TELECOPY SEND                                                     
    You will be able to watch the process as each file is sent.                 
    NOTE: Duplicate filenames will cause the procedure to fail.                 
                                                                                
6.  When the job is done, you can either logout or return to D43                
    to examine your new disk by entering                                        
            TELECOPY TALK 43                                                    
                                                                                
                                                                                
HOW TO TRANSFER FILES BETWEEN HOSTS USING A TAPE                                
                                                                                
This method of file transfer is best when your files regularly exceed           
15 blocks each and/or you have over 50 files to send.                           
                                                                                
1.  Login to your F40 userid.                                                   
                                                                                
2.  Have a scratch tape mounted and labeled:                                    
          M OP PLS MNT A SCRATCH AS 181 WITH RING AT 6250...                    
          M OP LABEL AS <label>. WILL BE SHIPPED, THANKS.                       
    Include any other information, such as access users. *                      
                                                                                
3.  Send the shipping instructions for the Dallas center:                       
          M OP SHIP VIA AIRBORNE P2 TO: MDC, 6333 HARRY HINES BLVD...           
          M OP DALLAS TX 75235, ATTN: D43 LIBRARY. THANKS.                      
          SL                                                                    
          <ESC>                                                                 
                                                                                
4.  When the tape is ready, do the following:                                   
          REWIND 181                                                            
          TAPE DUMP * * A                                                       
    When the dump has finished, issue:                                          
          TAPE WTM 5                                                            
          REWIND 181                                                            
    If you want to check the tape, issue:                                       
          TAPE SCAN                                                             
    When done, issue:                                                           
          TAPE RUN                                                              
          DET 181                                                               
    Message the operator that you're done:                                      
          M OP ALL DONE W/TAPE AND DRIVE. NEED ANY MORE...                      
          M OP SHIPPING INFO? THANKS.                                           
                                                                                
5.  Your tape will arrive in Dallas in about 2 working days. Login your         
    userid on D43 and check your disk to see if any files exist that            
    have the same filename as those on F40.  The TAPE LOAD procedure will       
    automatically overwrite those duplicate files.  To save duplicates,         
    rename them:                                                                
          RENAME <oldfn> <oldft> A <newfn> <newft> A                            
                                                                                
6.  Request information about your tape by messaging the operator:              
          M OP PLS SEND MY TAPELIST, THANKS.                                    
          SL                                                                    
          <ESC>                                                                 
                                                                                
7.  Pull the information onto your disk by entering: READ *                     
    Examine the list by entering: TAPELIST                                      
    Note the Slot Number of your tape and request to                            
    have it mounted:                                                            
          M OP PLS MOUNT <slot#> AS 181 NO RING AT 6250, THANKS.                
          SL                                                                    
          <ESC>                                                                 
                                                                                
8.  When the tape is mounted, do the following to transfer the files            
    to your disk:                                                               
          REW 181                                                               
          TAPE LOAD * * A                                                       
    When the process is done, enter:                                            
          TAPE RUN                                                              
    If you want the tape saved in the library, detach it and inform the         
    operator you're done.  If you want to release it to scratch, tell           
    the operator:                                                               
          M OP DONE W/TAPE AND DRIVE. RELEASE TAPE TO SCRATCH, THANKS.          
          DET 181                                                               
                                                                                
* Whenever you message the operator, wait for his/her response by invoking      
  wait mode (sleep mode):  SL                                                   
  To re-enter interactive mode, press the Escape key: <ESC>
Received: from F29.Tymnet by D35.Tymnet; Thu, 12 May 88 14:07:29 PDT
Received: from D35.Tymnet by F29.Tymnet; Thu, 12 May 88 14:06:16 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Thu, 12 May 88 14:00:27 PDT
Return-path: <IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet> 
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 12 MAY 88 15:40:32 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A96349@Ontyme.Tymnet 
Subject: F-40 Userids 

Date:  May 12, 1988 
     
  To:  All Managers 
     
Copy:  Supervisors  
     
From:  Jan Krivanec 
     
Subj:  F-40 Userids 
     
------------------------------------------------------------------------   
     
     
     
As you will know system F-40 is shutting down. We have found several  
internal userids valid with one file: MAIL ADDRESS. These users will  
not participate in the move to Dallas. I will simply remove the user  
or cancel (if only valid on F-40) by May 31st.    
     
If you have any questions, please call me at 415 498-2556 or ontyme   
IPC.J/KRIVANEC.
     
Thank you,
Jan
Received: from F29.Tymnet by D35.Tymnet; Tue, 17 May 88 14:11:24 PDT
Received: from D35.Tymnet by F29.Tymnet; Tue, 17 May 88 14:09:36 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Tue, 17 May 88 14:00:25 PDT
Return-path: <NTD.L/JOHNSON@EMSTXS.Ontyme.Tymnet> 
From: NTD.L/JOHNSON@EMSTXS.Ontyme.Tymnet 
Date: 17 MAY 88 17:38:53 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I93395@Ontyme.Tymnet 
Subject: "MCDONNELL DOUGLAS INFORMATION"... 

 
 
 
 
 
                         MCDONNELL DOUGLAS
                     INFORMATION SYSTEMS GROUP
                      INTEROFFICE MEMORANDUM
 
 Network Systems Company            Network Technology Development
 
 
DATE>      17 MAY 88  09:38

TO>        NTD PERSONNEL

COPIES>    ALL CONCERNED PARTIES

FROM>      LINDA JOHNSON


SUBJECT>   OUT-OF-THE-OFFICE:  LANA VAYSBURD


-----------------------------------------------------------------------


Lana Vaysburd will be out of the office until 6/4/88.  Please contact
Roger Rousselle for information pertaining to the Network Communications
Interfaces Department.

lj
Received: from F29.Tymnet by D35.Tymnet; Thu, 19 May 88 14:07:26 PDT
Received: from D35.Tymnet by F29.Tymnet; Thu, 19 May 88 14:06:17 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Thu, 19 May 88 14:00:27 PDT
Return-path: <IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet> 
From: IPC.R/SWANSON@EMSTXS.Ontyme.Tymnet 
Date: 19 MAY 88 20:21:07 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A99611@Ontyme.Tymnet 
Subject: CONVERSION SERVICE 
ISCWORDPROCESSINGCONVERSIONSERVICE: 

TO:       ALL ISC BUSINESS UNITS

SUBJECT:  ISC WORD PROCESSING CONVERSION SERVICE


     ISC is now offering Word Processing Document conversions.  
    This service is being performed in the St. Louis Computer 
    Center.  Software pairings (single-direction-links between 
    incompatibles) are readily available for virtually all major 
    Word Processing packages and dedicated systems on the market 
    today.  Additional pairings will be ordered as needed.  A 
    total list of the available software pairings for conversions 
    can be acquired from the location below.

    For further information regarding the conversion service,  
you may contact:

                  ISC CONVERSION SERVICE
                  MAIL STOP: 307/2E/L238/D15
                  Phone:  314-233-8250
Received: from F29.Tymnet by D35.Tymnet; Wed, 25 May 88 14:05:50 PDT
Received: from D35.Tymnet by F29.Tymnet; Wed, 25 May 88 14:04:59 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 25 May 88 14:00:31 PDT
Return-path: <IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet> 
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 24 MAY 88 23:39:49 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A01722@Ontyme.Tymnet 
Subject: FSC Internal User move F-40 to D-43 

Date:  May 24, 1988 
     
  To:  FSC Internal Users valid on host F-40 
       TXS Internal Users valid on host F-40 
     
Copy:
     
From:  Jan Krivanec 
     
Subj:  FSC Internal User move F-40 to D-43   
     
------------------------------------------------------------------------   
     
     
     
In two weeks, I will be moving your accounts from F40 to D43. The move
will begin at 5pm pdt on June 3rd. 
     
A previous memo was sent to you on May 4th, listing all users found   
on F40. Several ids were found valid on a Dallas IBM host. These users
are responsible for moving their own files to Dallas. A memo regarding
information to transfer files to Dallas was sent on May 10th.    
     
Again, here is the list of userids that I will be moving to D-47:
     
MAINTFSC  
ABELE
AGTDMS    
CSS1 
CSS10
CSS11
CSS5 
CSS6 
CSS7 
CSS8 
CSS9 
DEPUY
FINNEGAN  
JACKT
LARRYB    
MIKEA
MORTON    
TDFOCUS   
TDMS 
TDMSDB    
BAIGENT   
BSTRONG   
CUSTIN    
DOC2 
NDT  
OSU  
BRUCES    
FSCSITE   
JCARTER   
WFACDB    
WNFE 
CADPLOT   
CADPRO3   
CADPRO4   
CADPRO5   
CADTEST   
DWALPOLE  
HVBURTON  
JCCHEN    
JWILLOTT  
MIKEMO    
MSTRBRD   
NORTHRIP  
RBROWN    
SOLOMON   
SULRICH   
JCM  
     
And again, this is the list of userids that are responsible for moving
their files to Dallas by the closing of June 30th.
     
1213MGR   
OSMAN
TXSDOC    
ANVERM    
MOORING   
PKRUMV    
SALTYRON  
BUDGET    
     
And finally, this list contains users only valid on F-40 with one file:    
MAIL ADDRESS. These users will be removed from the move and will be   
removed from F40 on May 31, 1988:  
     
ARELLA    
FACILITY  
FSCLI
LAUVER    
WAGNERD   
WWPC 
WWPM 
BILLROD   
BROWNR    
CHINJEFF  
DBLISS    
GOLOBIC   
GUINASSO  
JGIUSTI   
KENNEDY   
KOLICZEW  
PATELN    
     
To ensure a smooth center-to-center customer move, the users that I am
moving must be FREE of bad files. If BAD FILES  are found on the day of    
the move, I will delete them from their directory.
     
Any users who have BATCH jobs, must be canceled on June 3rd and re-   
submitted on D-47.  
     
The users involved in this move, must be logged off at the time of the
move. This includes disconnect users. Any users found logged on when  
the move begins, will be messaged to log off within two minutes. After
a two minute lapse, the users will be forced off. 
     
If you have any questions, I can be reached at (415)498-2556.    
     
Thank you,
Jan
Received: from F29.Tymnet by D35.Tymnet; Wed, 25 May 88 14:06:07 PDT
Received: from D35.Tymnet by F29.Tymnet; Wed, 25 May 88 14:05:18 PDT
Received: from EMSTXS.Ontyme.Tymnet by D35.Tymnet; Wed, 25 May 88 14:01:04 PDT
Return-path: <TYMHQ.C/DEGABRIELLE@EMSTXS.Ontyme.Tymnet> 
From: TYMHQ.C/DEGABRIELLE@EMSTXS.Ontyme.Tymnet 
Date: 25 MAY 88 17:38:23 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I96987@Ontyme.Tymnet 
Subject: USA Volleyball Teams 
U.S.A.VolleyballMen'sTeamSchedule: 

                                  MCDONNELL DOUGLAS
                              INFORMATION SYSTEMS GROUP
                                       TYMNET

DATE>      11 MAY 88  15:28

TO>        Tymnet

COPIES>    

FROM>      Clint DeGabrielle


SUBJECT>   U.S.A. Volleyball Men's Team Schedule


-----------------------------------------------------------------------


The U.S.A. men's volleyball team will be playing over
twenty-five matches between now and the Olympics.  Get out
and see a match in your area and tell the coaches you are  
from Tymnet.  Here is the schedule including the Olympics:
 
Date               Opponent                   Location
 
5/20-5/30    Brazil, Canada, Italy    5/23  Verona, Italy
             Korea, Japan, Sweden     5/27  Padua, Italy
             Russia                   5/29  Treviso, Italy
 
6/14         Russia                   Portland Civic Center-
                                      Portland, ME
6/15         Russia                   Springfield Civic Center-
                                      Springfield, MA
6/16         Russia                   Dupont Pavilion - 
                                      Philadelphia, PA
6/19         Russia                   American University -
                                      Washington, D.C.
6/22         U.S.A. Cup, France,      The Forum, Los Angeles
             Japan, Russia, U.S.
6/24         U.S.A. Cup, France,      The Forum, Los Angeles
             Japan, Russia, U.S.
6/25         U.S.A. Cup, France,      The Forum, Los Angeles
             Japan, Russia, U.S.
7/7-7/17     Korea                    In U.S. locations to be
                                      announced.
8/4          France                   Nantes, France
                                                                Page  2

8/5          France                   Paris, France
8/7          Russia                   Tallinn, Russia
8/9-8/15     Savin Cup                Riga, Russia
8/10         Japan                    Osaka, Japan
8/11         Japan                    Nagoya, Japan
 
                 Olympics
 
9/18         Japan                    Seoul, Korea
9/19         Holland                  Seoul, Korea
9/22         Argentina                Seoul, Korea
9/24         France                   Seoul, Korea
9/26         Trinesia                 Seoul, Korea
9/28         Semi Finals              Hanyang University
9/30         Semi Finals              Hanyang University
10/2         Finals                   Chamsil Gymnasium
 
The U.S. is in group B with Japan, Holland, Argentina, France 
and Tanesia.  Group A consists of Brazil, Bulgaria, Cuba, 
Italy, Korea and Russia.  The top two teams from each group 
meet in the semi finals and the two winners play for the Gold 
and Silver in the finals.
 
Womens' schedule will be out Friday.
 
** Note - Correction on Mens Team name (previous OnTyme): 
 
Should be Bob Ctvrtlik instead of Cturtlik.  
 
/to
From: Judy Smith <TXSSUP> 
Date: Fri, 7 Oct 88 16:20:06 PDT 
To: Carl A Baltrunas <CARL>, Joe Smith <JMS>, Osman Guven <OSMAN>, Craig
	Fletcher <FLETCHERC> 
Subject: First Time Sending by JA/Smith 

Carl has just taught me how to use this machine.
From: Judy Smith <TXSSUP> 
Date: Fri, 7 Oct 88 16:29:46 PDT 
To: txssup 
Subject: test 

hellow test
   5 ]