Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 23 Dec 86 23:27:18 UT 
To: CARL 
Subject: Req #2420 DSK:(DENCOFF)TEST.CTL Done-Error 

; Processed:  Req #2420 DSK:(CARL)TEST.LOG=DSK:(DENCOFF)TEST.CTL
; Scheduled:  23-Dec-86 15:26:43
; Actual run: 23-Dec-86 15:26:48
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Error  at  23-Dec-86 15:27:15
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 24 Dec 86 0:29:03 UT 
To: CARL 
Subject: Req #2423 DSK:(DENCOFF)TEST.CTL Done-Stop 

; Processed:  Req #2423 DSK:(CARL)TEST.LOG=DSK:(DENCOFF)TEST.CTL
; Scheduled:  23-Dec-86 16:28:19
; Actual run: 23-Dec-86 16:28:22
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  23-Dec-86 16:29:00
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 24 Dec 86 1:18:03 UT 
To: CARL 
Subject: Req #2425 DSK:(DENCOFF)TEST.CTL Done-Stop 

; Processed:  Req #2425 DSK:(CARL)TEST.LOG=DSK:(DENCOFF)TEST.CTL
; Scheduled:  23-Dec-86 17:17:15
; Actual run: 23-Dec-86 17:17:21
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  23-Dec-86 17:17:59
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 24 Dec 86 1:49:09 UT 
To: CARL 
Subject: Req #2427 DSK:(CARL)TEST1.CTL Done-End 

; Processed:  Req #2427 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST1.CTL
; Scheduled:  23-Dec-86 17:47:44
; Actual run: 23-Dec-86 17:47:49
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  23-Dec-86 17:49:07
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 24 Dec 86 2:09:38 UT 
To: CARL 
Subject: Req #2428 DSK:(CARL)TEST1.CTL Done-End 

; Processed:  Req #2428 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST1.CTL
; Scheduled:  24-Dec-86 02:08:23
; Actual run: 24-Dec-86 02:08:27
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  24-Dec-86 02:09:35
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 24 Dec 86 3:03:27 UT 
To: CARL 
Subject: Req #2430 DSK:(CARL)TEST1.CTL Done-End 

; Processed:  Req #2430 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST1.CTL
; Scheduled:  23-Dec-86 19:02:23
; Actual run: 23-Dec-86 19:02:29
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  23-Dec-86 19:03:23
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Thu, 25 Dec 86 12:20:34 UT 
To: CARL 
Subject: Req #2441 DSK:(CARL)XFER.CTL Abort-Time (43) 

; Processed:  Req #2441 DSK:(CARL)XFER.LOG=DSK:(CARL)XFER.CTL
; Scheduled:  25-Dec-86 00:20:00
; Actual run: 25-Dec-86 00:20:02
;
; Options:  Log:Append Mail:Error Restart:Start Unique:Job
; Limits:  Time 240  TRUs 0
; Flags:   Logout
; Status:  Abort-Time (43)  at  25-Dec-86 04:20:30
;
; Output recorded in file DSK:(CARL)XFER.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Mon, 29 Dec 86 21:06:02 UT 
To: CARL 
Subject: Req #2646 DSK:(TELE)ASMC.CTL Done-Error 

; Processed:  Req #2646 DSK:(TELE)ASMC.LOG=DSK:(TELE)ASMC.CTL
; Scheduled:  29-Dec-86 13:05:05
; Actual run: 29-Dec-86 13:05:36
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 500  TRUs 0
; Flags: 
; Status:  Done-Error  at  29-Dec-86 13:05:58
;
; Output recorded in file DSK:(TELE)ASMC.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Mon, 29 Dec 86 21:16:01 UT 
To: CARL 
Subject: Req #2647 DSK:(TELE)ASMC.CTL Done-End 

; Processed:  Req #2647 DSK:(TELE)ASMC.LOG=DSK:(TELE)ASMC.CTL
; Scheduled:  29-Dec-86 13:07:25
; Actual run: 29-Dec-86 13:07:31
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 300  TRUs 0
; Flags: 
; Status:  Done-End  at  29-Dec-86 13:15:57
;
; Output recorded in file DSK:(TELE)ASMC.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Mon, 29 Dec 86 21:28:19 UT 
To: CARL 
Subject: Req #2649 DSK:(TELE)ASMC.CTL Done-End 

; Processed:  Req #2649 DSK:(TELE)ASMC.LOG=DSK:(TELE)ASMC.CTL
; Scheduled:  29-Dec-86 13:18:16
; Actual run: 29-Dec-86 13:18:25
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 300  TRUs 0
; Flags: 
; Status:  Done-End  at  29-Dec-86 13:28:16
;
; Output recorded in file DSK:(TELE)ASMC.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Mon, 29 Dec 86 22:30:37 UT 
To: CARL 
Subject: Req #2652 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2652 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  29-Dec-86 14:27:36
; Actual run: 29-Dec-86 14:27:41
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  29-Dec-86 14:30:34
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Mon, 29 Dec 86 22:48:00 UT 
To: CARL 
Subject: Req #2653 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2653 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  29-Dec-86 14:44:32
; Actual run: 29-Dec-86 14:44:51
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  29-Dec-86 14:47:55
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Mon, 29 Dec 86 23:56:33 UT 
To: CARL 
Subject: Req #2656 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2656 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  29-Dec-86 15:52:12
; Actual run: 29-Dec-86 15:52:16
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  29-Dec-86 15:56:30
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 8:32:57 UT 
To: CARL 
Subject: Req #2682 DSK:(CARL)TEST.CTL Done-Stop 

; Processed:  Req #2682 DSK:(CARL)QUIT.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 30-Dec-86 08:32:11
;
; Options:  Log:Supersede Mail:Always
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  30-Dec-86 08:32:54
;
; Output recorded in file DSK:(CARL)QUIT.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 9:59:50 UT 
To: CARL 
Subject: Req #2685 DSK:(CARL)TEST.CTL Done-Stop 

; Processed:  Req #2685 DSK:(CARL)STOP.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 09:58:56
; Actual run: 30-Dec-86 09:59:28
;
; Options:  Log:Supersede Mail:Always
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  30-Dec-86 09:59:47
;
; Output recorded in file DSK:(CARL)STOP.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 10:00:09 UT 
To: CARL 
Subject: Req #2686 DSK:(CARL)TEST.CTL Done-Stop 

; Processed:  Req #2686 DSK:(CARL)QUIT.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 09:59:38
; Actual run: 30-Dec-86 09:59:56
;
; Options:  Log:Supersede Mail:Always
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  30-Dec-86 10:00:06
;
; Output recorded in file DSK:(CARL)QUIT.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 10:03:33 UT 
To: CARL 
Subject: Req #2687 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2687 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 10:00:02
; Actual run: 30-Dec-86 10:00:10
;
; Options:  Log:Supersede Mail:Always
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Dec-86 10:03:30
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 10:18:45 UT 
To: CARL 
Subject: Req #2689 DSK:(CARL)F.CTL Done-Stop 

; Processed:  Req #2689 DSK:(CARL)F.LOG=DSK:(CARL)F.CTL
; Scheduled:  30-Dec-86 10:18:34
; Actual run: 30-Dec-86 10:18:37
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  30-Dec-86 10:18:42
;
; Output recorded in file DSK:(CARL)F.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 10:41:24 UT 
To: CARL 
Subject: Req #2691 DSK:(CARL)TEST.CTL Done-Stop 

; Processed:  Req #2691 DSK:(CARL)STOP.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 10:41:02
; Actual run: 30-Dec-86 10:41:14
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  30-Dec-86 10:41:19
;
; Output recorded in file DSK:(CARL)STOP.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 10:54:56 UT 
To: CARL 
Subject: Req #2692 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2692 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 02:51:42
; Actual run: 30-Dec-86 02:51:49
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Dec-86 02:54:53
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 30 Dec 86 20:15:20 UT 
To: CARL 
Subject: Req #2710 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2710 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 12:11:38
; Actual run: 30-Dec-86 12:11:44
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Dec-86 12:15:17
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 31 Dec 86 0:46:16 UT 
To: CARL 
Subject: Req #2721 DSK:(CARL)F.CTL Done-End 

; Processed:  Req #2721 DSK:(CARL)F.LOG=DSK:(CARL)F.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 30-Dec-86 16:44:26
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Dec-86 16:46:13
;
; Output recorded in file DSK:(CARL)F.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 31 Dec 86 4:05:59 UT 
To: CARL 
Subject: Req #2728 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2728 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 20:03:13
; Actual run: 30-Dec-86 20:03:18
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Dec-86 20:05:56
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Wed, 31 Dec 86 6:38:47 UT 
To: CARL 
Subject: Req #2735 DSK:(CARL)TEST.CTL Done-End 

; Processed:  Req #2735 DSK:(CARL)TEST.LOG=DSK:(CARL)TEST.CTL
; Scheduled:  30-Dec-86 22:35:10
; Actual run: 30-Dec-86 22:35:12
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Dec-86 22:38:44
;
; Output recorded in file DSK:(CARL)TEST.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 27 Jan 87 15:25:03 UT 
To: CARL 
Subject: Req #3734 DSK:(CARL)ASH.CTL Done-End 

; Processed:  Req #3734 DSK:(CARL)ASH.LOG=DSK:(CARL)ASH.CTL
; Scheduled:  27-Jan-87 04:23:06
; Actual run: 27-Jan-87 04:23:43
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Done-End  at  27-Jan-87 07:25:00
;
; Output recorded in file DSK:(CARL)ASH.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Tue, 27 Jan 87 15:25:07 UT 
To: CARL 
Subject: Req #3735 DSK:(CARL)ASHQ.CTL Done-End 

; Processed:  Req #3735 DSK:(CARL)ASHQ.LOG=DSK:(CARL)ASHQ.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 27-Jan-87 04:24:20
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Done-End  at  27-Jan-87 07:25:04
;
; Output recorded in file DSK:(CARL)ASHQ.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 0:07:41 UT 
To: CARL 
Subject: Req #3903 DSK:(SYSFIL)SYSTAT.CTL Done-End 

; Processed:  Req #3903 DSK:(SYSFIL)SYSTAT.LOG=DSK:(SYSFIL)SYSTAT.CTL
; Scheduled:  30-Jan-87 16:03:39
; Actual run: 30-Jan-87 16:03:51
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Jan-87 16:07:36
;
; Output recorded in file DSK:(SYSFIL)SYSTAT.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 0:27:50 UT 
To: CARL 
Subject: Req #3905 DSK:(SYSFIL)SYSTAT.CTL Done-End 

; Processed:  Req #3905 DSK:(SYSFIL)SYSTAT.LOG=DSK:(SYSFIL)SYSTAT.CTL
; Scheduled:  30-Jan-87 16:25:17
; Actual run: 30-Jan-87 16:25:21
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Jan-87 16:27:44
;
; Output recorded in file DSK:(SYSFIL)SYSTAT.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 1:14:13 UT 
To: CARL 
Subject: Req #3906 DSK:(CARL)1.CTL Done-End 

; Processed:  Req #3906 DSK:(CARL)1.LOG=DSK:(CARL)1.CTL
; Scheduled:  30-Jan-87 17:13:07
; Actual run: 30-Jan-87 17:13:16
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Jan-87 17:14:09
;
; Output recorded in file DSK:(CARL)1.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 1:17:48 UT 
To: CARL 
Subject: Req #3908 DSK:(CARL)1.CTL Done-Error 

; Processed:  Req #3908 DSK:(CARL)1.LOG=DSK:(CARL)1.CTL
; Scheduled:  30-Jan-87 17:17:29
; Actual run: 30-Jan-87 17:17:35
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Error  at  30-Jan-87 17:17:42
;
; Output recorded in file DSK:(CARL)1.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 1:34:09 UT 
To: CARL 
Subject: Req #3909 DSK:(CARL)PPN.CTL Done-End 

; Processed:  Req #3909 DSK:(CARL)PPN.LOG=DSK:(CARL)PPN.CTL
; Scheduled:  30-Jan-87 17:33:16
; Actual run: 30-Jan-87 17:33:21
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Jan-87 17:34:05
;
; Output recorded in file DSK:(CARL)PPN.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 1:38:03 UT 
To: CARL 
Subject: Req #3910 DSK:(CARL)1.CTL Done-End 

; Processed:  Req #3910 DSK:(CARL)1.LOG=DSK:(CARL)1.CTL
; Scheduled:  30-Jan-87 17:37:00
; Actual run: 30-Jan-87 17:37:06
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Jan-87 17:38:00
;
; Output recorded in file DSK:(CARL)1.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 2:18:54 UT 
To: CARL 
Subject: Req #3913 DSK:(CARL)1.CTL Done-End 

; Processed:  Req #3913 DSK:(CARL)1.LOG=DSK:(CARL)1.CTL
; Scheduled:  30-Jan-87 18:17:58
; Actual run: 30-Jan-87 18:18:01
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  30-Jan-87 18:18:50
;
; Output recorded in file DSK:(CARL)1.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 2:20:51 UT 
To: CARL 
Subject: Req #3914 DSK:(CARL)1.CTL Done-Error 

; Processed:  Req #3914 DSK:(CARL)1.LOG=DSK:(CARL)1.CTL
; Scheduled:  30-Jan-87 18:20:37
; Actual run: 30-Jan-87 18:20:42
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Error  at  30-Jan-87 18:20:47
;
; Output recorded in file DSK:(CARL)1.LOG.

Reply-to: SUBMIT 
From: X62 Job Processor 
Sender: OPER@X62.Tymnet 
Date: Sat, 31 Jan 87 2:22:15 UT 
To: CARL 
Subject: Req #3915 DSK:(DENCOFF)TST2.CTL Done-Stop 

; Processed:  Req #3915 DSK:(DENCOFF)TST2=DSK:(DENCOFF)TST2.CTL
; Scheduled:  30-Jan-87 18:21:47
; Actual run: 30-Jan-87 18:21:53
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-Stop  at  30-Jan-87 18:22:12
;
; Output recorded in file DSK:(DENCOFF)TST2.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Wed, 20 May 87 19:36:07 UT 
To: CARL 
Subject: Req #8591 DSK:(CARL)FOO.CTL Done-End 

; Processed:  Req #8591 DSK:(CARL)FOO.CTL
; Scheduled:  20-May-87 12:33:28
; Actual run: 20-May-87 12:33:46
;
; Options:  Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  20-May-87 12:36:02

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Wed, 20 May 87 19:37:31 UT 
To: CARL 
Subject: Req #8592 DSK:(CARL)FOO.CTL Done-End 

; Processed:  Req #8592 DSK:(CARL)FOO.LOG=DSK:(CARL)FOO.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 20-May-87 12:34:13
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags: 
; Status:  Done-End  at  20-May-87 12:37:28
;
; Output recorded in file DSK:(CARL)FOO.LOG.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Wed, 3 Jun 87 0:37:53 UT 
To: CARL 
Subject: Req #8985 DSK:(CARL)FOO.CTL Abort-Time (4) 

; Processed:  Req #8985 DSK:(CARL)FOO.LOG=DSK:(CARL)FOO.CTL
; Scheduled:  02-Jun-87 17:31:01
; Actual run: 02-Jun-87 17:31:31
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 5  TRUs 0
gs: 
; Status:  Abort-Time (4)  at  02-Jun-87 17:37:48
;
; Output recorded in file DSK:(CARL)FOO.LOG.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Tue, 4 Aug 87 4:51:51 UT 
To: CARL 
Subject: Req #10917 DSK:(CARL)LOGOUT.CTL Done-End 

; Processed:  Req #10917 DSK:(CARL)LOGOUT.LOG=DSK:(CARL)LOGOUT.CTL
; Scheduled:  03-Aug-87 21:51:00
; Actual run: 03-Aug-87 21:51:02
;
; Options:  Log:Append Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Logout
; Status:  Done-End  at  03-Aug-87 21:51:47
;
; Output recorded in file DSK:(CARL)LOGOUT.LOG.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Tue, 4 Aug 87 4:56:45 UT 
To: CARL 
Subject: Req #10918 DSK:(CARL)LOGOUT.CTL Done-End 

; Processed:  Req #10918 DSK:(CARL)LOGOUT.LOG=DSK:(CARL)LOGOUT.CTL
; Scheduled:  03-Aug-87 21:56:00
; Actual run: 03-Aug-87 21:56:02
;
; Options:  Log:Append Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Logout
; Status:  Done-End  at  03-Aug-87 21:56:42
;
; Output recorded in file DSK:(CARL)LOGOUT.LOG.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Tue, 4 Aug 87 5:01:42 UT 
To: CARL 
Subject: Req #10919 DSK:(CARL)LOGOUT.CTL Done-End 

; Processed:  Req #10919 DSK:(CARL)LOGOUT.LOG=DSK:(CARL)LOGOUT.CTL
; Scheduled:  03-Aug-87 22:01:00
; Actual run: 03-Aug-87 22:01:03
;
; Options:  Log:Append Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Logout
; Status:  Done-End  at  03-Aug-87 22:01:39
;
; Output recorded in file DSK:(CARL)LOGOUT.LOG.

Reply-to: SUBMIT 
From: X930 Job Processor 
Sender: PERPOPER@X930.Tymnet 
Date: Wed, 5 Aug 87 5:33:01 UT 
To: CARL 
Subject: Req #10950 DSK:(XEXEC)RDIST.SAV Done-End 

; Processed:  Req #10950 DSK:(CARL)RDIST.LOG= Running DSK:(XEXEC)RDIST.SAV
; Scheduled:  04-Aug-87 22:03:16
; Actual run: 04-Aug-87 22:05:30
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run
; Status:  Done-End  at  04-Aug-87 22:32:56
;
; Output recorded in file DSK:(CARL)RDIST.LOG.

Received: from F26.Tymnet by X930.Tymnet; Thu, 6 Aug 87 1:51:10 PDT
Return-path: <PERPOPER@F26.Tymnet> 
Reply-to: SUBMIT 
From: F26 Job Processor 
Sender: PERPOPER@F26.Tymnet 
Date: Thu, 6 Aug 87 8:50:52 UT 
To: CARL 
Subject: Req #10840 DSK:(CARL)RDIST.CTL Done-End -Normal- 

; Processed:  Req #10840 DSK:(CARL)RDIST.LOG=DSK:(CARL)RDIST.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 06-Aug-87 01:45:42
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Done-End   -Normal-
;
; Output recorded in file DSK:(CARL)RDIST.LOG.

Received: from F70.Tymnet by X930.Tymnet; Thu, 6 Aug 87 2:00:29 PDT
Return-path: <PERPOPER@F70.Tymnet> 
Reply-to: SUBMIT 
From: F70 Job Processor 
Sender: PERPOPER@F70.Tymnet 
Date: Thu, 6 Aug 87 9:00:16 UT 
To: CARL 
Subject: Req #13886 DSK:(CARL)RDIST.CTL Done-End -Normal- 

; Processed:  Req #13886 DSK:(CARL)RDIST.LOG=DSK:(CARL)RDIST.CTL
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 06-Aug-87 01:56:46
;
; Options:  Log:Supersede Mail:Always Unique:Job
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Done-End   -Normal-
;
; Output recorded in file DSK:(CARL)RDIST.LOG.

 x 