! Assumed:
!   1)	the terminal string will recognise single or double quoted strings
!	and correctly handle embedded occurrences of the terminators
!   2)  the terminal ident will recognise ONLY strings of letters and
!	will upshift them  (necessary in order to recognise the keywords)

terminal 0	tab
terminal 1	space
terminal 2	string
terminal 3	(
terminal 4	)
terminal 5	*
terminal 6	+
terminal 7	,
terminal 8	-
terminal 9	.
terminal 10	/
terminal 11	0
terminal 12	1
terminal 13	2
terminal 14	3
terminal 15	4
terminal 16	5
terminal 17	6
terminal 18	7
terminal 19	8
terminal 20	9
terminal 21	:
terminal 22	<
terminal 23	=
terminal 24	>
terminal 25	#
terminal 26	?
terminal 27	[
terminal 28	]
terminal 29	_
terminal 30	letter
terminal 31	ident

terminal keyword DELETE
terminal keyword EXPUNGE
terminal keyword UNDELETE
terminal keyword DECLARE
terminal keyword ALL
terminal keyword CP
terminal keyword UPD
terminal keyword AP
terminal keyword RD
terminal keyword RUN
terminal keyword LK
terminal keyword NO
terminal keyword DIRECTORY
terminal keyword FILES
terminal keyword COPY
terminal keyword RENAME
terminal keyword TO
terminal keyword LICENSE
terminal keyword WC
terminal keyword RC
terminal keyword OP
terminal keyword SY
terminal keyword GD
terminal keyword TD
terminal keyword ST
terminal keyword HF
terminal keyword JL
terminal keyword AC
terminal keyword XC
terminal keyword RP
terminal keyword RF
terminal keyword RA
terminal keyword WP
terminal keyword WF
terminal keyword WA

terminal keyword SAME
terminal keyword TERMINAL

production 0	command		::= command-line

! production 1	command-line	::= delete-command
! production 2	command-line	::= directory-command
! production 3	command-line	::= copy-command
production 4	command-line	::= license-command

! production 5	delete-command	::= delete-class file-list

! production 6	delete-class	::= DELETE
! production 7	delete-class	::= EXPUNGE
! production 8	delete-class	::= UNDELETE
! production 9	delete-class	::= DECLARE prot prot prot

! production 10	prot		::= ALL
! production 11	prot		::= CP
! production 12	prot		::= UPD
! production 13	prot		::= AP
! production 14	prot		::= RD
! production 15	prot		::= RUN
! production 16	prot		::= LK
! production 17	prot		::= NO

! production 18	directory-command ::= directory-keyword
! production 19	directory-command ::= directory-keyword directory-file		  
! production 20	directory-command ::= directory-keyword file-list
! production 21	directory-command ::= directory-keyword directory-file file-list

! production 22	directory-keyword ::= DIRECTORY
! production 23	directory-keyword ::= FILES

! production 24	directory-file	  ::= file-spec =
! production 25	directory-file    ::= file-spec _

! production 26	copy-command	::= copy-keyword link-group copy-director link-group

! production 27	copy-keyword	::= COPY
! production 28	copy-keyword	::= RENAME

! production 29	copy-director	::= TO
! production 30	copy-director	::= ,
! production 31	copy-director	::= =
! production 32	copy-director	::= _

production 33	license-command	::= LICENSE group-list
production 34	license-command	::= LICENSE group-list license-list

production 35	license-list	::= license-name
production 36	license-list	::= license-list license-name

production 37	license-name	::= WC
production 38	license-name	::= RC
production 39	license-name	::= OP
production 40	license-name	::= SY
production 41	license-name	::= GD
production 42	license-name	::= TD
production 43	license-name	::= ST
production 44	license-name	::= HF
production 45	license-name	::= JL
production 46	license-name	::= AC
production 47	license-name	::= XC
production 48	license-name	::= RP
production 49	license-name	::= RF
production 50	license-name	::= RA
production 51	license-name	::= WP
production 52	license-name	::= WF
production 53	license-name	::= WA

! production 54	file-list	::= group-list
! production 55	file-list	::= switch-list group-list

production 56	group-list	::= link-group
production 57	group-list	::= group-list , link-group

production 58	link-group	::= file-spec-list
production 59	link-group	::= link file-spec-list

production 60	link		::= +
production 61	link		::= -

production 62	file-spec-list	::= switched-file-spec
production 63	file-spec-list	::= file-spec-list switched-file-spec

production 64	switched-file-spec ::= file-spec
production 65	switched-file-spec ::= file-spec switch-list

production 66	switch-list	::= switch
production 67	switch-list	::= switch-list switch

production 68	switch		::= / switch-name
production 69	switch		::= / switch-name switch-arg-list

production 70	switch-arg-list	::= switch-argument
production 71	switch-arg-list	::= switch-arg-list switch-argument

production 72	switch-argument	::= : value
! production 73	switch-argument	::= white value

! production 74	white		::= space
! production 75	white		::= tab
! production 76	white		::= white space
! production 77	white		::= white tab

production 78	switch-name	::= letters
production 79	switch-name	::= digits
production 80	switch-name	::= ?

production 81	value		::= letters-or-digits
production 82	value		::= string
! production 83	value		::= file-spec
production 84	value		::= ?

production 85	file-spec	::= file-keyword
production 86	file-spec	::= file-name
production 87	file-spec	::= device file-name

production 88	file-keyword	::= ALL
production 89	file-keyword	::= SAME
production 90	file-keyword	::= TERMINAL

production 91	device		::= letter :
production 92	device		::= letter letters-or-digits :

production 93	file-name	::= file
production 94	file-name	::= user file
production 95	file-name	::= file user
production 96	file-name	::= user

production 97	user		::= ( user-name )
production 98	user		::= [ ppn ]

production 99	user-name	::= user-character
production 100	user-name	::= user-name user-character

production 101	user-character	::= letter
production 102	user-character	::= digit
production 103	user-character	::= .
production 104	user-character	::= /
production 105	user-character	::= -
production 106	user-character	::= space
production 107	user-character	::= *

production 108	ppn		::= -
production 109	ppn		::= ppn-half , ppn-half

production 110	ppn-half	::=
production 111	ppn-half	::= *
production 112	ppn-half	::= ppn-character-list
production 113	ppn-half	::= ppn-character-list *

production 114	ppn-character-list ::= ppn-character
production 115	ppn-character-list ::= ppn-character-list ppn-character

production 116	ppn-character	::= octal-digit
production 117	ppn-character	::= #
production 118	ppn-character	::= ?

production 119	file		::= wild protection
production 120	file		::= wild . protection
production 121	file		::= wild . wild protection

production 122	wild		::= *
production 123	wild		::= wild-character-list
production 124	wild		::= wild-character-list *

production 125	wild-character-list ::= wild-character
production 126	wild-character-list ::= wild-character-list wild-character

production 127	wild-character	::= letter
production 128	wild-character	::= digit
production 129	wild-character	::= #
production 130	wild-character	::= ?

production 131	protection	::=
production 132	protection	::= < octal-digit octal-digit octal-digit >

production 133	letters-or-digits ::= letters
production 134	letters-or-digits ::= digits
production 135	letters-or-digits ::= letters-or-digits letters
production 136	letters-or-digits ::= letters-or-digits digits

production 137	letters		::= ident

production 138	digits		::= digit
production 139	digits		::= digits digit

production 140	digit		::= 0
production 141	digit		::= 1
production 142	digit		::= 2
production 143	digit		::= 3
production 144	digit		::= 4
production 145	digit		::= 5
production 146	digit		::= 6
production 147	digit		::= 7
production 148	digit		::= 8
production 149	digit		::= 9

production 150	octal-digit	::= 0
production 151	octal-digit	::= 1
production 152	octal-digit	::= 2
production 153	octal-digit	::= 3
production 154	octal-digit	::= 4
production 155	octal-digit	::= 5
production 156	octal-digit	::= 6
production 157	octal-digit	::= 7
  