#TUMS ARCHIVE

This is mail sent or returned to PERPOPER, a non-user directory.
PERPOPER is used by the PERP replacement system XEXEC-EXECX.


RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@X32.Tymnet 
Date: Fri, 28 Aug 87 3:07:23 UT 
To: PERPOPER@X32.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
maiQueue: error return



----------
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Subject: Req #11445 :() Abort-Input (0) 

; Processed:  Req #0 :()
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 01-Jan-64 00:00:00
;
; Options:  Mail:Error
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Input (0)  at  28-Aug-87 03:07:20

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@X32.Tymnet 
Date: Wed, 12 Oct 88 2:38:33 UT 
To: PERPOPER@X32.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
maiQueue: error return



----------
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Subject: Req #13651 :() Abort-Notice (0) 

; Processed:  Req #0 :()
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 01-Jan-64 00:00:00
;
; Options:  Mail:Error
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Notice (0)  at  12-Oct-88 02:38:32

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@X32.Tymnet 
Date: Fri, 21 Oct 88 21:14:31 UT 
To: PERPOPER@X32.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
Invalid address(s):
<JOE>


----------
RCPT To: <JOE> 
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Date: Fri, 21 Oct 88 21:14:30 UT 
To: SYS 
Subject: Req #13711 DSK:(SYS)REDSAT.SAV Done-End 

; Processed:  Req #13711  Running DSK:(SYS)REDSAT.SAV
; Scheduled:  21-Oct-88 14:14:24
; Actual run: 21-Oct-88 14:14:27
;
; Options:  Mail:Always Unique:Job
; Limits:  Time 60  TRUs 0
; Flags:   Run  Detach  Logout
; Status:  Done-End  at  21-Oct-88 14:14:28

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@X32.Tymnet 
Date: Wed, 26 Oct 88 9:33:14 UT 
To: PERPOPER@X32.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
maiQueue: error return



----------
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Subject: Req #13721 :() Abort-Time (0) 

; Processed:  Req #0 :()
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 01-Jan-64 00:00:00
;
; Options:  Mail:Error
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  26-Oct-88 09:33:11

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@X32.Tymnet 
Date: Sat, 29 Oct 88 6:06:24 UT 
To: PERPOPER@X32.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
maiQueue: error return



----------
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Subject: Req #13733 :() Abort-Input (0) 

; Processed:  Req #0 :()
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 01-Jan-64 00:00:00
;
; Options:  Mail:Error
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Input (0)  at  29-Oct-88 06:06:21

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@X32.Tymnet 
Date: Mon, 5 Dec 88 4:54:27 UT 
To: PERPOPER@X32.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
maiQueue: error return



----------
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Subject: Req #13941 :() Abort-Time (0) 

; Processed:  Req #0 :()
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 01-Jan-64 00:00:00
;
; Options:  Mail:Error
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  05-Dec-88 04:54:24

RCPT To: <!PERPOPER/XEXECX.MSG>
From: Postmaster@X32.Tymnet 
Date: Mon, 5 Dec 88 20:12:51 UT 
To: PERPOPER@X32.Tymnet 
Subject: Returned MAIL 

The following message was not delivered because:
maiQueue: error return



----------
Reply-to: SUBMIT 
From: X32 Job Processor 
Sender: PERPOPER@X32.Tymnet 
Subject: Req #13941 :() Abort-Time (0) 

; Processed:  Req #0 :()
; Scheduled:  01-Jan-64 00:00:00
; Actual run: 01-Jan-64 00:00:00
;
; Options:  Mail:Error
; Limits:  Time 0  TRUs 0
; Flags: 
; Status:  Abort-Time (0)  at  05-Dec-88 20:12:49

