	  Directories over 2k pages

		    directory        authored
  who              files/pages      files/pages
-----------------------------------------------
SYS                 769   15878       0       0   
M33                1090   14382      62     281   
SDANIELS            931    6739    1567   14642   
OSP                 338    6413       1       8   
MPL                 539    5602      16     120   
CARL                558    5599    1661   20754   
UPL                 360    5297     224    3139   
TSUCOOP             225    5029     235    4589   
CURR11              743    4990       0       0   
WRS                 755    4514    1453   12477   
FTMAGNUM             28    4497       1       8   
MAGNUM               29    4011       1       8   
KL10                153    3349       0       0   
NEW11               358    2760       0       0   
T20MON              169    2714       0       0   
SAILTEST            118    2111       0       0   
SOCCI               359    2053     745    6355   

	  Authors of over 2k pages

		    directory        authored
  who              files/pages      files/pages
-----------------------------------------------

SSINSTALL           112    1025     863   23311   
CARL                558    5599    1661   20754   
SDANIELS            931    6739    1567   14642   
WRS                 755    4514    1453   12477   
LOIS                222    1144    1028   10401   
ERNSTD                0       0    1042    7096   
DARREN               89     734     507    6432   
SOCCI               359    2053     745    6355   
TODD                293    1839     466    5793   
OPER                 18     427     202    5731   
TSUCOOP             225    5029     235    4589   
CALSTATE             31     256      90    4282   
UPL                 360    5297     224    3139   
KEN                 142     962     277    2758   
GINZBURGA           308    1833     346    2465   
GLYONS              136     811     201    2006   
