MODULE DAYOFWEEK;

$HEADER DAYOFW.HDR

$SYSTEM IDTIME.TYP
$SYSTEM DTIMEI.INC

PUBLIC FUNCTION DAY_OF_WEEK(DATE: DATE_INT): WEEK_DAY;

VAR
   NORM_DATE: 0..777777B;
   DAY_INDEX,I: 0..6;

BEGIN
   NORM_DATE := DC_DAYS ( DATE );

   DAY_INDEX := (NORM_DATE + 3) MOD 7;  (* DAY ZERO WAS A WED *)

   DAY_OF_WEEK := SUNDAY;

   FOR I := 1 TO DAY_INDEX DO
      DAY_OF_WEEK := SUCC(DAY_OF_WEEK)

END.
