MODULE ECDCDATE;

$HEADER ECDCDA.HDR

$SYSTEM IDTIME.TYP

EXTERNAL PROCEDURE EC_DATE(VAR DTIME_ERR;
   DATEREC; VAR DATE_INT);

PUBLIC FUNCTION EC_DCDATE(D_DATE: DEC_DATE): DATE_INT;

VAR
   DATE_BIN: DATEREC;
   DAYS_LEFT: DEC_DATE;
   ERR_CODE: DTIME_ERR;
   DATE: DATE_INT;

BEGIN

   WITH DATE_BIN DO

   BEGIN
      YEAR := D_DATE DIV (12 * 31) + 1964;
      DAYS_LEFT := D_DATE MOD (12 * 31);
      MONTH := DAYS_LEFT DIV 31 + 1;
      DAY := DAYS_LEFT MOD 31 + 1;
   END;

   EC_DATE(ERR_CODE, DATE_BIN, DATE);

   IF ERR_CODE = DT_NOERR THEN
      EC_DCDATE := DATE
   ELSE EC_DCDATE := ( 0, 0 )

END.
