.DECLARE@BUILDS.DCL
.PA@BUILDS.PTH
.PA=BASE:
.DELETE BASE:FGEN.AOK
.IF (ERROR)
.DELETE BASE:FGEN.FUB
.IF (ERROR)
.R FILCOM
*BASE:.SCM=MON:FGEN.HLP,BASE:
.PRINT/PRINT:ARROW/FILE:ASCII BASE:FGEN.HLP,FGEN.SCM
.COPY BASE:=DSK:MONGEN.EXE
.COPY BASE:FGEN.AOK=NUL:AOK.AOK
.GOTO DONE
BADCOM::
.COPY BASE:FGEN.FUB=NUL:FUB.FUB
DONE::
