SUBTTL HDWCNF - HARDWARE CONFIGURATION DEFINITION FILE OUTPUT BY MONGEN


DEFINE XP(A,B),<A==:B>


XP M.GEN,306

;;	DECsystem10(KL,KS)[
;;	KL is a system with KL10 cpu's and internal channels
;;	KS is a system with a KS10 cpu]: KL
XP M.KI10,0
XP M.KL10,1
XP M.KS10,0
XP M.1070,0
XP M.1080,0
XP M.1090,1
XP M.1091,0
XP M.2020,0

;;	Cpu's(1,1-3)[Total number of cpu's in the system]: 1
XP M.CPU,1

;;	System name[24 characters or less]: TEST SYSTEM
DEFINE	SYSNAM
<	ASCIZ	&TEST SYSTEM&>
DEFINE	SYSDAT<
ASCIZ &08-11-87&>
XP M.MON,10
XP M.DAY,13
XP M.YEAR,127

;;	CPU0 serial #(1-10000): 1026
XP M.C0SN,2002
XP M.C1SN,0
XP M.C2SN,0
XP M.C3SN,0
XP M.C4SN,0
XP M.C5SN,0
XP M.RT0,0
XP M.RT1,0
XP M.RT2,0
XP M.RT3,0
XP M.RT4,0
XP M.RT5,0
XP M.RTX,0

;;	Exclude monitor overhead from user run time(Y,N)[
;;	Overhead is CPU time spent clock queue processing, command
;;	decoding, swapping, and scheduling.
;;	User run time always includes UUO execution and
;;	unless EBOX/MBOX runtime accounting is selected
;;	(KL10 systems only) includes IO interrupt service time.]: Y
XP M.RTCO,1

;;	EBOX/MBOX runtime accounting(Y,N)[
;;	If EBOX/MBOX runtime accounting is selected in a KL10
;;	based system, user runtime is computed using the KL10
;;	internal accounting clocks]: Y
XP M.EMRT,1

;;	Exclude PI time from user runtime(Y,N)[
;;	An answer of "yes" to this question will cause the monitor
;;	to set up the KL10 accounting meters in such a manner that
;;	users will not be charged for cpu time used during interrupts]: 
XP M.XPI,1
XP M.RTCA,0
XP M.RTC,0

;;	Account verification(Y,N)[LOGIN and the batch system will
;;	verify that the user has specified a valid account]: 
XP M.ACV,1

;;	MOS memory(Y,N)[Include support for the user mode MOS memory diagnostic THGA
;;	which collects statistics on single bit memory errors and substitutes the spare
;;	bit when a single bit error is determined to be hard]: 
XP M.MOS,1

;;	SCA support(Y,N)[Load monitor modules needed to provide Systems
;;	Communications Architecture support]: 
XP M.SCA,1

;;	Include RNXKON(Y,N)[Support for RP20 disks]: 

;;	Include RAXKON(Y,N)[Support for disks on the CI bus]: 

;;	Include TM2KON(Y,N)[Support for TU16/TU45/TU77 tape drives]: 

;;	Include TD2KON(Y,N)[Support for DX20/TU7x tape drives]: 

;;	Include T78KON(Y,N)[Support for TU78 tape drives]: 
XP M0DPC,0
XP M0FHD,0
XP M0FSD,0
XP M0MDF,0
XP M0RPX,1
XP M0TAPN,1
XP M0RNX,1
XP M0RAX,1
XP M.P0T,1
XP M.N0T,1
RP0==650
RN0==650
RA0==650
XP M.CHN,1
XP M.RC10,0
XP M.RH1S,0
XP M.RH1P,0
XP M.RH2P,0
XP M.RH20,0
XP M.RHP4,1
XP M.RP20,1
XP M.RP10,0
XP M.TX01,0
XP M.TM02,1
XP M.DX20,1
XP M.TM78,1
XP M.TM10,0
XP M.R11D,0
XP M.TRH1,0

;;	# of DTEs on CPU0(1,1-4)[Interfaces for front-end PDP-11s]: 
XP M0DTEN,1

;;	  Type of front end on DTE0 (RSX20F,ANF10,IBM,DECNET): 
XP M00DTE,1

;;	  # terminals on front end #0(0,0-128)[include
;;	only timesharing (DH11) lines, not CTY or KLINIK]: 16
XP M0TTDN,24

;;	  # line printers on front end #0(0,0-2): 1
XP M0LP0N,1
XP M0LP1N,0
XP M0LP2N,0
XP M0LP3N,0

;;	     Front end printer 0 lower case(Y,N)[Does printer 0 have lower case capability]: Y
XP M0FL0L,1
XP M0CR0N,0
XP M0CR1N,0
XP M0CR2N,0
XP M0CR3N,0
XP M01DTE,0
XP M02DTE,0
XP M03DTE,0
XP M.TTDN,24
XP M.DLP,1
XP M.DCR,0
XP M.DN6S,0
XP M.DN8S,0
XP M.DDCN,0
XP M.DC10,0
XP M.DC68,0
XP M.DC76,0
XP MD.DCS,0
XP M.D70N,0
XP M.D71N,0
XP M.D72N,0
XP M.D73N,0
XP M.D74N,0
XP M.D75N,0
XP M.D76N,0
XP M.D77N,0
XP M.D78N,0
XP M.D79N,0
XP M.D7AN,0
XP M.D7BN,0
XP M.TTG0,0
XP M.TTG1,0
XP M.DSG0,0
XP M.DSG1,0
XP M.68L0,0
XP M.68L1,0
XP M.DZNL,0
XP M0DZNL,0
XP M.TLTL,0 ;TOTAL LOCAL TTY LINES


;;	OPR octal line #(CTY,0-23)[OPR is privileged operator terminal]: 
DEFINE	OPRLIN<

	OPRL	CTY
>

DEFINE	MACDSD<

;;	Data set lines
;;	[Class of terminal for LOGIN, LOGIN resets line
;;	to computer echoing and no hardware tabs.
;;	Type one octal line #(M) or one range(M-N) on separate
;;	lines.  Type extra carriage return when through.]
;;	
>

;;	# Jobs(1-511)[Maximum number attached and detached, not
;;	counting null job]: 100
XP M.JOB,144
XP MD.2RR,1
XP MD.SEG,0
XP MD.DDT,1

;;	Maximum P of core for each job(0,0-16384)[0 means all of core]: 
XP M.CORE,0

;;	# K total system core(512-4096)[ONCE-only reports if
;;	less core at startup]: 
;;	1024
XP M.NKC,2000

;;	Clock ticks per second(60,50)[Power line frequency]: 
XP M.TPS,74

;;	# Real-time devices(0,0-77)[Max. # which can be put
;;	on PI channels simultaneously]: 
XP M.RTD,0

;;	Allow jobs to be locked in core(Y,N): 
XP M.LOK,1

;;	# Pages min guaranteed among jobs not locked in core(0,0-16384)[
;;	minimum free core pool for unlocked jobs, 0 assumes all of core]: 
XP M.MGC,0

;;	# High priority queues(0,0-15): 3
XP M.HPQ,3
XP M.METR,0
XP M.FPS,0

;;	MSGSER(Y,N)[Support for device MPX. (more than one device
;;	on an I/O channel). This feature is required for MCS-10]: 
XP M.MSG,1

;;	PSISER(Y,N)[Advanced programmed software interrupt service -
;;	Support for the PISYS. UUO. This provides an easy
;;	and powerful interrupt method for program to trap asynchronous
;;	events. Required by GALAXY-10]: 
XP M.PSI,1

;;	IPCF(Y,N)[Inter process communication facility]: 
XP M.IPCF,1

;;	ENQ/DEQ(Y,N)[Sychronization primitives to allow
;;	simultaneous file update by multiple co-operating processes]: 
XP M.EQDQ,1
XP M.SYSC,0
XP M0CDR,0
XP MD.C10,0
XP MD0C10,0
XP M0CDP,0
XP M.VP10,0
XP M0VP10,0
XP M.340,0
XP M0340,0
XP M.VBXC,0
XP M0VBXC,0
XP M.DIS,0
XP M0DIS,0
XP M0TD10,0

;;	LPTs(1,0-3)[Line printers on the I/O Buss]: 
XP M0LPT,1
XP MD.MOV,0

;;	LPT0 Lower case(Y,N)[Does LPT0 have lower case capability]: 
XP M.LP0L,1
XP M0LP0L,1
XP M0PLT,0
XP M0PTP,0
XP M0PTR,0
XP M0RX20,0
XP M0RX20,0
XP M.XTC,0
XP M0XTC,0
XP M0XTL,0
XP M00D78,0
XP M01D78,0
XP M02D78,0
XP M03D78,0
XP M04D78,0
XP M05D78,0
XP M06D78,0
XP M07D78,0
XP M0D78L,0
XP M0XXI,0
XP M0XXO,0
XP M.DN6D,0
XP M00D60,0
XP M01D60,0
XP M02D60,0
XP M03D60,0
XP M04D60,0
XP M05D60,0
XP M06D60,0
XP M07D60,0
XP M0D60L,0
XP M.0D60,0
XP M.1D60,0
XP M.2D60,0
XP M.3D60,0
XP M.4D60,0
XP M.5D60,0
XP M.6D60,0
XP M.7D60,0
XP M.D60L,0
XP M.DN6K,0
XP M.DN6R,0
XP M.DN60,0
XP M.CDR,0
XP M.CDP,0
XP M.TD10,0
XP M.LPT,1
XP M.PLT,0
XP M.PTP,0
XP M.PTR,0
XP M.DAS78,0
XP M.XXI,0
XP M.XXO,0
XP M.RX20,0

;;	# PTYs(20,1-510)[Pseudo-terminals - each operator
;;	service program and Batch stream needs one]: 
XP M.PTY,24

RADIX	10
;;	Decimal "symbol,value"[
;;	For any symbols to be defined.
;;	Type one per line, extra carriage return when through]
;;	
RADIX	8
;;	
;;	Octal "symbol,value"[
;;	For any symbol to be defined.
;;	Type one per line, extra carriage return when through]
;;	
;;	
;;	SIXBIT "symbol,value"[
;;	For any sixbit symbol to be defined.
;;	Type one per line, extra carriage return when through]
;;	

DEFINE	SPCINT<
;;	Type "device-mnemonic,PI-channel" for special devices[
;;	With neither channel AC save routine nor device data block,
;;	the "device-mnemonic" must be 3 characters or less.
;;	Type extra carriage return when through.]
;;	
>

DEFINE	SPCDDB<
;;	Type "device-mnemonic,PI-channel,no.-of-devices"[
;;	For special devices with device data blocks.
;;	the "device-mnemonic" must be 3 characters or less.
;;	Type extra carriage return when through.]
;;	
>

DEFINE	SPCSAV<
;;	Type "device-mnemonic,PI-channel,highest-ac-to-save"[
;;	For special devices with channel save routines to save acs up to
;;	the "highest-ac-to-save".  "Device" must be 3 char or less.
;;	Type extra carriage return when through.]
;;	
>

DEFINE	SPCEDN<
;;	Type "ersatz-device,P,Pn,search-list-type"[
;;	For customer defined ersatz devices.
;;	The "esratz-device" must be exactly 3 characters long.
;;	"P,Pn" is the Project/Programmer number associated.
;;	"search-list-type" is one of ALL,SYS,JOB.
;;	Type extra carriage return when through.]
;;	
>

DEFINE	SPCCMD<
;;	Type "command-name,dispatch,flags,unique-bits,PRVTAB-name"[
;;	For customer defined commands.
;;	The "command-name" is the name of the monitor command to be added.
;;	"dispatch" is one of:
;;		omitted to run the program with the same name as the command
;;		the SIXBIT name of the program to run if different
;;		#address to use the already existing monitor location "address"
;;			as the dispatch routine for this command, e.g., #RUNQUE
;;	"flags" are the flags used in the command table macros, e.g., RUNFLG
;;	"unique-bits" are the command table unique bits, e.g., UNIQ.1
;;	"PRVTAB-name is the name of the program to be added to PRVTAB, if any
;;	Type extra carriage return when through.]
;;	
>

DEFINE	SPCTRM<
;;	Type "terminal-type/Alias,WIDTH,LENGTH,FF,TAB,LC,ALT,DISPLAY,CRLF,XON,8BIT,FILL,erase-to-EOL,backspace-space-backspace"[
;;	For customer defined terminal types.
;;	
;;	Terminal-type is the SIXBIT name of the terminal.
;;	/Alias is optional.  Alias is the SIXBIT name sent to other systems on
;;	set host.
;;	WIDTH is the width of the terminal
;;	LENGTH is the length/pagesize of the terminal
;;	FF/NOFF is whether or not the terminal has hardware form feeds
;;	TAB/NOTAB is wheither or not the terminal has hardware tabs
;;	LC/NOLC is wheither or not the terminal is capabile of lower case
;;	ALT/NOALT is wheither or not the terminal generates old altmodes
;;	DIS/NODIS is wheither or not the terminal is a display terminal
;;	CRLF/NOCRLF is wheither or not the terminal needs a CRLF at right margin
;;	XON/NOXON is wheither or not ^S/^Q should pause the terminal
;;	8BIT/NO8BIT is whether the terminal handles the 8-bit ASCII character set
;;	FILL is the number of fill characters required for the terminal
;;	Erase-to-EOL is address of sequences to cursor right and erase to EOL
;;	Backspace-space-backspace is address of sequences to backspace, space, backspace
;;	
;;	Type extra carriage return when through.]
;;	
>
;;	
;;	END OF HDWCNF.MAC
  