.DECLARE@BUILDS.DCL
.PA@BUILDS.PTH
.DELETE BASE:UNIV.AOK
.IF (ERROR)
.DELETE BASE:UNIV.FUB
.IF (ERROR)
.PA =KL:
.COMPILE/COMPILE @UNIV.CMD
.PA =KLF:
.COMPILE/COMPILE @UNIV.CMD
;.PA =KLI:
;.COMPILE/COMPILE @UNIV.CMD
.PA =KS:
.COMPILE/COMPILE @UNIV.CMD
;.PA =KST:
;.COMPILE/COMPILE @UNIV.CMD
.COPY BASE:UNIV.AOK=NUL:AOK.AOK
.GOTO DONE
%ERR::
.COPY UNIV.FUB=NUL:FUB.FUB
DONE::
