Title	TTYCOR Macro subroutines for TTY support plus more
Subttl	Revised by Carl A Baltrunas - Gallaudet College - 1980/CB
Subttl	Revised by Carl A Baltrunas - Tymshare Inc - 1980-1/CB

	VUEWHO==0	;Who last edited
	VUEVER==1	;Major version
	VUEMIN==0	;Minor version
	VUEEDT==0	;Edit level (# of edits)

	loc	137	;.jbver
	Byte (3) vuewho (9) vuever (6) vuemin (18) vueedt
	reloc

	Twoseg		;[CB]
	Reloc	400000	;[CB]

ifndef ftdebug,<ftdebug==-1>	; Allow (SYS), (YEUX) and (VUE)
tymcom=1
vanilla=1
ftcommand=1
twenex=0
ifn twenex,<	search monsym>
	radix	^d10

;Copyright 1979 by Michael L. Kazar

s=0
v=3
a=4
b=5
c=6
d=7
e=10

external ctrlat,ctrla,ctrlb,ctrld,ctrle,ctrlf,ctrlg,rubout,ctrlk
external ctrll,ctrln,ctrlo,ctrlp,ctrlq,ctrlr,ctrls,ctrlt,ctrlu,ctrlv
external ctrlw,ctrly,ctrlz,metab,metac,metad,metadel,metaf,metaj,metap
external metaq,metar,metav,metaw,metaz,ctrlxe,ctrlxf,ctrlxm,ctrlxt
external metacn,metacp,metagt,metalt,metaquest,ctrlxr,ctrlxv,ctrlxw
external ctrlxx,ctrlxz,metarb,metalb,writeloss,writestring,silent
external ToStatus,ToPrompt,echord,zapmac,therep,horizspace
external munchline,setchar,getchxr,delforward,delback,insertchar
external whitespace,wbreak,ctrln2,ctrlp2,pbreak,updatecursor,initdispat
external forceinput,ttyzap,clearscreen,moveback,moveforward,gppn
external filescan,open,close,dmpin,dmpout,combuf,getstr,read
external uctrlo, ctrlxr,rptr,goxy,ttyzap,metam,corecheck,pageon,pageoff
external rstk,MaxPPerFrame,parmarray,popio,cstk

	entry fef,fen,wrnum,clulin,clupos,autblk,cluhac,imout,realup,flush
	entry scrsze,screen,curline,dskbuf,filblk,fixfil,ppn,cucl,defdsk,base
	entry comchar,newcount,repcount,coresize,readch,lowend,linesz,puntsos
	entry ttytyp,sst,mark,maxss,muncho,munchi,ocline,scrmod,muline,dbx
	entry hend,ttyidle,reset,echof,hbot,p,dskbfh,putch,flubfr,modpos
	entry csnum,qreg,dorescan,setint,setlab,lookop,hitsts,submod,vuetyp
	entry physpos,physlin,tabsize,distbl,bfblk1,bfblk2,scroff,scrlen
	entry jbstr,relcor,getwid,getlen,gt20,gt10,rsrchr,rsrptr,rsrstk
	entry ttype,tspeed
	Radix ^d8

ifn tymcom,<
Opdef	Auxcal	[042000,,0]
Opdef	Setmod	[Calli -26]
Opdef	Putlsa	[Calli -63]

.Axi8c==0	; Input character image and wait
.Axi8s==1	; Input character image and skip
.Axsic==10	; skip if character
.Axobr==16	; Read Output baud rate code
.Axwid==27	; Terminal Width
.Axics==45	; input character and skip
.Axost==52	; Outstr to Aux port
.Axrvx==55	; reverse ^S/^Q enable
.Axcfs==64	; Setmod for Aux port

io.nee==1b27	; no-escape-