	title JUNK10
a== 1
p== 17
stack:	block 20

start:	reset
	move	p,[xwd	-20,stack]
	move	[jrst loop]
	settr1
	 jfcl
;;	hrlzi	a,000200	;trap 1 bit
	setz
loop:	addi	1
;;	jrstf	.+1(a)
	MOVSI	2,400000
	SUBI	2,1
	outstr	[asciz " Failure after "]
	pushj	p,decprt
	outstr	[asciz " tries."]
	exit	1,

decprt:	idivi	12
	hrlm	1,(p)
	caie	0
	 pushj	p,decprt
	hlrz	a,(p)
	outchi	"0"(a)
	popj	p,
end start
