



BNF for PERP Valid Date Expressions 
====================================


dow = 'MON'|'TUE'|'WED'|'THU'|'FRI'|'SAT'|'SUN'| .

moy = 'JAN'|'FEB'|'MAR'|'APR'|'MAY'|'JUN'|
      'JUL'|'AUG'|'SEP'|'OCT'|'NOV'|'DEC'| .

date = <moy> <integer<=31> <integer>1920> |
       'TODAY' |
       'TOMORROW' .

ord = '1ST'|'2ND'|'3RD'|'4TH'|'5TH'|
      '6TH'|'7TH'|'8TH'|'9TH'|'10TH'|
      'FIRST'|'SECOND'|'THIRD'|'FOURTH'|'FIFTH'|
      'SIXTH'|'SEVENTH'|'EIGTH'|'NINTH'|'TENTH'|
      'OTHER' .

DayUnit = ['every'] [ ord ] ( dow | 'DAY' ) .

Unit = date | DayUnit .

MonthUnit = ['every'] [ ord ] 'MONTH'  .

expression = DayUnit [ MonthUnit ] .

group = ( Unit | expression ) { 'and' group } .

exception clause = 'EXCEPT' group .

until clause = 'UNTIL' date .

starting clause = 'STARTING' date .

Valid Date Expression = group [exception clause] 
                              [until clause] 
                              [starting clause]  .

VALID KEYWORDS in a Date Expression
===================================

TOD[AY]       Current date .
TOM[ORROW]    Current date + 1 .
EVE[RY]       Indicates a cyclic expression ,
                ex: "MONDAY" would mean the next MONDAY after today (only);
                    "EVERY MONDAY" means the next MONDAY after today and
                       each subsequent MONDAY .
AND           Links single expressions into groups of expressions .
EXC[EPT]      List of date expressions for dates on which job will not be run.
STA[RTING     As "STARTING AUG 11, 1985" - A date before which the job 
                will not be run.
UNT[IL]       As "UNTIL AUG 11, 1985" - A date after which the job 
                will not be run.

Any words which are not recognized are discarded before the date expression
  is parsed.
  ex: "THE 1ST DAY OF THE MONTH" becomes "1ST DAY MONTH", etc.






EXAMPLES of VALID DATES
=======================

SIMPLE EXPRESSIONS:

TODAY .
TOMORROW .
EVERY FRIDAY .
EVERY OTHER WEDNESDAY .
EVERY 4TH TUESDAY .
EVERY 2ND MONDAY OF THE MONTH .
EVERY 2ND MONDAY OF EVERY 2ND MONTH. .
JAN 12, 1986 .
EVERY MONDAY AND EVERY FRIDAY .
EVERY 3RD MONDAY OF THE MONTH AND EVERY 4TH WEDNESDAY OF EVERY OTHER MONTH .
EVERY FRIDAY AND AUG 21, 1986 .

EXAMPLES with UNTIL:

EVERY MONDAY UNTIL AUG 21, 1986 .
EVERY OTHER THURSDAY OF EVERY OTHER MONTH UNTIL JAN 21, 1986 .
EVERY THIRD MONDAY AND EVERY FRIDAY AND JUL 21, 1986 UNTIL AUG 10, 1986 .

EXAMPLES with STARTING:

EVERY MONDAY STARTING AUG 21, 1986 .
EVERY OTHER THURSDAY OF EVERY OTHER MONTH STARTING JAN 21, 1986 .
EVERY THIRD MONDAY AND EVERY FRIDAY AND JUL 21, 1986 STARTING AUG 10, 1986 .

EXAMPLES with EXCEPTIONS:

EVERY MONDAY EXCEPT THE THIRD MONDAY OF THE MONTH .
EVERY TUESDAY EXCEPT AUG 12, 1986 .
EVERY MONDAY AND EVERY FRIDAY EXCEPT THE THIRD MONDAY OF EVERY MONTH AND
  THE SECOND FRIDAY OF EVERY MONTH .

COMBINATIONS:

EVERY MONDAY AND EVERY FRIDAY STARTING JUL 12, 1985
  EXCEPT THE SECOND MONDAY OF EVERY MONTH AND THE 2ND WED OF EVERY 3RD MONTH
  UNTIL DEC 11, 1985 .
JAN 11, 1986 AND EVERY OTHER FRIDAY UNTIL AUG 16, 1986 EXCEPT THE 3RD FRIDAY
  OF EVERY MONTH .


