type
    filblock = array [1..4] of machine_word; (* internal file name block *)

    log_file_record = packed record
	file_name: filblock; (* encoded file block *)
	version: integer; (* from .JBVER *)
	run_time: integer; (* in milliseconds *)
	no_lines: integer; (* source lines read *)
	no_incl_lines: integer; (* lines from include files *)
	no_errors: integer; (* errors detected *)
	users_ppn: machine_word; (* from GETPPN uuo *)
	date_and_time: dtime_int;
	lowseg_size: 0..777777b; (* generated code low segment *)
	highseg_size: 0..777777b; (* generated code high segment *)
	alloc_strategy: 0 .. 99; (* ALLOC=n *)
	ki10: boolean; (* no/yes *)
	kl10: boolean; (* yes *)
	opt_debug: boolean; (* DEBUG *)
	opt_double: boolean; (* no - no such thing *)
	opt_check: boolean; (* anything in CHECK mode? *)
	opt_main: boolean; (* program vs. module *)
	opt_overlay: boolean; (* OVERLAY *)
	opt_progress: boolean; (* no *)
	opt_source: boolean; (* SOURCE ever specified? *)
	opt_special: boolean; (* anything in SPECIAL mode *)
	opt_terse: boolean; (* TERSE vs. VERBOSE *)
	opt_trace: boolean; (* TRACE ever specified? *)
	opt_xref: boolean; (* GLOBAL *)
	opt_virtual: boolean; (* no *)
	opt_auto_run: boolean; (* run at offset 1 *)
	opt_tmpcor: boolean; (* run from tmpcor file *)
	opt_hash: boolean; (* run from ###PAS.TMP *)
	fill1, fill2, fill3: integer (* record size = 16 (decimal) words *)
    end;
