TBASRT=(SPUNKDEV)XLIST+(SPUNKDEV)DCLD+(SPUNKDEV)TBADCL+(SPUNKDEV)PAGD+;
(SPUNKDEV)ERRNUM+(SPUNKDEV)LIST+TBASRT(,P)

SORTSB=(SPUNKDEV)XLIST+(SPUNKDEV)MVER+(SPUNKDEV)DCLD+(SPUNKDEV)PAGD+;
(SPUNKDEV)LIST+SORTSB(,P)

SRTIO=(SPUNKDEV)XLIST+(SPUNKDEV)DCLD+(SPUNKDEV)PAGD+(SPUNKDEV)LIST+SRTIO(,P)

KEY=KEY

NUMKEY=NUMKEY
