        title stufib
        hiseg

entry stufib     ; tba procedure to stuff input buffer

; r1  adr of tba string descriptor

stufib:
        hrlzi   3,^d16  ; set indirect bit of byte pointer
        hrr     3,(1)   ; get adr of string body
        add     3,[point 7,0]   ; specify 7 bit bytes
        move    2,[-1,,33]      ; specify auxcal .axsi(33) on the command port
        auxcal  2,3
        jfcl            ; error return, no big deal
        popj    17,     ; all done   return

end
