CTEST SETPROC MACRO=(FTSYS)MACRO,LOADER=(SPL)LINKER
LOAD @PIP.CMD
DELETE PIP.REL
R CKSUM
PIP.CTL
PIP.CMD
PIP.MAC
PIP.SHR
PIP.LOW

DECLARE RUN RUN RUN PIP.SHR,PIP.LOW
DIRECT PIP.*/PROT/LIC
