Received: from tymix.Tymnet by B39.Tymnet; Tue, 22 Sep 87 21:02:26 PDT
Received: by tymix.Tymnet (5.51/4.7) id AA19867; Tue, 22 Sep 87 21:06:26 PDT
Received: from tymix.Tymnet by hobbes.Tymnet.com (3.2/SMI-3.2) id AA20942; Tue,
	22 Sep 87 21:06:05 PDT
Received: by tymix.Tymnet (5.51/4.7) id AA19860; Tue, 22 Sep 87 21:06:18 PDT
Received: by oliveb.OLIVETTI.COM (5.51/smail2.2/03-10-87) id AA20433; Tue, 22
	Sep 87 17:51:58 PDT
Received: by oliven.ATC.OLIVETTI.COM (5.51/smail2.2/03-10-87) id AA23223; Tue,
	22 Sep 87 17:51:53 PDT
Return-path: <oliveb!gnome@tymix.Tymnet> 
From: gnome@oliveb.OLIVETTI.COM (Gary) 
Date: Tue, 22 Sep 87 17:51:53 PDT 
To: oliveb!tymix!wrs 
Message-id: <8709230051.AA23223@oliven.ATC.OLIVETTI.COM> 
Subject: forwarded stuff 

Path: oliveb!pyramid!decwrl!labrea!rutgers!iuvax!pur-ee!j.cc.purdue.edu!ags
From: ags@j.cc.purdue.edu (Dave Seaman)
Organization: Purdue University

> Yesterday, I watched a movie named "Electric Dream".
>There, the heroine (a cellist) played a piece of music that was
>echoed by the computer.  The music was very familiar to me, but I failed
>to name it.  The orchestra in the movie was also rehearsing it, I think.

It's a selection from the "Little Music Book for Anna Magdalena Bach" by
J. S. Bach.  
-- 
Dave Seaman	  					
ags@j.cc.purdue.edu
