Received: from EMSNTD.Ontyme.Tymnet by B39.Tymnet; Wed, 23 Jul 86 0:14:50 UT
From: PMTS.B/OHARA@EMSNTD.Ontyme.Tymnet 
Date: 22 JUL 86 17:10:55 
To: NTD.B/SOLEY@EMSNTD.Ontyme.Tymnet (NTD.WRS) 
Cc: NTD.B/SOLEY@Ontyme.Tymnet, NTD.D/CHANG@Ontyme.Tymnet,
	PMTS.B/OHARA@Ontyme.Tymnet 
Message-id: J66583@Ontyme.Tymnet 
Subject: PMTS simulation data 

Bill,
  I have moved the report I mentioned over to filename MULT06 on OHARAB:65.
The first two pages are summaries that you probably want to delete.  Starting
on the third page is detail (by node) info.  For your simulation runs, you
probably only want to look at lines preceeded with POS, as CRT and ARU
traffic are not eligible for MPVC, nor do we intend to use class positions to
target them.
  Good luck.  Feel free to call me at 116-2414 if you need any further info
or clarification.
   Barry
