Received: From EMSNTD.Ontyme.Tymnet by C39.Tymnet; Wed, 15 Jan 86 11:15:12 PST
From: NTD.SUP@Ontyme.Tymnet 
Date: 15 JAN 86 09:46:42 
To: NTD.B/SOLEY@Ontyme.Tymnet (NTD.WRS@Ontyme.Tymnet) 
Message-id: I02795@Ontyme.Tymnet 
Subject: "MCDONNELL DOUGLAS ADMINISTRATIVE"... 

    MCDONNELL DOUGLAS       ADMINISTRATIVE     NO:  ISG-86-4
INFORMATION SYSTEMS GROUP      BULLETIN        DATE: 14 Jan 86



To:       ISG Employees

Subject:  ISG LEAVE OF ABSENCE PRACTICES



1.  The  attached  document  provides  information concerning ISG
    Leave of Absence.

2.  This  information will be included with future updates to the
    ISG handbooks.

3.  If   you  have  questions  concerning  this  subject,  please
    contact your local Human Resources office.



(Original signed by Mike Becker)

M. R. Becker
Staff Vice President
Human Resources-ISG



                                               Enclosure (1) to
                                               AB# ISG-86-4

                        LEAVE OF ABSENCE

SUMMARY:

A  leave  of absence is a management-approved absence authorizing
full-time  employees  an  absence  from  the  Company for reasons
considered  satisfactory  to  the  Company  provided the employee
definitely  plans  to  return  to  work at the Company or is on a
disability leave.

APPLICABLE TO:

All  full-time employees covered by McDonnell Douglas Information
Systems Group Benefits.

DEFINITION:

A  Leave of Absence is an authorized absence granted to employees
who  will be absent from work for 6 or more consecutive scheduled
work days.

REGULATIONS:

A.  General

    An  approved  Leave  of  Absence  Authorization  (LOAA)  form
signed  by  the  supervisor  and  next  management  level must be
submitted   to   Human   Resources.      Attach   any   pertinent
documentation  justifying the leave.  Leaves may be approved when
substantiated  with  reasons  acceptable to the Company.  Maximum
leave  durations  and  extensions for various types of leaves are
specified in Appendix 1.

    Extension  of  a  leave will require the supervisor to submit
an  additional LOAA form to Human Resources with the new expected
return  date  of  the employee.  When a requested leave extension
will  result  in  a total leave period which exceeds the "maximum
leave   duration"  specified  in  Appendix  1,  approval  of  the
Business  Unit Head, Business Unit/Regional Human Resources Head,
and Manager Benefits - ISG.

    An  employee  planning  to  return to work on expiration of a
leave  is  requested  to  give  supervision  at  least one week's
notice  of  this intent, if possible.  Upon the employee's return
to  work  the supervisor must inform Human Resources of the date,
thus, terminating the leave of absence.

    Employees  failing  to  return to work at the expiration of a
leave will be considered to have voluntarily resigned.



    An  employee  will  not be granted a leave of absence for the
purpose  of  seeking or taking employment elsewhere, or operating
a private business.

B.  Types of Authorized Leaves:

    1.  Disability

    Leaves  of absence for personal illness, injury, maternity or
other  physical  disability  will  be granted when an employee is
absent from work 6 or more consecutive days.

    If   a   doctor's   statement   has  not  been  submitted  to
supervision  at  the  beginning  of  the  absence, due to medical
reasons   or   emergency,   the   supervisor  will  notify  Human
Resources,  who will send the employee a letter explaining that a
doctor's  note is required in order for sick leave payments to be
continued.    If  Human  Resources  does not receive the doctor's
verification  of  disability within two weeks or Human Resources'
letter  to  the  employee, the employee will have assumed to have
voluntarily terminated.

    During  an  absence  due  to  disability,  the  employee will
receive  disability pay as specified in the Short Term Disability
Policy  for  up  to  26 weeks.  At the end of the maximum 26 week
paid  leave  period,  the  employee  will  be placed on an unpaid
leave.    The  employee  should  file for benefits under the Long
Term  Disability Plan for leaves that extend beyond 26 continuous
weeks.

    Employees  on  an  approved  disability leave may continue to
participate  in their current health care benefits and group life
insurance  plans  through  payroll deductions for up to 26 weeks.
On  leaves  accrued  beyond this period, payroll will deduct from
employee's  earning,  appropriate  insurance premiums upon return
to work.

    Except  for  long  term  leaves  (i.e.  leaves  longer than 6
months),   employees   continue  to  accrue  service  credit  and
vacation.

    It  is the employee's responsibility to notify supervision if
an  extension of disability leave is needed at least five working
days  prior  to  the  original  expected  return  date  to  work.
Employee  must  submit  a  statement from the attending physician
indicating  the  complications which require additional leave and
must specify the new expected return date.

    Prior  to  return  to  work after disability leave, a medical
release  must  be  submitted  to Human Resources in situations as
described under the Short Term Disability Policy.



    An  employee  who becomes pregnant will notify her supervisor
of  her  pregnancy.   The employee may continue working until the
date  established  by  the  employee's doctor that work should be
discontinued.    The  employee  must  furnish  a  letter from her
attending  physician  attesting  to  her  good health and stating
probable  date  of delivery.  Leave will commence when it becomes
necessary  for her to discontinue work as a result of information
provided by her physician.

    2.  Military Leave

    Employee  must  have  one  or  more years of credited service
with   the  Corporation  to  qualify  for  paid  military  leave.
Differential  pay  is  provided  for  up  to  two  (2)  weeks per
calendar  year  for short term active duty of 30 calendar days or
less,  including  annual  training  duty, as a member of the U.S.
Military  Reserves  or  National  Guard.  Differential pay is the
difference  between  the employee's base military pay and regular
rate  of  pay.    Military pay includes all military earnings and
allowances except for rations, quarters, subsistence and travel.

    The  employee informs management of requirement to report for
annual  military reserve training and arranges for time off up to
a  maximum  of  30  calendar  days.  If required to be absent for
more  than  ten (10) working days, the employee may elect to take
vacation or unpaid personal leave.

    On  completion  of  duty,  the  employee  should  submit  the
following to Payroll:

    a.  Pay  voucher  showing all military earnings for the total
        period of absence,
    b.  Military orders,
    c.  "Statement of Earnings for Paid Military Absence" form.

    On  receipt  of  the  above documentation, Payroll will issue
the  pay  differential  between  employee's  military pay and the
employee's  regular  rate  of  pay, for normal five-day workweek,
the pay period after the documentation is received.

    If  an  employee enlists or is drafted into any branch of the
U.S.  Armed  Services  for more than 30 calendar days, employment
will  be  terminated to enter military service.  Supervision must
submit  to  Human  Resources  a termination notice accompanied by
military  orders.    Employee's reinstatement will be governed by
Military Selective Service Act, as amended.



    3.  Civic Service

    Leaves  may  be  granted to permit employees to serve initial
terms  in  full-time municipal, county, state, or federal office,
whether  elected or appointed, provided any conflicts of interest
can  be  resolved  before  a leave is granted.  Extensions may be
granted  in  accordance  with  Appendix 1.  Leaves of absence for
civic  service  requires  the  approval of the Business Unit Head
and  Business  Unit/Regional  Human  Resources  Head.  This is an
unpaid   leave   of   absence   and   all  company  benefits  are
discontinued, including service credit and vacation accrual.

    4.  Jury Duty

    Full  pay  to employees is provided for up to 20 working days
for  jury duty or duty as a subpoenaed witness.  Employee retains
any  court compensation for service in addition to receiving full
pay.

    In  instances  where  an  employee's  absence  would  have an
adverse  influence  upon  the  work  schedule, or when a critical
work  skill  is  involved,  the  Company  may  request  that  the
employee  be  excused from jury duty.  Such requests, prepared by
the  Human  Resources Head, will be held to a minimum and require
approval of the Business Unit Head.

    Employees  called  for  jury  or witness duty will present to
their  supervisor,  in  advance,  official  evidence  that  their
service is required.

    An  employee  is  required  to  report for work if excused or
dismissed  from  jury  or  witness  service before the end of the
working   day  (of  shift)  provided  there  is  sufficient  time
remaining before the end of the employee's regular shift.

    If  a  shift  employee  serves  on  jury duty or as a witness
during  the  day and is scheduled for work on the second or third
shift,  the  supervisor  determines  whether  the  employee  must
report  for work on the scheduled shift.  All hours worked on the
scheduled  shift will be compensated by the Company in the normal
manner.

    Time  spent on jury or witness duty applies toward employee's
regular work schedule.

    While  on  jury duty, the employee will submit to supervision
at  the  end  of  each week a Jury Attendance Report, signed by a
court official, to be eligible for compensation.



    5.  Personal

    An  employee  may be granted a personal leave of absence upon
approval  by  the  immediate  supervisor  and  the  next level of
management  up, to a maximum of four (4) weeks.  Current business
conditions,   job   performance,  attendance  and  necessity  for
requesting  the  personal leave will be taken into consideration.
Based  on  these factors, leave may be paid or unpaid.  Extension
beyond four (4) weeks require approval as shown in Appendix 1.

    Company  benefits  will  continue  during  this  period.  For
unpaid  leaves,  payroll  will  deduct  from employee's earnings,
upon   return   to   work,  insurance  premiums  which  may  have
accumulated during leave.

    If  the  employee  should  terminate while on Personal Leave,
the  effective  date  of  the  termination  will  be the last day
worked.

    6.  Educational

    Employees  may  be  granted  an  educational leave of absence
without  pay  to  satisfy  residence  requirements  leading to an
approved  Doctorate  degree.   Such a leave requires the approval
of   the   Business   Unit  Head,  Business  Unit/Regional  Human
Resources  Head,  and Manager Benefits - ISG.  Employee must have
6   months   active   Company  service  to  be  eligible  for  an
educational  leave.    Maximum duration and extension is shown in
Appendix 1.

    Company  benefits  will continue during this period.  Payroll
will  deduct  from  employee's  earnings,  upon  return  to work,
insurance premiums which may have accumulated during the leave.

    If  the  employee  should  terminate  while on an educational
leave,  the  effective  date  of the termination will be the last
day worked.

    7.  Peace Corps/VISTA

    Employees  volunteering  for  either  Peace  Corps  or  VISTA
activity  may  be  granted  an  unpaid leave for the full term of
their  enlistment in accordance with Appendix 1.  Approval of the
Business Unit Head and Human Resources Head is required.

    Company   benefits   and  group  insurance  coverage  is  not
continued during this leave of absence.



                        LEAVES OF ABSENCE
                           Appendix 1


    ABSENCE REASON              LEAVE DURATION      EXTENSION

Nonoccupational Disability:     26 weeks            *78 weeks
 Leave necessary as a result
 of non-job related illness,
 injury or pregnancy.

Occupational Disability:        2 years             *1 year
 Leave necessary as result
 of job related illness or
 injury.

Military, Short Term:           30 calendar days    No extension
 Leave granted to members of
 the U.S. Armed Forces Reserve
 or National Guard to perform
 short term active duty
 necessary because of public
 emergency or to participate
 in annual training programs.

Civic Service:                  Original term       *As approved
 Leave to serve in full-time
 municipal, county, state,
 or federal public office,
 whether elected or appointed.
 Group insurance and other
 benefits are discontinued
 during leave.

Jury Duty:
 Leave as necessary to serve    20 days             *As approved
 as a petit juror or on a
 Federal Grand Jury, or to
 report to court in person in
 response to jury duty summons.

Personal:
 Leave for a personal reason    4 weeks             *As approved
 acceptable to the Company.

Educational:
 Leave to devote full-time to   *13 months          *9 months
 attainment of approved
 Doctorate Degree.

*Requires approval of Business Unit Head, Business Unit/Regional
 Human Resources Head, and Manager Benefits - ISG.



                        LEAVES OF ABSENCE
                           Appendix 1

                           (Continued)


    ABSENCE REASON              LEAVE DURATION      EXTENSION

Peace Corps/VISTA:              25 months           No extension
 Leave to serve full-time.
 Group insurance and other
 benefits are discontinued
 during leave.



                      SHORT TERM DISABILITY


SUMMARY:

The   Short   Term  Disability  benefit  provides  protection  to
employees   against  loss  of  compensation  due  to  illness  or
disability.    Paid  disability leave, to the extent specified in
this  directive,  is  provided when employees must be absent from
work  due to illness, injury or pregnancy.  Short Term Disability
is not to be used for any other time-off purposes.

APPLICABLE TO:

All  full-time employees covered by McDonnell Douglas Information
Systems Group Benefits.

DEFINITIONS:

Service  Date:    The employee's hire date or most recent re-hire
date.    Adjustments are made to the service date for all periods
of absence in excess of 26 consecutive weeks.

REGULATIONS:

    1.  Eligibility  for  this  benefit  is based on the original
        hire  date  or  the most recent re-hire date.  The amount
        and  duration  of  disability  leave  payments depends on
        length of service.

    2.  The   Short   Term  Disability  benefit  schedule  is  as
        follows:

        Length of                Weeks at            Weeks at
         Service                100% of Pay         70% of Pay

        0-1 Year                  4 Weeks            22 Weeks
        Over 1 Year              26 Weeks               --

        The  percentage  and  amount of disability leave payments
        are  based  on  a  cumulative  total  for  each  year  of
        continuous service.

    3.  Short  Term  Disability  payments  are  coordinated  with
        State   Disability   Income  Benefits  and/or  any  other
        Company   paid   disability   benefit  such  as  Workers'
        Compensation.    (NOTE:  Some states have mandatory state
        disability  programs whereby the amount of the benefit is
        dependent  on  the  length of time the contributions were
        made   to  the  state  fund  and  the  employee's  salary
        level.)   Employees who are eligible for State Disability
        or  Workers'  Compensation  are  responsible  for  filing
        their own claims for benefits.



                      SHORT TERM DISABILITY
                           (Continued)


     4.  Each   anniversary   of   the  employee's  service  date
         re-establishes   a   26   week   Short  Term  Disability
         eligibility  unless  employee  is on Leave of Absence on
         the  anniversary  date.    In this event eligibility for
         maximum   disability  benefits  will  be  restored  upon
         return to work.

     5.  If  the  disability  exceeds  26  continuous  weeks, the
         employee  is  eligible to apply for Long Term Disability
         as  described  in  the  Summary  Plan  Description.  The
         Human   Resources   Department  must  be  contacted  for
         processing of the claim.

     6.  Disability   leave   hours   must  be  recorded  on  the
         employee's time sheet and approved by supervision.

     7.  For   absences  of  six  (6)  or  more  working  days  a
         statement  from  the attending physician may be required
         which  specifies  the date of disability, diagnosis, and
         expected  date  of  return.  All absences of ten (10) or
         more  days  require  a  physician's statement certifying
         the  need  for  the  absence.  Employees must keep their
         supervisors   advised   of   their   status  during  the
         disability.

     8.  Employees  who  are on a disability leave for six (6) or
         more  consecutive  days  will  be  placed  on  Leave  of
         Absence.    Human  Resources must be notified.  Requests
         for  medical  documentation and other forms will be sent
         to  the  employee  as outlined in the Policy on Leave of
         Absence.

     9.  Vacation  accrual  will  continue  for employees on paid
         disability  leave  status  up  to  26 weeks, after which
         vacation   accrual   will   be  discontinued.    Accrued
         vacation  may  be  paid to the employee at any time upon
         request by the employee.

    10.  Prior  to  return  to  work  from  a disability leave, a
         medical  release  from  the employee's phyn will be
         required in cases of:

         a.  An  absence  due  to occupational injury, contagious
             disease, surgery, broken bones, or hospitalization.
         b.  An  absence where treatment results in corrective or
             prosthetic  devices  required  to  be  worn  by  the
             employee.
         c.  Other  absences due to sickness or disability of six
             (6)  or  more consecutive working days may require a
             medical release.



                      SHORT TERM DISABILITY
                           (Continued)


    11.  In   the   case  of  a  pregnant  employee,  a  doctor's
         statement  is  required  indicating the date after which
         the  employee  cannot  work and the expected due date of
         the child.

PROCEDURES:

None.

REFERENCES:

None.
   $no9–