	SUBROUTINE SETDAY(JULIAN,LIN)
	IMPLICIT INTEGER(A-Z)

	PARAMETER	MAXTAB = 500
	PARAMETER	LINK   = 1		! LINK POINTER
	PARAMETER	LENGTH = 2		! LENGTH OF ITEM
	PARAMETER	LINNUM = 3		! WHAT LINE TO PUT IT ON
	PARAMETER	NSTART = 4		! WHERE THE NAME STARTS
	PARAMETER	NSIZE  = 18		! NSTART + 14 = 15 FOR NAME

	INTEGER L0,TABENT,INF(NSIZE,MAXTAB)
	INTEGER NAME(15),SET(366)

	COMMON /NAME/NAME/SET/SET
	COMMON /TABENT/TABENT/INF/INF


D	TYPE 120,NAME,JULIAN
D 120	FORMAT(1X,15A1,' is the ',I3,'th day of the year')

	DO 125 I = 15,1,-1
125	IF (NAME(I).NE.' ') GOTO 126
	Return					! IF =0, IGNORE IT
126	L0 = I					! USE LEFTOVER FOR LENGTH

	SETUP = SET(JULIAN)			! GET CURRENT JULIAN USAGE
130	IF (SETUP.EQ.0) GOTO 140		! A NEW ONE, SKIP SOME WORK
132	IF (INF(LINK,SETUP).EQ.0) GO TO 135	! IF NEW SLOT, GET READY
	SETUP = INF(LINK,SETUP)			!  ELSE BUMP & GRIND AWAY
	GO TO 132				!       USING A SMALL LOOP

135	INF(LINK,SETUP) = TABENT		! SET TABLE ENTRY
	GO TO 150				! THEN GO TO COMMON PROCESSING

140	SET(JULIAN) = TABENT			! SET TABLE ENTRY
						! FALL INTO COMMON STUFF

150	INF(LENGTH,TABENT) = L0			! REMEMBER CHARACTER COUNT
	INF(LINNUM,TABENT) = LIN		! SAVE LINE NUMBER FROM ABOVE
	DO 155 I = 1,L0				! TRANSFER THE CHARACTERS
155	INF(I+NSTART-1,TABENT) = NAME(I)	!  1-15 ==> 4-18

	TABENT = TABENT + 1			! INCREMENT TAB-ENTRY
	IF (TABENT.LE.MAXTAB) Return		!  IF WITHIN RANGE GA.

	TYPE 160,TABENT
160	FORMAT(1X'Date table array overflow at ',I4,' entries.',
	1/1X,'Please show this to a SYSTEMS PROGRAMMER!!!')
	Return
	END
