$PAGE PASERR.TYP, last modified 3/26/84, zw
$IFNOT paserrtyp

TYPE
error_severity = (no_errors, warnings, errors, fatal_errors);
error_code = (
     (* scalar_id		user_number *)
	err_bad_file		(*    0 *),
	err_flex_var_assignment	(*    1 *),
	err_incl_too_many	(*    2 *),
	err_file_variable	(*    3 *),
	err_fmt_typed		(*    4 *),
	err_bad_directive	(*    5 *),
	err_mword_no_special	(*    6 *),
	err_unclosed_comment	(*    7 *),
	err_comments_too_deep	(*    8 *),
	err_unopened_comment	(*    9 *),
	err_unbalanced_quote	(*   10 *),
	err_number_expected	(*   11 *),
	err_bad_token		(*   12 *),
	err_io_arg_type		(*   13 *),
	err_size_generic	(*   14 *),
	err_bad_option		(*   15 *),
	err_parse_overflow	(*   16 *),
	err_semi_expected	(*   17 *),
	err_then_exp		(*   18 *),
	err_eq_instead		(*   19 *),
	err_do_exp		(*   20 *),
	err_until_exp		(*   21 *),
	err_end_exp		(*   22 *),
	err_if_exp		(*   23 *),
	err_no_operand		(*   24 *),
	err_no_expression	(*   25 *),
	err_no_rparent		(*   26 *),
	err_no_rbracket		(*   27 *),
	err_range_exp		(*   28 *),
	err_upb_exp		(*   29 *),
	err_no_if_pred		(*   30 *),
	err_for_idx_exp		(*   31 *),
	err_no_until_pred	(*   32 *),
	err_no_while_pred	(*   33 *),
	err_following_text	(*   34 *),
	err_prog_id_exp		(*   35 *),
	err_dot_exp		(*   36 *),
	err_semi_before_else	(*   37 *),
	err_for_init_exp	(*   38 *),
	err_for_limit_exp	(*   39 *),
	err_prog_exp		(*   40 *),
	err_fmt_packed		(*   41 *),
	err_no_begin		(*   42 *),
	err_no_rhs		(*   43 *),

$PAGE

	err_stmt_end		(*   44 *),
	err_bad_stmt		(*   45 *),
	err_bad_clause		(*   46 *),
	err_no_declaration	(*   47 *),
	err_no_label		(*   48 *),
	err_no_const_val	(*   49 *),
	err_colon_exp		(*   50 *),
	err_subr_id_exp		(*   51 *),
	err_subr_body_exp	(*   52 *),
	err_parm_decl_exp	(*   53 *),
	err_id_expected		(*   54 *),
	err_eq_expected		(*   55 *),
	err_lbracket_exp	(*   56 *),
	err_of_expected		(*   57 *),
	err_semi_improper	(*   58 *),
	err_no_variant		(*   59 *),
	err_lparent_exp		(*   60 *),
	err_no_case		(*   61 *),
	err_no_stmt		(*   62 *),
	err_no_with_ref		(*   63 *),
	err_no_target_label	(*   64 *),
	err_no_field		(*   65 *),
	err_case_label_exp	(*   66 *),
	err_bad_case_label	(*   67 *),
	err_set_compat		(*   68 *),
	err_no_type_decl	(*   69 *),
	err_no_idx_type		(*   70 *),
	err_not_type		(*   71 *),
	err_no_names		(*   72 *),
	err_cst_too_large	(*   73 *),
	err_operands_bad	(*   74 *),
	err_fil_text		(*   75 *),
	err_symb_kind		(*   76 *),
	err_not_constant	(*   77 *),
	err_not_variable	(*   78 *),
	err_undeclared_name	(*   79 *),
	err_bad_record		(*   80 *),
	err_invalid_field	(*   81 *),
	err_not_pointer		(*   82 *),
	err_not_array		(*   83 *),
	err_str_range		(*   84 *),
	err_rhs_proc		(*   85 *),
	err_not_subr		(*   86 *),
	err_not_scalar		(*   87 *),
	err_bad_subr_decl	(*   88 *),
	err_class_bad		(*   89 *),
	err_already_dcled	(*   90 *),
	err_ret_for_proc	(*   91 *),

$PAGE

	err_no_return		(*   92 *),
	err_opt_set_bad		(*   93 *),
	err_size_flexible	(*   94 *),
	err_zero_divide		(*   95 *),
	err_low_upb		(*   96 *),
	err_bad_element_type	(*   97 *),
	err_type_dcl_invalid	(*   98 *),
	err_module_has_body	(*   99 *),
	err_no_prgm_body	(*  100 *),
	err_pr_error		(*  101 *),
	err_ext_initial		(*  102 *),
	err_type_undefined	(*  103 *),
	err_func_parm_conflict	(*  104 *),
	err_trunc_string	(*  105 *),
	err_pad_char		(*  106 *),
	err_no_forward_body	(*  107 *),
	err_loc_initial		(*  108 *),
	err_no_initial		(*  109 *),
	err_cst_type		(*  110 *),
	err_case_conflict	(*  111 *),
	err_sem_opt_bad		(*  112 *),
	err_int_opt_bad		(*  113 *),
	err_ext_opt_bad		(*  114 *),
	err_set_not_scalar	(*  115 *),
	err_str_len		(*  116 *),
	err_sub_count		(*  117 *),
	err_not_string		(*  118 *),
	err_str_count		(*  119 *),
	err_sub_length		(*  120 *),
	err_exit_bad		(*  121 *),
	err_return_bad		(*  122 *),
	err_io_str_format	(*  123 *),
	err_idx_parameter	(*  124 *),
	err_idx_complex		(*  125 *),
	err_idx_not_scalar	(*  126 *),
	err_list_found		(*  127 *),
	err_with_not_record	(*  128 *),
	err_label_required	(*  129 *),
	err_std_call_arg	(*  130 *),
	err_io_no_args		(*  131 *),
	err_io_file_format	(*  132 *),
	err_fmt_int		(*  133 *),
	err_fmt_real		(*  134 *),
	err_fmt_string		(*  135 *),
	err_scalar_case_required(*  136 *),
	err_lab_defined		(*  137 *),
	err_lab_not_defined	(*  138 *),
	err_incompatible_types	(*  139 *),
	err_cvt_named		(*  140 *),

$PAGE

	err_cvt_unnamed		(*  141 *),
	err_no_file_name	(*  142 *),
	err_addr_ref		(*  143 *),
	err_fmt_extra		(*  144 *),
	err_text_out_type	(*  145 *),
	err_text_in_type	(*  146 *),
	err_lhs_func		(*  147 *),
	err_addr_packable	(*  148 *),
	err_flex_type_required	(*  149 *),
	err_bind_var		(*  150 *),
	err_bind_named		(*  151 *),
	err_bind_unnamed	(*  152 *),
	err_arg_extra		(*  153 *),
	err_arg_missing		(*  154 *),
	err_bind_packable	(*  155 *),
	err_elem_extra		(*  156 *),
	err_elem_missing	(*  157 *),
	err_fld_extra		(*  158 *),
	err_fld_missing		(*  159 *),
	err_set_trunc		(*  160 *),
	err_sub_brackets	(*  161 *),
	err_ptr_deref		(*  162 *),
	err_bad_forward		(*  163 *),
	err_bad_precision	(*  164 *),
	err_packing_invalid	(*  165 *),
	err_psize_not_allowed	(*  166 *),
	err_not_packable	(*  167 *),
	err_bad_flexible	(*  168 *),
	err_bad_generic		(*  169 *),
	err_flex_invalid	(*  170 *),
	err_data_dcl_bad	(*  171 *),
	err_no_entry		(*  172 *),
	err_digit_bad		(*  173 *),
	err_cond_in_subr	(*  174 *),
	err_cond_expected	(*  175 *),
	err_ptr_cvt		(*  176 *),
	err_ptr_no_special	(*  177 *),
	err_extent_textfile	(*  178 *),
	err_dim_specified	(*  179 *),
	err_dim_too_large	(*  180 *),
	err_dim_less_one	(*  181 *),
	err_row_major		(*  182 *),
	err_size_arg		(*  183 *),
	err_size_packable	(*  184 *),
	err_sub_range		(*  185 *),
	err_exp_undef		(*  186 *),
	err_cst_field		(*  187 *),
	err_lab_unrefer		(*  188 *),
	err_bin_buffer		(*  189 *),

$PAGE

	err_for_assignment	(*  190 *),
	err_und_label		(*  191 *),
	err_fil_binary		(*  192 *),
	err_xrf_ref		(*  193 *),
	err_never_called	(*  194 *),
	err_eof			(*  195 *),
	err_unmatched_end	(*  196 *),
	err_in_system		(*  197 *),
	err_sw_expected		(*  198 *),
	err_opt_paren		(*  199 *),
	err_val_expected	(*  200 *),
	err_dir_unterminated	(*  201 *),
	err_bad_length		(*  202 *),
	err_bad_width		(*  203 *),
	err_set_range		(*  204 *),
	err_flex_rec_invalid	(*  205 *),
	err_bio_ref		(*  206 *),
	err_bio_packed		(*  207 *),
	err_bio_generic		(*  208 *),
	err_bio_flexible	(*  209 *),
	err_bio_fmt		(*  210 *),
	err_prog_option		(*  211 *),
	err_alloc_mode		(*  212 *),
	err_bad_hdr_fil		(*  213 *),
	err_ovl_module		(*  214 *),
	err_deb_module		(*  215 *),
	err_deb_optimize	(*  216 *),
	err_cmt_dollar_option	(*  217 *),
	err_addr_nospecial	(*  218 *),
	err_bad_expr		(*  219 *),
	err_chk_sub_option	(*  220 *),
	err_opt_comment		(*  221 *),
	err_inc_file_name	(*  222 *),
	err_fil_not_text	(*  223 *),
	err_fil_typed		(*  224 *),
	err_cst_special		(*  225 *),
	err_fmt_char		(*  226 *),
	err_upb_type		(*  227 *),
	err_lwb_type		(*  228 *),
	err_dim_type		(*  229 *),
	err_bnd_ref		(*  230 *),
	err_standard		(*  231 *),
	err_scl_range		(*  232 *),
	err_sp_sub_option	(*  233 *),
	err_flx_upb_required	(*  234 *),
	err_flx_record		(*  235 *),
	err_rng_empty		(*  236 *),
	err_env_dcl_bad		(*  237 *),
	err_env_has_body	(*  238 *),

$PAGE

	err_type_warning	(*  239 *),
	err_envtype_undefined	(*  240 *),
	err_bad_rl_const	(*  241 *),
	err_ovl_mainseg		(*  242 *),
	err_set_size		(*  243 *),
	err_unused_a		(*  244 *),
	err_no_handler		(*  245 *),
	err_cond_name		(*  246 *),
	err_cond_user		(*  247 *),
	err_cond_maskable	(*  248 *),
	err_hnd_conflict	(*  249 *),
	err_set_rng_empty	(*  250 *),
	err_file_error		(*  251 *),
	err_ptr_new		(*  252 *)
	err1, (*can not open source file*)
	err2, (*file name expected*)
	err4, (*right paren expected*)
	err3, (*switch name expected*)
	err5, (*unexpected text after directive*)
	err6, (*switch name expected after "IF"*)
	err7, (*unexpected "ENDIF"*)
	err8, (*text expected*)
	err9, (*unexpected "SOURCE" in system file*)
	err10, (*keyword expected*)
	err11, (*directive expected*)
	err12, (*unclosed comment*)
	err13, (*number expected*)
	err14, (*length value out of range*)
	err15, (*width value out of range*)
	err16, (*"ENDIF" expected*)
	err17, (*source line too long*));

TYPE
user_range = 0..9999;
level_range = 0..3;
error_table = ARRAY[error_code] OF PACKED RECORD
  user_number: user_range;
  level: level_range
END;


$ENABLE paserrtyp
$ENDIF
  