!
! Grammar for the designation of PRT command lines.
;


G1 =
begin
  <command.line> ->
      (<output.filespec> "_") (list+(",", <input.filespec>))

  <output.filespec> ->
      <file.designation> <switches>

  <input.filespec> ->
      <file.designation> <switches>

  <switches> ->
      ("/" <switch>)*

  <switch> ->
      <switch.name> |
      "no" <switch.name> |
      <switch.name> ":" <switch.value>

  <file.designation> ->
      (<device>) (<username>) <filename> (<ext>) (<ppn>)

  <device> ->
      (V1)6 ":"

  <username> ->
      "(" (V2)12 ")"

  <filename> ->
      (V1)6

  <ext> ->
      (V1)3

  <ppn> ->
      "[" (N)6 "," (N)6 "]"
end;
!
! Grammar designating the switch value which corresponds to the "pages:"
! switch.
;


G2 =
begin
  <switch.value> ->
      list(";", <page.designator>)

  <page.designator> ->
      <page.list> | <page.list> "-" <subpage.list>

  <page.list> ->
      <pg.list>

  <subpage.list> ->
      <pg.list>

  <pg.list> ->
      list(",", <pg.range>)

  <pg.range> ->
      <field> | <field> ".." <field>

  <field> ->
      (= {Integers})
 end;