TITLE	DEFS - Global symbols for BADLH
SUBTTL	The command ".DEBUG BADLH.MAC" get ILL MEM REF in LINK
	LEN1=:111_^D27
	TABLE1=:10000
	LEN2=:222_^D27
	TABLE2=:20000
	LEN3=:333_^D27
	TABLE3=:30000
	PRGEND
TITLE BADLH - MACRO version 53 generates bad LH fixup
	J=2	;Index register
OK:	XWD	LEN1##+400+J,TABLE1##	;This works
BAD1:	XWD	LEN2##+400,TABLE2##(J)	;Fixes up LH of J, WRONG!
BAD2:	XWD	LEN3##+400,TABLE3##(J)	;2nd fixup of J, ILL MEM REF!
	END
