:LOGFILE CHECK1.LOG
INITIA
RDIST CARL.RDS=(CARL)/MASTER:14/HOST:17/CHECK/VERBOSE
RDIST SYS.RDS=(SYS)/MASTER:14/HOST:17/CHECK/VERBOSE
RDIST DERNST.RDS=(DERNST)/MASTER:14/HOST:17/CHECK/VERBOSE
RDIST NOBACK.RDS=(NOBACKUP)/MASTER:14/HOST:17/CHECK/VERBOSE
RDIST JMS.RDS=(JMS)/MASTER:14/HOST:17/CHECK/VERBOSE
