        TITLE NODGET
        ENTRY NODGET
        INFO=0
        NODE=1
        NODE1=2
NODGET:   0
START:  SETZ NODE,
        SETZ NODE1,
        MOVE    INFO,[-1,,-24]
        GETTAB INFO,
        JRST ERROR
        LDB     NODE,[POINT 6,INFO,27]
        LDB     NODE1,[POINT 6,INFO,19]
        DPB NODE1,[POINT 6,NODE,29]
STOP:   MOVE INFO,NODE
        JRA 16,1(16)
ERROR:  SETO    NODE,
        JRST STOP
        END
