Received: from X14.Tymnet by D35.Tymnet; Sun, 23 Aug 87 16:43:57 PDT
Return-path: <Carl@X930.Tymnet> 
From: Carl A Baltrunas <Carl@X930.Tymnet> 
Date: Sun, 23 Aug 87 16:42:56 PDT 
To: ge.kjk@forsythe.stanford.arpa 
Subject: Test #4 

if this works... then ...arpa must be used on our end
instead of ...edu

/Carl
Received: from X930.Tymnet by D35.Tymnet; Sun, 23 Aug 87 21:00:50 PDT
Return-path: <WRS@X930.Tymnet> 
From: WRS@X930.Tymnet 
Date: Sun, 23 Aug 87 20:58:54 PDT 
To: osman, dencoff, carl, jms 
Subject: "I took the liberty of editing"... 

I took the liberty of editing your MAIL.FWD on 930.  I added the
"!" in front of the name so you don't have to worry about forwarding
loops between 930 and 35.  For example, !JMS@C35 is the same as
JMS@C35 except that with the "!" it will suppress any further forwarding.
This ony works if the destination is a Tymcom-X.  -Bill
Received: from X930.Tymnet by D35.Tymnet; Sun, 23 Aug 87 23:56:45 PDT
Return-path: <TXSSUP@X930.Tymnet> 
From: Tymcom-X Supervisor <TXSSUP@X930.Tymnet> 
Date: Sun, 23 Aug 87 23:54:23 PDT 
To: Carl A Baltrunas <carl@X930.Tymnet>, jms 
Subject: "PLEASE SEND THE FOLLOWING MESSAGE"... 

(begin forwarded message)
----------------------------------------------------------------
Received: from F29.Tymnet by X930.Tymnet; Fri, 21 Aug 87 17:25:33 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 21 Aug 87 16:07:03 PDT
Return-path: <NTD.L/JOHNSON@EMSTXS.Ontyme.Tymnet> 
From: NTD.L/JOHNSON@EMSTXS.Ontyme.Tymnet 
Date: 21 AUG 87 20:59:00 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I74923@Ontyme.Tymnet 
Subject: "PLEASE SEND THE FOLLOWING MESSAGE"... 

PLEASE SEND THE FOLLOWING MESSAGE TO ALL OF THOSE INVOLVED IN
SNA/SDLC INTERFACE DEVELOPMENT AND SUPPORT WITHIN HQTECH.

THANK YOU.



                         M E M O R A N D U M

                                          [] T Y M N E T, I N C
DATE>      21 AUG 87  10:13                  Network Technology Development

TO>        NTD MANAGERS

COPIES>    

FROM>      MICHAEL F. RUDE


SUBJECT>   NEW RESPONSIBILITY FOR DRUE BONDAD


-----------------------------------------------------------------------


I AM PLEASED TO ANNOUNCE THAT DRUE BONDAD HAS ACCEPTED THE RESPONSIBILITIES
OF ACTING MANAGER OF THE SNA/SDLC SECTION.

DRUE HAS BEEN A MEMBER OF THE SNA/SDLC TEAM SINCE 1983 WITH PRIME RESPONSIBILITY
FOR THE SDLC PRODUCT.  RECENTLY SHE ALSO ASSUMED RESPONSIBILITY FOR THE SNA
PRODUCT.

I FEEL THAT DRUE'S UNDERSTANDING OF THESE PRODUCTS AND EXPERIENCE WITHIN NTD
SHOULD ENABLE HER TO BE HIGHLY EFFECTIVE IN HANDLING HER NEW RESPONSIBILITIES.
I ASK YOU ALL TO HELP SUPPORT DRUE IN HER NEW ROLE.

MFR/lj
----------------------------------------------------------------
(end forwarded message)

Keywords: IBM interface, 2780/3780/HASP.
Received: from X930.Tymnet by D35.Tymnet; Sun, 23 Aug 87 23:59:23 PDT
Received: from F29.Tymnet by X930.Tymnet; Fri, 21 Aug 87 17:24:37 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Thu, 20 Aug 87 19:24:19 PDT
Return-path: <TXSSUP@X930.Tymnet> 
From: NTD.SUP@EMSTXS.Ontyme.Tymnet 
Date: 20 AUG 87 22:03:20 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I74414@Ontyme.Tymnet 
Subject: NTD ADDRESS/PHONE CHANGES 
Resent-from: Tymcom-X Supervisor <TXSSUP@X930.Tymnet> 
Resent-date: Sun, 23 Aug 87 23:58:18 PDT 
Resent-to: Carl A Baltrunas <carl@X930.Tymnet>, Osman Guven
	<osman@X930.Tymnet>, Joe Smith <jms@X930.Tymnet> 
Resent-cc: Craig Fletcher <fletcherc@X930.Tymnet>, DenCoff 

                         M E M O R A N D U M

                                          [] T Y M N E T, I N C
DATE>      20 AUG 87  12:19                  Network Technology Development

TO>        ALL TYMNET PERSONNEL

COPIES>    AL FENN

FROM>      GAIL CONE


SUBJECT>   NTD ADDRESS/PHONE CHANGES


-----------------------------------------------------------------------



          PLEASE NOTE THAT NTD'S NEW LOCATION IS 2580 N. 1ST. ST. - BLDG B.
          OUR  NEW  FAX PHONE NUMBER IS 922-6125.   ALSO NOTE THAT FLOORS 1
          THROUGH 5 HAVE MESSAGE CENTERS.   FOR GENERAL  ASSISTANCE  PLEASE
          CONTACT:
 
          ELLAN STOKES  - X.7792 - 2ND FLOOR - ENGINEERING DEPT
          SILVIA PULIDO - X.6069 - 3RD FLOOR - NETWORK INTERFACES & APPS
          DIANA VORNE   - X.6498 - 4TH FLOOR - NTD HQ & NETWORK SYS. & ARCH
          ANNE HARRIMAN - X.6649 - 5TH FLOOR - CONSULTING & SUPPORT SERVCS
 
 
          THE FOLLOWING LIST INDICATES DEPT HEAD, DEPT, SECRETARY, ETC.
 
 
          AL FENN,V.P. - NTD HQ - X.6347 - 4TH FLOOR
               GAIL CONE,SECRETARY - X.6090 - 4TH FLOOR
 
          DAVE ALCORN,DIRECTOR - ENGINEERING DEPT.- X.6066 - 2ND FLOOR
               RILLA HARTSOE,SECRETARY - X.6034 - 2ND FLOOR
 
          BILL EUSKE,DIRECTOR - NETWORK SYS & ARCH - X.6093 - 4TH FLOOR
               STARR BLACK,SECRETARY - X.6722 - 4TH FLOOR
 
          MIKE RUDE,DIRECTOR - NETWORK INTERF & APPS - X.6160 - 3RD FLOOR
               LINDA JOHNSON,SECRETARY - X.6057 - 3RD FLOOR

          KEN HOLCOMB,DIRECTOR - CONS & SUPPORT SERVCS - X.6614 5TH FLOOR
               JOY SARGENT,SECRETARY - X.6152 - 5TH FLOOR
Received: from F29.Tymnet by D35.Tymnet; Mon, 24 Aug 87 17:30:09 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 24 Aug 87 14:28:15 PDT
From: TYMPLN.HQ@EMSTXS.Ontyme.Tymnet 
Date: 24 AUG 87 19:56:15 
To: TXSSUP@D35.Tymnet 
Message-id: M14190@Ontyme.Tymnet 
Subject: ACCESS CHARGE SEMINAR 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Mon, 24 Aug 87 19:47:59 CDT 
Resent-to: Joe Smith <jms>, Osman Guven <osman>, Carl A Baltrunas <carl>, Craig
	Fletcher <fletcherc>, Dennis Coffey <dencoff> 

                           T Y M N E T

           MC DONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                       M E M O R A N D U M


   DATE:  AUGUST 24, 1987

     TO:  ALL TYMNET MANAGERS & ALL SALES

   FROM:  JO AN COUCHE

SUBJECT:  ACCESS CHARGE SEMINAR
__________________________________________________________________




               * * ACCESS CHARGE UPDATE * *



Access charges -

  What are they?

  Why does the FCC want to impose them on Tymnet?

  How will they impact our business?

  What can we do to stop the FCC from imposing these charges?


These  questions  and  many more will be answered at  the  Access
Charge  Seminar  on  Thursday,  August 27 9:00-11:00  AM  in  the
Training Room at Valley Green Drive

Please plan to attend.  Contact Jo An Couche at (408) 446-7154 if
you have questions.
Received: from F29.Tymnet by D35.Tymnet; Mon, 24 Aug 87 17:30:09 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 24 Aug 87 14:28:15 PDT
From: TYMPLN.HQ@EMSTXS.Ontyme.Tymnet 
Date: 24 AUG 87 19:56:15 
To: TXSSUP@D35.Tymnet 
Message-id: M14190@Ontyme.Tymnet 
Subject: ACCESS CHARGE SEMINAR 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Mon, 24 Aug 87 19:52:39 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 

                           T Y M N E T

           MC DONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                       M E M O R A N D U M


   DATE:  AUGUST 24, 1987

     TO:  ALL TYMNET MANAGERS & ALL SALES

   FROM:  JO AN COUCHE

SUBJECT:  ACCESS CHARGE SEMINAR
__________________________________________________________________




               * * ACCESS CHARGE UPDATE * *



Access charges -

  What are they?

  Why does the FCC want to impose them on Tymnet?

  How will they impact our business?

  What can we do to stop the FCC from imposing these charges?


These  questions  and  many more will be answered at  the  Access
Charge  Seminar  on  Thursday,  August 27 9:00-11:00  AM  in  the
Training Room at Valley Green Drive

Please plan to attend.  Contact Jo An Couche at (408) 446-7154 if
you have questions.
Received: from F29.Tymnet by D35.Tymnet; Mon, 24 Aug 87 17:30:09 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 24 Aug 87 14:28:15 PDT
From: TYMPLN.HQ@EMSTXS.Ontyme.Tymnet 
Date: 24 AUG 87 19:56:15 
To: TXSSUP@D35.Tymnet 
Message-id: M14190@Ontyme.Tymnet 
Subject: ACCESS CHARGE SEMINAR 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Mon, 24 Aug 87 19:54:55 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 

                           T Y M N E T

           MC DONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                       M E M O R A N D U M


   DATE:  AUGUST 24, 1987

     TO:  ALL TYMNET MANAGERS & ALL SALES

   FROM:  JO AN COUCHE

SUBJECT:  ACCESS CHARGE SEMINAR
__________________________________________________________________




               * * ACCESS CHARGE UPDATE * *



Access charges -

  What are they?

  Why does the FCC want to impose them on Tymnet?

  How will they impact our business?

  What can we do to stop the FCC from imposing these charges?


These  questions  and  many more will be answered at  the  Access
Charge  Seminar  on  Thursday,  August 27 9:00-11:00  AM  in  the
Training Room at Valley Green Drive

Please plan to attend.  Contact Jo An Couche at (408) 446-7154 if
you have questions.
Received: from F33.Tymnet by D35.Tymnet; Wed, 26 Aug 87 0:22:29 PDT
Return-path: <JMS@F33.Tymnet> 
From: JMS@F33.Tymnet 
Date: Wed, 26 Aug 87 0:21:11 PDT 
To: CARL 
Subject: "Why does OSNF:33 get zapped when"... 

Why does OSNF:33 get zapped when it logs in?  OSNF does not have an INIT
file, and PJCVFY says it's null.  I'm confused.  /Joe
Received: from B39.Tymnet by D35.Tymnet; Thu, 27 Aug 87 4:19:16 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Thu, 27 Aug 87 4:11:20 PDT 
To: CARL@B39.Tymnet 
Subject: Re: "Bill, Do you know why I get bared""... 
In-reply-to: your message of Fri, 21 Aug 87 13:46:53 PDT

I fixed this.  Sorry for the delay, but NETVAL has been down every time
I checked lately.  -Bill

----------------------------------------------------------------
From: CARL@B39.Tymnet 
Date: Fri, 21 Aug 87 13:46:53 PDT 
To: wrs 
Subject: "Bill, Do you know why I get bared""... 

Bill,
  Do you know why I get "Access bared" when I try to build a circuit
from BUBBNET back into TYMNET?  It makes it a little difficult to do
anything on system 39.

  If I masque as WRS or something, it works fine...  if you could fix
the problem for me, I'd really appreciate it.  Thanks /Carl

PS.  We've played muciscal hosts in preparation for the move.  X930 is
still the same host, but right now it keeps crashing.  It would be best
to try sending mail to X14 or X17 if 930 is down, or maybe best to D35
during the move.   I will update my local MAIL.FWD to go to 35.

/carl
----------------------------------------------------------------
Received: from D35.Tymnet by D35.Tymnet; Thu, 27 Aug 87 15:07:00 PDT
Return-path: <JMS@D35> 
From: Joe Smith <JMS@D35> 
Date: Thu, 27 Aug 87 16:53:05 CDT 
To: Carl A Baltrunas <Carl@D35.Tymnet> 
Cc: Craig Fletcher <FletcherC@D35>, osman, dencoff 
Subject: Re: File dumps 
In-reply-to: your message of Thu, 27 Aug 87 0:04:41 PDT

Osman restored the 19-AUG 2020 all files to X32 with MODE OLD TAPE.
I restored the 19-AUG F3 all files to X32 with MODE OLD NEWEST.
I restored the 2 tapes from X14 (RP06-2020) with MODE OLD NEWEST to get NEW11.
I restored the 2 tapes from X930 with MODE OLD TAPE for CARL, XEXEC, SUBMIT.
The remainder of the 2nd tape (X930's incomplete incremental) was restored
with MODE OLD NEWEST.  At this point X32 should have the union of all files
from X930, X62, X95, and X118 - no files missing.
From: Joe Smith <JMS@X32> 
Date: Sat, 29 Aug 87 20:52:47 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff, Landa Morris <IPC.L/Morris@Ontyme>, Jan Krivanec
	<IPC.J/Krivanec@Ontyme>, Vida Stafford <TYMOPS.V/Stafford@Ontyme> 
Subject: Host 14 is still on 940NET. 

When I tried to log into JMS:14, the Supervisor told me the host was down
before I had entered my password.  Using JMS:17 requires a password go get
the host down message.  It appears that transparent login to 940NET is still
in effect.

The following hosts are transparent: 1,2,4,6,8,9,11,12,13,14,16,20.
The following hosts are normal: 3,7,10,15,17,18,19,21.

Someone needs to tell the Supervisors that hosts 14 and 16 are normal hosts,
not transparent.   /Joe
From: Carl A Baltrunas <Carl> 
Date: Mon, 31 Aug 87 23:04:04 PDT 
To: jms 
Subject: X32, etc 

I removed X32 or D35 etc from our names in my TUMS.INI so that it will
always try to get the info from MAIL.FWD on those hosts.

/Carl
From: Joe Smith <JMS@D35> 
Date: Tue, 1 Sep 87 16:00:51 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: How to patch the CPU serial number into a monitor SAV file. 

There are three consecutive locations, starting at .CPLOG which describe
the CPU ID.  To look at them, use .CPLOG$6T/=<lf>=<lf>.
  .CPLOG has 2 or 3 letter hardware designation in LH, node number in RH.
  .CPCPU has 'KI', 'KL', etc in LH, APRID number (in decimal) in RH.
  .CPSNO has system number (such as 'F22') in sixbit.
The sixbit quantities can be left or right justified.  I changed 33035C.SAV to
22035C.SAV by using:
  .CPLOG/ $"/XXX/,,3374
  .CPCPU/ $"/KL/,,1421.
  .CPSNO/ $"/F22/
When the new KL is installed, the right half of .CPCPU must be changed.  /Joe
Received: from F33.Tymnet by D35.Tymnet; Tue, 1 Sep 87 16:30:43 PDT
Return-path: <JMS@F33.Tymnet> 
From: JMS@F33.Tymnet 
Date: Tue, 1 Sep 87 16:30:18 PDT 
To: carl 
Subject: "MAILER is not running on F33."... 

MAILER is not running on F33.
Received: from F33.Tymnet by D35.Tymnet; Tue, 1 Sep 87 17:13:15 PDT
Return-path: <OSMAN@F33.Tymnet> 
From: OSMAN@F33.Tymnet 
Date: Tue, 1 Sep 87 17:12:23 PDT 
To: dencoff, carl 
Subject: Meeting 9/2 @10:00 


Received: from B39.Tymnet by D35.Tymnet; Tue, 1 Sep 87 18:22:10 PDT
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Tue, 1 Sep 87 18:15:48 PDT 
To: wrs 
Subject: "?Access barred" 

From B39, I'm still getting barred.  Does it have something to do with the
wrong supervisor being up... each having a different database?

/Carl
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@X930> 
Date: Tue, 1 Sep 87 21:00:04 PDT 
To: carl, Joe <JMS>, osman 
Subject: Host X32. 

Guys,

  I thought we would have X32 for a longer time than it looks like we're
getting.  All day today I've seen a message from Operations telling me that
"Host D32 is no longer timesharing.  Please see your representative.  ..."
Does this mean that any files I had on X32 are now gone, and can only be
recovered by a restore from tape?

Thx!
-D.-
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Sep 87 0:52:30 PDT 
To: dencoff 
Subject: X32 

OOps... we must have overlooked you.. I thought you had heard yesterday
from Joe or Osman...

System 32 went away on Monday at 6pm so that they could swap the KL we
had for X32 in place of the KKI on system 22.  Rather than give us the
KI immediately, since they are moving the KL from BUBB-C to Fremont, we
will get the KL from BUBB-C sometime late Wednesday (if all goes well).

So.. for a KL instead of a KI, no one made any noise... more at the meeting
or from Osman.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Wed, 2 Sep 87 11:03:18 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Wed, 2 Sep 87 10:54:15 PDT 
To: CARL@B39.Tymnet 
Subject: Re: "?Access barred" 
In-reply-to: your message of Tue, 1 Sep 87 18:15:48 PDT

Well, I logged in to NETVAL and lo and behold, somebody had restored the
NETVAL disk to before the change.  They've been having alot of disk
trouble since the move.  Anyway, I made the change again so...here is
your current entry and all SUPs have been updated so it should work.
-Bill

NETVAL - Version 3.10 at 09/02/87 17:54:53

* disp user carl
GAN: 3
UUN: 352477
shut override
district: 3
entry changed: 09/02/87 17:51:06
password changed: 03/14/86
(1) Origin     : class: 0
    Destination:
         groups: 0
          hosts: 39 (home)

* disp update
Current time is 09/02/87 17:55:05 GMT
Blocks in CUD: 2039     MUD update EOF: 0 (0% full)
Class/group table last created: 08/31/87 18:36:28
Scheduled consistency period: 04:00 to 08:00

Sup                    MUD          CLASS/GROUP
          Ptr        Updated          Updated
121           0     09/02 17:53      08/31 18:37
123           0     09/02 17:53      08/31 21:36
124           0     09/02 17:53      08/31 18:37
127           0     09/02 17:53      08/31 19:08

Sup                   CONSISTENCY
     Last Start     Last Stop   End Block         Current Start   Block
121  09/02 04:00   09/02 04:12  complete            
123  09/02 04:00   09/02 04:11  complete            
124  09/02 04:00   09/02 04:08  complete            
127  09/02 04:00   09/02 04:11  complete            

* 
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Sep 87 22:11:49 PDT 
To: Osman Guven <Osman>, dencoff 
Subject: Nicholson status 

I left at 8:40pm after cabling up nodes 6760, 6657, 2346, part of 10115 and
554A.  I tried to load 6760 but it didn't look like it worked... probably
need to check the DR11-C cables to make sure they are connected properly.

I ran KMCLOD so that I could reload the system and got PLEASE LOG IN and
no response on the CTY.  I pushed BOOT and oops... no boot on this pack, so
we are down waiting to be booted from tape.

When I come in, we can check the connections and try it all again.. if anyone
hears from Tracy... let me know what happens or what has happenned.

Thanks... G'night

/Carl
Received: from B39.Tymnet by D35.Tymnet; Thu, 3 Sep 87 23:28:20 PDT
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Thu, 3 Sep 87 23:07:50 PDT 
To: wrs, bartletw 
Subject: NAD %1.07 

I've looked at the code for NAD and it appears that listings are currently
available to anyone running (SOURCE)NAD or anyone having TYMSHARE license.

Actually if the FPN of NAD matches the PPN of the input file, (or TP license)
then a listing can be generated.  What this means is that the current e
will allow anyone running NAD to get listings of any file in SOURCE since the
only version of NAD that is really NAD will be in SOURCE.  Files in BETATEST
are not listable unless you have TP license.

I know where to make the changes... as soon as Dennis Ernst confirms which
source file is the correct file then I will make the changes we discussed.

I feel the following "other" changes should be made...
  1)  Listings can only be generated if you have TP license (or)
      if the input file is in your own directory (or)
      if the input file is in your own GAN [since these are unreadable if
                                            the file is protected, so all ok]
  2)  As per (1) don't care what FPN NAD is run from -- remove check.

...otherwise having everyone run (SOURCE)NAD will allow everyone to get
listings whether or not they have TP license.

To Dennis:  Any reason why your current changes cannot released to the
            entire world?  Or should I change (NAD)NAD01.R05 as well as
            your version [NAD01.R06 or NAD01.R07?]

To Wayne:  Please pass this on to Doug so he knows about the listing 'twist'.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Thu, 3 Sep 87 23:32:19 PDT
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Thu, 3 Sep 87 23:23:46 PDT 
To: dernst 
Subject: NAD sources 

Dennis you have:
   NAD01.BAK  & NAD02.BAK   which appear to be previous versions of
   NAD01.R06  & NAD01.R07   respectively... the difference between each
                            set (*.BAK and .R06/.R07) is the same.

   NAD01.R06 has a newer creation date than .R07 and the major difference is
the treatment of underline "_" between .R06 and .R07.  Which version should
I change?

/Carl
Received: from B39.Tymnet by D35.Tymnet; Fri, 4 Sep 87 8:59:45 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Fri, 4 Sep 87 8:51:24 PDT 
To: qsats.d/ellenberg@ontyme.tymnet 
Cc: WRS@C39.Tymnet, carl@b39 
Subject: "note following message from Carl"... 

note following message from Carl - looks o.k. to me - any comments,
concerns????
----------------------------------------------------------------
From: CARL@B39.Tymnet 
Date: Thu, 3 Sep 87 23:07:50 PDT 
To: wrs, bartletw 
Subject: NAD %1.07 

I've looked at the code for NAD and it appears that listings are currently
available to anyone running (SOURCE)NAD or anyone having TYMSHARE license.

Actually if the FPN of NAD matches the PPN of the input file, (or TP license)
then a listing can be generated.  What this means is that the current scheme
will allow anyone running NAD to get listings of any file in SOURCE since the
only version of NAD that is really NAD will be in SOURCE.  Files in BETATEST
are not listable unless you have TP license.

I know where to make the changes... as soon as Dennis Ernst confirms which
source file is the correct file then I will make the changes we discussed.

I feel the following "other" changes should be made...
  1)  Listings can only be generated if you have TP license (or)
      if the input file is in your own directory (or)
      if the input file is in your own GAN [since these are unreadable if
                                            the file is protected, so all ok]
  2)  As per (1) don't care what FPN NAD is run from -- remove check.

...otherwise having everyone run (SOURCE)NAD will allow everyone to get
listings whether or not they have TP license.

To Dennis:  Any reason why your current changes cannot released to the
            entire world?  Or should I change (NAD)NAD01.R05 as well as
            your version [NAD01.R06 or NAD01.R07?]

To Wayne:  Please pass this on to Doug so he knows about the listing 'twist'.

/Carl
----------------------------------------------------------------
From: Carl A Baltrunas <Carl> 
Date: Fri, 4 Sep 87 19:17:50 PDT 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: uNet, Nicholson 

The 2020, host :14 is up on a single pack and all the nodes are connected
at Nicholson.  6657, 6760, 2346, 10115 and 554A via the modems.  On tuesday
we can try to connect 2770, and or move node 554A to South Bay Center.

Have a nice weekend all...

/Carl & Osman
Received: from F33.Tymnet by D35.Tymnet; Tue, 8 Sep 87 17:52:48 PDT
Return-path: <TXSTEXT@F33.Tymnet> 
From: TXSTEXT@F33.Tymnet 
Date: Tue, 8 Sep 87 17:51:26 PDT 
To: CARL 
Subject: "YOU LEFT THE CAGE COVER ON THE"... 

YOU LEFT THE CAGE COVER ON THE BIRD'S CAGE ALL FDADAY, AND TYYOU DIDN'T CLOSE THE
VERTICAL BLINDS BEFORE YOU LEFT FOR WORK THIS AM.
Received: from B39.Tymnet by D35.Tymnet; Wed, 9 Sep 87 16:25:35 PDT
Return-path: <DERNST@B39.Tymnet> 
From: DERNST@B39.Tymnet 
Date: Wed, 9 Sep 87 16:23:43 PDT 
To: CARL@D35 
Subject: NAD 

CARL, YES NAD01.R06 IS THE ONE TO USE.
DENNIS
From: Osman Guven <OSMAN@X35> 
Date: Thu, 10 Sep 87 16:21:55 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Operator Trainning .. 


                        M E M O R A N D U M

                                                 MC DONNELL-DOUGLAS IPS




DATE>      10 SEP 87  13:56

TO>        Cheryl Eldred
           Supervisors

COPIES>    Bill Fischer
           Osman Guven

FROM>      Rick Daniels


SUBJECT>   TYMCOM-10 Seminar


-----------------------------------------------------------------------


The TYMCOM-10 Seminar will begin the week of 12 October.

Seminar will be conducted from :

     0800 - 1200

     1300 - 1600

each day and will cover different subjects each day.

Participants must be able to attend each day session.

Seminar is opened to everyone who wishes to attend.

Thanks Rick

=====================================================================

Any objection or comment about the date??

-Osman-

Received: from F29.Tymnet by D35.Tymnet; Mon, 31 Aug 87 11:44:10 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 31 Aug 87 11:36:15 PDT
From: IPC.J/KRIVANEC@EMSTXS.Ontyme.Tymnet 
Date: 31 AUG 87 19:34:00 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A07141@Ontyme.Tymnet 
Subject: System D-27 Memo 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Thu, 10 Sep 87 22:42:11 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 
D-27UserMove: 

   Date:  August 31, 1987
     
     To:  All INTERNAL D-27 User's 
     
   From:  Resource Planning & Management
          Jan Krivanec   
     
Subject:  D-27 User Move 
     
 Reason:  System D-27 Shutdown
     
-------------------------------------------------------------------------  
     
     
System D-27 will be permanently shutdown on September 31, 1987. RPM   
has chosen to route all D-27 User's to System D-34 by September 26, 1987.  
     
If you are valid on D-27 and D-34 you are requested to move your own  
files and tapes to D-34. You are to be completed by September 26, 1987.    
     
If you are valid only on D-27, RPM and Operations will move your files
and tapes to D-34. This request will begin September 25, 1987 beginning    
at 1800 pst.   
     
If you have any questions, please call me at (415) 498-2556 or ontyme 
IPC.J/KRIVANEC.


Thank you,
Jan Krivanec
Received: from F29.Tymnet by D35.Tymnet; Wed, 2 Sep 87 7:47:33 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 2 Sep 87 7:45:26 PDT
From: ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet 
Date: 02 SEP 87 15:31:10 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: J11985@Ontyme.Tymnet 
Subject: "ADMINISTRATIVE NO: DIS-87-012"... 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Thu, 10 Sep 87 22:42:49 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 




                                ADMINISTRATIVE          NO:    DIS-87-012
                                    BULLETIN            DATE:  02 SEP 87

         MCDONNELL DOUGLAS DIVERSIFIED INFORMATION SYSTEMS COMPANY



To:                ISG St. Louis Tract III Lists A - H

Subject:           EXPRESS SHIPPING SERVICES



Effective September 1, 1987, the processing of expedite/express parcels
previously handled by Production Services, Information Processing Company
has been transferred to the Metropolitan Services Organization.  The
function and the receiving window has been relocated from Building 307,
1 West to Building 307, 1 East.

The basic services previously provided will continue at the new location.
Hours of operation will be changed effective September 7, 1987 to
8:30 a.m. to 4:30 p.m., Monday through Friday.  Therefore, all parcels
must be to the MSO before 4:30 p.m.

We continue to look forward to being of service to you in this area of
responsibility.


(Original signed by M. J. Daniels)

M. J. Daniels, Manager
Branch Center Tract III
Metropolitan Services Organization - St. Louis


(Original signed by R. W. Brown)

R. W. Brown, Manager
Production Services
Information Processing Services


(Original signed by R. D. Windsor)

R. D. Windsor, Director
Metropolitan Services Organization - St. Louis
From: Tymcom-X Supervisor <TXSSUP> 
Date: Thu, 10 Sep 87 22:43:36 CDT 
To: CARL 
Subject: WHO'S THE SUP!!! 

(begin forwarded message)
----------------------------------------------------------------
Received: from F29.Tymnet by D35.Tymnet; Fri, 4 Sep 87 17:16:08 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 4 Sep 87 17:15:41 PDT
Return-path: <ACS.W/PARSONS@EMSTXS.Ontyme.Tymnet> 
From: ACS.W/PARSONS@EMSTXS.Ontyme.Tymnet 
Date: 05 SEP 87 01:10:53 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A09336@Ontyme.Tymnet 
Subject: WHO'S THE SUP!!! 
WHO'STHESUP!!: 

                      APPLIED COMMUNICATIONS SYSTEMS
 
                           M E M O R A N D U M
 
 
                                                      []  ISG     
 
DATE>      04 SEP 87  17:07

TO>        INTERNAL ONTYME ACCOUNT SUPERVISORS

COPIES>    LES METOUR
           ROBERT LEVRINI
           PHILIPPE DES HORTES

FROM>      WENDY PARSONS


SUBJECT>   WHO'S THE SUP!!


-----------------------------------------------------------------------



ACS is currently updating the DIR.SUPERVISORS file which identifies each
internal OnTyme Account Supervisor and their respective address and telephone
number.
 
Attached you will find the current directory.  Among other benefits, this
directory reduces the amount of time your users may spend trying to locate you.
 
As you will see, some information is incomplete.  That's why we need your
help!  Please send an OnTyme to ACS.SUP with any additions, deletions, or
changes by September 25, 1987.
 
We appreciate you cooperation and look forward to hearing from you.
 
 
*******************************************************************************
 
 
 
*** DIR.SUPERVISORS
UPDATED:  8-6-87
BY: Wendy Parsons
 
                                                                Page  2

 
ACCOUNT        ADDRESS/TELEPHONE*              ACCOUNT SUPERVISOR
=======     =========================         ====================
 
 ACS        SJ: C22 - X6172                      Wendy Parsons
 
 APD                                             Dave Weaver
 
 ARC                                             Richard Goodwin
 
 ATE                                             Marian Del Russo
 
 AUGMENT                                         Bill Daul
 
 CANCSC     4211 Yonge St., Suite 230            Michael Gallant
            Willowdale, Ontario,
            M2P 2A9 Canada
            [   ]
 
 CNS        STL:                                 ?
 
 CREDIT     CUP:                                 Karyn Jenson
 
 CSUK                                            Cherril Foster
 
 CTG        CUP:                                 Nancy Vittum
 
 DBSD       CUP:                                 ?
 
 DSCHQ      STL:                                 ?
 
 DSS        IRV:                                 Cathy Polichetti
 
 ENS        SJ :                                 Laurie Caesar
 
 FAI        STL: L927/303/2E                     Val Wadlington
                 [314] 232-9401
 
 FEDSYS     STL: M614/Bldg 281/Level 4           Gene Weeke
                 [314] 234-3102
 
 FIN        CUP: VG1-B14                         Anita Giluso
                 [408] 446-7778
 
 FSC                                             ?
 
 HRD        CUP: VG1-A08                         Jeri McGoughey
 
 HSD        STL: N519/270/D-1/Post E-2           Nancy Ake
                 [314] 234-3997
 
 IBIS                                            Norm Comite
 
 INTL                                            Laurie Caesar
 
 IPC        STL: L237/306/3/C6                   Bev Martin
                 [314] 232-6943
 
                                                                Page  3

 IS                                              Linn Scoggins
 
 ISGFM      STL: LO69/306/2W/250                 Kathy Waddell
                 [314] 233-5116
 
 ISGHQ      STL: I210/301/3D/392                 Mary Spencer
                 [314] 212-1354
 
 ISGHR      STL:                                 Carolyn Patton
 
 ISID                                            Richard Krahn
 
 ISIGB                                           J. Millward
 
 ISIPR                                           ?
 
 ISITPR                                          Julie Erdman
 
 MAG        CUP:                                 ?
 
 MDACTVL                                         Brad Schuette
 
 MDAIS      STL: W255/306/3E                     Rich Brauer
                 [314] 233-8372
 
 MDCHQ      STL: H351/HQ/5S/572                  Jan Schneider
                 [314] 233-9060
 
 MDCSC      IRV: 99410/TWR/T907                  Jeff Christie
                 [714] 250-1000 x2148
 
 MDCSS      COL: D320/                           Phil Estrem
                 [303] 695-1500
 
 MDISB                                           Jean Van Waterschoot
 
 MDISF                                           Phil Costes
 
 MDISS                                           Eduardo Mancisidor
 
 MDSGP                                           J. Burek, Pollyn
 
 MFG                                             Bob Bockman
 
 MISCO      STL: I386/305/3E/251                 Tom Whelan
                 [314] 232-5895
 
 
 NAD                                             ?
 
 NETS                                            Susan Voth
                       432-5399
 
 NIS                                             Koniyoshi Kamoi
 
 NSCHQ      CUP:                                 Carolee Neff
                [408] 446-7682
 
                                                                Page  4

 NSMS       SJ: Orchard Parkway                  Julia Reuscher
                [408] 942-
 
 NSS        SJ: Orchard Parkway                  Linda Kypke
                [408] 942-5213
 
 NTD        SJ:                                  Gail Cone
 
 NTS        SJ:                                  Kimberly Holland
 
 OPERA      FR:                                  Rick Daniels
 
 PMTS       39100 Liberty Street                 Anne Downard
            Fremont, CA 94538
                [415] 794-2554
 
 PSB        STL:
 
 PSD                                             ?
 
 QSATS      SJ: Orchard Parkway                  Linda Kypke
 
 RCS                                             ?
 
 REMS                                            Lora Brading
 
 SLI                                             Henri Tocheport
 
 TBS                                             Bill French
 
 TCHECK                                          Jan Mueller
 
 TNAD                                            Fran Zapala
 
 TNS                                             Corinne Zerbib
 
 TOC                                             Debbie Hill
 
 TT                                              Irene Fischer-Uhrig
 
 TUK                                             Peter Boraston
 
 TXS                                             Carl Baltrunas
 
 TYM                                             Pat Relfe
 
 TYMHQ                                           Terri Osteen
 
 TYMOPS      SJ:  Orchard Parkway                Rose Doolittle
                  [408] 432-5202
 
 TYMPLN                                          ?
 
 TYMVEND                                         ?
 
 UKCS                                            H.B. Wallace
 
 UKNS                                            H.B. Wallace
                                                                Page  5

 
 UTX                                             Judith Smith
 
 
The following is a list of international internals.  (This list may be
redundant to this list above)
 
 
 ISIGB
 
 ISIPR
 
 ISID
 
 TNS
 
 MDICUST
 
 UKNS
 
 SUPS
 
 SUP
 
 MDISB
 
 TUK
 
 OPERS
 
 CMCSA
 
 ISIAHS
 
 MDINET
 
 MDISES
 
 UKCS
 
 MDISF
 
 OTSUPS
 
 MDI
 
 ISIAPR
 
 ISITPR
----------------------------------------------------------------
(end forwarded message)

Received: from B39.Tymnet by D35.Tymnet; Thu, 10 Sep 87 23:47:23 PDT
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Thu, 10 Sep 87 23:36:20 PDT 
To: dernst 
Subject: NAD 

Dennis,
  I've made the changes that I mentioned to you the other day to a copy of
your file (DERNST)NAD01.R06 which resides in (CARL)NAD01.R06.

The changes are as follows:

 1)  Listing control is dependent soley on TP in .GTPRV for the user.
 2)  Input files in (SOURCE) or (BETATEST) may be read by anyone that
     can run NAD.  Listings or symbols in NIB files still require TP.
 3)  Command files may be read from directory (SOURCE) or (BETATEST) by
     anyone that can run NAD.

When the program is released to (SOURCE) it should have RF license and
be protected ALL RUN RUN.  It is NOT to be put on (SYS).

Bill Soley will replace the NAD on sys with a program which verifies who
the user is by GAN and/or USERNAME and run (SOURCE)NAD for that user who
is allowed to run NAD.   (If he hasn't done it already).

I didn't know whether to rename the file to NAD01.R07 or to change the
name in the source from .R06 or not.  I need someone to test the changes
more thoroughly.  (CARL)NAD###.DIF shows the differences between your
file .R06 and my file .R06 on system 39.

Thanks.

/Carl
Received: from X32.Tymnet by D35.Tymnet; Mon, 14 Sep 87 18:16:12 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Mon, 14 Sep 87 18:14:16 PDT 
To: Ed Barens <IPC.E/Barens@Ontyme>, Jim English <IPC.J/English@Ontyme>, Leland
	Yarbrough <IPC.L/Yarbrough@Ontyme>, Tom Marconi <IPC.T/Marconi@Ontyme>,
	Bill Fischer <IPC.B/Fischer@Ontyme>, Cheryl Eldred
	<IPC.C/Eldred@Ontyme>, Rick Daniels <IPC.R/Daniels@Ontyme>, Bill
	Richardson <FSC.B/Richardson@Ontyme>, Jerry Meyer <FSC.G/Meyer@Ontyme>,
	Ray Donahue <FSC.R/Donahue@Ontyme>, Steve Atwell <FSC.S/Atwell@Ontyme>,
	Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: AR/ARX Parity Error .. 





                                                           Sept 11, 1987


                            AR/ARX Parity Error
                            -------------------

	Any system running with the P035/C monitor if enabled will
report the AR/ARX parity error.  This would give FSCO personnel more
precise information where in the hardware the error happened.

	AR/ARX parity error checking is enabled by KLDCP.  While
in KLDCP type "PE 36<cr>" to enable it and "PE 16<cr>" to disable it.
Once the AR/ARX parity error checking is enabled on the KL10 you must
bring the system up with P035/C monitor or later.

Any question or comment:
OSMAN         =  PDP10 User name
FSC.O/GUVEN   =  Ontyme user name
Phone: (415)922-6236

-Osman-
Received: from F33.Tymnet by D35.Tymnet; Tue, 15 Sep 87 13:01:29 PDT
Return-path: <JMS@X32> 
From: Joe Smith <JMS@X32> 
Date: Tue, 15 Sep 87 12:58:16 PDT 
To: CARL@D35, DERNST@B39 
Subject: NEW11 etc copied from B39 to X32. 

CURR11, NEW11, TOOLS11, DERNST, and part of OLD11 have been copied to
system 32 (the test KI n Fremont).  They were restored with MODE OLD NEWEST.
			/Joe
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 21:09:24 PDT
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Tue, 15 Sep 87 21:04:18 PDT 
To: wrs@b39 
Subject: (MAIL)930.Q 

At least temporarily... you need to have the router forward mail for
system 930 to system 35.  most of the messages in this file on 39 were
probably sent from mailing lists..?..  anyway,   XXX@X930 won't get
delivered until 1) 930 comes back up, and 2) we get a tymnet line to
our micronet so that we can get to 930 from Tymnet.

can you do anything about it... (other than edit the .Q file changing all
the X930's to F35 and renaming it 35.Q ???)

Is this an existing capability of ROUTER.DAT?

/Carl
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 21:12:17 PDT
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Tue, 15 Sep 87 21:08:41 PDT 
To: wrs 
Subject: Bimbo @F70 

Can you tell me the name of the bimbo on F70 that was running a perp job
every 4 seconds and never reading his mail?

Have you implemented the "do not retrun this message" feature when users
do not read their mail?  ...or was it "discard after 30 days" ..or "n days"?
(the second is excellent for messages which are "timely").

/Carl
From: Carl A Baltrunas <Carl> 
Date: Tue, 15 Sep 87 21:15:13 PDT 
To: Dennis Ernst <DErnst@B39.Tymnet> 
Subject: NAD 

Have you had time to check what I did to NAD?
/Carl
From: Carl A Baltrunas <Carl> 
Date: Tue, 15 Sep 87 21:15:55 PDT 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet>, William R Soley <WRS@B39.Tymnet> 
Subject: (SOURCE)NAD 

I made the changes to NAD, but I don't know what Dennis Ernst needs to do
to release his version (prior to my changes) as far as testing.  My new
version is on (CARL:39)NAD.SAV and is in need of testing.  It currently
has RF license for reading files in SOURCE and BETATEST and is protected
ALL RUN RUN.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:08:10 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Tue, 15 Sep 87 22:59:45 PDT 
To: CARL@B39.Tymnet 
Subject: Re: (MAIL)930.Q 
In-reply-to: your message of Tue, 15 Sep 87 21:04:18 PDT

If I change ROUTER.DAT, the mail will be sent to 35, but 35 needs to have
something to do with it.  It'll spend alot of ime sitting there trying to
deliver it to the real 930 or worse yet, to itself.  I'll work on it.  For
now I'll just send it to 35.  -Bill
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:08:13 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Tue, 15 Sep 87 23:05:29 PDT 
To: CARL@B39.Tymnet 
Subject: Re: Bimbo @F70 
In-reply-to: your message of Tue, 15 Sep 87 21:08:41 PDT

I'm sorry, I have no idea how frequently he was running the PERP job.
I've since forgotten the name.  The discard feature is probably not in
the immediate future.  *SIGH*  -Bill
Received: from F29.Tymnet by D35.Tymnet; Fri, 11 Sep 87 16:44:26 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 11 Sep 87 16:25:30 PDT
From: QSATS.G/KOLEK@EMSTXS.Ontyme.Tymnet 
Date: 11 SEP 87 23:46:27 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M18544@Ontyme.Tymnet 
Subject: NEW ADDRESS AND PHONE NUMBERS FOR QSATS 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Wed, 16 Sep 87 1:35:27 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 
NEWADDRESS/TELEPHONENUMBERS: 

                                     MEMORANDUM
                               NETWORK SYSTEMS COMPANY
                       QUALITY SERVICES AND TECHNICAL SUPPORT

          TO:       DISTRIBUTION                       CC:  DON JOHNSON
          FROM:     GLORIA KOLEK                            GARY WALKER
          DATE:     11 SEPTEMBER 1987                       ROURKE McCUSKER
          SUBJECT:  NEW ADDRESS/TELEPHONE NUMBERS:
                    (QSATS) N.T.S., S.T.S, Q.A.
          _________________________________________________________________

          NEW ADDRESS FOR U.S. MAIL DELIVERY:
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-2
          2560 N. FIRST STREET
          P. O. BOX 49019
          SAN JOSE, CA 95161-9019

          NEW ADDRESS FOR PRIVATE DELIVERY SERVICE (UPS, FED-EX, DHL, ETC)
          McDONNELL DOUGLAS CENTER
          (DEPT OR EMPLOYEE NAME + MAIL STOP)  HTS, STS, QA: M.S. F-2
          2560 N. FIRST STREET
          SAN JOSE, CA 95131

          TELEPHONE LISTING FOR QSATS (HTS, STS, QA):
          AREA CODE: 408      PREFIX NUMBER FOR ALL EXTENSIONS: 922

          NAME________________     DEPARTMENT__________________  EXTENSION
          AKELLA, RAM              QUALITY ASSURANCE             7461
          ARNETT, MARY             QUALITY ASSURANCE             7462
          BUBSEY, GAIL             STS (INTERFACE SUPPORT)       7463
          BURROUGH, JOHN           STS (INTERFACE SUPPORT)       7464
          CATTANEO, AUGUST         NTS (H/W TECH. SUPPORT)       7466
          CHEN, BEN                STS (NETWORK SUPPORT)         7468
          CHENG, HENRY             QUALITY ASSURANCE             7470
          CHIANG, SHIRLEY          STS (INTERFACE SUPP, MGR)     7471
          CHU, PING                STS (INTERFACE SUPPORT)       7472
          CLARIDGE, JON            QUALITY ASSURANCE             7473
          CURRI, LOUISE            STS (STS TECH. ANALYST)       7477
          DIAS, LARRY              QUALITY ASSURANCE             7478
          ELLENBERG, DOUG          STS (APPLICATIONS SUPP, MGR)  7480
          FISTE, TOD               STS (INTERFACE SUPPORT)       7484
          HO, RICHARD              STS (INTERFACE SUPPORT)       7486
          HOUGE, DIANA             QUALITY ASSURANCE             7487
          HUSSEY, DAVE             QUALITY ASSURANCE             7489
          JOHNSON, DON             QSATS (NTS, QA, MANAGER       6222
          KOCHMANN, TIM            NTS (H/W TECH. SUPPORT)       7493
          KOLEK, GLORIA            QSATS (NTS, STS, QA, SECY)    7495
          KRUMVIEDE, PAUL          NTS (H/W, S/W DIAG. SUPPORT)  7496
          LANGDON, CARL            STS (NETWORK SUPP, MGR)       7497
          LIU, JEFF                STS (APPLICATIONS SUPPORT)    7498
          LUCAS, JERRY             STS (NETWORK SUPPORT)         7499
          MATUCHA, DEAN            QUALITY ASSURANCE             7500
          McKIERNAN, JOHN          STS (INTERFACE SUPPORT)       7501












          MISTRY, PRAVIN           QUALITY ASSURANCE             7502
          MOORING, ED              NTS (H/W, S/W, DIAG. SUPPORT) 7504
          NARAYAN, KRISHNAN        STS (APPLICATIONS SUPPORT)    7507
          NELSON, PHIL             NTS (H/W TECH. SUPPORT)       7508
          NILLUKA, SANDRA          STS (NETWORK SUPPORT)         7510
          REILLY, JOHN             STS (NETWORK SUPPORT)         7447
          RICHARDS, STAN           NTS (H/W TECH. SUPPORT)       7513
          ROWE, CLIVE              STS (NETWORK SUPPORT)         7514
          SHARMA, ALOK             STS (INTERFACE SUPPORT)       7516
          SHEPHERD, BRUCE          NTS (H/W TECH. SUPPORT)       7517
          SHUTICH, JOHN            NTS (H/W TECH. SUPPORT)       7069
          STEIN, JIM               NTS (H/W TECH. SUPPORT, MGR)  7518
          TURNER, TOM              QUALITY ASSURANCE             7520
          VIVIER, RON              NTS (H/W S/W DIAG SUPP, MGR)  7521
          WALKER, GARY             STS (APPL,NW,INTERFACE, MGR)  7523
          WANG, JAMES              STS (NETWORK SUPPORT)         7524
          WARNER, RUTH             QUALITY ASSURANCE             7525
          YEH, TED                 STS (APPLICATIONS SUPPORT)    7528


          NOTE #1:
          FIELD ENGINEERING HANDBOOK IS COMPLETE AND AVAILABLE TO ORDER.
          PLEASE CONTACT YOUR MANAGER FOR FURTHER DETAILS.


          NOTE #2:
          DUE TO "CIRCUMSTANCES BEYOND OUR CONTROL", OUR MOVE HAS BEEN
          DELAYED FOR ONE WEEK.  WE WERE ORIGINALLY SCHEDULED TO MOVE ON
          FRIDAY, 11 SEPTEMBER 1987; OUR NEW MOVING DATE IS TARGETED FOR
          FRIDAY, 18 SEPTEMBER 1987.  ANY AIL BY U.S. POSTAL SERVICE OR
          PRIVATE MAIL CARRIER WILL BE DELIVERED TO NEW MAILING ADDRESS
          AND REROUTED TO ORCHARD PARKWAY.

          PRESENT TELEPHONE NUMBERS FOR NTS,  STS AND QA  ARE  STILL  VALID
          UNTIL FURTHER NOTICE.

          WHEN  TELEPHONE  NUMBERS  ARE  CHANGED,  AND  YOU  PHONE  OUR OLD
          NUMBERS, THERE WILL BE A RECORDED MESSAGE STATING THAT THESE
          NUMBERS HAVE BEEN DISCONNECTED AND YOU WILL BE GIVEN A NEW NUMBER
          TO USE.

          VOICE MAIL WILL REMAIN ACTIVATED ON OLD TELEPHONE NUMBERS FOR ONE
         WEEK AFTER TELEPHONE NUMBERS ARE CHANGED.

          IF IN DOUBT, PLEASE CALL CORPORATE TELEPHONE OPERATOR AT
          (408) 922-0250.
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:46:06 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Fri, 28 Aug 87 9:01:05 PDT 
To: CARL@D35, WRS@C39.Tymnet 
Subject: "reminder meeting next thurs. 9/3"... 

reminder - meeting - next thurs. 9/3 @ 1:30 - 4th F. B - NAD revisited.
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:46:14 PDT
Received: from tymix.Tymnet by B39.Tymnet; Mon, 7 Sep 87 20:14:25 PDT
Received: by tymix.Tymnet (5.51/4.7) id AA23404; Mon, 7 Sep 87 20:15:48 PDT
Received: by hobbes.Tymnet.com (3.2/SMI-3.2) id AA15598; Mon, 7 Sep 87 20:15:46
	PDT
Return-path: <wrs@hobbes> 
From: wrs@hobbes (Bill Soley) 
Date: Mon, 7 Sep 87 20:15:46 PDT 
To: carl@D35, jms@D35 
Message-id: <8709080315.AA15598@hobbes.Tymnet.com> 
Subject: C compiler 

I've found sources for a Tops-20 C compiler on one of the MIT machines.
Is anyone interested?  -Bill
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:46:18 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 7 Sep 87 22:57:03 PDT 
To: Wayne D. Bartlett <BARTLETW@B39.Tymnet>, Carl A. Baltrunas
	<Carl@D35.Tymnet> 
Subject: (SYS)NAD 

(SYS)NAD is done.  It just needs to be installed.
I guess it can get transmitted by Carl when he does (SOURCE)NAD
or whatevr the procedure is.  -Bill
Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:46:21 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Thu, 10 Sep 87 12:53:11 PDT 
To: Carl A. Baltrunas <Carl@D35.Tymnet> 
Subject: PERPOPER 

I just got about 2500 pages (disk) of mail from system 70 that was
returned to PERPOPER because some bimbo never reads his mail but has
6,123,472 perp jobs that run every 4 seconds.  Anyway, I noticed that
systems 29, 55 and 70 didn't have a mail.fwd in (perpoper) so I created
an empty one.  This will send all the mail to the bit bucket rather
than me.  I noticed on the other systems, you had it going to a file,
but I wasn't sure that was a good idea given the huge volume of stuff
that seems to be happening.  Anyway, change it if you want, just PLEASE
make sure it goes somewhere other than to me.  Wasn't sure you knew
about the empty mail.fwd feature.  -Bill
From: Joe Smith <JMS@X32> 
Date: Wed, 16 Sep 87 1:49:04 CDT 
To: OSMAN, DENCOFF 
Cc: carl, fletcherc 
Subject: C compiler 

(begin forwarded message)

Received: from B39.Tymnet by D35.Tymnet; Tue, 15 Sep 87 23:46:14 PDT
Received: from tymix.Tymnet by B39.Tymnet; Mon, 7 Sep 87 20:14:25 PDT
Received: by tymix.Tymnet (5.51/4.7) id AA23404; Mon, 7 Sep 87 20:15:48 PDT
Received: by hobbes.Tymnet.com (3.2/SMI-3.2) id AA15598; Mon, 7 Sep 87 20:15:46
	PDT
Return-path: <wrs@hobbes> 
From: wrs@hobbes (Bill Soley) 
Date: Mon, 7 Sep 87 20:15:46 PDT 
To: carl@D35, jms@D35 
Message-id: <8709080315.AA15598@hobbes.Tymnet.com> 
Subject: C compiler 

I've found sources for a Tops-20 C compiler on one of the MIT machines.
Is anyone interested?  -Bill

(end forwarded message)

I think we could get Marc Crispin to write a tape at Stanford, if there is
sufficient interest.  /Joe
From: Joe Smith <JMS@X32> 
Date: Wed, 16 Sep 87 8:33:38 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: MUX 2096 is very slow today. 

As of 9/15, MUX hosts 2096 and 1274 have moved from Engines in Orchard Parkway
to Microengines in South Bay Center.  If you have nodes 2366 or 2367 in your
SWITCH.INI, they should be changed to 3170 and 3345 respectively.  I noticed
the change because host 2096 was having problems.  It was "2*OV" and "****"
meaning the link to its only neighbor was overloaded both directions and
had a high line error rate.  1274 was better.   /Joe
From: Joe Smith <JMS@X32> 
Date: Wed, 16 Sep 87 8:40:36 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: [1, 4].UFD damaged on F26. 

The first UFD data page for (SYS:26) was on BPA3 page 10010.  That was one
of the pages that PAKCOP could not read, and had pointers to LOGINN and RPG.
DSKCLN aborted with "Error in RIB - wrong hash code" and "Critical file
damaged".  Page 0 was indeed garbage, and the 2nd page for that hash code
was 10.  After zeroing the offending paged and putting 10 in the link at 777,
the UFD was readable.  Having REFLAG, I restored all of SYS until TITO asked
to overwrite a file.  Typing control-C at that point caused TITO to report
that 102 files were processed, exactly one page worth.  F26 is running a
full DSKCLN at this moment.  /Joe
From: Carl A Baltrunas <Carl> 
Date: Thu, 17 Sep 87 0:58:34 PDT 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: 98% dialup connection 

I sent mail on X14 describing the events, but you won't see them until you
get to the office.  I returned to the office around 7:30 and generated new
code at Nicholson, reloaded 2346, went to SBC to install the new boards,
went back to Nicholson to get a 2nd DUV11 for 2770, back to SBC to install
it, back to Nicholson to load 2770, back to SBC to check the DZV11 and the
node itself, re-pinned 4 male connectors as cross-overs at the DZV11 panel
and connected the modem with a straight male connector.

The modem line works... however, the code is generated with the DZV11 lines
as Hard-Wired and I need to change the configuration to Dial-Up and reload
2770.  I will try to do that on my way to the office tomorrow (today).  I
will check to see who is on before I yank out the plug on 2770, besides I
will need someone to push the HALT/ENABLE and INIT buttons to put it into
it's bootstrap to load.  (I don't remember how to do it remotely).

I am logged in on the modem, and even though I hung up, the modem will not
because the line isn't a dial-up... this should be fixed when I reload it.
Possibly if I logged out first, the modem would drop the circuit... but that
isn't the case.  I just hung up.

/Carl
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Thu, 17 Sep 87 15:35:57 PDT 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: "Guys, The connection to Tymnet"... 

Guys,

    The connection to Tymnet on floor 3 of this building is O.K.!  I've talked
with Dick Kovachs about connecting to Tymnet through his engine.  No problem
-- except that Dick reminded me that we will have to run cable from his
printer room to his phone closet, and from our phone closet to our lab.  He
was concerned about the appearance of the cables.  We might be able to run
them up the (inside of the) walls and through the ceiling, since both ends of
the cable are in rooms with real walls, and I've looked at the ceiling:  it's
typical suspended ceiling.  We could pull cable just like Carl and I did at
Nicholson Way.

    We could be in Tymnet just as soon as the cable is pulled and connected,
and the code is cut!

-D.-
Received: from F29.Tymnet by D35.Tymnet; Fri, 18 Sep 87 8:04:11 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 18 Sep 87 8:01:13 PDT
Return-path: <TYM.D/STUDER@EMSTXS.Ontyme.Tymnet> 
From: TYM.D/STUDER@EMSTXS.Ontyme.Tymnet 
Date: 18 SEP 87 07:35:01 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Message-id: I87128@Ontyme.Tymnet 
Subject: GETTING THE PDP-10 MODE TO WORK! 

HI CARL,
  I'VE FINALLY HAD THE CHANCE/TIME TO TRY TO IMPLIMENT THE SWITCH.INI
STUFF THAT YOU SETUP FOR JOE AND I WHEN WE WERE OUT THERE TO SEE YOU.
WELL, IT SEEMS THAT JOE CHANGED SOME STUFF IN THE INI FILE FOR SOME
REASON. MY BACKSPACE KEY WORKS, BUT I THINK I'M STILL IN TYMSHARE MODE.
ALSO, COULD YOU GIVE ME A FEW QUICK INSTRUCTIONS FOR REC/SENDING
ONTYMS FROM THE PDP 10 MODE.
  ONE OTHER THING, I HAVE A EXECUTIVE REFERENCE MANUAL #IX, AND UNDERSTAND
THAT THERE IS A VERSION X AVAILABLE. DO YOU KNOW WHERE I COULD GET ONE?
YOU CAN EITHER ONTYM ME OR I CAN BE REACHED AT 313-855-0790 EXT 360.
THANKS FOR ALL YOUR HELP,
DAN
From: Joe Smith <JMS> 
Date: Fri, 18 Sep 87 23:53:36 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Micronet dialups are 922-6235 and 922-7432. 

1) The modems are connected to extensions 6235 and 7432.
2) X14 is currently running on the RP06 connected to X17.
3) The San Jose Public Outdial host is 2457.  See example below.

please log in: JMS:2457
TYMNET ASYNCHRONOUS OUTDIAL -- HOST 2457 -- SAN JOSE, CA
>DAIL 922-6235
Dialing...................
Call failed - no answer

>DAIL 922-7432
Dialing....
Connect 1200

G'Day Group, Welcome to TXSNET
We are an island!
-2770-013-
please log in: JMS:14;
host not available through net

please log in: JMS:17;;
proj code:
X14       This is the one-pack RP06 system in Nicholson Lane        X14
.EXIT

please log in:

It looks like someone disconnected the modem in the KL Library - 6235 was
working last night.  /Joe
From: Joe Smith <JMS> 
Date: Thu, 24 Sep 87 12:30:29 CDT 
To: carl, wrs 
Subject: OPER getting duplicate mail on F33. 

I have hardcopy of the following, which was printed from the OPR terminal:

please log in: OPER:33;;
tymshare  1713  23-sep-1987
[mail waiting]
.O MOST
PEREZC
.
!  [mail from Carl A Baltrunas <Carl@D35.Tymnet>]
!  [mail from OPER@F33.Tymnet]
!  [mail from JMS@F33.Tymnet]
!  [mail from Carl A Baltrunas <Carl@D35.Tymnet>]
!  [mail from OPER@F33.Tymnet]
!  [mail from JMS@F33.Tymnet]
!  [mail from Carl A Baltrunas <Carl@D35.Tymnet>]
!  [mail from OPER@F33.Tymnet]
!  [mail from JMS@F33.Tymnet]
!
!DAYTIME
23-SEP-87 19:04:01 PDT
!RDMAIL -H
Carl A Baltrunas <Carl@D35.Tymnet>    Wed, 23 Sep 87 13:37:17 PDT
OPER@F33.Tymnet                       Wed, 23 Sep 87 13:31:22 PDT
JMS@F33.Tymnet                        Wed, 23 Sep 87 13:36:30 PDT


The file (MAIL:33)LOG shows some strangeness going on - it says 
"REQ: <OPER>" every hour!  I tried to clean up a bit by modifying the
SUBMIT jobs for VWALKER and RKARLSON to not send mail and renamed 32.Q to
35.Q after editting it.			/Joe
Received: from D35.Tymnet by D35.Tymnet; Thu, 24 Sep 87 10:55:27 PDT
Received: from B39.Tymnet by D35.Tymnet; Wed, 16 Sep 87 15:20:22 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 16 Sep 87 15:01:56 PDT 
To: CARL@X35 
Subject: "Meant to send copy of the following"... 

Meant to send copy of the following to you::::
----------------------------------------------------------------
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 16 Sep 87 14:58:08 PDT 
To: <QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet> 
Cc: INTL.VIDA@ONTYME.TYMNET 
Subject: Re: Proposal 
In-reply-to: M19398@Ontyme.Tymnet of 16 SEP 87 14:18:03

Just got your draft - to repeat - we (vida, et all) will implement, but we
need the info ( example - the customer list).
the following is the memo from Carl ---
----------------------------------------------------------------
Received: from D35.Tymnet by B39.Tymnet; Tue, 15 Sep 87 22:09:41 PDT
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Tue, 15 Sep 87 21:15:55 PDT 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet>, William R Soley <WRS@B39.Tymnet> 
Subject: (SOURCE)NAD 

I made the changes to NAD, but I don't know what Dennis Ernst needs to do
to release his version (prior to my changes) as far as testing.  My new
version is on (CARL:39)NAD.SAV and is in need of testing.  It currently
has RF license for reading files in SOURCE and BETATEST and is protected
ALL RUN RUN.

/Carl
----------------------------------------------------------------
----------------------------------------------------------------
DID YOU GET DOUG'S DRAFT???? IF NOT, LET ME KNOW.
Received: from D35.Tymnet by D35.Tymnet; Thu, 24 Sep 87 10:55:36 PDT
Received: from B39.Tymnet by D35.Tymnet; Wed, 16 Sep 87 15:57:01 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Wed, 16 Sep 87 15:50:34 PDT 
To: <QSATS.D/ELLENBERG@EMSNTD.Ontyme.Tymnet> 
Cc: Carl A. Baltrunas <Carl@X35.Tymnet>, Wayne D. Bartlett
	<BARTLETW@B39.Tymnet> 
Subject: Re: Proposal 
In-reply-to: M19398@Ontyme.Tymnet of 16 SEP 87 14:18:03

Doug, here is your document back.  It looks very good.  I've marked
a couple of things - some typeos and a couple clearifications.  All
my marks are enclosed in [].  Thanks -Bill

Received: from F29.Tymnet by B39.Tymnet; Wed, 16 Sep 87 14:44:38 PDT
Received: from EMSNTD.Ontyme.Tymnet by F29.Tymnet; Wed, 16 Sep 87 14:44:24 PDT
Return-path: <QSATS.D/ELLENBERG@EMSNTD.Ontyme.Tymnet> 
From: QSATS.D/ELLENBERG@EMSNTD.Ontyme.Tymnet 
Date: 16 SEP 87 14:18:03 
To: NTD.WRS@EMSNTD.Ontyme.Tymnet 
Message-id: M19398@Ontyme.Tymnet 
Subject: Proposal 

            PROPOSAL FOR PROVIDING ENHANCED SECURITY IN THE
            -----------------------------------------------

     STRUCTURE AND ACCESS CAPABILITIES OF DIRECTORIES ON THE PDP 10
     --------------------------------------------------------------

                          CODE GENNING SYSTEMS
                          --------------------






















|                           September 3, 1987

                                   by

                          Douglas G. Ellenberg













                | - Denotes changes from last document.


Contributions:

Individuals who contributed to the document and their organizations.


Quality Assurance    Hardware Technical Support    Network Technology Division

 Diana Houge             Ed Mooring                     Romolo Raffo
|                        Paul Krumviede                 William Soley
                         Ron Vivier


Security             Field Service Company

Wayne Bartlett           Dennis Coffey
                         Carl Baltrunas








Overview:

Security is a major concern in all areas of the Network.  From
restricting access to the Network to restricting the range of
capabilities a user has once a successful connection is made to a
host, security is a concern.  This proposal seeks to address one part
of the security picture.

Today, all users on the PDP Code Genning Systems have the capability to
| access the NAD program in the (SYS) directory.  This program has read
| file license (RF) assigned to it.  With RF license, any user has the
| capability of accessing any file on the PDP through the NAD program.

| What this proposal seeks to control is really two fold.  First, it will
| restrict which users are allowed to use the NAD program.  This will
| restrict users without RF license from accessing files on the PDP they
| should not access.  Secondly, users who are allowed to access the NAD
| program and gen code but should not create code listing will be
| restricted from performing the listing function.

[Thirdly, those who do have access to NAD will only be able to assemble
files from (SOURCE), (BETATEST) or directories that they normally have
access to without license.]

Goals and Compromises:

The ultimate goal for the implementation of restricted access was to
disallow access to the (SOURCE) and (BETATEST) directories from all
users except those that require access.  Those requiring access include
all field and Headquarters support people; Project Implementation; the
Field Service Organization; Customers who, by contract, are allowed
access; the Headquarters Quality Assurance group; and the development
organization.  Groups that required access only to a limited set of
files in the (SOURCE) and (BETATEST) directories would then be
restricted on a file by file basis.  For example, Customer A has in
their contract a license to gen X.25, Node Code and ISIS.  They would be
allowed access to only the source for this code and be barred access to
the remaining source code files.

Unfortunately, barring access down to a per file per user basis is not
possible under current TYMCOM-X limitations.  This capability would
require modifications to the Operating System.  What is possible is to
restrict access to the (SOURCE) and (BETATEST) directories as a whole
and restrict access to some of the capabilities of the NAD program. 
Thus, restricting access on a more limited basis is possible.

After the restructuring of the PDP systems, as will be documented,
restriction to the (SOURCE) and (BETATEST) directories will be on
a per user basis.  Certain users will be barred from being able to
create listings of the source code and will be able to only write files
into their own directories.  They will not be able to over-write files
| of any other users and will be restricted from accessing files that are
| protected and not in the (SOURCE) or (BETATEST) directories.



Restructuring with Restrictions:

There are [two] copies of the code genning program, NAD, on all PDP Code
Genning Systems.  One NAD is the aforementioned copy in the (SYS) directory.
| The second NAD is the copy in the (SOURCE) directory.  Both of these
| copies are identical.  They are both assigned Read File license.

There is also an important feature of NAD that is part of this
restructuring.  If a user lacks TYM license, NAD will not allow that
user to create listings of the source code.  Currently, most users that
gen code have TYM license.  They are able to both gen code and create
listings of the source code.

The changes proposed to create tighter controls on the capabilities of
users on the PDP Code Genning Systems are:

| 1.  Make modifications to the NAD program so the NAD program in the
|     (SYS) directory will only be a verification program for access
|     control.  The NAD program in (SYS) will verify the user attempting
|     to call the NAD program is validated on a GOODGUY list.  If valid,
|     the user will be routed to the real NAD program in the (SOURCE)
|     directory.  The (SYS)NAD program will be given ALL [RUN RUN]
|     restrictions.  (NOTE:  This is a common practice for programs on the
|     PDP's today.)
| 
| 2.  Place protections on NAD in the (SOURCE) directory so it can not be
|     called directly unless the user can override the restrictions with
|     their own license.  This [] will prevent users (such as customers)
|     without proper license from accessing the (SOURCE) NAD program
|     directly.
| 
| 3.  Modify the NAD program in the (SOURCE) directory to set Read File
|     license selectively.  When running NAD, the NAD program will set
|     Read File license if it is attempting to read a file in the
|     (SOURCE) or (BETATEST) directories.  If it is instructed to read a
|     file in any other directory, it will not set Read File license.
|     This will require any file [not in SOURCE or BETATEST] that needs
|     to be read by NAD to have the
|     proper protection to allow it to be read by all users.  This
|     includes files such as patches in other directories or special
|     source files in other directories.  The purpose of this is to not
|     allow users to use the Read File license of NAD to access files they
|     should not have access to.
| 
| 4.  Each customer will be placed in their own GAN.  This will restrict
|     them from being able to look at files in any directory but ones in
|     their own GAN.

| 5.  Remove TYM license from users who should not be able to create
|     listings of the source code.
| 
| 6.  The (SOURCE) and (BETATEST) directories should have directory access
|     protection of  SHARABLE and LISTABLE only.  They currently have
|     SHARABLE, LISTABLE and NEW FILES. 



| When these changes are complete, users not on the NAD GOODGUY list and
| without proper license will not have access to the NAD program.  Without
| the TYM license, they would be unable to create listings of the source
code.  Without the additional licenses on the NAD program they would be
unable to over-write files not in their own directory.  With directory 
access set, users will be prevented from writing into the (SOURCE) and
(BETATEST) directories.

With the current protections placed on all (SOURCE) and (BETATEST)
source code, users without the proper license will not have access to
the files in these directories.  They would be restricted from even
viewing the source files.

| Without proper license, users will not be able to view other users files
| in directories under different GANs.


Concerns and Questions:

PEAK and VUE, the text editors on the PDP's, require modification if they
are to be used by users that do not have TYM license.

Who will be tracking the change of GANs for the customers?

Who will identify the customers requiring these changes?

| An access list will have to be maintained for the (SYS)NAD program.
Received: from D35.Tymnet by D35.Tymnet; Thu, 24 Sep 87 10:55:40 PDT
Received: from B39.Tymnet by D35.Tymnet; Fri, 18 Sep 87 8:47:24 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Fri, 18 Sep 87 8:40:55 PDT 
To: CARL@X35 
Subject: "9/23 meeting bill cannot make"... 

9/23 meeting - bill cannot make it, but how about you - (at my office)??
Received: from D35.Tymnet by D35.Tymnet; Thu, 24 Sep 87 10:55:44 PDT
Received: from B39.Tymnet by D35.Tymnet; Tue, 22 Sep 87 10:05:10 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Tue, 22 Sep 87 9:56:43 PDT 
To: CARL@X35 
Subject: "help are we meeting tommorow or"... 

help - are we meeting tommorow or not??? if  not, how about next week,
Bill may be able to join us then???!!! please respond!!
Received: from D35.Tymnet by D35.Tymnet; Thu, 24 Sep 87 10:55:46 PDT
Received: from B39.Tymnet by D35.Tymnet; Wed, 23 Sep 87 9:34:22 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 23 Sep 87 9:09:12 PDT 
To: CARL@X35 
Subject: "guess router did not like your"... 

guess router did not like your x32 (got the following mail back - am 
resending again:)
`
----------------------------------------------------------------
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 23 Sep 87 8:52:20 PDT 
To: <Carl@X32.Tymnet> 
Subject: Re: PEAK removeal of TYM check 
In-reply-to: your message of Tue, 22 Sep 87 18:05:49 PDT

great news!!!!!!much thanks!! Will procede to get tymlicense removed...
----------------------------------------------------------------
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 23 Sep 87 8:56:29 PDT 
To: <Carl@X32.Tymnet> 
Cc: WRS@C39.Tymnet 
Subject: Re: Meeting 
In-reply-to: your message of Wed, 23 Sep 87 1:33:52 PDT

re the meeting - not this week - but how aboutnext week on thurs -
primary topic "new setop" - plus followup on action re nad etc.
how about tues @ 2:00 or thurs @ 2:00 - or we could meet fot lunch,
and follow with the meeting - also - Bill- can you join????
----------------------------------------------------------------
Received: from D35.Tymnet by D35.Tymnet; Thu, 24 Sep 87 10:55:50 PDT
Received: from B39.Tymnet by D35.Tymnet; Wed, 23 Sep 87 9:34:29 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 23 Sep 87 9:17:22 PDT 
To: <QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet> 
Cc: WRS@C39.Tymnet, CARL@X35, INTL.VIDA@ONTYME.TYMNET, TYMOPS.DJM@ONTYME.TYMNET
	
Subject: Re: Proposal 
In-reply-to: M19398@Ontyme.Tymnet of 16 SEP 87 14:18:03


Great news - PEAK now requires no tymlicense!!! and the NAD revisions
are completed - SEE ATTACHED!!!! Can you get things implemented (with 
help, of course, but you be the "program mgr") We (validations, Vida)
will get tymlicense removed if you tell us the usernames to change, 
and this also relates to the "good guy" names to go on the new GAN, etc.
PLEASE LET ME KNOW WHAT THE PLAN AND SCHEDULE ARE!!!!!!
And one more thing - the loading of NAD (see Carl's memo below)
----------------------------------------------------------------
Received: from X32.Tymnet by B39.Tymnet; Tue, 22 Sep 87 18:04:09 PDT
Return-path: <Carl@X32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Tue, 22 Sep 87 18:05:49 PDT 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet>, William R Soley <WRS@B39.Tymnet> 
Subject: PEAK removeal of TYM check 

I've found the proper sources for PEAK and generated a new version that
no longer checks for TYM-Proprietary.  It is installed on all systems.

/Carl
----------------------------------------------------------------
Received: from X32.Tymnet by B39.Tymnet; Wed, 23 Sep 87 1:34:32 PDT
Return-path: <Carl@X32.Tymnet> 
From: Carl A Baltrunas <Carl> 
Date: Wed, 23 Sep 87 1:33:52 PDT 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet>, William R Soley <WRS@B39.Tymnet> 
Subject: Meeting 

Did you both decide on a meeting time?
  I've not done anything more since our last meeting with SETOP.  I have
however, completed NAD and PEAK.  PEAK is on (SYS) on all PDP_10 systems.
NAD has been "tested" and still resides in (CARL:39)NAD.SAV for more
intensive testing (if anyone feels it necessary, or if some QA procedure
exists for NAD before it is released... however, I doubt it).

  I've not heard back from Dennis Ernst about transmitting it.  I guess
I cando it, but I'd prefer someone in NTD since there are "procedures".

Let me know ... CARL@D35.Tymnet ... if we need to have a review meeting
at this point (soetime this week).

/Carl
----------------------------------------------------------------
Received: from F29.Tymnet by D35.Tymnet; Mon, 21 Sep 87 16:53:59 PDT
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 21 Sep 87 16:45:25 PDT
From: TYMOPS.TOMASI@EMSTXS.Ontyme.Tymnet 
Date: 22 SEP 87 00:08:47 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: M20248@Ontyme.Tymnet 
Subject: NETWORK RESOURCES 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Thu, 24 Sep 87 13:02:33 CDT 
Resent-to: JMS, OSMAN, CARL, DENCOFF, FLETCHERC 

TO ALL SUPERVISORS:  PLEASE DISTRIBUTE THE FOLLOWING MESSAGE TO 
ONLY MANAGERS.  THANK YOU.

                 MCDONNELL DOUGLAS NETWORK SYSTEMS COMPANY

                     T Y M N E T    O P E R A T I O N S

                            M E M O R A N D U M



DATE>      21 SEP 87  15:50

TO>        ALL OPERATIONS PERSONNEL/TYMNET MANAGERS

COPIES>    P. KRETER  W. PRINCE

FROM>      BOB TOMASI


SUBJECT>   NETWORK RESOURCES


-----------------------------------------------------------------------



          I AM PLEASED TO ANNOUNCE THE APPOINTMENT OF THOM  KELLEY  TO  THE

          POSITION OF MANAGER,  NETWORK RESOURCES,  REPLACING JACK SNAVELY.

          THIS APPOINTMENT IS EFFECTIVE MONDAY, SEPTEMBER 28TH, 1987.


          WITH THOM'S APPOINTMENT,  SEVERAL CHANGES WILL BE TAKING PLACE IN

          THE  NETWORK  RESOURCES  GROUP.    FIRST,  THE LOGISTICS PLANNING

          FUNCTION, UNDER FRANK TROGLIONE,  WILL BE MERGED INTO THE NETWORK

          RESOURCES  GROUP AND WILL CONTINUE TO REPORT TO THOM.   THE ORDER

          PROCESSING GROUP, UNDER KATHERINE GOODWIN,  THE PROJECT IMPLEMEN-

          TATION GROUP,  UNDER BERYL AGUA, AND THE RESOURCE CENTER UNDER JO

          HANNAH, WILL ALSO REPORT TO THOM.   THIS COMBINATION OF FUNCTIONS

          WILL BETTER ENABLE US TO ADDRESS THE MATERIAL SUPPORT CONCERNS AS
                                                                Page  2


          THEY RELATE TO ORDER PROCESSING.   PEGGY MACDONALD,  SECRETARY TO

          JACK SNAVELY, WILL ALSO REPORT TO THOM.


          THIS  NEW  NETWORK RESOURCES GROUP WILL THEN REPORT INTACT TO DR.

          A.  S.  (RAJA) RAJARAMAN,  DIRECTOR OF NETWORK  PLANNING.    THIS

          CHANGE  IS  BEING  MADE  TO  CONSOLIDATE  REPORTING FUNCTIONS AND

          PROVIDE  A  MORE  COHESIVE  APPROACH  TO  NETWORK  PLANNING   AND

          IMPLEMENTATION.


          I  TRUST  THAT I CAN COUNT ON YOUR SUPPORT FOR BOTH THOM AND RAJA

          AS THEY ASSUME THEIR NEW ASSIGNMENTS.
Received: from B39.Tymnet by D35.Tymnet; Thu, 24 Sep 87 12:31:12 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Thu, 24 Sep 87 12:23:15 PDT 
To: <JMS@D35.Tymnet> 
Cc: carl 
Subject: Re: OPER getting duplicate mail on F33. 
In-reply-to: your message of Thu, 24 Sep 87 12:30:29 CDT

I checked out 33 and whatever it was is gone now.  You must have fixed it.
Its not clearwhat it was.  Some program was appearently running, opening
a file, and dieing without closing it (this is detected and the mail is
reprocessed by MAILER thus causing the REQ).  The idea being that when a
program dies without cleaning up, you can't tell if it has delivered the
mail it was working on, so to be safe, you deliver it again.  -Bill
From: Carl A Baltrunas <Carl> 
Date: Thu, 24 Sep 87 13:00:58 PDT 
To: Joe Smith <JMS>, William R Soley <WRS@B39.Tymnet> 
Subject: Re: OPER getting duplicate mail on F33 

Bill,
  This problem seems to be occurring off and on... Both Rick Daniels and
Osman have seen it on separate occasions... then it goes away?  Is (MAIL)
up to date on system 33?

/Carl
From: Carl A Baltrunas <Carl> 
Date: Thu, 24 Sep 87 13:02:28 PDT 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet> 
Subject: Meeting 

Apparently a week's worth of my mail got misdirected... I just got all
your mail about the meetings and such today...  Please specify CARL@D35
as my address for the time being... EVEN IF I SEND YOU MAIL FROM X32...
Bill doesn't have a router for that system yet.

/Carl
Received: from F33.Tymnet by D35.Tymnet; Thu, 24 Sep 87 13:05:28 PDT
Return-path: <JMS@F33.Tymnet> 
From: JMS@F33.Tymnet 
Date: Thu, 24 Sep 87 13:02:59 PDT 
To: carl, cc, submit 
Subject: "SUBMIT's default for jobs with"... 

SUBMIT's default for jobs with a repeating date expression should be
MAIL:ERROR instead of MAIL:ALWAYS.  SUBMIT should use defaults suitable
for TYMCOM-X instead of blindly emulating PERP.  /Joe
From: Carl A Baltrunas <Carl> 
Date: Thu, 24 Sep 87 13:09:40 PDT 
To: Joe Smith <JMS> 
Subject: Re: SUBMIT and MAIL 

Repeating dates using MAIL:ERROR as default is a good idea...  However, the
current impolementation of SUBMIT was "supposed" to imitate PERP blindly.

We can change it in the next release...
/Carl

PS.  your message went to SUBMIT, CC, CARL    I suspect you meant CC:Carl
Received: from B39.Tymnet by D35.Tymnet; Thu, 24 Sep 87 13:43:04 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Thu, 24 Sep 87 13:37:08 PDT 
To: <Carl@D35.Tymnet> 
Subject: Re: Meeting 
In-reply-to: your message of Thu, 24 Sep 87 13:02:28 PDT

HOW ABOUT NEXT WEEK'S MEETING - BILL SAYS THURS @ 2:00
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Thu, 24 Sep 87 17:42:11 PDT 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Micro-net to public net connection. 

I saw and talked with Gary Pretty late this afternoon.  I asked him about
completing the sync line for the connection of 2770 to engine 5566.  He is
busy getting async and voice access to those who are moving this weekend, so
he cannot afford the man-hours needed to immediately finish the sync line for
us.

Gary said that our line should be finished early next week.

-D.-
From: Joe Smith <JMS> 
Date: Mon, 28 Sep 87 13:31:31 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Nicholson voice line is 432-1564. 

As of Monday morning, the following phone lines are connected:
  (408)432-1564 = voice line (Pacific Bell beige telephone)
  (408)432-1735 = TXS modem (with Pacific Bell yellow telephone)
  (408)432-0935 = MIS modem (with Radio Shack brown telephone).
The ringer on the Radio Shack phone cannot be heard above the noise of all
the fans, which is why a real telephone is connected to 432-1564.
/Joe
From: Carl A Baltrunas <Carl> 
Date: Mon, 28 Sep 87 12:27:35 PDT 
To: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Subject: Re: Meeting 
In-reply-to: your message of Thu, 24 Sep 87 13:37:08 PDT

Wayne, Thursday at 2:00 will be fine.  Where?
/Carl
   From: Carl A Baltrunas <Carl> 
Date: Mon, 28 Sep 87 12:29:34 PDT 
To: dernst@b39 
Subject: NAD 1.6 (or 1.7) 

What testing has been done to your 1.6 modifications?
(Exactly what were your changes supposed to fix, enhance)?

What has to be done for NAD to be given to QA?

(I don't care whether my changes are included in 1.6 or whether we
 change the version to 1.7 as long as the new version goes out soon.
 I'll be happy to do the legwork if you tell me what needs to be
 done and who needs to get what information.)

/Carl
Received: from B39.Tymnet by D35.Tymnet; Mon, 28 Sep 87 14:31:50 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Mon, 28 Sep 87 14:19:35 PDT 
To: CARL@D35, WRS@C39.Tymnet 
Subject: "this confirms meeting this thurs"... 

this confirms meeting this thurs 10/1 @2:00 - Bill's office (thats to
be sure we have Bill there)
Received: from B39.Tymnet by D35.Tymnet; Mon, 28 Sep 87 14:31:54 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Mon, 28 Sep 87 14:24:22 PDT 
To: CARL@D35 
Cc: WRS@C39.Tymnet 
Subject: "NAD In case you have not heard, "... 

NAD - In case you have not heard, Doug is working on the implementation.
He has asked ??? to move the code over in order to do testing, etc....
Received: from B39.Tymnet by D35.Tymnet; Mon, 28 Sep 87 15:34:20 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 28 Sep 87 15:28:39 PDT 
To: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Cc: CARL@D35 
Subject: Re: "this confirms meeting this thurs"... 
In-reply-to: your message of Mon, 28 Sep 87 14:19:35 PDT

Confirmed but it will be very brief!  -Bill
Received: from B39.Tymnet by D35.Tymnet; Mon, 28 Sep 87 15:39:37 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 28 Sep 87 15:29:58 PDT 
To: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Cc: CARL@D35 
Subject: Re: "NAD In case you have not heard, "... 
In-reply-to: your message of Mon, 28 Sep 87 14:24:22 PDT

~c qsats.d/ellenberg@ontyme
Doug, I've moved my version of NAD to (WRS:33)SYSNAD.* but it should
be installed with the name NAD as follows.

The file (WRS)SYSNAD.SAV goes in (SYS)NAD.SAV with RF license and ALL RUN RUN.
The file (WRS)SYSNAD.LIS goes in (SOURCE)NAD.LIS with no special protection.

NAD.LIS is a demo.  It has comments in it (which you may want to remove
to prevent someone from being tempted to edit it).  Let me know if there
are any questions.  -Bill
Received: from B39.Tymnet by D35.Tymnet; Mon, 28 Sep 87 15:39:43 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 28 Sep 87 15:29:58 PDT 
To: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Cc: CARL@D35, qsats.d/ellenberg@ontyme 
Subject: Re: "NAD In case you have not heard, "... 
In-reply-to: your message of Mon, 28 Sep 87 14:24:22 PDT

Doug, I've moved my version of NAD to (WRS:33)SYSNAD.* but it should
be installed with the name NAD as follows.

The file (WRS)SYSNAD.SAV goes in (SYS)NAD.SAV with RF license and ALL RUN RUN.
The file (WRS)SYSNAD.LIS goes in (SOURCE)NAD.LIS with no special protection.

NAD.LIS is a demo.  It has comments in it (which you may want to remove
to prevent someone from being tempted to edit it).  Let me know if there
are any questions.  -Bill
From: Joe Smith <JMS> 
Date: Mon, 28 Sep 87 22:07:59 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: F38 fixed. 

INFO stopcode "BADSAT" at 28-Sep 10:05 on BPA0 at page 264000
INFO stopcode "BADUFD" at 28-Sep 10:51
INFO stopcode "REDSAT" at 28-Sep 14:04 on BPA0 at page 264000
Hung BPA12,BPA15,BPB5,BPA7,BPA12,BPB7,BPA1,BPA15,BPA10,BPA1,BPA15,BPA6,
     BPA10,BPA3,BPA11,BPA15,BPB7,BPA4,BPA17,BPB4,BPB5,BPA14,BPB6,BPB7,
     BPA13,BPB4,BPB6
INFO stopcode "REDSAT" at 28-Sep 14:    (OPR terminal zapped at this point)
LOGINN not found

At this point they called us.  The RIB for [1,4].UFD was marked bad, the
self pointer was corrupted.  Carl and I fixed the RIB pointer using (MPL)FILDDT.
Tried to bring up system in MANUAL mode, but still "?LOGINN not found".
I went to Solar Way, came up REFLAGged to run TSTSUP.  Turned off the bit
which is set when the monitor finds a bad RIB, and (SYS).UFD was then OK.
Ran a full DSKCLN, answered at 19:41.    /Joe
From: Joe Smith <JMS> 
Date: Tue, 29 Sep 87 13:12:57 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32 disk gone. 

Osman says they overwrote part of our DSKB on the 3650s.  The last incremental
backup was done Friday night - any work done Sunday and Monday is gone.
Received: from F30.Tymnet by D35.Tymnet; Thu, 1 Oct 87 20:12:54 PDT
Return-path: <WADES@F30.Tymnet> 
From: WADES@F30.Tymnet 
Date: Thu, 1 Oct 87 20:12:13 PDT 
To: CARL 
Subject: "WHERE IS SUBMIT CURRENT DOCUMENTATION."... 

WHERE IS SUBMIT CURRENT DOCUMENTATION.
Received: from B39.Tymnet by D35.Tymnet; Fri, 2 Oct 87 0:34:09 PDT
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Fri, 2 Oct 87 0:30:09 PDT 
To: wrs 
Subject: (MAIL)SIGNUP 

Bill,
  Is SIGNUP documented.. that is, do real people know about it, or is it
just for NTD?  Also, can it be run on public network hosts? i.e. 29, or
some host for system 29?  I'd like to have something like it running in
the public net so people can signup for using TUMS instead of having to
login to ONTYME themselves.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Fri, 2 Oct 87 2:06:27 PDT
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Fri, 2 Oct 87 2:03:49 PDT 
To: CARL@B39.Tymnet 
Subject: Re: (MAIL)SIGNUP 
In-reply-to: your message of Fri, 2 Oct 87 0:30:09 PDT

I don't think it works.  At least not right.  It was never finished and
I believe nobody uses it since things moved to 29.  -Bill
From: Joe Smith <JMS> 
Date: Sun, 4 Oct 87 21:13:23 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32's console on F33. 

I called Fremont to see if the test KL was down for a particular reason.
They said the CTY on F33 started smoking, so they borrowed the LA36 from X32.
I suppose they don't have any other current-loop LA36's available.  /Joe
Received: from X32.Tymnet by D35.Tymnet; Tue, 6 Oct 87 11:22:28 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Tue, 6 Oct 87 11:21:11 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: This afternoon .. 

I am going to BLDG "C" to pack my books
this afternoon.
-Osman-
Received: from X32.Tymnet by D35.Tymnet; Tue, 6 Oct 87 11:31:58 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Tue, 6 Oct 87 11:30:57 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Group Meeting .. 

Our "Group Meeting" on Thursday mornning has been
rescheduled to Thursday 10/7 @13:00
-Osman-
Received: from X32.Tymnet by D35.Tymnet; Tue, 6 Oct 87 11:36:16 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Tue, 6 Oct 87 11:33:18 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Group Meeting 10/8 @13:00 

Our "Group Meeting" on Thursday mornning has been
rescheduled to Thursday 10/8 @13:00
-Osman-
From: Carl A Baltrunas <Carl> 
Date: Tue, 6 Oct 87 18:26:49 PDT 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: Kudo's for F26 

Hurray... and another job well done...  We need to test the patch on X32
first, of course...
/Carl
From: Carl A Baltrunas <Carl> 
Date: Tue, 6 Oct 87 18:28:01 PDT 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet>, William R Soley <WRS@B39.Tymnet> 
Subject: Schedule 

My schedule for the rest of october is as follows:
  Oct 5-9 vacation and class preparation
  Oct 12-16 class presentation & possibly available for a quick meeting
  Oct 19-23 Tymnet Class: Engine Programming
  Oct 26-.. back from class and available again

I expect to get back to work on SETOP sometime around the 26th.  If we need
to meet before then, asend mail and I'll see what can be arranged.

/Carl
Received: from X32.Tymnet by D35.Tymnet; Thu, 8 Oct 87 1:02:46 PDT
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Thu, 8 Oct 87 1:01:33 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Schedule .. 

	I would like to work from home for the next 2 days.  Our baby 
was admitted to the hospital last night and is expected to be there for 
severel days. They have diagnosed her as having septic arthritis and 
have started her on antibiotics.  My wife is going to be at the hopital 
most of the time and I will take care of the other kids at home.

	I know Friday we were planning to have a dry run of Monday's 
class.  Please go ahead without me. I will plan to teach the "HARDWARE"
section and it should take me about a day and a half.

	Call me at home or on the pager if you need me or have any questions.

-Osman-
From: Joe Smith <JMS> 
Date: Fri, 9 Oct 87 21:31:27 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: TYMNET moving into Nicholson 

There are 6 Engines in Nicholson Lane.  They are powered up, but not
connected to anything.  It appears that TYMNET has changed the combination
to the back door.  /Joe
From: Carl A Baltrunas <Carl> 
Date: Sun, 11 Oct 87 12:38:39 PDT 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Cc: Rick Daniels <DanielsR@F74.Tymnet> 
Subject: Schedule 10/12-10/16 

Joe,
  I called Osman on Saturday and he was still trying to juggle his schedule
to be available on Monday.  His daughter is not expected to be released from
the hospital until Tuesday sometime (if all goes well).

  I told him that we discussed doig the HARDWARE portion of the class without
him and if he couldn't make it, we would do it.  He was relieved, because it
would have been very difficult for him to make it to Fremont before Wednesday.
On Wednesday, he'll try to be there and cover anything we didn't cover in as
much detail as the class is interested.

  I will stop by the office today to pick up the KL handbook set and the three
volume KL handouts from Rhett's class, just so we will have them available.  I
will also bring the processor reference manual (unless you happen to already
have a copy at home, then you can bring it.  Let me know, so I can leave it at
the office.)

/Carl
From: JMS@D35.Tymnet 
Date: Sun, 11 Oct 87 17:37:48 CDT 
To: carl 
Subject: "It's 3:30pm Sunday afternoon."... 

It's 3:30pm Sunday afternoon.  Node 2770 is down, maybe needs 1000G.
From: Carl A Baltrunas <Carl> 
Date: Sun, 11 Oct 87 17:26:51 PDT 
To: Joe Smith <JMS> 
Subject: F32 still hung 

It's 5:30pm sundy, and F32 is still out to lunch.

/Carl
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Sun, 11 Oct 87 20:30:33 PDT 
To: (Monitor Group:), Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: My availability this week. 

Guys,

  Concerning teaching this week, Wednesday sounds ideal for me.  I'm going to
be at the Cal. Berkeley Extension seminar on UNIX System Administration on
Monday.  The Cal. Extension seminar will be all day, in Mountain View.  I'll
be checking TUMS, Aspen & Judy for messages.  It will be difficult to provide
user support Monday, but I'll do what I can about getting and answering
messages.

-D.-
From: LINDLEY@D35.Tymnet 
Date: Mon, 12 Oct 87 10:36:05 PDT 
To: carl 
Subject: Lunch for Scott 

Just in case you did not get the voice mail message, there will be a lunch
for Scott Daniels on Wednesday, October 14th at 11:45 a.m. at Nicolinos
which is on Tasman off of Lawrence Expressway.  Questions, give me a call.

Incidentally OnTymes sent to you at FSC.C/baltrunas get returned by Tums
as undeliverable to 
Mail was sent on to carl/junk.mai@f29.
-Lois
From: FLETCHERC@D35.Tymnet 
Date: Tue, 13 Oct 87 14:52:14 PDT 
To: OSMAN, JMS, CARL, DENCOFF 
Subject: "SINCE I WILL BEGOING TO"... 

SINCE I WILL BEGOING TO IRVINCE ON THURSDAY I WILL RESCHEDULE THE
WEEKLY MEETING TO FRIDAY AT 10;00 A.M.

	CRAIG
From: FLETCHERC@D35.Tymnet 
Date: Tue, 13 Oct 87 15:06:47 PDT 
To: OSMAN, JMS, CARL, DENCOFF 
Subject: "SYSTEM 39 WILL BE ARUNXXX AROUND"... 

SYSTEM 39 WILL BE ARUNXXX AROUND THRUGH 1988 PER BILL RICHARDSON
VIA BILL \MASURAT.  THAT MEANS WE SHOULD GET IT TO RUN P035/C.

	CRAIG
Received: from D25.Tymnet by D35.Tymnet; Wed, 14 Oct 87 14:22:53 PDT
Return-path: <DenCoff@D35> 
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Wed, 14 Oct 87 14:15:46 PDT 
To: carl 
Subject: SUBMIT Problem, D25. 

Carl,

  We have a problem on D25.  XEXEC jobs (1.) (NETALERT)ALERT 8132, &
(2.) NETALERT)ALERT 8985 are in/out of the queue.  The LIST and SHOW commands
show them as in the queue, but they cannot be MODIFIed or DELETEd.  When I
tried the MODIFY command I got a warning about inability to find the record in
the queue for update, when I tried to INSERT the updated request.  I don't
understand it and have forgotten how to use QUEDDT.  Help!

Thx!
-D.-
From: Dennis Coffey (Tymcom-X Systems) <DenCoff@D35> 
Date: Wed, 14 Oct 87 14:25:43 PDT 
To: carl 
Subject: Problem on :56. 

Carl,

  I've been called by both Don Murtaugh (Tymnet, Mgr. Network Operations)
and Tom Trosuk (FSCO, Mgr. Eastern Reg., Network).  They are having a problem
with their "trouble ticket" software.  For security reasons the program
doesn't allow user to run it from an aux ckt.  It thinks anyone logged in at
2400 bps or with TID 20 is running from an aux ckt.

  Don believes the problem is due to an error in a monitor table.

  Don is here at San Jose, maybe till end of week.  X 7098.  Tom Trosuk is in
Connecticut.  His phone number is 203/562-7020.  (This number is temporary;
the standard number in the FSCO Field Directory is temporarily out of service.
The standard number is 203/562-1885.)
From: Carl A Baltrunas <Carl> 
Date: Thu, 15 Oct 87 1:06:32 PDT 
To: Mail Wizard <MAIL> 
Subject: TUMS-10 bug report (v45000000 of 23-MAY-87) 

Not sure if this si a bug or not...
  but, it appears that some of us are getting multiple copies of mail sent
by OPER on system 33 via TUMS to D35.  If you check messages 157-160 for me
on system 35, user CARL  you'll see what I mean.  I really don't think they
sent the message multiple times, although it is possible...

/Carl
Received: from B39.Tymnet by D35.Tymnet; Thu, 15 Oct 87 8:31:14 PDT
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Thu, 15 Oct 87 8:25:35 PDT 
To: WRS@C39.Tymnet, CARL@D35 
Subject: "Note the following memo. Do you"... 

Note the following memo. Do you have any help for Doug??? Or isit already covered as part of the plan????
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Wed, 14 Oct 87 22:02:56 PDT
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Wed, 14 Oct 87 21:44:53 PDT
Return-path: <ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet> 
From: ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet 
Date: 14 OCT 87 21:10:51 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Message-id: S24491@Ontyme.Tymnet 
Subject: BETATEST File Protections 
BETATESTFileProtections: 

 
                           M E M O R A N D U M
                           - - - - - - - - - -
                            MCDONNELL DOUGLAS
                       INFORMATION SYSTEMS PTY LTD
                         Network Systems Division
                                Australia
 
      TO:  Doug Ellenberg                      DATE:  15 October 1987
    FROM:  Dan Upthegrove                    ONTYME:  ISITPR.D/UPTHEGROVE
  COPIES:  Gary Walker                        PHONE:  (02)887-9415
           Wayne Bartlett
           Tom Turner
           Gary Gardina
 
 SUBJECT:  BETATEST File Protections
 
=========================================================================
 
Doug,
 
As I know that you are already immersed in the protection measures
for source code, I will adress this memo to you. 
 
The attempts to protect the source code on the BETATEST and SOURCE
directories have caused me problems out here in the field before.
Our private net customers have been allocated accounts on PDP-10s,
and are responsible for the generation and loading of their own
network codes.
 
The current plan was to protect the source code files, and only
give NAD the read file license to access these.  I would assume
that the release parameter files would remain accessible, as these
are necessary to the generation and maintenance of the code.
 
This created a problem with PASCAL files, as these files are
initially merged using COPY, not NAD, so someone with RF license
must be involved in the generation of these files.  This is a
hassle that I complained about before.
 
Now, it appears that there is no standard for the allocations
of protection to the BETATEST file, and some release and
parameter files can be accessed, and many cannot.  What, if
it exist, is the policy on the file protections assigned to
these files?  Is there any consideration in these security
policies for the extra time and effort required by field CC's
to transfer this information to the customers, who until now,
have been able to access it on-line?
 
Best regards,
 
 
Dan
----------------------------------------------------------------
Received: from F26.Tymnet by D35.Tymnet; Sun, 18 Oct 87 23:40:35 PDT
Return-path: <JMS@F26.Tymnet> 
From: JMS@F26.Tymnet 
Date: Sun, 18 Oct 87 23:39:07 PDT 
To: carl 
Subject: "Please read crash mail on system"... 

Please read crash mail on system 26, then type (JMS:26)FNDBAD.LOG and
SZRPT.LOG.  Maybe SCNSER dropped ALL yellow balls?
From: Carl A Baltrunas <Carl> 
Date: Mon, 19 Oct 87 11:42:32 PDT 
To: Joe Smith <JMS> 
Subject: CRASH MAIL ON 26 

Anything in pArticular?... I see that you suggested they hit the INIT
button on the base... (I suspectr that it recovers without crashiung
most of the time... Last time it died with TTYFLM)

/Carl
Received: from F29.Tymnet by D35.Tymnet; Mon, 19 Oct 87 13:19:37 PDT
Return-path: <JMS@F29.Tymnet> 
From: JMS@F29.Tymnet 
Date: Mon, 19 Oct 87 13:17:30 PDT 
To: carl 
Subject: "There is a single file by the"... 

There is a single file by the name of (MAIL:29)*.Q which has an ONTYME
message forwarded to <CARL/JUNK.MAI@*>.  "@*" is not correct.
From: Joe Smith <JMS> 
Date: Tue, 20 Oct 87 21:28:54 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Formatting X32's disks. 

I found 2 bugs in PAKCOP(PAKCP5).   
If the 1st string controller is off-line (BPA0-BPA7), then PAKCOP assumes
the entire 3674 controller is off-line (BPA0-17 & BPB0-17).  PAKCP5 didnot
want to look at the string of 3650 disks on BPA10-17 as a result of
the string of 3675 disk on BPA0-7 being switched off.

2nd problem: Although I tried to make PAKCOP do everything SA10NW does,
something is missing.  Those paacks have not been formatted using PAKCOP,
because PAKCOP dies on CYL 559 with "Equip Check".    They were formatted with
SA10NW with FMTM=0, wich does cylinders 0-554 only.  When I tried FMTM=1,
SA10NW aborted because cylinders 555-559 were not set up.  I am now using
FMTM=-1 to re-write HA and R0 - this takes 2 secons per cylinder, 19 minutes
per pack.  After SA10NW finished, thhen I reformat thhem in pages.
I plan do do all but BPA16 - I'll leave that one as a test case for the
next version of PAKCOP.			/Joe
From: Joe Smith <JMS> 
Date: Tue, 20 Oct 87 22:45:38 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32 down - PAKCP5 broken. 

Something is wrong with the current version of PAKCOP - it won't
format at all.  I will investigaet tomorrow.  /Joe
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Wed, 21 Oct 87 13:29:11 PDT 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Leased line troubles. 

Yesterday afternoon I went to Nicholson Way, to look at possible modem
problems.  Our Paradyne modem was powered down.  I turned the power back on
for it.  The indicator LEDs were lit for the 3 left-most indicators and the 1
right-most indicator.  The 4th from the left, which Joe tells me is carrier
detect, was not lit.

I returned to D-2.  The modem in the lab was indicating the same state.  I
tried to load 2770 from the public network, but it wouldn't take a load (it
"timed out", according to LOADII), which should indicate that it was already
loaded fine.

While at Nicholson Way, I neglected to look at the connection between the
Paradyne modem and the leased line.  If it was disconnected when the line was
being worked on Monday (which is highly possible, since they were there and
had powered the modem down) that could be a cause for the communication
failure.

Or (paranoid fantasy):  Tymnet is messing with us, because we have a
non-Tymnet line going into "their" "super site".  (Remember the fortune
cookie:  "Just because you're crazy doesn't mean they're not out to get you.")

-D.-
From: Joe Smith <JMS> 
Date: Thu, 22 Oct 87 1:45:40 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Nicholson Modem working now. 

The 9600 baud modem is in the rack by the F3's, but the leased line interface
is on the other side of the ramp, by the 2020's.  The modular plug at the
interface end was unplugged.  It was not obvious because the it was hidden
by the blue panel.  It has been moved to the back of that rack to be more
accessable - the link came up as soon as it was plugged in.

Host 17 was down to allow Osman to build another KLAD pack on the RP06,
host 14 was brought up but is not visible to the Supervisor due to 2770's
config file.  Until that's fixed, the only way to get to the 2020 that is
host 14 is by dialing (408)432-1735.  It is up now, on the 1-pack RM03.
/Joe
From: Joe Smith <JMS> 
Date: Thu, 22 Oct 87 1:59:02 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: X32 on three 3650s in blocks. 

So that we can all have something to work with, I have formatted 3650's using
SA10NW (BPA10,BPA11,BPA12) and restored X32's files on them.  This way we can
get to our files and I can load PAKCP5 from disk to test it on the other 5
disks.  PAKCOP (all versions) is getting EQUIP CHECK - SYNC OUT ERROR on this
particular string of HDAs.  I plan to add code to type out the 3650 specific
portions of the sense bytes when this occurs.  /Joe

From: Osman Guven <OSMAN@X35> 
Date: Thu, 22 Oct 87 8:57:53 PDT 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Opeartion Class Evaluation .. 

=====================================================================

From: OPERA.SUP@EMSTXS.Ontyme.Tymnet 
Date: 22 OCT 87 00:13:00 
To: TXS.O/GUVEN@EMSTXS.Ontyme.Tymnet 
Message-id: A25027@Ontyme.Tymnet 
Subject: "a. HOW DO YOU FEEL THE SEMINAR"... 

a.  HOW DO YOU FEEL THE SEMINAR WAS PRESENTED?

    THE SEMINAR WAS PRESENTED IN A WELL-ROUNDED MANNER.
NOT ONLY DID THE CLASS LEARN ABOUT BASIC OPERATOR FUNCTIONS
AND THIER IMPORTANCE, BUT ALSO THE FUNCTIONS OF SOFTWARE
SUPPORT AND FIELD SERVICE AND THE WAY IN WHICH ALL GROUPS
INTERACT WITH ONE ANOTHER.

b.  DO YOU FEEL THE SEMINAR SHOULD HAVE BEEN LONGER?

    THE SEMINAR ON THE 10'S LASTED ONE WEEK.  THE AMOUNT OF
MATERIAL COVERED SEEMED TO BE SUFFICIENT. ALTHOUGH CLASS WAS
DISMISSED EARLY EVERYDAY (WHICH THE OPERATORS DIDNT MIND)
SOME OF THAT TIME COULD HAVE BEEN PUT TO MORE USE.

c.  WHAT DID YOU GET OUT OF THE SEMINAR?

    THE SEMINAR PRESENTED MUCH INFORMATION THAT PEOPLE WERE         
UNAWARE OF. FOR EXAMPLE: DIFFERENT COMMANDS AND THIER MEANINGS,
HARDWARE CONFIGURATION AND THE IMPORTANCE OF UNDERSTANDING IT,
DAILY DUTIES AND AN IN DEPTH EXPLANATION OF WHY THEY ARE DONE.

d.  INCLUDE OTHER COMMENTS YOU FEEL ARE PERTINENT.

    OVER ALL, THE PDP10 SEMINAR WAS GOOD.  IT LED ME TO UNDERSTAND
THE SYSTEM BETTER AND THE ACTUAL IMPORTANCE OF MY JOB.  ALTHOUGH
THE FIRST SEMINAR DID COVER A LOT, THE INSTRUCTORS MIGHT WANT TO THINK
ABOUT SPENDING MORE TIME ON BASIC COMMANDS (ESPECIALLY THE BT COMMAND)
AND ALSO HARDWARE  CONFIGURATION.

=====================================================================

This is the class evaluation from Rick Daniels.  It looks good.

-Osman-
Received: from F33.Tymnet by D35.Tymnet; Thu, 22 Oct 87 9:34:40 PDT
Return-path: <JMS@F33.Tymnet> 
From: JMS@F33.Tymnet 
Date: Thu, 22 Oct 87 9:33:50 PDT 
To: CARL 
Subject: "XEXEC is constipated JQUEUE.SYS"... 

XEXEC is constipated - JQUEUE.SYS is 622 pages long - see (JMS)CHAMBR.LOG.
Received: from F33.Tymnet by D35.Tymnet; Fri, 23 Oct 87 17:51:15 PDT
Return-path: <JMS@F33.Tymnet> 
From: JMS@F33.Tymnet 
Date: Fri, 23 Oct 87 17:46:17 PDT 
To: carl 
Subject: "Listing the SUBMIT queue on F33"... 

Listing the SUBMIT queue on F33 takes too long.
Try "LIST (VWARKER) *" to SUBMIT and notice the long pause after the third
line.  Also notice 14039 in there twice with two different statuses.
Then ask SUBMIT for a full LIST and time it with a stopwatch.
It looks like XEXEC needs to do garbage collection on JQUEUE.SYS.
Also, try "FIND 14039 FAILURE (SUBMIT)87102#.JQL"  Verry strang.
From: Joe Smith <JMS> 
Date: Fri, 23 Oct 87 22:22:09 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Where the files went 

Before move:  All TXS files were spread out on 3 systems: X930, X62, X95.

Liberty St:  All of X930 and X62 files were combined onto one system.
  This system was called X118 and consisted of 3 RP06 packs.  It had
  everything that X930+X62 had, except for the directories Carl saved
  on the "ripoff" tape and directories (such as KS2020) which were
  kept on the 2 RM03 X95 system instead.

During move:  Everything was moved to X32 in Solar Way.  X32 used 4 3675
  packs, and had X118's RP06 save restored to it.  To make sure nothing got
  lost, the saves for X930, X62, and X95 were also restored.  Some of the
  ripped off directories came back as a result of this.

After move:  A one-pack RP06 system was build on X17 from the 1-tape save
  and Carl's 4-tape save and the microNET sources from B39.  A one-pack
  RM03 system was built on X14 from the 1-tape save only.

23-Oct-87:  A third RM03 was added to X95's 2-pack set and mounted on X14.
  All the files that Carl had on the 1-pack RP06 system are being restored
  to it.  X14 will have KS2020 and microNET related files.
  The 3-pack RP06 set has been formatted and is being restored to the way
  it was when it was in Liberty St.

Future:  Directories which exist on X17 and X14 need to be sorted out.
  Between the two of them, they have enough space to handle everything
  that is currently on X32.  A 1600bpi save of X32 can then be restored
  to the two 2020s.
From: Joe Smith <JMS> 
Date: Sat, 24 Oct 87 9:19:53 CDT 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Hotline call - TELECO fails with F26-P035/C03. 

Contact: Fremont Operations, (415)498-2588, David Jorgenson, System 26
Problem: Users called in complaining that TELECOPY does not work.
         "TRANSFER ABORTED DUE TO CONTROLLER TRAP" or "NO RESPONSE".
Fix:     Told them to go back to SYSTEM.SAV with F26-P035/C.

This bug is now high priority.  It might affect F22 or F74 running /C03.
			/JMS
From: Joe Smith <JMS> 
Date: Sun, 25 Oct 87 14:41:27 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff, DANIELSR@F26, RICHARDSON@F26 
Subject: TELECO not working (again) on F26. 

Contact: Fremont Operations, David Jorgenson, F26
Problem: TELECO got "TRANSFER ABORTED DUE TO CONTROLLER TRAP" on recieve and
         "CIRCUIT NOT RESPONDING" on sends.
         They were running P035/C.

Work:    Tried reloading P035/C, no luck.  Tried P035/B07 from OLDMON, no luck.
         Tried reloading F26's base, no luck.

         Created special TELECO.SAV with DDT and breakpoint at location TRAP.
         Failure was caused by recieving a null character.  Modified BIO.MAC
         to output in hex all characters read from block I/O input buffer.
         Ran on X32 to get good data, compared with run on F26.  Found
         null characters in input buffer - all non-null characters were good.
         Log is (TSUCOOP:26)TEL0.LOG

Block I/O not working.  Maybe base needs ECO?  Will look at it Monday.  /JMS
From: Osman Guven <OSMAN@X35> 
Date: Wed, 28 Oct 87 9:44:20 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Class Evaluation .. 

Here is an other class evaluation from Sharon Marcotte.
-Osman-


===============================================================================

Subject: TYMCOM - 10 SEMINAR 

DATE> 27 OCT 87
 
FROM> SHARON MARCOTTE
 
TO>   RICK
 
CC>   CHERYL
 
SUBJ> TYMCOM - 10 SEMINAR
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
Rick,
 
Here is my feelings on the TYMCOM-10 training class:
 
A) I feel that the information was well grouped. The instructors did not teach
   as if the students were all programmers, like in most cases.
   The presentation for the most part was well structured, the only obvious
   problem I felt was the fact that the people who were training did not get
   to prepare for the class, due to the personal problems of Osman & Joe.
   For example: The first day Osman was to teach and he had to attend to
   personal business which left Carl & Joe fairly unprepared to teach that day.
 
B) I feel that as far as time constraints that the training should have been
   on a more rigid schedule. Breaks on the hour for 10 minutes, lunches 1 hour,
   class starting and ending as scheduled.
   One week was fine for the duration.
 
C) I refreshed on a lot of items that I had forgotten, unfortunately I missed
   more than I wanted to, but I will be attending the next session.
 
D) All in all I feel that it was a valuable training session.

==============================================================================
From: Joe Smith <JMS> 
Date: Wed, 28 Oct 87 17:09:06 CST 
To: DERNST@39 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC, DenCoff 
Subject: Simultaneous node errors. 

Yesterday, I rerouted power at Nicholson Lane.  I reloaded node 2346 last,
and expected the date and time to come in from the Supervisor as soon as it
started to node 2770.  Instead, the following happened:

27-Oct-87 15:05 2020 host 17 died with ?PAR ERR 373 001, node 6657 OK
27-Oct-87 15:05 2020 host 14 died with ?PAR ERR 373 001, node 6760 OK
27-Oct-87 15:05 node 2346 died with Fatal node error BPT
27-Oct-87 15:05 node 2770 died with Fatal node error CSE
----------------------------------------------------------
G'Day Group, Welcome to TXSNET
You want modems?  We got modems!
-2346-004-
please log in:
Fatal node error BPT
Registers:
  177740  156500  001374  000004  131402  141134  150364  021166  000001
150364:  106214  014626
Debug:
  000000  000000  000000  000000  000000  000000  000000  000000

5
 130374
@
----------------------------------------------------------
G'Day Group, Welcome to TXSNET
We are not an island!
-2770-004-
please log in:
Fatal node error CSE
Registers:
  130164  000000  000004  000000  000000  000000  146460  014042  000000
Stack:
146460:
Debug:
  000000  000000  000000  000000  000000  000000  000000  000000
----------------------------------------------------------

It looks like the "DP parity error" (373) was caused by bad data from the
KMC as a result of 2346 sending garbage to the two bases.  Very strange.
From: Osman Guven <OSMAN@X35> 
Date: Fri, 30 Oct 87 19:41:31 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Class Evaluation .. 

Here is an other "Class Evaluation"

===============================================================================

Date: 29 OCT 87 09:07:00 
To: TXS.O/GUVEN@EMSTXS.Ontyme.Tymnet 
Subject: PDP10 Class Evaluation 

DATE> 29 OCT 87
 
FROM> Jim Wallace
 
TO>   Rick Daniels
 
SUBJ> PDP10 Class Evaluation
 
                              M E M O R A N D U M
 
-----------------------------------------------------------------------------
 
 
      a. How do you feel the seminar was presented?
COMMENT: Due to circumstances the order of the classes had to be changed,
         this did have an effect on the big picture goal of the class since
         it meant others had to be called upon before they were ready. The
         class was also prepared for those who had some experience, yet the
         participants were mainly made of inexperienced persons. These two
         things lessened the effect of the class, however, I thaught the
         classes were very informative.
 
      b. Do you feel the seminar should have been longer?
COMMENT: The seminar really couldn't have been any longer because of
         scheduling problems. I do think that we need to go into detail
         in some areas, in another seminar. A sequel of sorts.
 
      c. What did you get out of the seminar?
COMMENT: I picked up bits and pieces of information from all areas covered.
         I now feel more comfortable with the file structure, and monitor
         concepts inparticular.
 
      d. Include as other comments you feel are pertinent.
COMMENT: Next time we should match the information and class objective with
         the expected participants of the class. I was very satisfied with
         what Lynn and myself took from the class, but the new people will
         probably need to reattend the class once they've worked with the
         PDP10's for a while. Rick I commend you on your part in making
         these classes happen.

===============================================================================
Received: from F33.Tymnet by D35.Tymnet; Sun, 1 Nov 87 23:59:34 PST
Return-path: <JMS@F33.Tymnet> 
From: Joe Smith <JMS> 
Date: Sun, 1 Nov 87 23:52:27 PST 
To: carl 
Subject: Unwedged XEXEC on F33. 

My jobs still had not run since 2-Oct-87, and several other SUBMIT jobs were
also long overdue.  Believing the problem was in the two requests 14039, I
did the following:

	!ATTACH 4		;Job running XEXEC
	.SETE 777777,6		;"O ALL" does not provide QM license
	!R DECDDT
	File: SYS:JQUEUE.SYS/D/P
	0,,-1$M   14039.$W
	xxxx/ yyyy,,14039.
	zzzz/ 14039.
	$<cr> 14039.   $Q-2
	$<cr> yyyy,,14039.   $Q-3
	^Z
	!SUBMIT
	SUBMIT> CANCEL CHAMBR 14036
	SUBMIT> CANCEL CHAMBR 14037
	SUBMIT> ^Z
	!GET (SYS)XEXEC
	!CSTART
	;9 jobs started up.
From: Carl A Baltrunas <Carl> 
Date: Wed, 4 Nov 87 0:53:38 PST 
To: lmorris 
Subject: New INIT file 

Landa,
  I changed your INIT program from (CARL)LOGON to (SYS)LOGON and modified
your SWITCH.INI to reflect the changes necessary to make it work.  There
were a few changes...  Anyway, I wanted you to know so you could complain
if anything appears broken.  Thanks again.  /Carl
Received: from F33.Tymnet by D35.Tymnet; Thu, 5 Nov 87 16:23:42 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Thu, 5 Nov 87 15:37:08 PST 
To: wrs 
Subject: RUB (restricted user?) 

Bill,
  I'm going to be releasing a new version of NONAME  <Yayyyy!!!> very
soon, (like next week) with many changes.  All the whitespace is gone
and it tells you what you've changed, but doesn't ask you if it's OK
or do you want another... like the old one.  I've added capabilities to
set AUTOLOGOUT,  LOGOUT-ON-STOP,  and  RCM  which require acct-sup to
change..  So, now anyone with A.S. can set/clear these options..

Do you know what the RUB bit is for?

/Carl
Received: from F29.Tymnet by D35.Tymnet; Thu, 5 Nov 87 23:00:48 PST
Received: from B39.Tymnet by F29.Tymnet; Thu, 5 Nov 87 23:00:33 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Thu, 5 Nov 87 22:55:20 PST 
To: carl@29 
Subject: SUBMIT/PERP 

How can I get the syystem to automatically retry jobs that abort?
I can't find any documented way to do this.  Thanks -Bill
From: Carl A Baltrunas <Carl> 
Date: Fri, 6 Nov 87 14:01:10 PST 
To: William R Soley <WRS@B39.Tymnet> 
Subject: Retry jobs in submit 

That stuff hasn't been written yet...  it will be available with the
restart option, when the next release of XEXEC/SUBMIT after the next
monitor release P035/D occurs.  Sorry, but the whole ABORT thing happens
as a deficiency in the current system.
/Carl

From: TXSTEXT@D35.Tymnet 
Date: Fri, 6 Nov 87 16:36:54 PST 
To: carl 
Subject: "How come, when I've tried to link"... 


How come, when I've tried to link to you lately, you are always, repeat ALWAYS 
unavailable? I CAN take a hint, ya know.   /Wad
From: Carl A Baltrunas <Carl> 
Date: Sun, 8 Nov 87 23:54:59 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Cc: William R Soley <WRS@B39.Tymnet> 
Subject: NONAME version %42(22) 

There is a new version of NONAME which has a variety of things changed
in it, in particular allowing different changes to be made depending on
your status.  Of course, all that horrid white-space has been flushed
away in favor of a more user friendly scanner.

New features for Roy Roskilly - Autologout may be set, however no limit
                                is currently available although there is
                                room in the district word for it...

New features for security     - Logout on stop may be set/cleared
                                requires an account-supervisor to do this

                              - Restricted Command Mode may be set
                                requires an account-supervisor to do this

/Carl

Release will occur after some beta-testing by Roskilly.
From: Carl A Baltrunas <Carl> 
Date: Mon, 9 Nov 87 0:03:02 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Cc: William R Soley <WRS@B39.Tymnet> 
Subject: Autologout changes 

Again... to aid in implementing Roy Roskilly request the monitor commands
which affect the user's incativity time-out have been modified to allow
anyone to set a limit between 1 and the system default limit.  However, to
set the limit to 0 or to a value greater than the system default, you MUST
be an account supervisor or (have OP, WC or JL license, since anyone with
these licenses can change their limits by mucking around).

Affected areas:
   SET AUTOLOGOUT n           0 < n <= system-default   anyone
                              n=0 or n > system-default supervisor or license
   SET NOAUTOLOGOUT           same as SET AUTOLOGOUT 0 -- see above

   SETINA UUO                 same as commands above

Unaffected:
   SET DEFAULT INACTIVITY n   requires OP license to set/change system-default


/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 9 Nov 87 0:14:45 PST 
To: Osman Guven <Osman> 
Subject: Noname %42 

Osman, the .SHR and .LOW files are in (OSNF:35) and may be moved to
  (FTSYS:??) where ?? is any system that ROY would like to try it on.
  License required is: RF and WF so it may access and write to LUD.SYS
in directory SYS.

/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 9 Nov 87 18:35:00 PST 
To: William R Soley <WRS@B39.Tymnet> 
Subject: MAIL from oper@f33 

We have F33 setup using SENDMAIL with the send command... and  we consistantly
receive 2 copies of each message sent by OPER to (UTIL)CRALST.CMD.  Could you
please take some time to investigate why we get 2 copies... I think everyone onn
the list gets 2 copies... if you'd like an example, I can put you in CRALST so
you can see what I mean.

/Carl
Received: from F33.Tymnet by D35.Tymnet; Tue, 10 Nov 87 18:17:51 PST
Return-path: <JMS@F33.Tymnet> 
From: JMS@F33.Tymnet 
Date: Tue, 10 Nov 87 18:17:05 PST 
To: carl, osman 
Subject: "Strange coincidence: On system"... 

Strange coincidence: On system 33 type "DIRECT (M33)ONC###.MAC/WORDS".
Received: from B39.Tymnet by D35.Tymnet; Thu, 12 Nov 87 8:37:49 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Thu, 12 Nov 87 8:35:41 PST 
To: CARL@D35 
Subject: "Are you there Oh Carl!!!! See"... 

Are you there - Oh Carl!!!! See my 11/9 me.............
Received: from X32.Tymnet by D35.Tymnet; Fri, 13 Nov 87 9:17:21 PST
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Fri, 13 Nov 87 9:16:13 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: Meeting is at 11:00 today .. 

Metting is rescheduled.
From: Joe Smith <JMS> 
Date: Sat, 14 Nov 87 23:32:00 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: C05 working. 

A minor typo was found in /C05 which caused LDBLOG to report the wrong node
number on PTYs (such as SUBMIT jobs).  (M33)C05.PAT has been applied to all
copies of ##XC05.SAV and to NEWMON.SAV on all Fremont systems.  74XC05.SAV
had to be rebuilt with 127 jobs instead of 128 to handle 4 strings of 3675
disks.  We expect P035/C05 on all Fremont machines on Sunday.  /Joe
From: Joe Smith <JMS> 
Date: Sat, 14 Nov 87 23:37:43 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC, DenCoff 
Subject: Backup save done - (NOBACKUP:32)INC.NOV 

I did an incremental save of X32's disks tonight before the power shutdown.
As usual, the tape directory is stored in directory NOBACKUP.  /Joe
Received: from F29.Tymnet by D35.Tymnet; Mon, 2 Nov 87 10:03:16 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 2 Nov 87 9:58:05 PST
From: NETS.TTE@EMSTXS.Ontyme.Tymnet 
Date: 02 NOV 87 17:32:54 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: I06734@Ontyme.Tymnet 
Subject: TTE 1st Qtr Schedule 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Sun, 15 Nov 87 0:10:57 CST 
Resent-to: JMS, OSMAN, CARL 
Resent-cc: DENCOFF, FLETCHERC 
TTE1stQuarter88Schedule: 

                            M E M O R A N D U M

                          NETWORK SYSTEMS COMPANY
                         NETWORK SYSTEMS MARKETING


DATE>      30 OCT 87  13:17

TO>        The World

COPIES>    

FROM>      Tymnet Training and Education


SUBJECT>   TTE 1st Quarter 88 Schedule


-----------------------------------------------------------------------


The Tymnet Training and Education schedule for the 1st quarter '88
is now available via ontyme  :EXEC *** TTE.ENROLL

As a result of your feedback after class and the recommendations of the
training advisory task forces we have made some changes in our
courses.

  1.  The length of  TTE 455 Utilities Code Generation has been
      increased to 8 days to provide more time for hands-on labs.

  2.  SmarTym has been added to the TTE 230 Tymnet 3270/CMT/SmarTym
      course and the length has been extended to 8 days.

  3.  The name of TTE 260 has been changed to Async Error Correction, we
      now cover X.PC, Network Server, Menu Server and 2 new
      protocols - MNP & AFT

  4.  The CPU III, MAC III and Nano engine were added to the TTE 330
      TYMNET Hardware Maintenance and Troubleshooting.

  5.  The requirement for either TTE 455 or TTE 445 as a prerequisite 
      for TTE 450 has been revised.

The enrollment procedure remains the same - use  :EXEC *** TTE.ENROLL
In the last quarter we had some students show up who were not on our
roster.  Please be sure to send an enrollment form at least 5 weeks 
before your class.  That way we will be sure we have enough materials
and lab equipment available for you.  You should receive confirmation of
your enrollment within 2 days of your registration.

We look forward to seeing you in class next quarter.  If you have any
questions about the schedule or prerequisite courses, please give us a
call.  Our new phone number is (408) 922-7620


Sincerely,

Robert C. Grandey
Received: from F29.Tymnet by D35.Tymnet; Tue, 3 Nov 87 13:25:42 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 3 Nov 87 13:24:29 PST
From: OPERA.SUP@EMSTXS.Ontyme.Tymnet 
Date: 03 NOV 87 21:01:42 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: A28777@Ontyme.Tymnet 
Subject: "MCDONNELL DOUGLAS INFORMATION"... 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Sun, 15 Nov 87 0:11:53 CST 
Resent-to: JMS, OSMAN, CARL 
Resent-cc: DENCOFF, FLETCHERC 

                            MCDONNELL DOUGLAS
                      INFORMATION PROCESSING COMPANY
                             4340 Solar Way
                         Fremont, California 94538
                             POWER SHUTDOWN

Time and Date Scheduled Down (PST or PDT)?  2300, 14 NOV 87 (PST)
Time and Date Scheduled Up (PST or PDT)..?  0700, 15 NOV 87 (PST)





The following ONTYME Hosts are affected:

515(B), 832(A), 1304(C), 2256(D), 2257(F), 2258(E),
2259(G), 2260(H), 2261(I), 7148(J), 7150(K), 7152(L),
7153(M), 7154(N), 2287(O), 2288(P), 2289(Q), and
2859(Z)

The following RAILTRACK Hosts are affected:

114, 555

The following ONTYME Utility Nodes are affected:

5321

The following OUTDIAL Hosts are affected:

4258, 834, 919

The following BISYNC VM Hosts are affected:

590 and 7246

The following TYMCOM-10's are affected:

F22, F26, F29, F30, F33, F38, B39, F58, F74

The following RAM Systems are affected:

6914 and 6915

The following NETVAL System is affected:

5514

The following OFFICE Systems are affected:

OF4-1087, OF1-1088, OF8-1643



Reason:  

>P G and E will be working on the street power during this time frame.
>

Please adjust your processing schedule as necessary.

Thank You, 
Fremont Computer Operations  <MDCISG IPC>                              
(415)498-2588 or Ontyme OPERA.BATCH
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Sun, 15 Nov 87 16:33:32 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Temporary absence from office. 



                                  MEMORANDUM


                                                              TYMCOM-X SYSTEMS

DATE:  15-Nov-87    16:34:44    

  TO:  Craig, Carl, Osman & Joe

FROM:  Dennis Coffey  (Tymcom-X Systems)

SUBJ:  Delayed arrival Monday.

------------------------------------------------------------------------------

Guys:

	There have been a few problems around here, that I must stay home
Monday morning to try to get fixed.  I will not be arriving until I have
gotten the minimum fixed, or at least started.  Item on my list:

	1.)  Repair the U-joint on my car which broke Saturday, so it can move
under its own power and thereby get me to work.  (Car is currently in my
driveway.  I am unable to find a replacement U-joint.  The car must be out of
the driveway Monday morning, to make room for the 40 cubic yard "dumpster"
which will be placed to receive the old roofing shake and other construction
material/debris which is scattered throughout the house and yard.)

	2.)  Hire someone to dig up my front lawn, to find and fix the place
in the main sewer line from the house which is broken and since Saturday will
not allow anything to flow.  (I miss clean clothes, a shower and a toilet.)

	3.)  Be here to meet the roofers Monday morning.

	4.)  Finish wiring the kitchen and installing the range hood vent
through the ceiling and roof, so the kitchen ceiling drywall can be finished
and the new roof can be installed with the vent included.

	Items 1, 2 & 3 will be taken care of Monday morning.  Item 4 is a
project for tonight.

	-D.-
Received: from X32.Tymnet by D35.Tymnet; Mon, 16 Nov 87 0:19:03 PST
Return-path: <OSMAN@X35> 
From: Osman Guven <OSMAN@X35> 
Date: Mon, 16 Nov 87 0:17:23 PST 
To: Monitor Group <OSMAN>, Joe Smith <JMS@X35>, Carl Baltrunas <Carl@X35> 
Cc: Craig Fletcher <FletcherC@X35>, Dennis Coffey <DenCoff@X35> 
Subject: On call .. 

I am on call 11/16 to 11/22  -Osman-
From: Carl A Baltrunas <Carl> 
Date: Tue, 17 Nov 87 14:38:58 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: Schedule 

  I haven't been feeling well the past couple of days.  I was running a fever
Sunday night and yesterday and felt rather weak.  Today, feeling better but
still a little weak.

  I expect to be in for the meeting at 10am on Wednesday.  Will be doing a
little work from home today.  Send mail or call me if anything important
comes up.

/Carl
Received: from X32.Tymnet by D35.Tymnet; Sat, 21 Nov 87 14:30:22 PST
Return-path: <JMS@X32.Tymnet> 
From: Joe Smith <JMS> 
Date: Sat, 21 Nov 87 14:27:12 PST 
To: carl@X32, Carl@D35 
Subject: My 3rd Hartnell tape. 

Tape  Pos  Counters  Story         (**** means story not recorded yet)
#H2   11  2914-3106 The Sensorites - Strangers in Space         17-Dec-86
#H2   12  3107-3295 The Sensorites - The Unwilling Warriors     18-Dec-86
#H2   13  3296-3482 The Sensorites - Hidden Danger              19-Dec-86
#H2   14  3483-3654 The Sensorites - A Race Against Death       20-Dec-86
#H2   15  3655-3835 The Sensorites - Kidnap                     21-Dec-86
-------------------------------------------------------------------------
#H3  1-1  0027-**** The Sensorites - A Desperate Venture        21-Nov-87
#H3  2-4  ****-**** Planet of the Giants                        28-Nov-87
#H3  5-10 ****-**** Dalek Invasion Earth                         5-Dec-87
#H3 11-12 ****-**** The Rescue                                  12-Dec-87
#H3 13-15 ****-**** The Romans (parts 1 thru 3)                 19-Dec-87
#H4  1-1  ****-**** The Romans (part 4)                         19-Dec-87
Received: from F29.Tymnet by D35.Tymnet; Tue, 17 Nov 87 14:04:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 17 Nov 87 13:56:23 PST
From: ISGFM.R/KAMINSKI@EMSTXS.Ontyme.Tymnet 
Date: 17 NOV 87 21:31:26 
To: TXS.SUP@EMSTXS.Ontyme.Tymnet 
Message-id: J40902@Ontyme.Tymnet 
Subject: "ADMINISTRATIVE NO: DIS-87-019"... 
Resent-from: Tymcom-X Supervisor <TXSSUP> 
Resent-date: Sat, 21 Nov 87 16:34:37 CST 
Resent-to: JMS, OSMAN, CARL 
Resent-cc: DENCOFF, FLETCHERC 



                                ADMINISTRATIVE          NO:    DIS-87-019
                                    BULLETIN            DATE:  17 NOV 87

         MCDONNELL DOUGLAS DIVERSIFIED INFORMATION SYSTEMS COMPANY



To:                ISG Lists B - E

Subject:           NEW ORGANIZATION FOR MDIPS PRODUCTION SERVICES,
                   ST. LOUIS



Effective immediately, the following organization is in place within
Production Services, St. Louis.

Ron Brown is Manager of IBM Processing Services, with responsibility for
mainframe and tape operations, print operations and distribution,
production job management, storage management, validations and security
management.

Gene Stephens is Manager of Specialized Processing Services, with
responsibility for Tandem, DEC, VAX and KL10 operations, ULTRIX
processing, and other special processing support activities requested by
MDISG business units.

Alice Diehl is Senior Section Manager in charge of St. Louis Processing
Change Management with responsibility for change control, daily planning,
hardware planning, problem management and hardware maintenance management.

Alice, Gene and Ron will report to the undersigned.  Your support of them
in their assignments will be appreciated.





Luke R. Abkemeier, Director
Production Services, St. Louis


CONCURRENCE:





Karen S. Gedera, Director
Information Processing
From: Carl A Baltrunas <Carl> 
Date: Mon, 23 Nov 87 0:06:19 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: On Call 

I am on call Nov 23-29.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Mon, 23 Nov 87 9:11:36 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Mon, 23 Nov 87 9:03:47 PST 
To: CARL@D35 
Cc: WRS@C39.Tymnet 
Subject: "Good to hear you are alive and"... 

Good to hear you are alive and "kicking" - How about lunch (our cafeteria)
next week Wed or Thurs, 12/2 -3 Maybe Bill can join us.......
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Mon, 23 Nov 87 15:05:50 PST 
To: carl 
Subject: TXS-NET---esp. node 10115. 

Node 10115 will remain 'ours' until Julie Wagner receives an Ontyme telling
her to cancel it.  I believe the current cost is about $300 - $350 per month.
I guess this can be your baby, now.

-D.-
Received: from F33.Tymnet by D35.Tymnet; Mon, 30 Nov 87 0:26:40 PST
Return-path: <JMS@F33.Tymnet> 
From: Joe Smith <JMS> 
Date: Mon, 30 Nov 87 0:20:03 PST 
To: Richardson, DanielsR 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC, DenCoff 
Subject: We can't log into system 32 - neighbor's TYM file changed. 

I have been unable to login into system X32 running on the spare KI.
Someone changed the TYM files for the two neighbor nodes on 25-Nov, and as
of 26-Nov-87, nodes 2275 and 2276 have declared node 4525 to be illegal.

Node 2276 reloaded at 330:12:51:09 = 26-Nov-87 at 04:51am PST
Node 2275 reloaded at 330:10:46:14 = 26-Nov-87 at 02:46am PST

334:08:10:03 7FC4  69: NO LINK FOR NEW LINE - LN= 00  NEIG= 04525
334:08:10:03 7FC4  20: LINE SUSPENDED - SEC'S= 0120  LN= 00  NEIG= 04525

(TYMNET)BK2275.TYM			(TYMNET)ND2275.TYM 25-Nov-87 08:52
1) : VERSION 5.21 26-OCT-87 BIS		2) : VERSION: 5.21 16-NOV-87 KLG
1) : ORDER #: CHANGE H/W TO M/S PER EDS	2) : ORDER #: 38448W.EB
1) : LOAD DATE: 26-OCT-87 MAC III	2) : LOAD DATE: 25-NOV-87 MAC III
**************
1) NLINES EQ $A 9			2) NLINES EQ $A 8
**************
1) TIILNK(4525,8,8)			2) TIILNK(2100,8,8)
1) TIILNK(2100,8,8)

(TYMNET)BK2276.TYM			(TYMNET)ND2276.TYM 25-Nov-87 08:53
1) : VERSION 5.21 01-OCT-87 CMK/BIS	2) : VERSION: 5.21 16-NOV-87 KLG
1) : ORDER #: 36900.WEB			2) : ORDER #: 38448W.EB
1) : LOAD DATE: 08-OCT-87 MAC III	2) : LOAD DATE: 25-NOV-87 MAC III
**************
1) NLINES EQ $A 9			2) NLINES EQ $A 8
**************
1) TIILNK(4525,8,8)			2) TIILNK(6415,8,8)
1) TIILNK(6415,8,8)
From: TXSTEXT@D35.Tymnet 
Date: Mon, 30 Nov 87 12:54:48 PST 
To: carl @ x35 
Subject: "I called Peninsula Building Materials, "... 

I called Peninsula Building Materials, and they quoted me prices of $19.50 for
2/3 yd3 of drainage gravel if we pick it up, and $46.50 if they deliver. He
said that 2/3 yd3 of gravel is about 1 ton. I'm leaving now to go over to the
place next to Milpitas Materials, and I'll let you know. Bye...

ILYVMADYFI,E! /Wad
From: Carl A Baltrunas <Carl> 
Date: Mon, 30 Nov 87 15:13:08 PST 
To: Julie Wagner <TYM.J/WAGNER@ONTYME.Tymnet> 
Cc: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Dennis Coffey <dencoff> 
Subject: Node 10115 

As per our telephone conversation, we have no further need for node
number 10115.  The node was previously connected to node 3146 in
Fremont (Liberty street site).  The node was disconnected from TYMNET
on August 28th, 1987.

I don't know if you need our cost code number.  If so,  the code for
Field Service Company - Product Support is 90842.  The old Tymshare
cost code for our group is 4011 (whichever one is on your books).

Thank you for your help.

Carl A Baltrunas			Phone: 408-922-6206
TYMCOM-X Product Support		Mailstop: D2-325
Field Service Company
Received: from X17.Tymnet by D35.Tymnet; Mon, 30 Nov 87 19:25:46 PST
Received: from D35.Tymnet by X17.Tymnet; Thu, 19 Nov 87 21:22:24 PST
Received: from B39.Tymnet by D35.Tymnet; Thu, 19 Nov 87 0:54:57 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Thu, 19 Nov 87 0:49:01 PST 
To: <QSATS.D/ELLENBERG@EMSNTD.Ontyme.Tymnet> 
Cc: TYM.W/BARTLETT@Ontyme.Tymnet, QSATS.D/ELLENBERG@Ontyme.Tymnet,
	QSATS.G/WALKER@Ontyme.Tymnet, Carl A. Baltrunas <Carl@X35.Tymnet> 
Subject: Re: Everything went OK on the first install of NAD 1.6 onto system 54 
In-reply-to: M31875@Ontyme.Tymnet of 18 NOV 87 13:33:58

I can change the name of the file ... to what, Wayne?  On the issue
of adding directory QSATS - that's a change to NAD itself as per
Carl's fix so I'll forward this to him and you can follow it up.
Thanks -Bill
Received: from X17.Tymnet by D35.Tymnet; Mon, 30 Nov 87 19:25:54 PST
Received: from D35.Tymnet by X17.Tymnet; Thu, 19 Nov 87 21:22:34 PST
Received: from B39.Tymnet by D35.Tymnet; Thu, 19 Nov 87 0:55:03 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Thu, 19 Nov 87 0:50:27 PST 
To: Carl A. Baltrunas <Carl@X35.Tymnet> 
Subject: Everything went OK on the first install of NAD 1.6 onto system 54 

(begin forwarded message)
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Wed, 18 Nov 87 13:53:47 PST
Received: from EMSNTD.Ontyme.Tymnet by F29.Tymnet; Wed, 18 Nov 87 13:55:52 PST
Return-path: <QSATS.D/ELLENBERG@EMSNTD.Ontyme.Tymnet> 
From: QSATS.D/ELLENBERG@EMSNTD.Ontyme.Tymnet 
Date: 18 NOV 87 13:33:58 
To: NTD.WRS@EMSNTD.Ontyme.Tymnet 
Cc: TYM.W/BARTLETT@Ontyme.Tymnet, NTD.WRS@Ontyme.Tymnet,
	QSATS.D/ELLENBERG@Ontyme.Tymnet, QSATS.G/WALKER@Ontyme.Tymnet 
Message-id: M31875@Ontyme.Tymnet 
Subject: Everything went OK on the first install of NAD 1.6 onto system 54 

SUBJ: Everything went OK on the first install of NAD 1.6 onto system 54

Bill,

Everything went OK on the first install of NAD 1.6 onto system 54
yesterday.  Of course the .LIS file contains only a * so no restrictions.
Wayne's group will handle that after we get the names.

But, there are 2 requests.  1.  Change the name of the NAD.LIS file
to something cryptic (Wayne to create name).  2. Allow NAD to set read file
for the (QSATS) directory.  This directory contains patches and just 
yesterday has become the OFFICIAL patch directory (new procedures).  So,
we would like NAD to read from Source, Betatest and QSATS directories.

Let me know if problems, we are not in a great hurry but the sooner...

Thanks Bill,
Doug
----------------------------------------------------------------
(end forwarded message)

See previous message.
From: Carl A Baltrunas <Carl> 
Date: Mon, 30 Nov 87 20:16:35 PST 
To: William R Soley <WRS@B39.Tymnet> 
Cc: Wayne D Bartlett <BARTLETW@B39.Tymnet> 
Subject: QSATS stuff 

I just got your forwarded messagee.  Will try to put in the change
this week and let Doug know where the new version is...  will keep
you and Wayne informed.

/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 30 Nov 87 20:50:49 PST 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet> 
Subject: Lunch this week 

I thought that I sent you a phone reply, but maybe not...  Let me know
when you'd like to get together... I'm available for a late lunch on
Thursday, or anytime Tuesday.  Wednesday and Friday I'll be on vacation.

I'm scheduled for vacation Thursday & Friday for the next three weeks
(this week, I've swapped Wednesday for Thursday due to our monitor
meeting being moved to Thursday 10-12. So sometime after that, 12:30 or
1:00pm would be fine)

What kind of schedule do you have this week?

/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 30 Nov 87 21:38:12 PST 
To: William R Soley <WRS@B39.Tymnet>, Wayne D Bartlett <BARTLETW@B39.Tymnet> 
Cc: Dennis Ernst <DErnst@B39.Tymnet>, Doug Ellenberg
	<QSATS.D/ELLENBERG@ONTYME.Tymnet> 
Subject: NAD %1.7 

Bill & Wayne,
  As per Doug's request, I have added directory (QSATS) to the list of valid
directories.  My previous version %1.6 is now (CARL:39)NAD1x6.SAV and the
new version %1.7 is now in (CARL:39)NAD.SAV.

  This version %1.7 does NOT include the changes made by Dennis Ernst to NAD
in his directory (dated 24-Jul-87) which changes the treatment of the "_"
character.  If Dennis wants his change incorporated into my version, I will
add it, but not without his confirmation.  Dennis?

  If my address for Doug is incorrect, please forward this message to him.

  The new version is ready for release/testing.  The only change between the
version now running as 1.6 and this version is the addition of QSATS to the
list of valid directories.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Tue, 1 Dec 87 8:30:11 PST
Return-path: <DERNST@B39.Tymnet> 
From: DERNST@B39.Tymnet 
Date: Tue, 1 Dec 87 8:28:49 PST 
To: CARL@D35 
Subject: NAD 1.7 

CARL,
  THE "_" CHANGES WERE JUST STARTED IN MY V1.7.  THEY ARE NOT OFFICIAL OR
EVEN WELL THOUGHT OUT.   THERE HAVE BEEN ONE OR TWO NEW BUGS REPORTED
AND THEY WILL HAVE TO BE FIXED, BUT WE HAVE HAD THEM FOR 5 YEARS
NOW.  SO THERE DOESN'T SEEM TO BE A RUSH.

DENNIS
Received: from B39.Tymnet by D35.Tymnet; Tue, 1 Dec 87 9:07:07 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Tue, 1 Dec 87 9:05:56 PST 
To: <Carl@D35.Tymnet> 
Subject: Re: Lunch this week 
In-reply-to: your message of Mon, 30 Nov 87 20:50:49 PST

OK - Thurs @ 12:30 - 12/3 - start at my office - By copy to Bill,
am asking him to join us-------THINK SETOP--------
From: Carl A Baltrunas <Carl> 
Date: Tue, 1 Dec 87 11:33:27 PST 
To: Wayne D Bartlett <BARTLETW@B39.Tymnet> 
Subject: Re: Your office... 

I don't believe I've been to your office since the move... we've been
meeting at Bill's.  Are you in C or F ?

/Carl
Received: from F33.Tymnet by D35.Tymnet; Tue, 1 Dec 87 15:22:04 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Tue, 1 Dec 87 15:21:09 PST 
To: douge 
Subject: NAD 1.7 

Doug,
  NAD.SAV is in (CARL:33) and (TECHSERV:33) with RF license set already.

/Carl
Received: from F33.Tymnet by D35.Tymnet; Tue, 1 Dec 87 16:05:09 PST
Return-path: <DOUGE@F33.Tymnet> 
From: DOUGE@F33.Tymnet 
Date: Tue, 1 Dec 87 16:04:21 PST 
To: carl 
Subject: "Thanks, I received your message."... 

Thanks, I received your message.  I will check out the code
and let you know how things go.

Doug.
Received: from B39.Tymnet by D35.Tymnet; Wed, 2 Dec 87 8:45:47 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 2 Dec 87 8:45:23 PST 
To: <Carl@D35.Tymnet> 
Subject: Re: Your office... 
In-reply-to: your message of Tue, 1 Dec 87 11:33:27 PST

Am in c - 3rd floor 530 - southeast side toward hills......
Received: from B39.Tymnet by D35.Tymnet; Wed, 2 Dec 87 8:45:47 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 2 Dec 87 8:45:23 PST 
To: <Carl@D35.Tymnet> 
Subject: Re: Your office... 
In-reply-to: your message of Tue, 1 Dec 87 11:33:27 PST

Am in c - 3rd floor 530 - southeast side toward hills......
Received: from B39.Tymnet by D35.Tymnet; Wed, 2 Dec 87 9:33:45 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 2 Dec 87 9:24:35 PST 
To: CARL@D35, WRS@C39.Tymnet 
Cc: TYMOPS.DJM@ONTYME.TYMNET, qsats.d/ellenberg@ontyme.tymnet 
Subject: "the PASCAL copy requirement is"... 

the PASCAL copy requirement is being forced to a resolution by
Dan Upthegroc
py


DAN UPTHEGROVE..... Need you help ---- 1)what is a good solution for 
the longer term (recall, temp solution - we copy files need for
specific customers, now TRW and Dan's)and for other Pnet customers..
2)Implementation - who, how, when, etc --- note following memos betweenm
Dan and Doug E.   
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Tue, 1 Dec 87 13:27:18 PST
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Dec 87 13:25:23 PST
Return-path: <QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet> 
From: QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet 
Date: 01 DEC 87 12:48:56 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Cc: ISITPR.D/UPTHEGROVE@Ontyme.Tymnet, ISITPR.G/GARDINA@Ontyme.Tymnet,
	QSATS.D/ELLENBERG@Ontyme.Tymnet, QSATS.G/WALKER@Ontyme.Tymnet,
	TYM.W/BARTLETT@Ontyme.Tymnet 
Message-id: M34056@Ontyme.Tymnet 
Subject: PASCAL Code Access 
PASCALCodeAccess: 

                            M E M O R A N D U M

                                                        [] TYMNET - NETWORK
                                                           SYSTEMS SUPPORT
DATE>      01 DEC 87  12:41

TO>        Dan Upthegrove

COPIES>    Wayne Bartlett
           Gary Walker
           Rourke McCusker
           Gary Gardina

FROM>      Doug Ellenberg


SUBJECT>   PASCAL Code Access


-----------------------------------------------------------------------


Dan,

If you send me a list of the systems and code involved I will declare
them readable by all users of the PDP.  I have found the programs that
reset the license of the SOURCE and BETATEST code and can modify them
to insure the code is always readable.

It seems to me the failing here is in the writing of the contract for
Private Networks to gen their own code.  It is obvious the authors of
the contracts are not in tune with established code management procedures
which you have been requesting to modify.  

The changes will be made after I request and receive approval from
Security to make the changes you request.

Doug.
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Tue, 1 Dec 87 16:22:26 PST
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Dec 87 16:09:37 PST
Return-path: <ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet> 
From: ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet 
Date: 01 DEC 87 15:49:20 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Cc: QSATS.D/ELLENBERG@Ontyme.Tymnet, ISITPR.G/GARDINA@Ontyme.Tymnet,
	ISITPR.D/UPTHEGROVE@Ontyme.Tymnet, QSATS.G/WALKER@Ontyme.Tymnet,
	TYM.W/BARTLETT@Ontyme.Tymnet 
Message-id: S29842@Ontyme.Tymnet 
Subject: Reply To: PASCAL Code Access 
FileAccess: 

 
                           M E M O R A N D U M
                           - - - - - - - - - -
                            MCDONNELL DOUGLAS
                       INFORMATION SYSTEMS PTY LTD
                         Network Systems Division
                                Australia
 
      TO:  Doug Ellenberg                      DATE:  02 December 1987
    FROM:  Dan Upthegrove                    ONTYME:  ISITPR.D/UPTHEGROVE
  COPIES:  CC:                                PHONE:  (02)887-9415
 
 SUBJECT:  File Access
 
=========================================================================
 
Attached is a list of all SOURCE/BETATEST command files which reference
files using the COPY command.  All files referenced by these products
must be readable without license.
 
Note also, that many release documentation (.X, .Y, .Z) and parameter
(.T, .C, .A) have also been found to be protected.  These have been copied
from the directories on an as needed basis, but with some inconvenience.
 

 
(SOURCE)NTCN03.C01      
{Page 1}copy~ (source)ntcn03.i01+(source)ntcn03.a01+(source)ntcn03.r01,
   nd9999.z01
 
(SOURCE)NVDM01.C02      
{Page 1}...
copy~ (betatest)nval02.i04+(betatest)nval02.a04+(betatest)nvdm01.r02
 
(SOURCE)TMCS07.C08      
{Page 1}...
copy~ (source)tmcs07.i08+(source)tmcs07.a08+(source)tmcs07.r08,
   (username)nd9999.z01
 
(SOURCE)NCDM01.C00      
{Page 1}copy~ (source)ncdm01.r00,(username)nd9999.z99
 
(SOURCE)TMCS10.C10      
{Page 1}copy~
 
(SOURCE)TMCS10.C20      
{Page 1}copy~
 
(SOURCE)ELF03.C10       
{Page 1}...
copy~ (source)elf03.i10+(source)elf03.a10+(source)elf03.r10,nd9999.z99
 
(SOURCE)ELF04.C00       
{Page 1}...
copy~ (source)elf04.i00+(source)elf04.a00+(source)elf04.r00,nd9999.z99
 
(SOURCE)NVAL02.C05      
{Page 1}...
copy~ (source)nval02.i05+(source)nval02.a05+(source)nval02.r05
 
(SOURCE)TMDM01.C03      
{Page 1}...
copy~ (betatest)tmdm01.i03+(username)nd9999.a99+(betatest)tmdm01.r03
   +(username)nd9999.d99+(betatest)tmdm01.f03,nd9999.zi9
 
(SOURCE)TMDM01.C02      
{Page 1}...
copy~ (source)tmdm01.i02+(username)nd9999.a99+(source)tmdm01.r02
   +(username)nd9999.d99+(source)tmdm01.f02,nd9999.zi9
 
(SOURCE)NVAL02.C02      
{Page 1}...
copy~ (source)nval02.i02+(source)nval02.a02+(source)nval02.r02
 
(SOURCE)TMDM10.C20      
{Page 1}...
copy~ (source)tmdm10.i20+(username)nd9999.a99+(source)tmdm10.r20
   +(username)nd9999.d99+(source)tmdm10.f20,nd9999.zi9
 
(SOURCE)TMDM02.C01      
{Page 1}...
copy~ (source)tmdm02.i01+(username)nd9999.a99+(source)tmdm02.r01
   +(username)nd9999.d99+(source)tmdm02.f01,nd9999.zi9
 
(SOURCE)NMDM01.C03      
{Page 1}copy~ (source)nmdm01.i03+(username)nd9999.A99+(source)nmdm01.r03
 
(BETATEST)NTCN03.C02    
{Page 1}copy~ (betatest)ntcn03.i02+(betatest)ntcn03.a02+(betatest)ntcn03.r02,
   nd9999.z99
 
(BETATEST)NTCN03.C03    
{Page 1}copy~ (betatest)ntcn03.i03+(betatest)ntcn03.a03+(betatest)ntcn03.r03,
   nd9999.z99
 
(BETATEST)NVDM03.C11    
{Page 1}...
copy~ (betatest)nvdm03.i11+(betatest)nval03.a11+(betatest)nvdm03.r11
 
(BETATEST)TMCS10.C22    
{Page 1}copy~
 
(BETATEST)TMCS11.C00    
{Page 1}copy~ (betatest)tmcs11.i00+(betatest)tmcs11.a00+(betatest)tmcs11.r00,
   nd9999.z99
 
(BETATEST)NVAL02.C07    
{Page 1}...
copy~ (betatest)nval02.i07+(betatest)nval02.a07+(betatest)nval02.r07
 
(BETATEST)ELF04.C02     
{Page 1}...
copy~ (betatest)elf04.i02+(betatest)elf04.a02+(betatest)elf04.r02,nd9999.z99
 
(BETATEST)NVAL03.C10    
{Page 1}...
copy~ (betatest)nval03.i10+(betatest)nval03.a10+(betatest)nval03.r10
 
(BETATEST)NVAL03.C11    
{Page 1}...
copy~ (betatest)nval03.i11+(betatest)nval03.a11+(betatest)nval03.r11
 
(BETATEST)TMCS10.C01    
{Page 1}copy~
 
(BETATEST)ELF04.C01     
{Page 1}...
copy~ (betatest)elf04.i01+(betatest)elf04.a01+(betatest)elf04.r01,nd9999.z99
 
(BETATEST)TMDM11.C00    
{Page 1}...
copy~ (betatest)tmdm11.i00+(username)nd9999.a99+(betatest)tmdm11.r00
   +(username)nd9999.d99+(betatest)tmdm11.f00,nd9999.zi9
 
(BETATEST)NVDM03.C10    
{Page 1}...
copy~ (betatest)nvdm03.i10+(betatest)nval03.a10+(betatest)nvdm03.r10
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Tue, 1 Dec 87 16:43:08 PST
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Dec 87 16:38:36 PST
Return-path: <QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet> 
From: QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet 
Date: 01 DEC 87 16:22:53 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Cc: QSATS.D/ELLENBERG@Ontyme.Tymnet, ISITPR.D/UPTHEGROVE@Ontyme.Tymnet,
	ISITPR.G/GARDINA@Ontyme.Tymnet, QSATS.G/WALKER@Ontyme.Tymnet,
	TYM.W/BARTLETT@Ontyme.Tymnet 
Message-id: M34133@Ontyme.Tymnet 
Subject: What systems?? 

Dan,

You will have to have QA track the sporatic changes on the .X and other
files.

What systems are you concerned with?  I will only make the changes 
on the systems you are working on since this is a security issue.

Thanks.
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Tue, 1 Dec 87 17:12:12 PST
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Dec 87 17:10:04 PST
Return-path: <ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet> 
From: ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet 
Date: 01 DEC 87 16:47:08 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Cc: ISITPR.D/UPTHEGROVE@Ontyme.Tymnet, QSATS.D/ELLENBERG@Ontyme.Tymnet,
	ISITPR.G/GARDINA@Ontyme.Tymnet, QSATS.G/WALKER@Ontyme.Tymnet,
	TYM.W/BARTLETT@Ontyme.Tymnet 
Message-id: S29844@Ontyme.Tymnet 
Subject: Reply To: What systems?? 

Doug,

Systems 22 & 37.

Can you inform the first level of management responsible for
QA, STS, NTD and PDP operations?  As an external entity, MDIS
is paying MDNSC for support, and I do not have the time to
attempt to allocate responsibility for NSC products from across
the world.

This does not imply in anyway that I am unappreciative of your
efforts on my behalf, but I plan to make a lot of noise until
the quality of the support for these products shows improvement.

Best regards,

Dan
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Tue, 1 Dec 87 18:45:42 PST
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Dec 87 18:35:01 PST
Return-path: <QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet> 
From: QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet 
Date: 01 DEC 87 18:02:16 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Cc: ISITPR.D/UPTHEGROVE@Ontyme.Tymnet, ISITPR.G/GARDINA@Ontyme.Tymnet,
	TYM.W/BARTLETT@Ontyme.Tymnet, QSATS.G/WALKER@Ontyme.Tymnet,
	QSATS.D/ELLENBERG@Ontyme.Tymnet 
Message-id: M34158@Ontyme.Tymnet 
Subject: I'll do what I can on the specific files you mentioned. 

Dan,

I'd guess Warren Prince would be the best focal point for QA, STS
NTD, and PDP operations.  

You are running into unchartered waters with your requests for procedural
changes.  I hope you relize that by making the changes you request,
ANY user on the PDP's can delete, modify or copy the source
code we declare readable.  I view it not as a support issue but a security 
issue.  

I'll do what I can on the specific files you mentioned.  You will have
to change Company policy to make the changes stick.  You might consider
submitting a PIR for making any changes you feel necessary.  I will follow
it up for you at the product release meetings.

Let me know if you need anything else (small requests only please).

Thanks,
Doug.
----------------------------------------------------------------
Received: from B39.Tymnet by D35.Tymnet; Wed, 2 Dec 87 13:26:24 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 2 Dec 87 13:23:07 PST 
To: WRS@C39.Tymnet, CARL@D35 
Subject: "More re PASCAL, the initial memo"... 

More re PASCAL, the initial memo that resulted in the string I sent
you earlier today, follows....If Bill joins us, we can also discuss
this overall issue.....
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Wed, 2 Dec 87 10:49:13 PST
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Wed, 2 Dec 87 10:46:14 PST
Return-path: <QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet> 
From: QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet 
Date: 02 DEC 87 10:29:54 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Message-id: M34264@Ontyme.Tymnet 
Subject: Here is the first Ontyme 
SOURCE/BETATESTAccessandSecurity: 

 
                           M E M O R A N D U M
                           - - - - - - - - - -
                            MCDONNELL DOUGLAS
                       INFORMATION SYSTEMS PTY LTD
                         Network Systems Division
                                Australia
 
      TO:  Rourke McCusker                     DATE:  1 December 1987
    FROM:  Dan Upthegrove                    ONTYME:  ISITPR.D/UPTHEGROVE
  COPIES:   CC:                               PHONE:  (02)887-9415
 
 SUBJECT:  SOURCE/BETATEST Access and Security
 
=========================================================================
 
Although I have discussed this issue with STS many months ago, it is still
an ongoing problem, and I hope that you can be of some assistance in its
resolution.
 
For security reasons, all actual source code files (.I and .R) have been 
declared to have ALL RD NO protections.  NAD has been set up with 
Read File (RF) license so that private net customers can still generate
code, but cannot read, or copy, the files directly.
 
This is fine in most cases, except for PASCAL codes, which require to
merge the files using COPY, prior to calling the PASCAL compiler programs.
Because these files are also protected, our private network customers are 
unable to access them.
 
This means that the local Communications Consultant must actually undertake
the preparation and genning of these files, no matter how trivial the change.
 
Private Network customers have been trained to generate, modify and maintain 
their networks' code on a day to day basis.  Although MDIS is glad to assist 
the customer with any software problem, day to day code generation is not
covered under our provision of software support.  If we did provide this 
service, the consultants time would be chargeable to the customer.
 
As this extra time and effort is not at customer request, but due to problems 
introduced by NSC, and which, so far, NSC has been disinterested in 
correcting,  MDIS will be recording the time spent in supporting these codes, 
and billing NSC for same.
 
For solving the problem itself, I have some recommendations:
 
        Drop protections on PASCAL source code files.
 
        Modify CPPRO to accept as input a multiple file string, and
        give CPPRO Read File license (similar to what we are doing 
        with NAD).
 
I would appreciate your timely response to the above problem.
----------------------------------------------------------------
Received: from B39.Tymnet by D35.Tymnet; Thu, 3 Dec 87 9:05:13 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Thu, 3 Dec 87 9:04:59 PST 
To: WRS@C39.Tymnet, CARL@D35 
Subject: "Still more on the PASCAL&READ"... 

Still more on the PASCAL&READ FILE story ---
----------------------------------------------------------------
Received: from F29.Tymnet by B39.Tymnet; Wed, 2 Dec 87 17:45:39 PST
Received: from EMSTYM.Ontyme.Tymnet by F29.Tymnet; Wed, 2 Dec 87 17:39:17 PST
Return-path: <ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet> 
From: ISITPR.D/UPTHEGROVE@EMSTYM.Ontyme.Tymnet 
Date: 02 DEC 87 17:15:47 
To: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet 
Cc: QSATS.D/ELLENBERG@Ontyme.Tymnet, ISITPR.G/GARDINA@Ontyme.Tymnet,
	TYM.W/BARTLETT@Ontyme.Tymnet, QSATS.G/WALKER@Ontyme.Tymnet,
	ISITPR.D/UPTHEGROVE@Ontyme.Tymnet 
Message-id: S30002@Ontyme.Tymnet 
Subject: Reply To: I'll do what I can on the specific files you mentioned. 
CodeAccess: 

                              M E M O R A N D U M
                              - - - - - - - - - -
                               MCDONNELL DOUGLAS
                          INFORMATION SYSTEMS PTY LTD
                           Network Systems Division
                                  Australia
 
                                          ONTYME:  ISITPR.D/UPTHEGROVE
                                           PHONE:  (02)887-9415
DATE>      03 DEC 87  09:06

TO>        Doug Ellenberg

COPIES>    CC:

FROM>      Dan Upthegrove


SUBJECT>   Code Access


-----------------------------------------------------------------------


Doug,

The setting of the files to public READ status should not allow
anyone to modify, or delete, these files.  All it will allow as
a security issue is that these files can be read, displayed or
listed.

If this is still a security issue, it should be corrected, but not
at the expense of field personnel and customers.  Either the systems
need to be modified, or the access programs (ND, PAscal compilers,
etc.) need to enforce only the necessary level of security.  With the
PASCAL preprocessor, the output is in fully readable form anyway.

Thanks for getting these files modified.

Best,

Dan
----------------------------------------------------------------
From: Joe Smith <JMS> 
Date: Thu, 3 Dec 87 13:03:10 CST 
To: OPER@F26.Tymnet 
Cc: OSMAN, CARL, UKMKTG@26, dencoff, danielsr@74 
Subject: Re: "HELLO SUPPORT... DENNIS LYNDSEY"... 
In-reply-to: your message of Thu, 3 Dec 87 3:47:07 PST

The message "Bits 18,19,20 disabled cannot swap" should be interpreted as
"disk full or quota exceeded".  User UKMKTG on F26 has a quota of 5000 pages
and is currently using 5030 pages.  The easy way of checking this is to
GFD to that directory and "R QUOLST".
UKMKTG will not be able to created any new files until either
a) some old files are deleted, or
b) the logged in quota is increased and the user logs out and back in again.
/Joe
Received: from B39.Tymnet by D35.Tymnet; Thu, 3 Dec 87 13:45:54 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Thu, 3 Dec 87 13:45:46 PST 
To: CARL@D35 
Subject: "confirming meeting tues, 12/15@11:30, "... 

confirming meeting - tues,12/15@11:30, my office
  Received: from B39.Tymnet by D35.Tymnet; Thu, 3 Dec 87 13:54:01 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Thu, 3 Dec 87 13:46:42 PST 
To: WRS@C39.Tymnet 
Cc: CARL@D35 
Subject: "reminder RRaffo about PASCAL re"... 

reminder -Ask RRaffo about PASCAL - re the copy problem............
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Thu, 3 Dec 87 15:01:01 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Sys 14 & 17. 

Guys:

  I just got a call from Tracy, who's at Nicholson.  The TU45s are down.  He
did not get the time to get them back up.  Probably (possibly) Friday.  He
needs to talk to Osman.  He'll call to Solar.

-D.-


P.S.  Osman:  Tracy said to let you know that he needs the sheet on the
9100.  With that info he said he'll be able to hook it up to the TU45.
Received: from B39.Tymnet by D35.Tymnet; Fri, 4 Dec 87 2:07:22 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Fri, 4 Dec 87 2:06:59 PST 
To: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Cc: CARL@D35 
Subject: Re: "reminder RRaffo about PASCAL re"... 
In-reply-to: your message of Thu, 3 Dec 87 13:46:42 PST

Good news.  Peggy Hall handed me source code listing for the CPP preprocessor
and it is in SAIL!  She does not know where it lives online.  I'll leave that
until next week to try and track down.  Taking tomorrow off.  -Bill
Received: from F33.Tymnet by D35.Tymnet; Fri, 4 Dec 87 14:45:25 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Fri, 4 Dec 87 14:28:19 PST 
To: Monitor Group <CARL@D35>, Osman Guven <Osman@D35.Tymnet>, Joe Smith
	<JMS@D35.Tymnet> 
Cc: Craig Fletcher <fletcherc@D35.Tymnet>, Dennis Coffey <dencoff@D35.Tymnet> 
Subject: XEXEC Monitor solution! 

Joe,
  I've come up with a solution to the problem XEXEC has with the universal
identifier JBTUID which currently restarts at 1 each time the system is
reloaded.  If instead of using a monotonically increasing number, we set
the UID to the universal-date-time, we will be guaranteed of unique UIDs
that will never be reused.  Thus, if a job number and UID match at any time
we know we have the right job.

  Of course, we know the UDT is accurate to 1/3 second, so what do we do
about jobs that would have the same UDT?  Simple... since we keep the last
UID, we now keep the last UDT used for a UID and if the current UDT matches,
we increment it by 1  (1/3 second isn't going to hurt anything).  It's a
small possibility that the UID could get ahead of the UDT but it wouldn't
stay ahead for very long.

  And last, but not least, we can redirect .GTJLT (130) to point to JBTUID
and be able to obtain the login time for a job.

  The change should be in FRMSER in FRMASN where the UDT is incremented and
set for each frame

*** I would like this change to be made in /C09 ***

/carl
Received: from F33.Tymnet by D35.Tymnet; Fri, 4 Dec 87 15:09:28 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Fri, 4 Dec 87 15:03:49 PST 
To: Joe Smith <JMS@D35.Tymnet> 
Subject: Suprise! Suprise!!! 

Hmmmm.... It makes sense, since just assigning a frame number doesn't
guarantee that the job will get logged in... but, there are 2 places in
the monitor that set the UID.

  1) in FRMSER in .FOCFM code after most everything is setup
  2) in SCHED1 {page 40} where it sets up/resets the context pages

For two instructions <AOS T1,SYSUID & MOVEM T1,JBTUID(J)> it's not worth
having this done by a routine, but it should be for what I propose.  I'm
actually waiting for system 32 to come back up so I can make the changes.
Please let me know when you brng it up.

Thanks.  /Carl
Received: from D34.Tymnet by D35.Tymnet; Fri, 4 Dec 87 17:41:00 PST
Return-path: <JMS@D34.Tymnet> 
From: Joe Smith <JMS> 
Date: Fri, 4 Dec 87 19:38:06 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Suprise inspection 

Word has gotten out that Bert Novak will be in San Jose 11-Dec to maake a
site inspection.  We should get our offices and Nicholson ready.  /Joe
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Sat, 5 Dec 87 11:48:44 PST 
To: Carl A Baltrunas <Carl@D35.Tymnet> 
Subject: Re: XEXEC Monitor solution! 
In-reply-to: your message of Fri, 4 Dec 87 14:28:19 PST

Carl,

  Beautiful!  I think your XEXEC Monitor solution is elegant in its
simplicity, directness and effectiveness!  XEXEC is closer to fulfilling it
potential.

-D.-
From: FLETCHERC@D35.Tymnet 
Date: Mon, 7 Dec 87 16:23:51 PST 
To: OSMAN, JMS, CARL 
Subject: "I AM TYPING THIS BLIND ECHO) SO"... 

I AM TYPING THIS BLIND (WITHOUT ECHO) SO PARDON MISTAKES.
THE SURPRISE SITE INSPECTION IS REALLY SECONDARY TO BERT'S VISIT BUT
WE SHOUDL BE PREPARED ANYWAY. THE VIST IS NOW SCHEDULED
FOR FRIDAY DEC 18, NOT DEC 11 BUT NICHOLSON STILL NEEDS TO BE 
CLEANED UP.

SEE YOU THRERE.

		CRAIG
Received: from F74.Tymnet by D35.Tymnet; Tue, 8 Dec 87 15:47:48 PST
Return-path: <JMS@F74.Tymnet> 
From: Joe Smith <JMS> 
Date: Tue, 8 Dec 87 15:43:38 PST 
To: Rick Daniels <OPERA.SUP@EMSTXS.Ontyme> 
Cc: Monitor Group <JMS>, Carl, Osman, FletcherC 
Subject: P035/C10 

There were 2 changes to P034/C09 yesterday.
1) Output correct information on CPU stopcodes, instead of getting a
   2n stopcode in the middle of the first stopcode.
2) Fix problem where TYPBAT and other programs couldn't find DSKB1 but
   found DSKB10 twice.
The second change was not implemented correctly.  It has been fixed and
P035/C10 has been copied to NEWMON on all systems in Fremont.
Please resume loading from NEWMON.    /Joe
From: Dennis Coffey (Tymcom-X Systems) <DenCoff> 
Date: Tue, 8 Dec 87 15:59:07 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: SPOOL Support. 

Guys,

  I'm a little late with this---I probably should have doen this last week.
Who will be the SPOOL maintainer?  I will get with him to give him the easiest
intro to what I've been doing to maintain SPOOL (and how I've been doing
it).  The monthly stuff can wait until near the end of the month, and this
week's stuff required no manual intervention, so I've finished it.

Till later,
-D.-
From: Carl A Baltrunas <Carl> 
Date: Tue, 8 Dec 87 23:18:39 PST 
To: dencoff 
Subject: Username change... 

Dennis,
  In preperation that you might want to re-use DENCOFF and so that we do not
lose any info that you have (for yourself and for us) in your directories,
we will have SRA change username DENCOFF to TXSINFO.  This should not change
the password, and you can continue to use the new name until Ron has your
new username or DENCOFF validated again.

  SRA has recently received a memo from Irvine requesting the cancellation
of a list of usernames, among which was found DENCOFF... apparently someone
doesn't know what your username was used for, because I can't believe that
they have their act together to cancel your username so fast.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Wed, 9 Dec 87 1:59:22 PST
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Wed, 9 Dec 87 1:17:17 PST 
To: Dennis Ernst <DErnst@B39.Tymnet> 
Subject: NAD 1.7 

Dennis,

I have moved all copies of NAD from my directory back into the NAD directory.
Unless I notify you further, (NAD)NAD01.R06 and (NAD)NAD01.R07 are the new
base versions for any changes you wish to make.  NAD01.R06 is based on your
version of NAD01.R06 in directory DERNST:39.  NAD01.R07 contains additional
changes to .R06.  (NAD)NAD.SAV is the to-be-distributed version.  The files
(NAD)NAD1X6.SAV and (NAD)NAD1X5.SAV are the previous versions of NAD.SAV.

Please delete or rename your NAD01.R06 and rename your NAD01.R07 to avoid
confusion in the future.

Thanks again for you help in locating the sources.

/Carl
Received: from D37.Tymnet by D35.Tymnet; Thu, 10 Dec 87 11:30:15 PST
Return-path: <JMS@D37.Tymnet> 
From: Joe Smith <JMS> 
Date: Thu, 10 Dec 87 13:20:50 CST 
To: CARL 
Subject: Problem with (SOURCE)NAD version 1.5 

There are a bunch of PCOM jobs that have been idle for more than 12 hours.
I looked at one of the log files - the job was running (SOURCE)NAD and the
last thing NAD typed was:
	Bit 18,19,20, or 21 read by GETSTS UUO. Can't swap
	Type "CONTINUE" to save new NIB or listing file.
	-
System 37 got a BADPAG typeout - it might have been a hard write error
as opposed to a disk quota exceeded error.
1) While you were mucking aroung in NAD, did you make any of the error messages
   more explicit?  The current message is the pits.
2) We have to worry about programs doing different things when they are batch
   jobs.
Received: from B39.Tymnet by D35.Tymnet; Thu, 10 Dec 87 12:07:55 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Thu, 10 Dec 87 12:03:19 PST 
To: Omar A. Serang <OSerang@B39.Tymnet> 
Subject: Re: (SPL)FICHE 
Resent-from: William R. Soley <WRS@B39.Tymnet> 
Resent-date: Thu, 10 Dec 87 12:08:41 PST 
Resent-to: Carl A. Baltrunas <Carl@35.Tymnet> 
In-reply-to: your message of Thu, 10 Dec 87 11:48:22 PST

Carl Baltrunas is the author of (SPL)FICHE and I'm sure its in SAIL.
I've copied him on this reply so he will send you mail with the location
of the sources.  Then either he or I can copy them to system 39 in
case you're not valid on the system they are on.  Porting to Unix
should not be much work - writting tapes on Unix is much easier as
long as you don't need variable length records (then its hard).  -Bill
From: Joe Smith <JMS> 
Date: Fri, 11 Dec 87 12:12:26 CST 
To: WRS, CARL 
Subject: RDMAIL has bad filespec parser. 

RDMAIL cannot parse "(ATTEND.DEV)MAIL" - it confuses ".DEV" with a file
extension.  That user cannot use the MAIL command to read his mail on
system 38.  TUMS can handle periods in usernames, RDMAIL cannot.
Received: from B39.Tymnet by D35.Tymnet; Fri, 11 Dec 87 13:10:17 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Fri, 11 Dec 87 13:07:04 PST 
To: <JMS@D35.Tymnet> 
Cc: CARL, attend.dev@f38 
Subject: Re: RDMAIL has bad filespec parser. 
In-reply-to: your message of Fri, 11 Dec 87 12:12:26 CST

rdmail uses the sail parser, tums uses one I wrote in FLIB.  I will put
it on the list of things to do to convert rdmail to use flib, until then
anyone having a dot in their username should just use tums to read their
mail or get the dot removed.  At least as many programs don't work as do.
I think getting rid of the dot is the best solution since nobody is about
to fix all the programs.  Originally, of course, dots were illegal.  The
validations group suddenly decided one day they were okay and...  -Bill
From: Carl A Baltrunas <Carl> 
Date: Mon, 14 Dec 87 0:59:40 PST 
To: Joe Smith <JMS> 
Cc: WRS 
Subject: Re: RDMAIL has bad filespec parser. 
In-reply-to: your message of Fri, 11 Dec 87 12:12:26 CST

The problem is in the CVFIL filespec decoder in the SAIL runtimes.  I showed
the problem to Mike and Adele ages ago after Scott went to NTD and it was
tabled by them because of declining language support.  CVFIL uses the same
routine to read usernames as it does file identifiers, only allowing twelve
characters instead of 6.  Changing the code to use a different routine that
accepts "." as well as the other special characters allowed in usernames is
trivial.  Then rebuilding the SAIL runtimes and re-distributing them is the
major "glitch"... Scott or Lois were the last to do this  and I'm not sure
what kind of documentation exists.

Bill, If you'd like us to make the change, we can...  let us know...

/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 14 Dec 87 1:08:54 PST 
To: douge@f33 
Subject: Problem with (SOURCE)NAD version 1.5 

(begin forwarded message)

Received: from D37.Tymnet by D35.Tymnet; Thu, 10 Dec 87 11:30:15 PST
Return-path: <JMS@D37.Tymnet> 
From: Joe Smith <JMS> 
Date: Thu, 10 Dec 87 13:20:50 CST 
To: CARL 
Subject: Problem with (SOURCE)NAD version 1.5 

There are a bunch of PCOM jobs that have been idle for more than 12 hours.
I looked at one of the log files - the job was running (SOURCE)NAD and the
last thing NAD typed was:
	Bit 18,19,20, or 21 read by GETSTS UUO. Can't swap
	Type "CONTINUE" to save new NIB or listing file.
	-
System 37 got a BADPAG typeout - it might have been a hard write error
as opposed to a disk quota exceeded error.
1) While you were mucking aroung in NAD, did you make any of the error messages
   more explicit?  The current message is the pits.
2) We have to worry about programs doing different things when they are batch
   jobs.

(end forwarded message)

Doug,
  After the new monitor is released, we can determine if the job is a
batch job and putting this into NAD will be useful to users ...   it will
require checking all of the error messages printed by NAD and deciding
which should continue and which should abort, but this item should be
brought up by your group to determine whether to do it.  We will NOT do
any work on NAD unless TYMNET asks for it...

Let me know what happens.. I thought you should know that some of the people
that use NAD are experiencing problems that they don't know  what to do about.

/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 14 Dec 87 1:26:56 PST 
To: Mail Wizard <MAIL> 
Subject: TUMS-10 bug report (v45000000 of 23-MAY-87) 


BIll,
  I deleted TUMS.TIX becuse it told me that I had an "?EOT found in message"
and since it determines what messagees are in TUMS.MSGS based on EOTs, it
should generate a new TUMS.TIX with proper indicies.

  I then typed HELP to see if there was a command to mark the messages as
"READ" and didn't see anything.  I typed "MARK *" and "LIST *" to see what
mark did.  ...nothing to see...

  
I then typed VERIFY and all was fine until it reached message 269, then
every message after that printed the statistics followed by 
"?EOT expected at end of message <crlf> ?EOT found in message"
which was followed by "[index corrupt]".

This "shouldn'" happen... right?

(Also, is ther a way to set all the messages as READ without actually
reading them all again... or deleting TUMS.TIX and renaming TUMS.MSG to
MAIL and reading them all in (that causes ?ill inst for too many messages)
... there ought to be a way... )

/Carl
Received: from B39.Tymnet by D35.Tymnet; Mon, 14 Dec 87 1:59:03 PST
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Mon, 14 Dec 87 1:29:56 PST 
To: oserang 
Subject: (SPL)FICHE 

Omar,
  The sources to FICHE are in SAIL and they should be in directory (SPL)
however I need to look around and check what system they are on.  I'm pretty
sure they are on system 32 in TYMNET (our test system) and possibly 14 or 17.

  Let me know if you need them moved to system 39.  I will confirm their
location tomorrow.  Due to hardware work and micro-net problems all of our
hosts are down or out of the network at the moment.

  The code is kind of "so so" and there isn't much that I do.  I count
characters and change tabs into the proper number of spaces and I issue
an extra form feed at the end.  If you do not use the index capability
or the cross-reference capabilities, there isn't much else... maybe some
code to "wrap" long lines and count them as 2 lines instead of one.

  A half hour on the phone, or less telling you what the major algorithm
used for your purposes whould probably be more productive since you ARE
re-writing it in C for UNIX, right?

/Carl
Received: from B39.Tymnet by D35.Tymnet; Mon, 14 Dec 87 11:44:37 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 14 Dec 87 11:44:14 PST 
To: <Carl@D35.Tymnet> 
Cc: Joe Smith <JMS> 
Subject: Re: RDMAIL has bad filespec parser. 
In-reply-to: your message of Mon, 14 Dec 87 0:59:40 PST

I guess I don't care much, all my new code uses FLIB and I can change
RDMAIL to use FLIB quite easily.  I'll put it on the list.  -Bill
Received: from B39.Tymnet by D35.Tymnet; Mon, 14 Dec 87 11:46:30 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 14 Dec 87 11:46:06 PST 
To: <Carl@D35.Tymnet> 
Subject: Re: TUMS-10 bug report (v45000000 of 23-MAY-87) 
In-reply-to: your message of Mon, 14 Dec 87 1:26:56 PST

What version of TUMS?  Make sure you have a new one, I've fixed alot of that
although it can still happen, it recovers much more gracefully.  There is
still no way to mark everything read except the rename kludge.  The
current version is on 39.  -Bill
Received: from B39.Tymnet by D35.Tymnet; Mon, 14 Dec 87 11:46:56 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 14 Dec 87 11:47:20 PST 
To: <Carl@D35.Tymnet> 
Subject: Re: TUMS-10 bug report (v45000000 of 23-MAY-87) 
In-reply-to: your message of Mon, 14 Dec 87 1:26:56 PST

Its TUMS-10 version 45.3 of 07-DEC-87
-Bill
Received: from B39.Tymnet by D35.Tymnet; Mon, 14 Dec 87 13:50:41 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Mon, 14 Dec 87 13:47:08 PST 
To: CARL@D35 
Cc: WRS@C39.Tymnet 
Subject: "LUNCH ARE WE ON FOR TOMMORROW"... 

LUNCH - ARE WE ON FOR TOMMORROW @ 11:30???? IF SO, CALL @ 11:30 TO 
MEET (???AT LOBBY??) OR COME TO MY OFFICE-
BY COPY TO BILL - CAN YOU JOIN US??? ALSO, BILL WHAT ABOUT THE 
2 PM THURS MEETING I HAVE (THE ONE ABORTED THIS AM)???????
CAN YOU ATTEND????(I HOPE)....
Received: from B39.Tymnet by D35.Tymnet; Mon, 14 Dec 87 15:51:50 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Mon, 14 Dec 87 15:51:40 PST 
To: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Cc: CARL@D35 
Subject: Re: "LUNCH ARE WE ON FOR TOMMORROW"... 
In-reply-to: your message of Mon, 14 Dec 87 13:47:08 PST

I don't know about tomorrow lunch.  I have a previous committment but the
time is not bound yet -- it is unlikely to conflict.  What is up for Thursday
at 2:00?  -Bill
Received: from B39.Tymnet by D35.Tymnet; Mon, 14 Dec 87 18:01:16 PST
Return-path: <CARL@B39.Tymnet> 
From: CARL@B39.Tymnet 
Date: Mon, 14 Dec 87 17:20:06 PST 
To: Sandy McFarland <smac@hobbes.Tymnet> 
Subject: TMCS usernames 

Sandy,
  As per our discussion a few weeks ago, I'm sending you mail requesting
TMCS usernames for the members of our PDP-10 Operating systems support
group so that we may provide better support to system 39 in BUBBNET.  The
usernames we use are as follows:

    CARL     Carl Baltrunas, x6206
    JMS      Joe Smith,      x6220
    OSMAN    Osman Guven,    x6236

Please excuse the delay in sending this messae, I've forgotten what mail
address to use to reach you.  I got this address from Bill Soley.


Thank you very much for your help.

/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 14 Dec 87 18:57:35 PST 
To: Jan Krivanec <IPC.J/Krivanec@Ontyme.Tymnet> 
Cc: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: GAN-5 and other usernames 

Jan,
  There are a reasonable number of usernames that currently exist on the
PDP-10s that no one ever logs into.  Is there really any reason for those
usernames to exist in TYMNET?  Is there any reason why a set of usernames
or directories cannot exist only on the PDP-10s?

  The only stipulation being that those usernames cannot be assigned to
users that want to use the PDP-10s.  A user could have the name (DEC) and
be valid to talk to the DECNET gateways 411 and 412, but not be valid on
the PDP-10s.  On the PDP-10s we could have username (DEC) with a designated
PPN that isn't billed against (since it would be an IPC internal name).

  Maybe we should get together to talk about this... since if you and Ed
and Nancy and I can agree on what I'm proposing, it would solve the problem
with duplicate UUNs and reduce the cost incurred by IPC and by us in TYMNET.
(Why should we have billable username sin TYMNET if no one ever logs in?)

/Carl
From: Carl A Baltrunas <Carl> 
Date: Mon, 14 Dec 87 19:09:06 PST 
To: Jan Krivanec <IPC.J/Krivanec@Ontyme.Tymnet> 
Subject: Proposal... 

Let me know if you'd like me to put together a written proposal for the
non-TYMNET usernames.  We may need to get together, or conference call
to discuss a few things first, so I make myself clear in the proposal.

/Carl
Received: from B39.Tymnet by D35.Tymnet; Wed, 16 Dec 87 9:05:55 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 16 Dec 87 8:52:28 PST 
To: <QSATS.D/ELLENBERG@EMSTYM.Ontyme.Tymnet> 
Cc: TYM.W/BARTLETT@EMSTYM.Ontyme.Tymnet, TYM.W/BARTLETT@Ontyme.Tymnet,
	NTD.WRS@Ontyme.Tymnet, QSATS.D/ELLENBERG@Ontyme.Tymnet, CARL@D35,
	nets.b/fultz@ontyme.tymnet 
Subject: Re: "Wait 'till '88!" 
In-reply-to: M36788@Ontyme.Tymnet of 15 DEC 87 11:52:48

I accept your "wait to 88", but have my reservations re the PIR process
for security measures - they are a corporate issue, not a marketing issue.
I have security PIR's in as long as 2 years and no action because no MKTG
priority....As to PASCAL, the idea was (is?) to do the similar thing that we
did with NAD.  As to NAD AND (maybe) PASCAL, non-NTD developers are 
involved, and they have no concern with the PIR process (eg, Carl b. and
IPC - Julian Mein...)anyway...........
From: Joe Smith <JMS> 
Date: Wed, 16 Dec 87 17:19:15 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: Connected at last! 

6657 (X17 base) is connected to ND5416 (XRAY:3732) and ND5561 (XRAY:3734).
6760 (X14 base) is connected to ND5416 and ND5561 also.
Node 2346 has been renamed to NICK (terminals & modems at Nicholson).
Node 10115 has been renamed to FOON (dual base for the Foonlys).
Node FRED (terminal & modems at MDC) is basically unchanged.
Node 2770 now tells the Supervisor that it has hosts 62 (alias for X14),
95 (alias for X17), 118 (alias for X930), and 897 (alias for X934).
TYMNET access to 930 and 934 is via node 6760.
			/Joe
From: Joe Smith <JMS> 
Date: Wed, 16 Dec 87 21:15:57 CST 
To: Monitor Group <JMS>, Carl, Osman 
Cc: FletcherC 
Subject: X17 down with PAR ERR. 

X17 dies with PAR ERR when there is a lot of disk activity, such as doing a
TITO store.  It dies even when it is in CONSOLE mode.  Tracy is looking at
it.   /Joe
From: Joe Smith <JMS> 
Date: Wed, 16 Dec 87 21:52:31 CST 
To: carl, osman 
Subject: X17 all-files not done. 

The RP06's have not been completely backed up.  Someone needs to re-do
tape 12, "STORE ALL STARTING WITH (UPL)".  I did not get a chance to do
the one-pack save of DSKB0: because of X17 dying with PAR ERR.  Carl, I
expect ASP to take a little over 5 tapes to do an ASP dump of a single
RP06.
			/Joe
P.S. I gave OP license to "TRACY" on X14 so he can run NODLOD.  He should
have at least OP license on the other PDP10s as well.
Received: from F29.Tymnet by D35.Tymnet; Fri, 18 Dec 87 12:31:15 PST
Return-path: <DenCoff@F29.Tymnet> 
From: Dennis Coffey <DenCoff> 
Date: Fri, 18 Dec 87 9:53:01 PST 
To: Carl, Osman, Joe <JMS> 
Cc: Craig <FletcherC> 
Subject: Mail to me, via DenCoff. 

My old username is on a few of the public network PDP-10s.  The hosts with
DENCOFF are 25, 29, 33, 34 & 54.  My home host is B39, for general use as well
as for TUMS.

-D.-
From: Carl A Baltrunas <Carl> 
Date: Mon, 21 Dec 87 3:24:18 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc> 
Subject: Standby 

I am on standby for the next two weeks 21-Dec-87 thru 3-Jan-88.

/Carl
From: TXSTEXT@D35.Tymnet 
Date: Mon, 21 Dec 87 12:38:37 PST 
To: carl 
Subject: "Hi! It's just me...now I've forgotten"... 


Hi!

It's just me...now I've forgotten what I had wanted to ask you...so, in the
meantime, could you bring home some small paper clips? I don't care for the plastic ones...also, are you planning on going shopping with me tonight? And, last
but not least, are you planning on helping me find my documentation for my 
student loan problem?...and maybe you can help me straighten out the mess I
made of our banking statements? I know this is asking alot, but I'd like to
get as much of this stuff out of the way as possible before the New Year, so
wer can "start fresh". Okay? I love you.

P.S....Oh! and the tax return, too? Please? ILYVMADYFI,E! /Wad
Received: from B39.Tymnet by D35.Tymnet; Wed, 23 Dec 87 9:21:23 PST
Return-path: <BARTLETW@C39.Tymnet> 
From: Wayne D. Bartlett <BARTLETW@C39.Tymnet> 
Date: Wed, 23 Dec 87 9:13:47 PST 
To: WRS@C39.Tymnet, CARL@D35, TYMOPS.DJM@ONTYME.TYMNET 
Subject: "HAPPY HOLIDAYS ITS BEEN A GOOD"... 

HAPPY HOLIDAYS - ITS BEEN A GOOD YEAR - BUT LOOK TO AN EVEN BETTER ONE
IN 88 -- AND - CARL - THINK SETOP!!!!!!
Received: from B39.Tymnet by D35.Tymnet; Wed, 23 Dec 87 10:46:05 PST
Received: from tymix.Tymnet by B39.Tymnet; Wed, 23 Dec 87 10:41:40 PST
Received: by tymix.Tymnet (5.51/4.7) id AA00732; Wed, 23 Dec 87 10:45:08 PST
Received: by birdix.Tymnet.com (3.2/SMI-3.2) id AA00833; Tue, 22 Dec 87
	13:28:24 PST
Return-path: <birdix!wrs@tymix.Tymnet> 
From: birdix!wrs (Bill Soley) 
Date: Tue, 22 Dec 87 13:28:24 PST 
To: b39!carl, b39!jms 
Message-id: <8712222128.AA00833@birdix.Tymnet.com> 
Subject: PEAK sources 

Can you point me at the current PEAK sources?  I'd like to teach it about
the SUN escape sequences.   Thanks -Bill
From: Carl A Baltrunas <Carl> 
Date: Wed, 23 Dec 87 13:42:46 PST 
To: William R Soley <WRS@B39.Tymnet> 
Subject: Re: PEAK sources 
In-reply-to: <8712222128.AA00833@birdix.Tymnet.com> of Tue, 22 Dec 87 13:28:24
	PST

I'm interested in knowing if TUMS handles these addresses correctly...

Bill,  the current sources to PEAK are in (MYPEAK:32).  The module you need
to look at is REDISP.SAI.

If you want, just send me a copy of the escape sequences and I'll make the
changes, since I am more familiar with what it expects to do with them.  If
you have them XEROX-able, I can stop by your office and get a copy, or you
can mail it to me inter-office to mailstop D21, cube D2-325.

/Carl

PS.  Merry Christmas to you and Becky and William Christian
     I hope you're taking some time to be home (and not working) for
     the holidays.
Received: from B39.Tymnet by D35.Tymnet; Wed, 23 Dec 87 16:28:10 PST
Return-path: <WRS@B39.Tymnet> 
From: William R. Soley <WRS@B39.Tymnet> 
Date: Wed, 23 Dec 87 16:19:47 PST 
To: <Carl@D35.Tymnet> 
Subject: Re: PEAK sources 
In-reply-to: your message of Wed, 23 Dec 87 13:42:46 PST

Thanks - I'll take a look at the source and see if its too cryptic and maybe
defer to you.  Otherwise I'll just put it on 39 to start with.  The only non-
trivial thing is the way insert works.  It takes a count of the number of
spaces to insert and then you write over the spaces.  This is much more
efficient than the way Hp does it.  I'll probably be spending the holidays
playing with my son and my Sun.  That's not a great loss, though, since we
don't celebrate Christmas or New Year they are just convenient long weekends.
I presume you do, though, so I hope you enjoy whatever you have planned.
-Bill
From: Carl A Baltrunas <Carl> 
Date: Wed, 23 Dec 87 18:41:10 PST 
To: William R Soley <WRS@B39.Tymnet> 
Subject: re: PEAK, REDISP 

The REDISP module does the entire redisplay algorithm.  There are a few
tables (setup by macros) which define terminal types.  The rest is pretty
much done with case statements with each type of terminal's escape seq's
banded together.  The functions that it relies on are pretty basic, so
you may not even need to worry much over character insert/delete unless
either function doesn't exist.  There should be a flag (or some thing) to
declare whether or not to use insert-delet-line and one for insert-delete-char.

The algorithm used to do one character at a time... I changed one versin to
delete as many as known at a time, but I don't remember whether it was PEAK
or VUE that I made the changes to.

Please send me a copy of the escape sequences... so I can add them to my tables
to be put into my next version of VUE if there ever is a next version.

/Carl
From: Carl A Baltrunas <Carl> 
Date: Wed, 23 Dec 87 18:47:20 PST 
To: William R Soley <WRS@B39.Tymnet> 
Subject: TUMS versions 

Please install the newest version of TUMS on system 35... I think it is running
a version that doesn't have the bugs fixed that I sent you mail about earlier
this month.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Wed, 30 Dec 87 15:24:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 30 Dec 87 15:08:10 PST
Return-path: <ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet> 
From: ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet 
Date: 30 DEC 87 14:12:05 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet 
Message-id: I29949@Ontyme.Tymnet 
Subject: re-send 

Carl, per our conversation on 87-12-30, below is press release.  Ken BeDell

                          M E M O R A N D U M
 
 
 
                                          T Y M N E T
DATE>      22 DEC 87  14:58               Network Services & Marketing Support

TO>        ALLSALES

COPIES>    Ron Bamberg
           Neil Sullivan
           Judie Sassali
           Lori Waggener

FROM>      Don Parkman


SUBJECT>   NIS-TYMNET Press Release


-----------------------------------------------------------------------



The following press release was sent out this morning.


 
 
 
 
 
 
                                           For Immediate Release
 
 
 
       DIRECT VAN SERVICE BETWEEN JAPAN AND U.S. BEGINS
 
 
    SAN JOSE, California, December 21, 1987 --  Tymnet, McDonnell
 
Douglas Network Systems Company, announced here today that its
 
Japanese affiliate, Network Information Service, Ltd. (NIS), a
 
provider of packet-switched network services, has linked its
                                                                Page  2

 
network with the TYMNET(R) data communications network in the
 
first direct connection between a Japanese VAN and one in the
 
U.S.
 
    The linking comes about as a direct result of an agreement
 
between NIS and the Japanese Ministry of Post and
 
Telecommunications that allows communication between the two
 
companies without having to go through International Record
 
Carriers (IRCs).  It is part of a recent deregulation of the
 
Japanese telecommunications market.
 
    Tymnet, along with Marubeni Corporation, a leading Japanese
 
general trading company, owns a controlling interest in NIS, and
 
will now be able to offer its U.S.- based customers the full
 
range of Tymnet data communications products and services for
 
locations in Japan.  Until the agreement, many services were
 
unavailable in Japan.  Conversely, Japanese NIS customers will
 
also now be able to take advantage of the full range of Tymnet
 
protocol conversion, error-protection, low-cost local access and
 
other value-added features when communicating with offices in the
 
U.S.  Additionally, the agreement will significantly reduce the
 
costs of communications between the two countries.
 
 
    In an inaugural ceremony in Tokyo on Friday, Japan's Minister
 
of Post and Telecommunications, Mr. Nakayama, was present to
 
signal his government's approval of the agreement.  In addition,
 
congratulatory letters from high ranking officials in the
 
Department of Commerce and the State Department were displayed
 
via Tymnet's OnTyme(R) Electronic Mail System.  The letters
 
hailed the agreement as an important step in the development of
 
liberalized regulations governing international tele- and data
 
                                                                Page  3

communications.
 
 
    The NIS network was one of Japan's first, with service
 
commencing in 1985 after deregulation of Japan's domestic
 
telecommunications market.  Since then, several other
 
packet-switched networks have emerged.  Until the end of last
 
month, these networks were strictly internal to Japan, with
 
international traffic having to go through gateways supplied by
 
the IRCs.
 
    The agreement is significant for a number of reasons.  Not
 
only does the full Tymnet product line become available for use
 
between the two countries, but billing and initiation of service
 
are improved.  With the agreement in place, companies can now
 
sign up for network services from either Japan or the U.S.  They
 
can also be billed in whichever location they choose.
 
    "We are very excited about this agreement," said Ron Bamberg,
 
Vice President of Business Development and Planning for Tymnet.
 
"It not only solidifies our position as the leader in
 
international data communications, but paves the way for future
 
agreements with other countries in Europe, Asia, and South
 
America."
 
     Tymnet, McDonnell Douglas Network Systems Company, owns and
 
operates TYMNET(R), the world's most ubiquitous public data
 
communications network.  In addition, they are a leading supplier
 
of private data networks.  Tymnet is a part of the McDonnell
 
Douglas Information Systems Group, with 1986 revenues in excess
 
of $1.1 billion.
 
 
 
                              # # #
 
 
                                                                Page  4

 
 
 
 
 
 
             For photos and other information, please contact:
 
 
                              Lori Waggener:  (408) 922-7602
 
                                             or
 
                              Don Parkman:    (408) 922-7583
    ?3{B