Received: from B39.Tymnet by D35.Tymnet; Sat, 24 Dec 88 20:21:16 PST
Received: from tymix.Tymnet by B39.Tymnet; Sat, 24 Dec 88 21:22:58 PST
Received: by tymix.Tymnet (5.51/4.7) id AA20809; Sat, 24 Dec 88 20:10:08 PST
Received: by antares.Tymnet.com (3.2/SMI-3.2) id AA03425; Sat, 24 Dec 88
	04:48:10 PST
Return-path: <cbaltru@antares> 
From: cbaltru@antares (carl baltrunas) 
Date: Sat, 24 Dec 88 04:48:10 PST 
To: carl@d35 
Message-id: <8812241248.AA03425@antares.Tymnet.com> 
Subject: Avengers 

Path: antares!tymix!oliveb!ames!eos!labrea!decwrl!sun!pitstop!sundc!netxcom!hadron!klr
From: klr@hadron.UUCP (Kurt L. Reisler)
Newsgroups: rec.arts.drwho,rec.arts.tv
Subject: Re: The Avengers (Long response)
Message-ID: <818@hadron.UUCP>
Date: 21 Dec 88 03:42:57 GMT
References: <3098@dalcs.UUCP> <3107@dalcs.UUCP> <4299@cs.utexas.edu> <3120@dalcs.UUCP> <330@inuxa.UUCP>
Reply-To: klr@hadron.UUCP (Kurt L. Reisler)
Organization: Hadron, Inc., Fairfax, VA
Lines: 347
Xref: antares rec.arts.drwho:1870 rec.arts.tv:1721

In article <330@inuxa.UUCP> rjs@inuxa.UUCP (Robert Snyder) writes:
>
>>In article <3107@dalcs.UUCP>, lane@dalcs.UUCP (John Wright) writes:
>>
>>       [...stuff deleted...]
>> 
>> Does anyone have an episode guide or other information about the Avengers
>> that they could send me.  I'm particularly interested in connections between 
>> this show and Dr. Who but, as well, I do have very fond memories of the show.
>> Is it in sindication anywhere?  Is it something the BBC would have to market
>> through Lionheart and have they ever tried?  Is it something we might bug a
>> PBS to get?  I'd love to see it again.
>> 
>>      [...stuff deleted...]
>> -- 
>> John Wright      /////////////////     Phone:  902-424-3805  or  902-424-6527
>One of the U.S. networks (CBS, I think) showed all the Avengers episodes
>around 1979 as part of their late night programming, i.e., after the late
>news. (I remember is as being network-wide, although it may just have been
>the local affiliate.) They went through both The Avengers and The New
>Avengers, showing them five nights a week. The show has also been on one of
>the independent stations in Indianapolis, so you might have better luck
>talking to the independents rather than PBS.

A while ago, I compiled a list of Avengers episodes, from several
reference books.  So, here it is.  I have all the Macnee/Riggs episodes
on tape, as well as most of the Macnee/Thorson episodes.  I have seen,
but not taped the New Avengers Episodes (Joanna Lumly, yummy!).  I have
NEVER seen any of the episodes in the first 3 seasons.  Does ANYONE have
any of these on tape?


                             The First Season

                           Hendry/Macnee (1961)

                                Ian Hendry
                              Patrick Macnee

   Episode               Title                Production   Transmission
                                              Completed        Date

      1      Hot Snow
      2      Brought to Book
      3      Square Root of Evil
      4      Nightmare
      5      Cresent Moon
      6      Girl on the Trapeze
      7      Diamond Cut
      8      The Radioactive Man
      9      Ashes of Roses
     10      Hunt the Man Down
     11      Please Don't Feed the Animals
     12      Dance With Death
     13      One for the Mortuary
     14      The Springers
     15      The Frighteners
     16      The Yellow Needle
     17      Death on the Slipway
     18      Double Danger
     19      Toy Trap
     20      The Tunnel of Fear
     21      The Far Distant Dead
     22      Kill the King
     23      Dead of Winter
             (The Case of the Happy Camper)
     24      The Deadly Air
     25      A Change of Bait
     26      Dragonsfield





                             The Second Season

                      Macnee/Blackman Series 1 (1962)

                              Patrick Macnee
                              Honor Blackman

     Episode             Title              Production   Transmission
                                            Completed        Date

        1      Dead on Course                  5/9/62      12/29/62
        2      Mission to Montreal            5/12/62      10/27/62
        3      The Sell Out                    6/9/62      11/24/62
        4      Death Dispatch                 6/23/62      12/22/62
        5      Warlock                         7/7/62       1/26/63
        6      Propellant 23                  7/21/62       10/6/62
        7      Mr. Teddy Bear                  8/4/62       9/29/62
        8      The Decapod                    8/12/62      10/13/62
        9      Bullseye                       9/20/62      10/20/62
       10      The Removal Men                10/4/62       11/3/62
       11      The Mauritius Penny           10/18/62      11/10/62
       12      Death of a Great Dane          11/1/62      11/17/62
       13      Death on the Rocks            11/15/62       12/1/62
       14      Traitor in Zebra              11/29/62       12/8/62
       15      The Big Thinker               12/13/62      12/15/62
       16      Intercrime                    12/29/62        1/5/63
       17      Immortal Clay                  1/10/63       1/12/63
       18      Box of Tricks                  1/17/63       1/19/63
       19      The Golden Eggs                1/31/63        2/2/63
       20      School for Traitors             2/9/63        2/9/63
       21      The White Dwarf                2/16/63       2/16/63
       22      Man in the Mirror              2/22/63       2/23/63
       23      A Conspiracy of Silence         3/1/63        3/2/63
       24      A Chorus of Frogs               3/8/63        3/9/63
       25      Six Hands across the Table     3/15/63       3/16/63
       26      Killerwhale                    3/22/63       3/23/63





                             The Third Season

                    Macnee/Blackman Series 2 (1963-64)

                              Patrick Macnee
                              Honor Blackman

     Episode             Title              Production   Transmission
                                            Completed        Date

        1      Concerto                       4/26/63        3/2/64
        2      Brief for Murder                5/1/63       9/28/63
        3      The Nutshell                   5/10/63      10/19/63
        4      The Golden Fleece              5/24/63       12/7/63
        5      Death a`la Carte               6/14/63      12/21/63
        6      Man with Two Shadows           6/21/63      10/12/63
        7      Don't Look Behind You           7/5/63      12/14/63
        8      The Grandeur That Was Rome     7/19/63      11/30/63
        9      The Undertakers                 8/2/63       10/5/63
       10      Death of a Batman              8/14/63      10/26/63
       11      Build a Better Mousetrap       8/28/63      10/26/63
       12      November Five                  9/27/63       11/2/63
       13      Second Sight                  10/11/63      11/16/63
       14      The Secret's Broker           10/19/63        2/1/64
       15      The Gilded Cage               10/25/63       11/9/63
       16      The Medicine Man               11/8/63      11/23/63
       17      The White Elephant            11/22/63        1/4/64
       18      Dressed to Kill                12/6/63      12/28/63
       19      The Wringer                   12/20/63       1/18/64
       20      The Little Wonders              1/3/64       1/11/64
       21      Mandrake                       1/16/64       1/25/64
       22      The Trojan Horse               1/30/64        4/8/64
       23      The Outside-In Man             2/12/64       2/22/64
       24      The Charmers                   2/27/64       2/29/64
       25      Esprit de Corps                3/11/64       3/14/64
       26      Lobster Quadrille              3/20/64       3/21/64





                             The Fourth Season

                  Macnee/Rigg Monochrome Series (1965-66)

                              Patrick Macnee
                                Diana Rigg

    Episode              Title               Production   Transmission
                                             Completed        Date

       1      The Town of No Return          Not Known       10/2/65
       2      The Murder Market                 n/k         11/13/65
       3      The Gravediggers                  n/k          10/9/65
       4      The Cybernauts                    n/k         10/16/65
       5      Death at Bargain Prices           n/k         10/23/65
       6      Castle De'Ath                     n/k         10/30/65
       7      The Master Minds                  n/k          11/6/65
       8      A Surfeit of H2O                  n/k         11/20/65
       9      The Hour that Never Was           n/k          1/27/65
      10      Dial a Deadly Number              n/k          12/4/65
      11      The Maneater of Surrey Green      n/k         12/11/65
      12      Two's a Crowd                     n/k         12/18/65
      13      Too Many Christmas Trees          n/k          1/25/65
      14      Silent Dust                       n/k           1/1/66
      15      Small Game for Big Hunters        n/k          1/15/66
      16      Room Without a View               n/k           1/8/66
      17      The 13th Hole                     n/k          1/29/66
      18      The Girl From Auntie              n/k          1/21/66
      19      The Quick, Quick Slow Death       n/k           2/5/66
      20      The Danger Makers                 n/k          2/12/66
      21      A Touch of Brimstone              n/k          2/19/66
      22      What the Butler Saw               n/k          2/26/66
      23      A Sense of History                n/k          3/12/66
      24      The House that Jack Built         n/k           3/5/66
      25      How to Succeed at Murder
              Without Really Trying             n/k          3/16/66
      26      Honey for the Prince              n/k          3/23/66





                             The Fifth Season

                   Macnee/Rigg Colour Series 1 (1967-68)

                              Patrick Macnee
                                Diana Rigg

   Episode               Title                Production   Transmission
                                              Completed        Date

      1      The Fear Merchants               Not Known       1/21/67
      2      Escape in Time                      n/k          1/28/67
      3      The Bird Who Knew Too Much          n/k          2/11/67
      4      From Venus With Love                n/k          1/14/67
      5      The See-Through Man                 n/k           2/4/67
      6      The Winged Avenger                  n/k          2/18/67
      7      The Living Dead                     n/k          2/25/67
      8      The Hidden Tiger                    n/k           3/4/67
      9      The Correct Way to Kill             n/k          3/11/67
     10      Never, Never Say Die              2/14/67        3/18/67
     11      Epic                              2/27/67         4/1/67
     12      The Superlative Seven             3/13/67         4/1/67
     13      A Funny Thing Happened
             on the Way to the Station         3/22/67        4/15/67
     14      Something Nasty in the Nursery     4/2/67        4/22/67
     15      The Joker                         4/11/67        4/29/67
     16      Who's Who?                        4/18/67         5/6/67
     17      Death's Door                       6/7/67        10/7/67
     18      Return of the Cybernauts          6/15/67        9/30/67
     19      Dead Man's Treasure                7/5/67       10/21/67
     20      The $50,000 Breakfast             7/20/67       10/14/67
     21      You Have Just Been Murdered        8/2/67       10/28/67
     22      The Positive Negative Man         8/31/67        11/4/67
     23      Murdersville                      8/25/67       11/11/67
     24      Mission Highly Improbable         9/22/67       11/18/67
     25      The Forget-Me-Knot *              1/19/68        1/12/69


     * This episode is included in both  lists  for  completeness
     and  though  it actually appears on the production company's
     records as the final Rigg story, it is,  of  course,  widely
     considered to be the first Thorson story.  In fact, this ep-
     isode was filmed between December  1967  and  January  1968,
     while the crossover scene between Emma and Tara was actually
     filmed on 19 January 1968.





                          The Sixth Season

                Macnee/Thorson Colour Series 2 (1969)

                           Patrick Macnee
                            Linda Thorson

   Episode            Title             Production   Transmission
                                        Completed        Date

      1      Invasion of the Earthmen    11/21/67       4/27/69
      2      The Curious Case of
             the Countless Clues          1/19/68       5/18/69
      3      The Forget-Me-Knot           1/19/68       1/12/69
      4      Split                         2/1/68        2/9/69
      5      Getaway                      2/15/68       7/27/69
      6      Have Guns Will Haggle        2/29/68       3/20/69
      7      Look, Stop Me If You've
             Heard This One Before
             (But There Were These..)     3/19/68       3/23/69
      8      My Wildest Dream              4/1/68        9/7/69
      9      Whoever Shot Poor George
             Oblique Stroke XR40          4/17/68       2/16/69
     10      You'll Catch Your Death      5/24/68        2/2/69
     11      All Done With Mirrors        5/24/68        3/2/69
     12      The Super Secret
             Cypher Snatch                6/14/68       1/26/69
     13      Game                         6/25/68       1/19/69
     14      False Witness                7/11/68       2/23/69
     15      Noon Doomsday                7/30/68       3/16/69
     16      Legacy of Death               8/9/68        3/9/69
     17      They Keep Killing Steed      8/29/68        4/6/69
     18      Wish You Were Here           9/12/68       5/25/69
     19      Killer                       9/27/68        5/4/69
     20      The Rotters                  10/8/68       4/20/69
     21      The Interrogators           10/22/68       4/13/69
     22      The Morning After            11/5/68       5/11/69
     23      Love All                    11/18/68       7/13/69
     24      Take Me To Your Leader      11/29/68       6/15/69
     25      Stay Tuned                  12/13/68        6/8/69
     26      Fog                         12/31/68       6/23/69
     27      Who Was That Man
             I Saw You With?              1/10/69       8/31/69
     28      Pandora                      1/17/69       8/10/69
     29      Thingumajig                  1/21/69        8/1/69
     30      Homicide and Old Lace        1/23/69        6/7/69
     31      Requiem                      2/13/69       8/17/69
     32      Take Over                    2/21/69       8/24/69
     33      Bizarre                       3/3/69       9/14/69





                             The New Avengers (1976)

                                  Patrick Macnee
                                   Gareth Hunt
                                  Joanna Lumley

     Episode                 Title                 Production   Transmission
                                                   Completed        Date

        1      The Eagle's Nest
        2      House of Cards
        3      The Last of the Cybernauts...?
        4      The Midas Touch
        5      Cat Amongst the Pigeons
        6      Target
        7      To Catch a Rat
        8      The Tale of the Big Why
        9      Faces
       10      Sleeper
       11      The Three-Handed Game
       12      Dirtier by the Dozen
       13      Gnaws
       14      Dead Men are Dangerous
       15      Angles of Death
       16      Medium Rare
       17      The Lion and the Unicorn
       18      Obsession
       19      Trap
       20      Hostage
       21      K is for Kill
               (Part 1: "The Tiger Awakes")
       22      K is for Kill
               (Part 2: "The Tiger by the Tail")
       23      Complex
       24      The Gladiators
       25      Emily
       26      Forward Base

Kurt Reisler (703) 359-6100
============================================================================
UNISIG Chairman, DECUS US Chapter                       | Hadron, Inc.
..{uunet|sundc|rlgvax|netxcom|decuac}!hadron!klr        | 9990 Lee Highway
Sysop, Fido 109/74  The Bear's Den   (703) 671-0598     | Suite 481
Sysop, Fido 109/483 The Pot of Gold  (703) 359-6549     | Fairfax, VA 22030
============================================================================
    