Received: from B39.Tymnet by D35.Tymnet; Mon, 19 Dec 88 10:32:53 PST
Received: from tymix.Tymnet by B39.Tymnet; Mon, 19 Dec 88 10:32:53 PST
Received: by tymix.Tymnet (5.51/4.7) id AA11188; Mon, 19 Dec 88 10:31:42 PST
Received: by antares.Tymnet.com (3.2/SMI-3.2) id AA20055; Mon, 19 Dec 88
	01:27:19 PST
Return-path: <cbaltru@antares> 
From: cbaltru@antares (carl baltrunas) 
Date: Mon, 19 Dec 88 01:27:19 PST 
To: carl@d35 
Message-id: <8812190927.AA20055@antares.Tymnet.com> 
Subject: Beatles 

Path: antares!tymix!oliveb!ames!ucsd!rutgers!rochester!pt.cs.cmu.edu!cadre!pitt!cisunx!ammoeh
From: ammoeh@cisunx.UUCP (Andrew M Meister)
Newsgroups: rec.music.beatles
Subject: Re: Excellent Beatle history reading.....
Keywords: real story
Message-ID: <14549@cisunx.UUCP>
Date: 17 Dec 88 03:34:47 GMT
References: <902@nvuxr.UUCP>
Reply-To: ammoeh@unix.cis.pittsburgh.edu (Andrew M Meister)
Organization: Univ. of Pittsburgh, Comp & Info Sys
Lines: 19

In article <902@nvuxr.UUCP> lji@nvuxr.UUCP (L.IACONA) writes:
>
>	Wanna read some Beatle history without the superficial
>	fluff and hype?   -  get "the Love You Make" by 
>	Peter Brown and (I think) Steven Gaines. 
>	It goes thru the complete story, from a struggling 
>	"bum" band to their breakthru in America to their end as a group.
>	The real story is told tastefully, without bashing anyone.
>				
>					Louie

Are you a rookie Beatles fan?? This book is bugus. It's full of
misconception and blunders. Try "Shout". This book will give you  
an accurate scoop.

                        Andrew
B4E 

B4E E
Received: from B39.Tymnet by D35.Tymnet; Mon, 19 Dec 88 10:33:43 PST
Received: from tymix.Tymnet by B39.Tymnet; Mon, 19 Dec 88 10:33:41 PST
Received: by tymix.Tymnet (5.51/4.7) id AA11203; Mon, 19 Dec 88 10:32:25 PST
Received: by antares.Tymnet.com (3.2/SMI-3.2) id AA19946; Mon, 19 Dec 88
	00:43:49 PST
Return-path: <cbaltru@antares> 
From: cbaltru@antares (carl baltrunas) 
Date: Mon, 19 Dec 88 00:43:49 PST 
To: carl@d35 
Message-id: <8812190843.AA19946@antares.Tymnet.com> 
Subject: Beatles 

Path: antares!tymix!oliveb!ames!mailrus!ukma!rutgers!att!ihlpa!rjp1
From: rjp1@ihlpa.ATT.COM
Newsgroups: rec.music.beatles
Subject: Re: New Releases
Message-ID: <10910@ihlpa.ATT.COM>
Date: 15 Dec 88 19:10:16 GMT
References: <2228@iscuva.ISCS.COM>
Lines: 29

In article <2228@iscuva.ISCS.COM>, jimk@iscuva.ISCS.COM (Jim Kendall) writes:
> 
> The latest scoop on new Beatleg releases:
> 
> CDs
> 
> 1) Ultra Rare Trax Vol. 1 & 2 have been released on a single CD entitled
> `Back Trax'.  Reportedly selling for ~$30.

From what I have seen, the above will also include two new tracks!
Namely, Do You Want To Know A Secret and Aerial, which is a previously
unreleased instrumental.  Haven't heard em though myself..

> LPs
> 
> 2) Lost Lennon Tapes Vol. 9 & 10 (Reportedly selling for ~$12.)

Yep.  Ordered mine a couple of daze ago from a friend of a friend.
I wonder if the LLT will ever appear on CD?  Well, in any event,
once we get our hands on that new CD player that allows you to record
your own CDs from albums or whatever, well, you can guess the rest! 
Yeah, Radio Shack has been keeping it under wraps (or under further
development) for a while now.  I don't have any more details though.. 


> Jim Kendall

--									    --
rj pietkivitch							att!ihlpa!rjp1
Received: from B39.Tymnet by D35.Tymnet; Mon, 19 Dec 88 11:43:25 PST
Received: from tymix.Tymnet by B39.Tymnet; Mon, 19 Dec 88 11:43:37 PST
Received: by tymix.Tymnet (5.51/4.7) id AA11159; Mon, 19 Dec 88 10:30:19 PST
Received: by antares.Tymnet.com (3.2/SMI-3.2) id AA20021; Mon, 19 Dec 88
	01:17:58 PST
Return-path: <cbaltru@antares> 
From: cbaltru@antares (carl baltrunas) 
Date: Mon, 19 Dec 88 01:17:58 PST 
To: carl@d35 
Message-id: <8812190917.AA20021@antares.Tymnet.com> 
Subject: Beatles 

Path: antares!tymix!oliveb!pyramid!decwrl!sun!pitstop!sundc!seismo!uunet!edsews!rphroy!teemc!mibte!gamma!pyuxp!nvuxj!nvuxr!lji
From: lji@nvuxr.UUCP (L.IACONA)
Newsgroups: rec.music.beatles
Subject: Excellent Beatle history reading.....
Keywords: real story
Message-ID: <902@nvuxr.UUCP>
Date: 15 Dec 88 14:32:20 GMT
Organization: Bell Communications Research
Lines: 9


	Wanna read some Beatle history without the superficial
	fluff and hype?   -  get "the Love You Make" by 
	Peter Brown and (I think) Steven Gaines. 
	It goes thru the complete story, from a struggling 
	"bum" band to their breakthru in America to their end as a group.
	The real story is told tastefully, without bashing anyone.
				
					Louie
Received: from B39.Tymnet by D35.Tymnet; Mon, 19 Dec 88 12:12:51 PST
Received: from tymix.Tymnet by B39.Tymnet; Mon, 19 Dec 88 12:13:03 PST
Received: by tymix.Tymnet (5.51/4.7) id AA11198; Mon, 19 Dec 88 10:32:11 PST
Received: by antares.Tymnet.com (3.2/SMI-3.2) id AA20028; Mon, 19 Dec 88
	01:18:40 PST
Return-path: <cbaltru@antares> 
From: cbaltru@antares (carl baltrunas) 
Date: Mon, 19 Dec 88 01:18:40 PST 
To: carl@d35 
Message-id: <8812190918.AA20028@antares.Tymnet.com> 
Subject: Beatles 

Path: antares!tymix!oliveb!ames!xanth!nic.MR.NET!tank!dlm3
From: dlm3@tank.uchicago.edu (saki)
Newsgroups: rec.music.beatles
Subject: Re: Excellent Beatle history reading.....
Summary: Must be a mixup somewhere
Keywords: real story
Message-ID: <1195@tank.uchicago.edu>
Date: 17 Dec 88 00:32:00 GMT
References: <902@nvuxr.UUCP>
Reply-To: dlm3@tank.uchicago.edu (saki)
Organization: University of Chicago
Lines: 21

In article <902@nvuxr.UUCP> lji@nvuxr.UUCP (L.IACONA) writes:
>
>	Wanna read some Beatle history without the superficial
>	fluff and hype?   -  get "the Love You Make" by 
>	Peter Brown and (I think) Steven Gaines. 
>	It goes thru the complete story, from a struggling 
>	"bum" band to their breakthru in America to their end as a group.
>	The real story is told tastefully, without bashing anyone.

Someone must have switched the dustjackets on you. This *can't* be the
same edition I read (once) and then discarded as biased balderdash. Why
does it continue to arouse this intense interest? How can you think it's
"without bashing"?

Stick with Philip Norman. He uses fact checkers.


-- 
"We know how to behave. We've had lessons."
-----------------------------
saki (dlm3@tank.uchicago.edu)
