:LOGFILE ENTER.LOG
;[ COMMAND FILE TO BUILD ENTER.ITEM ]
:$SUBSTITUTION=1
;  Time = \$DATE\ \$DAYTIME\
;
FTMAGNUM PERSONAL.DIRECTORY
COM ENTER.ITEM FROM FILE NENTER.MAG
Y
DIR TEXTS
QUIT
;  Time = \$DATE\ \$DAYTIME\
;
DIR/TODAY
