Received: from F29.Tymnet by D35.Tymnet; Mon, 11 Jan 88 10:04:33 PST
Return-path: <ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet> 
From: ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet 
Date: 11 JAN 88 09:25:23 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet 
Message-id: I33804@Ontyme.Tymnet 
Subject: PDP10 BIONIK (Bionic) problem reported by NIS 

SUBJ: 

           McDonnell Douglas Network Systems Company              M/S: F24
               TYMNET External Network Services
                                                  Tel. [-1] (408) 922-6473
 
DATE>      1988-01-11  09:08 PST                  Fax. [-1] (408) 922-7030

TO>        Carl Baltrunas (TXS.C/BALTRUNAS)
COPIES>    Rick Daniels (IPC.R/DANIELS)
           Jan Krivanec (IPC.J/KRIVANEC)
 
FROM>      Ken BeDell (ENS.K/BEDELL)

SUBJECT>   PDP10 BIONIK (Bionic) problem reported by NIS

REFERENCE> M40201 attached

- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
     Carl, NIS Japan has recently reported apparant problems with the
     BIONIK program, as outlined in the attached Ontyme (M40201) to Rick
     Daniels; perhaps Rick has already brought this to your attention.
 
     Also, an Ontyme from Kuni Kamoi today, stated further "I have no
     evidence which I can supply now.  But, I think I like to get the
     evidence as soon as possible.  Then, I don't know the right person
     which I contact."  He then references Dennis Coffey and yourself as
     persons contacted about PDP10 issues in the past.
 
     Do you have any ideas about the problem presented in the attached?
     What specific evidence can NIS supply to you in order for this to be
     checked out?
 
     I look forward to your prompt response.  Thanks Carl, best regards.
     Ken
Received: from F29.Tymnet by D35.Tymnet; Mon, 11 Jan 88 10:52:45 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 11 Jan 88 10:52:11 PST
Return-path: <ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet> 
From: ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet 
Date: 11 JAN 88 10:15:27 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet 
Message-id: I33860@Ontyme.Tymnet 
Subject: PDP10 BIONIK (Bionic) problem reported by NIS 

SUBJ: 

           McDonnell Douglas Network Systems Company              M/S: F24
               TYMNET External Network Services
                                                  Tel. [-1] (408) 922-6473
 
DATE>      1988-01-11  09:08 PST                  Fax. [-1] (408) 922-7030
 
TO>        Carl Baltrunas (TXS.C/BALTRUNAS)
 
COPIES>    Rick Daniels (IPC.R/DANIELS)
           Jan Krivanec (IPC.J/KRIVANEC)
 
FROM>      Ken BeDell (ENS.K/BEDELL)
 
SUBJECT>   PDP10 BIONIK (Bionic) problem reported by NIS
 
REFERENCE> M40201 attached
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 
     Carl, NIS Japan has recently reported apparant problems with the
     BIONIK program, as outlined in the attached Ontyme (M40201) to Rick
     Daniels; perhaps Rick has already brought this to your attention.
 
     Also, an Ontyme from Kuni Kamoi today, stated further "I have no
     evidence which I can supply now.  But, I think I like to get the
     evidence as soon as possible.  Then, I don't know the right person
     which I contact."  He then references Dennis Coffey and yourself as
     persons contacted about PDP10 issues in the past.
 
     Do you have any ideas about the problem presented in the attached?
     What specific evidence can NIS supply to you in order for this to be
     checked out?
 
     I look forward to your prompt response.  Thanks Carl, best regards.
     Ken
 
                                        v
                                        |
                                        |
                                        |
                                        |
                                        V

MSG#:M40201
 IN#:  3148
  TO: K/BEDELL        
FROM: NIS      OGURA           
SENT: 07 JAN 88 04:16:31  
READ: 07 JAN 88 08:15:22  
  CC: IPC.R/DANIELS  IPC.J/KRIVANEC  K/BEDELL  C/CHEN  L/HEINZEL 
      NIS.HQ  NIS.TC  NIS.OSAKA  NIS.TC  NIS.TC  NIS.TC  NIS.OGURA 
 
 
     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/07  21:14 (JST)  
     
Attn      : Rick Daniels    (IPC.R/DANIELS)  
     
Copies    : Jan Krivanec    (IPC.J/KRIVANEC) 
            Ken BeDell      (ENS.K/BEDELL)   
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.TC)    
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
            Hajime Itoh     (NIS.TC)    
            Kazuo Watanabe  (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 another problem    
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Rick,
     
Now, we have another problem on F74 (or the Base for F74).  
     
Our customers have sent files on to F74's KANA files by BIONIK, I will mentione 
about the BIONIK below, and the sent files had a problem.   
     
Some portion of the files, 8chars or 12 chars string, was replaced  as
unexpected same length string.
     
1. The characters which were replaced seemed to be by some Word unit. 
   (In KANA file,a word is 4 chars.)    
     
2. BIONIK is modified version for KANA file creation of BIONIC, and was    
   generated by ex-Tymshare person for NIS, ex-KTL. The program is located 
   on (UPLKT:74).   
     
3. About the timing of the problem, following 4 cases are reported.   
     
        In JST 
     
        '87  Dec  21st  morning    
                  21st  evening    
                  24th  morning    
        '88  Jan  06th  evening    
     
4. In those cases, the customers had made an access to F74 through 2 or 3  
   kind of HSA slot in Japan. 
     
5. We also know some unstable condition about I/O to F74 from the end of the    
   last year to the begin of this year. 
     
6. We have changed nothing in past one month, about BIONIK, HSA slot, etc. 
     
     
Regarding above matters, even though we have no explicit evidence, sorry,  
I suppose there might be some problems about I/O for F74 (or Base ?). 
And about the problem, the customers are very frustrated on our F74 system.
     
So please check and advise me on it, or please pass this letter to appropriate  
person. (Who is responsible about F74's system program now ?)    
     
Best regards,  
Makoto
From: Osman Guven <OSMAN@D35> 
Date: Mon, 11 Jan 88 14:06:07 PST 
To: Carl Baltrunas <Carl@D35>, Jms 
Subject: "OSMAN; HAS ANYTHING BEEN DONE"... 

(begin forwarded message)
----------------------------------------------------------------
Received: from F29.Tymnet by D35.Tymnet; Mon, 11 Jan 88 10:04:26 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 11 Jan 88 9:45:25 PST
Return-path: <IPC.R/DANIELS@EMSTXS.Ontyme.Tymnet> 
From: IPC.R/DANIELS@EMSTXS.Ontyme.Tymnet 
Date: 11 JAN 88 09:16:38 
To: TXS.O/GUVEN@EMSTXS.Ontyme.Tymnet 
Cc: TXS.O/GUVEN@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet 
Message-id: A49337@Ontyme.Tymnet 
Subject: "OSMAN; HAS ANYTHING BEEN DONE"... 

OSMAN;

HAS ANYTHING BEEN DONE IN REGARDS TO THIS?

THANKS RICK


     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/11  17:19 (JST)  
     
Attn      : Ken BeDell      (ENS.K/BEDELL)   
     
Copies    : Rick Daniels    (IPC.R/DANIELS)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Kei Suzuki      (NIS.HQ)    
            Makoto Ogura    (NIS.OGURA) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Kuni Kamoi      (NIS.TC)    
     
Subject   : pdp-10 problem    
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
     
Ken-san,  
     
How do you doing ?  
I heard you come to nis on Jan. 18. I look forward to meeting you again    
in Japan. 
By the way, I think you read Mr. Ogura's ontyme ( msg# M40201 dated 07
Jan. 88 ).
Now, I have serious problem of katakana version "BIONIK" which is
described in his ontyme. 
Our clients asked to us many complain about this matter.    
However, I have no evidence which I can supply you now.
But, I think I like to get the evidence as soon as possible.
Then, when I get the evidence, I don't know the right person which I contact.   
     
Please let me know the name of persons and his ontyme-id.   
     
In my old memory, Carl Baltrunas and Dennis Cofley were responsibilty 
for PDP system. Are they still be responsible ?   
     
See again in Tokyo. 
Best regards.  
Kamoi
----------------------------------------------------------------
(end forwarded message)

Carl..

Will you please give them a responce, Thank you.
-Osman-
From: Carl A Baltrunas <Carl> 
Date: Mon, 11 Jan 88 13:12:14 PST 
To: Ken BeDell <ENS.K/BEDELL@Ontyme.Tymnet> 
Cc: Rick Daniels <IPC.R/DANIELS@Ontyme.Tymnet>, Jan Krivanec
	<IPC.J/KRIVANEC@Ontyme.Tymnet> 
Subject: Re: PDP10 BIONIK (Bionic) problem reported by NIS 
In-reply-to: I33860@Ontyme.Tymnet of 11 JAN 88 10:15:27

Ken,
  Without more details of what data was substituted, we cannot reasonably
determine the exact nature of the problem that NIS was experiencing with
regards to their point 1, (modified or substituted characters in units of
a word).

  However, what is known is that on December 22nd, there was a problem on
system 74 with the SA-10 (the interface between the PDP-10 I/O buss and the
disk and tape drives).  My understanding is that system 74 was taken down
at 7am PST and brought up on the spare KL-10 CPU in the Fremont data center
by 11am PST.  The spare cpu worked fine, however the base hardware connected
to this cpu has a known problem with BLOCK-IO (which affects TELECOPY, BIONIC,
BIONIK and others).

  When the SA-10 on system 74 was fixed, the system came back up on it's
proper hardware at midnight (PST) of the 22nd and the problems that NIS was
having went away.

  On December 31st, more spurious disk problems were reported, and again the
SA-10 was suspect.  So system 74 was again brought up on the spare cpu at 9:45
PST with the "broken" base.  As of this message, system 74 is still running on
the spare cpu.  It is scheduled to return to it's own hardware on the 15th of
January.

  On January 3rd NIS again reported problems with BIONIK to operations and I
was called in to look at them.  I determined that the problem appeared to be
related to BLOCK-IO since all other network I/O appeared to behave correctly.
I asked operations to reload the base, so that we could rule out corrupted
base code.  They had reloaded the system a couple of hours earlier to try to
fix the problem.  The problem didn't change and I looked at the base with
probe and found that F74 was on the spare cpu and there was a good probablility
that it was connected to the "broken" base hardware.  I had operations call in
maintenance and swap the base hardware.  This was done in the early a.m. on
January 4th.  When the system came up, we tested BIONIC and TELECOPY and the
problems appeared to be solved.

  As regards to the "broken" base that is referred to above.  We use the spare
cpu and it's base as our working test system for software support.  From time
to time we have experienced problems with BLOCK-IO due to an intermittant
hardware problem.  I believe it was an oversight that when F74 was moved to
the space cpu, the base hardware was not immediately swapped with a known good
base.  Once the problem was identified as the base, the "broken" base was
swapped out and I do not expect that NIS will encounter any more problems due
to the base.

Ken, please check with Rick Daniels to verify that no other changes were made
to the hardware configuration than those mentioned above (before responding
to NIS).  If their problems occurred during the times specified above, even
thought they may not have been detected until a later date, then we have
pin-pointed the cause of their problems.  If not, we need to try to reproduce
their problems before we can try to fix them.

Rick, the times for the hardware swaps came from the system log book and the
center log book.  We didn't see any additional reports of problems or hardware
swaps.  Please verify that there were no additional changes.   Thanks!

Rick, we need to be aware that whenever we swap cpu's in the future, that we
do not swap to the "broken" base hardware, until we know it has been fixed.

Ken,
  As for software support for the PDP-10s, our group still exists.  We are now
only 3: Carl Baltrunas, x6206;  Osman Guven, x6236; and Joe Smith, x6220.  Our
manager is Craig Fletcher, x6213.  Best way to reach us is via the secretary
at x6224 and that is the published number to call for software support.  Again
we do not usually deal with customers directly... they should call operations
at their local data center or their customer representative.  There is a group
in IPC or RCS in St. Louis which is supposed to support customers directly.
The contact name I have is Sheldon Rundell.  I don't have his number handy.

/Carl

PS.  About BIONIK... my understanding is that it is a version of the "old"
     BIONIC program before the modifications that I made 2 years ago when
     the new HSA code was put in place.  I really would prefer that NIS
     move their applications (I realize that many of their command sequences
     are burned into ROMs and cannot be changed) by having all new applications
     use the new (SYS) BIONIC program.  It has a KATAKANA command which then
     allows it to do the job that BIONIK was modified to do.  The default is
     ASCII.  We could modify BIONIC to immediatly use KATAKANA mode if the
     user's terminal is in set to KATAKANA, as most of the japanese customers
     are.  I just don't like having multiple versions of programs around to
     be supported when one version can do the job.

From: Carl A Baltrunas <Carl> 
Date: Mon, 11 Jan 88 15:04:47 PST 
To: Monitor Group <Carl>, Osman Guven <Osman>, Joe Smith <JMS>, Craig Fletcher
	<fletcherc>, Jan Krivanec <IPC.J/Krivanec@Ontyme.Tymnet>, Rick Daniels
	<OPERA.SUP@EMSTXS.Ontyme>, Ken BeDell <ENS.K/Bedell@Ontyme.Tymnet> 
Subject: Summary 

Ken,
  I realize that I may not have been clear in summarizing what I said in the
previous memo.

  Basically, if the problems reported by NIS occurred entirely during the
periods when the "broken" base was known to be connected to the spare cpu
while system F74 was running on the spare cpu, then the problems are all
explained by the faulty base hardware.

  If they have other problems and we can reproduce them, we will try to
solve them as they provide sufficient information about reproducing them,
or when they occurred.

  We have seen some BLOCK-IO problems that are similar to those described
in the earlier mail messages, but those were pretty well fixed in recent
(within the last year) changes to the base code or the interface between the
base and TYMCOM-X.  If the character substitution problem continues to occur
we want to be able to reproduce it.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Tue, 12 Jan 88 9:44:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 12 Jan 88 9:43:31 PST
Return-path: <ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet> 
From: ENS.K/BEDELL@EMSTXS.Ontyme.Tymnet 
Date: 12 JAN 88 09:03:57 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet 
Message-id: I34413@Ontyme.Tymnet 
Subject: Additional input from Japan regarding BIONIK problem 

           McDonnell Douglas Network Systems Company              M/S: F24
               TYMNET External Network Services
                                                  Tel. [-1] (408) 922-6473
 
DATE>      1988-01-12  08:58 PST                  Fax. [-1] (408) 922-7030
 
TO>        Carl Baltrunas (TXS.C/BALTRUNAS)
 
FROM>      Ken BeDell (ENS.K/BEDELL)
 
SUBJECT>   Additional input from Japan regarding BIONIK problem
 
REFERENCE> M41068 attached
 
 
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
 
 
     Carl, yet another Ontyme sent by NIS Japan.  I note it was sent to
     your FSC ontyme name so I'm forwarding to your TXS name.
 
     Please let me know if the additional data gives you adequate infor-
     mation to follow up further on problem.  Also, do let me know if
     additional specific information is required by you, in order to fol-
     low up on this topic.
 
     I plan to alter your memo of yesterday and send to Japan; primarily
     so they are aware that problem has been, and is being, checked out;
     also to obtain a clarification on the dates of problem.
 
     I'll remove any sections which should not be seen by them and suggest
     that problems of this type be reported to Rick Daniels and myself,
     and that we'll follow up with you as needed (also that Dennis no lon-
     ger works in the Tymcom X group).
 
     Look forward to your comments.  Regards. Ken
 
                                        v
                                        |
                                        |
                                        |
                                        |
                                        V

MSG#:M41068
 IN#:  31 TO: K/BEDELL        
FROM: NIS      OGURA           
SENT: 12 JAN 88 03:22:10  
READ: 12 JAN 88 08:40:31  
  CC: FSC.C/BALTRUNAS  FSC.D/COFFEY  K/BEDELL  IPC.R/DANIELS 
      IPC.J/KRIVANEC  C/CHEN  L/HEINZEL  NIS.TC  NIS.HQ  NIS.OSAKA 
      NIS.TC  NIS.OGURA 
 
     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/12  20:20 (JST)  
     
Attn      : Carl Baltrunas  (FSC.C/BALTRUNAS)
            Dennis Coffey   (FSC.D/COFFEY)   
            Ken BeDell      (ENS.K/BEDELL)   
     
Copies    : Rick Daniels    (IPC.R/DANIELS)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Kuni Kamoi      (NIS.TC)    
            Kei Suzuki      (NIS.HQ)    
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 PROBLEM  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl and Dennis,    
     
At first, I'm sorry I'm not sure that you are the right person to be contacted  
on such problem. However, in my old memory, you have been the responsible  
persons for PDP-X system software. 
     
The problem on F74 reported during the middle of the last Dec and today, by
many users.    
     
And the problem is becoming very critical.   
     
So please check and advise me, or please pass this letter to appropriate person 
and let me know the name of the responsible person.    
     
The problem is 
     
        When users sent files onto F74 by BIONIC or BIONIK, the modified BIONIC 
        for KANA file input written by ex-Tymshare, they found that some   
        characters (8-12 char string) was replaced as other string.   
     
        For your checking, I located one of the troubled files onto (OGURA:74)  
        CHKDAT.NIS. (The original file in user area is (HAL:74)RHAMK2.020.)
        In that file, you can find a string "WW@@ZZ Z" at 15th column of the    
        307th record. But the original string for the 8 chars is ";  YVWYS",    
        and also we can find the "WW@@ZZ Z" at the 302nd rec in the file.  
        So I guess the 8 char string of 307th rec is overwritten by the 8 char  
        string of 302nd rec.  
     
        Anyway, our users found that the sent files on F74 were different from  
        the original files on their terminals.    
     
        The users tried to send the files through HSA in Japan. And regarding   
        the HSA, no Tymcom-370 user, who access to the host through the HSA
        slot, report such kind of problem.   
     
Thanks and regards, 
Makoto    
     
P.S. I also find some strange matter on creation date in dir information   
     of (OGURA:74)M28250.OTM. Year 1999 was indicated for the creation!!   
     I feel there is something wrong in the current F74.
Received: from F29.Tymnet by D35.Tymnet; Wed, 13 Jan 88 2:38:11 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 13 Jan 88 2:27:30 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 13 JAN 88 02:06:30 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, TXS.C/BALTRUNAS@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M41346@Ontyme.Tymnet 
Subject: F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/13  19:04 (JST)  
     
Attn      : Ken BeDell      (ENS.K/BEDELL)   
     
Copies    : Carl Baltrunas  (TXS.C/BALTRUNAS)
            Rick Daniels    (IPC.R/DANIELS)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.TC)    
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Problem  
            Ref M41068   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Ken san,  
     
Thanks for your OnTyme regarding the matter. 
     
I understood what was happened on F74 after the last December. And it explained 
about the status on 22nd Dec 87.   
     
However, one of our user reported the problem on the file which were sent onto  
F74 at 09-Jan-88 JST. ... This is just the case which I mentioned in my last    
OnTyme.   
Also Mr.Nakano made a test file and found the problem at about 15:30 12-Jan-88  
JST by BIONIK with the test file after some trials.    
     
So I think there is still the problem on the current F74.   
     
However, we will wait and coduct the test with the test file on 16t Jan after   
the hardwere return on 15th Jan. Fotunately, 15th Jan is a national holiday in  
Japan. So we, NIS and the customers, have only 1 bussines day by the hardwere   
returning.
     
About the hardwere returnning, please let me know the scheduled time, what time 
on 15th Jan PST, and please notify the time when the returnning take place.
By that information, we may identify the cause of the problem.   
     
Regarding the BIONIK, what Carl mentioned was just correct. In near future,
no user will use the BIONIK.  
     
Best regards,  
Makoto    
P.S. See you in Tokyo the next week !!
Received: from F29.Tymnet by D35.Tymnet; Wed, 13 Jan 88 12:18:55 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 13 Jan 88 12:17:07 PST
Return-path: <IPC.R/DANIELS@EMSTXS.Ontyme.Tymnet> 
From: IPC.R/DANIELS@EMSTXS.Ontyme.Tymnet 
Date: 13 JAN 88 12:01:05 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: IPC.J/KRIVANEC@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, TXS.C/BALTRUNAS@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet 
Message-id: A50343@Ontyme.Tymnet 
Subject: "SUBJ: M E M O R A N D U M DATE>"... 

SUBJ: 





                         M E M O R A N D U M





DATE>      13 JAN 88  12:00

TO>        Makoto Ogura

COPIES>    See CC List

FROM>      Rick Daniels


SUBJECT>   Moving F74 to Home Hardware


-----------------------------------------------------------------------


Makoto;

The following is the schedule for swapping F74 back to its HOME hardware:

System is scheduled down from 1600 (PST), 15 Jan (0900 your time on 16 Jan)

System is scheduled up at 2100 (PST), 15 Jan (1400 your time on 16 Jan).


Please let us know the result of your test after F74 is back on original
hardware.
Best regards;

Rick DAniels
   Received: from F74.Tymnet by D35.Tymnet; Thu, 14 Jan 88 17:06:56 PST
Return-path: <Carl@D35.Tymnet> 
From: Carl A Baltrunas <Carl@D35.Tymnet> 
Date: Thu, 14 Jan 88 15:40:42 PST 
To: Makoto Ogura <NIS.OGURA@Ontyme.Tymnet>, Ken Be Dell
	<ens.K/BeDell@Ontyme.Tymnet> 
Subject: (OGURA:74)M28250.OTM 

Ogura,
  The file (OGURA:74)M28250.OTM apparently had 2 extra bits set in the field
which designates the creation date of the file.  I have no explanation for
why the two bits were set.  They could have been set by a quirk shift of the
high-order 2 bits of the date field, but since the file was actually created
on 3-Nov-87, there shouldn't have been any changes to the file since then
to cause the two bits to be set.  Another possibility is that the SA-10 disk
controller problem twiddled the bits when it mapped the retrieval block page
back to disk...

  Anyway, I reset the high order bit in the date to a 0, and the creation
date now says 3-Nov-87 as it should.

/Carl Baltrunas  <TXS.C/Baltrunas>

PS.  Dennis Coffey continues to work for Tymnet, but does not work in
     our support group any longer.  He transferred last November.

     Also, when sending an ONTYME, please send to TXS.C/BALTRUNAS and
     do not send to FSC.C/BALTRUNAS.
Received: from F29.Tymnet by D35.Tymnet; Mon, 18 Jan 88 2:44:27 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 18 Jan 88 2:27:32 PST
Return-path: <NIS.KAMOI@EMSTXS.Ontyme.Tymnet> 
From: NIS.KAMOI@EMSTXS.Ontyme.Tymnet 
Date: 18 JAN 88 02:08:33 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.K/BEDELL@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet 
Message-id: M42012@Ontyme.Tymnet 
Subject: F74 problem's solution !!!! urgent !!!! 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/18  19:06 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Rick Daniels    (IPC.R/DANIELS)  
            Ken BeDell      (ENS.K/BEDELL)   
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Makoto Ogura    (NIS.OGURA) 
            Kei Suzuki      (NIS.HQ)    
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
            Jan Krivanec    (IPC.J/KRIVANEC) 
     
From      : Kuni Kamoi      (NIS.TC)    
     
Subject   : F74 problem's solution !!!! urgent !!!!    
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
     
Mr. Baltrunas, 
     
At the first, please let me introduce myself to you.   
My name is Kuniyoshi Kamoi and Application System Dept.'s General manager  
of NIS. Our dept. are supporting tymcom-x and tymcom-370 customer.    
Because, I am not sure whether you remember me or not. 
     
By the way, I think you read Mr. Ogura's ontyme and talked with Mr. Ken Bedell  
regarding F74's block I/O problem .
I received many complain from customer since last December. 
     
According to Mr. Ken Bedell's ontyme ( MSG # M41270 ), you said it is scheduled 
to return to it's own ( F74 ) hardware on the 15th of January(pst).   
Unfortunately, in japan, it was holiday thru. 15 to 17 of Jan. (jst). 
Then , we checked the F74's situation since changing hardware using bionik 
today ( 18th of Jan. jst ).   
     
Our testing method are as follows: 
     
        (1). we had data file on F74 and did down-loading ( from f74  
             to terminal's MAG. tape....terminal is DATA-100 ) using KPUNCH.    
             the data on f74's disk is original and Mag.'s tape data  
             is test data.    
     
        (2). we did up-loading from DATA-100 to F74 the Mag. tape data
             using BIONIK and checked contents of data between original    
             and test data repeatedly.  
     
As the result, we did test 6 times and it was occured 2 times that there   
were diffenrent between original and same data which loaded from terminal  
to F74 repeatedly.  
     
The time are as follows: 
     
        1st.    14:10 18th of Jan. (jst)  5th trial    
     
        2nd.    15:20 18th of Jan. (jst)  6th trial    
     
The error is as follows: ( a part of record )
     
1st:  5 record's error   
     
        correct data: AA100010120A12    
        error data:    AA10010120A12    
     
        correct data: 000040700 10M!!!  
        error data:   0000031429 11!!!  
     
        correct data: 000014000    
        error data:    00000920    
     
        correct data: 000002700 12M!!! !!!!!!
        error data:   0000027400 12M8!!!!!!!!
     
        correct data: 000157300 12M!!! !!!!!!!    
        error data:    00002740 12M!!! !!!!!!!    
     
2nd:  1 record error
     
        correct data: 12M !!!!!!!!!!! NTT 41220410000000    
        error data:   12M !!!!!!!!!!!!!!   1120530000000    
     
It is above information which we can test and give you .    
However, our clients are status of serious situation for their operation.  
Please contact with all participant and resolve this problem as soon as    
possible. 
     
I look forward to from your good response.   
     
thanks and best regards. 
kuni kamoi
Received: from F29.Tymnet by D35.Tymnet; Mon, 18 Jan 88 3:04:14 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 18 Jan 88 2:54:32 PST
Return-path: <NIS.KAMOI@EMSTXS.Ontyme.Tymnet> 
From: NIS.KAMOI@EMSTXS.Ontyme.Tymnet 
Date: 18 JAN 88 02:33:50 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Message-id: M42014@Ontyme.Tymnet 
Subject: m42012 

Attention: Mr. Baltrunas,

Today, Mr. Ogura is cold and dose not come to office.
I know he sent several message regardin f74's problem.
The ontyme which i sent you today is same matter.
( msg# M42012 ).

best regards.
kamoi
From: Carl A Baltrunas <Carl> 
Date: Mon, 18 Jan 88 4:15:07 PST 
To: Kuni Kamoi <NIS.KAMOI@Ontyme.Tymnet> 
Cc: IPC.R/DANIELS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	NIS.OGURA@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet, Joe Smith <JMS>,
	Osman Guven <Osman>, Craig Fletcher <fletcherc> 
Subject: Re: F74 problem's solution !!!! urgent !!!! 
In-reply-to: M42012@Ontyme.Tymnet of 18 JAN 88 02:08:33


To:      Kuni Kamoi

From:    Carl Baltrunas (TXS.C/Baltrunas)

Mr. Kamoi,
  As mentioned in your ONTYME regarding your test data... Could you please
up-load to the TYMCOM-X system the data multiple times, each time putting
the data into files with different filenames (such as TEST1, TEST2, etc.)
and send to me a copy of the results, so that I may examine the data files
directly.

  If you need more disk space temporarily, contact me or Jan Krivanec.

  I would also like you to try up-loading the data using the (SYS)BIONIC
program with the "KATAKANA" command.

    -R BIONIC                     << - normal ASCII mode
    *RUN
    FILE NAME: ....


    -R BIONIC                     << - normal ASCII mode
    *KATAKANA                     << - change to KATAKANA mode
    *RUN
    FILE NAME: ....

  I do not suspect that the problem is with your version of the BIONIK
program, but I wish to eliminate that possibility from my thoughts.  If
you can provide incorrect data transferred with BIONIK "and" incorrect
data transferred with (SYS)BIONIC using the KATAKANA command it may help.

  I am looking for a pattern for how the data corruption is occurring
during the data transfers and I need to be able to compare one copy of
the test data (which is known to be correct) against all copies of the
test data which transfer incorrectly.  Please make one file to keep on
disk that transfers correctly, and as many files containing bad transfer
data as you think reasonable.  The more data I can compare, the better
I will be able to find a pattern.  Please send an ONTYME with the file
names and any additional information you wish to send.

  It is 4:45 am PST now.  If you can send this information in the next 4
or 6 hours, I will look at the data when I wake up in a few hours and see
if we can find a solution.

                                Sincerely,


                                Carl A Baltrunas,  TYMCOM-X Software Support


/Carl
Received: from F29.Tymnet by D35.Tymnet; Mon, 18 Jan 88 18:24:17 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 18 Jan 88 18:21:49 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 18 JAN 88 18:07:03 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42225@Ontyme.Tymnet 
Subject: F74 problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/19  11:05 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.TC)    
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 problem  
            Ref Your OnTyme A51575 
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your Ontyme, A51007.    
     
And receiving your reply(A51575) for Mr. Kamnoi's OnTyme(M42012), yesterday I   
was inbed by sick so Kamoi sent the OnTyme for me, I will coduct the trials by  
the BIONIC (without katakana option). I think if we can reproduce the problem   
under the BIONIC's ordinary mode, ASCII mode, it helps your investigation more. 
     
And for your further investigation, I will inform you more about what mentioned 
in M42012 by Kamoi, as follows.    
     
1. The files which have the problem are 
     
                (OHTA:74)ERR.01    
                (OHTA:74)ERR.02    
     
2. The original (correct) file is (OHTA:74)JAN.XT.
     
3. The problem is found in    
     
        i. 124th, 241st, 626th, 656th, and 1026th record in (OHTA:74)ERR.01.    
        ii. 713rd record in (OHTA:74)ERR.02. 
     
4. The files mentioned above are sent by BIONIK and are the KANA files.    
     
I will send you after my trials for the BIONIC.   
     
Best regards,  
Makoto
From: Carl A Baltrunas <Carl> 
Date: Tue, 19 Jan 88 1:29:06 PST 
To: <NIS.OGURA@Ontyme.Tymnet> 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet, Osman@D35, Jms@D35 
Subject: Re: F74 problem 
In-reply-to: M42225@Ontyme.Tymnet of 18 JAN 88 18:07:03

To: Makoto Ogura

From: Carl Baltrunas

Re: Study of test files

Makoto,
  I have looked at the test data files on (OHTA:74)  including the new files
produced 18-Jan-88.   I have not found any particular pattern as of this
message.   I will check the logic in the BIONIC program to see how it counts
characters and records to determine if additional bytes of data are inserted
when a carriage-return or line-feed is encountered.  I do not expect any
suprises, but I cannot detect any reason why this problem can be happenning
at this time.   Both the hardware and software appear to be reliable... but
as we can see, the data is corrupted.

  Please notice that I moved the test data from (OHTA:74) to (TXSINFO:74)
because there was room for only 300 more pages in directory OHTA.  I also
copied file JAN.XT and created a file JAN.CAB which is the correct data
from JAN.XT, only in ASCII.  [I have a program which will do that very
easily, in case you have a need for someone to read a KATAKANA file on an
ASCII device, I will tell you where it is and how it works.]

------------------------

Re:  Additional tests.

  I would like you to perform two additional tests at this time.  First,
we want you to up-load the same test data that you have used on system
74 to another system.  I believe you are valid on systems 34 or 35.  If
you could make this test, we could rule out the CPU/Base hardware.

  The second test, will be to re-run the test data again on system 74
after we have put some diagnostic patches into system 74's operating
system.  If both of these tests fail, we will have to try to use the
same hardware, only change the load that is running on the system at the
time of failure.

  One last item...  how many times did you run the test in the past few
days and how many times was the data transferred successfully (if at all)
and how many times unsuccessfully.

  What hours of your working schedule overlap with pacific standard time?
It may be better if I re-arrange my schdule for a few days so that we can
overlap and work on this problem at the same time.

/Carl A Baltrunas
Received: from F29.Tymnet by D35.Tymnet; Tue, 19 Jan 88 3:41:12 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 19 Jan 88 3:39:47 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 19 JAN 88 02:11:57 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42243@Ontyme.Tymnet 
Subject: F74 problem, Our trials 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/19  19:09 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.TC)    
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 problem, Our trials
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Mr.Nakano coducted the trials using BIONIC to send an ASCII file, today.   
     
1. The trials :
     
Trial start time (JST)                  The sent file  
     
19-Jan-88  10:15        Not OK          (OHTA:74)ERR.03
           11:10        OK    
           13:10        OK    
           14:00        OK    
           15:20        OK    
           16:10        Not OK          (OHTA:74)ERR.04
     
2. The access to F74 was made under 4800bps/HSA in Japan.   
     
3. You can find the problem   
     
        i.  on 945th record in (OHTA:74)ERR.03.   
        ii. on 181st, 205th, 220th, and 406th record in (OHTA:74)ERR.04.   
     
4. The original (correct) file is (OHTA:74)JAN11.XT.   
     
Please check those files and advise me. 
     
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Tue, 19 Jan 88 18:41:40 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 19 Jan 88 18:40:07 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 19 JAN 88 18:30:41 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42448@Ontyme.Tymnet 
Subject: Reply for your Question on A52148 
ReplyforyourQuestiononA52148: 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/20  11:29 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Kuni Kamoi      (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : Reply for your Question on A52148
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
I was a little confused  on your OnTyme A52148, because I think you understand  
about the relation between BIONIC and HSA well. Or, I'm afraid that I mis- 
understood what you mentioned on that letter.
     
Anyway, we send records to F74 by BIONIC through HSA without CR,LF as a end-of- 
record characters. However, instead of the CR,LF, our terminal send the records 
with IRS as an ordinary 3780/BSC e-o-r character in non-transparent mode.  
     
For ex....
     
        S               I               I               IE  
        T<--132 bytes-->R<--132 bytes-->R<--132 bytes-->RT  
        X   in EBCDIC   S    in EBCDIC  S    in EBCDIC  SB  
     
In above example,   
        1. The record length is 132/record logicaly, however, in actual    
           transmission, blank string is compressed in 2 bytes under the   
           rule of BSC/3780 blank compression.    
           So our sending block(Max=512) contains several number of variable    
           length (Max=132) with IRS.   
        2. As you know, the end-of-block code of the last transmission block    
           is not EOT but ETX.
        3. Our terminal sends those formatted blocks to HSA through BBXS, and   
           I think the HSA conduct EBCDIC-ASCII conversion, Blank string de-    
           compression, and other interface operation for the Base of F74 and   
           BIONIC.  
     
     
I hope this is just the information you need.
     
Best regards,  
Makoto    
P.S. Now, one of my people is conducting the uploading test on D34.   
     I will send you the conclusion after the trials.
Received: from F29.Tymnet by D35.Tymnet; Wed, 20 Jan 88 3:24:27 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 20 Jan 88 3:17:56 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 20 JAN 88 02:59:57 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42479@Ontyme.Tymnet 
Subject: F74 PROBLEM 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/20  19:57 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 PROBLEM  
            Ref A52147   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your investigation on the matter. 
     
1. Our user reported that one of our users found the problem at yesterday  
   evening's uploading in 2 files. 
     
2. Trials on D34    
   As I mentioned before, my people have conducted the test for D34 through our 
   HSA.   
   The result is ....    
     
     
   Date & Time of the trial        Result    
   (JST)  
     
   1. 20-Jan-88 11:30              OK   
   2.           13:20              OK   
   3.           14:20              OK   
   4.           15:00              OK   
   5.           15:50              OK   
   6.           16:20              OK   
   7.           17:20              OK   
     
   On this evening, no user found the problem. ... it is happy for us !    
     
     
2. Our all trials in the past few days  
   following is all record of our trials for F74 after 12 Jan. They are    
   conducted through HSA/Async by BIONIC/BIONIK. And also the cases which  
   I reported to you in my previous letter are included in those records.  
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
     1. 12-Jan-88 13:10                X         X           X   
     2.           15:30                X         X               X     not saved
     3. 13-Jan-88 09:30        X                       X     X   
     4.           14:00        X                       X     X   
     5.           15:00        X                       X     X   
     6.           16:20        X                       X     X   
     7.           17:00        X                       X     X   
     8. 14-Jan-88 09:30                X         X               X     not saved
     9.           11:00                X         X           X   
    10.           15:30                X         X           X   
    11.           16:30                X         X           X   
    12. 18-Jan-88 09:30                X         X           X   
    13.           10:10                X         X           X   
    14.           11:30                X         X           X   
    15.           13:00                X         X           X   
    16.           14:10                X         X               X      ERR.01  
    17.           15:20                X         X               X      ERR.02  
    18.           16:10                X         X           X   
    19.           17:15                X         X           X   
    20. 19-Jan-88 10:15       X                  X               X      ERR.03  
    21.           11:10       X                  X           X   
    22.           13:10       X                  X           X   
    23.           14:00       X                  X           X   
    24.           15:20       X                  X           X   
    25.           16:10       X                  X               X      ERR.04  
    26. 20-Jan-88 09:30       X                        X     X   
    27.           10:00       X                        X     X   
    28.           10:20       X                        X     X   
    29.           10:45       X                        X     X   
    30.           11:00       X                        X     X   
    31.           13:00       X                        X     X   
    32.           14:00       X                        X     X   
    33.           14:50       X                        X     X   
     
     
   The date & time is indicated in JST. 
     
     
3. Overlap time for co-work.  
    Following is a time conversion table. Please contact me or Mr. Nakano, if   
    you need to watch our trials.  
     
     
     
   JST  09    10     11     12           15     16     17     18 .....
      ---+-----+------+------+............+------+------+------+......
   PST  16    17     18     19           22     23     24     01......
     
      i.  Our office in Japan is opend at 9:15 a.m. JST.(= 16:15 PST) 
      ii. Also the office is closed at 17:45 officially.    
      iii. Almost of the user problem was found at the uploading in the    
           evening of JST. (= Midnight of PST !!) 
     
     
4. F74's trap  
   If you set some trap(patches) on F74, please let me know an instruction 
   how to conduct the trails to make the trap enable.  
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Wed, 20 Jan 88 4:44:15 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 20 Jan 88 4:27:24 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 20 JAN 88 03:41:09 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42481@Ontyme.Tymnet 
Subject: F74 problem, again 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/20  20:39 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
            Hajime Itoh     (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 problem, again
            Ref M42479   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Again Carl,    
     
I reported in my today's previous OnTyme that we had no problem this evening.   
However, just before, an user informed us that he found 3 errors in his file    
which was sent at 20:00 JST by BIONIK through HSA/2400bps in Tokyo.   
The file had a bit much volume. (200char/rec * 3600 recs)   
     
For your reference, the troubled file was copied to (MKS:74)ERROR.20, and  
the original, correct, file was saved  as (MKS:74)OK.20.    
     
Best regards,  
Makoto    
P.S. And I will add further information on our trials mentioned in the
     previous Ontyme. The file which was tried to send was the file which  
     you found as (oHTA:74)JAN.XT in KANA file and as (OHTA:74)JAN11.XT in 
     ASCII file.
From: Carl A Baltrunas <Carl> 
Date: Wed, 20 Jan 88 16:47:50 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Cc: jms, Osman Guven <Osman> 
Subject: Re: F74 problem, again 
In-reply-to: M42481@Ontyme.Tymnet of 20 JAN 88 03:41:09

To: Matoko Ogura

From: Carl A Baltrunas

re: Additional testing on F74

------------------------------

Matoko,
  I would like you to please continue to run the tests again on system
D34 in Dallas.  Since the problem is spurious, it is possible that the
conditions were not right for the error to occur on D34.

  We have also reloaded F74 today with my patch to gather information
about a possible cause of the problem.  Please re-run the tests again
on system F74 today and let me know the results.

  I will be working and observing the system from time to time during
your working hours today.  So, messages can be sent and returned on
the same day.  I will check my mail messages every 2 hours today.

  Thank you again for your assistance in tracking down this problem.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Wed, 20 Jan 88 23:24:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 20 Jan 88 23:12:46 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 20 JAN 88 22:38:49 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42672@Ontyme.Tymnet 
Subject: F74 PROBLEM 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/21  15:36 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 PROBLEM  
            REF A53095   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thaks for your co-operation, and sorry for delay of this OnTyme. Because, I
was out of office this morning. Anyway, after my returnning to the office, 
I checked and found that by this moment another 9 trials were conducted on 
D34, and also another 2 trials were conducted on F74.  
     
On both host, we can't find the problem today.    
followings are the evidence of our trials.   
     
     
On D34    
======    
     
Start Date &                           HSA  Async          Error 
time for trial        BIONIC  BIONIK  4800   2400  OK  NG  File  
     
 1. 20-Jan-88 11:30      x               x          x  
 2.           13:20      x               x          x  
 3.           14:20      x               x          x  
 4.           15:00      x               x          x  
 5.           15:50      x               x          x  
 6.           16:20      x               x          x  
 7.           17:20      x               x          x  
 8. 21-Jan-88 09:20      x               x          x  
 9.           10:00      x               x          x  
10.           10:30      x               x          x  
11.           10:45      x               x          x  
12.           11:15      x               x          x  
13.           11:30      x               x          x  
14.           11:45      x               x          x  
15.           13:50      X               X          X  
16.           14:20      X               X          X  
     
     
The date & time is indicated in JST.    
     
     
Above data includes data for yesterday's which I already reported to you.  
     
     
On F74    
======    
     
     
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
    34. 21-Jan-88 14:50       X                  X           X   
     
     
   The date & time is indicated in JST. 
     
Above data includes only trial on today. Now the second trial is running.  
     
     
About the results on both host, I locates the data on (OGURA:74)74.FIL for 
trials on F74, and on (OGURA:74)34.FIL for D34.   
     
Best regards,  
Makoto
From: Carl A Baltrunas <Carl> 
Date: Thu, 21 Jan 88 0:26:01 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet,
	NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet,
	Joe Smith <JMS>, Osman Guven <Osman> 
Subject: Re: F74 PROBLEM 
In-reply-to: M42672@Ontyme.Tymnet of 20 JAN 88 22:38:49

To: Makoto Ogura

From: Carl A Baltrunas

Re: Testing of F74 problem

As of this message, we have not seen a reported instance of the situation
we are expecting to occur with our diagnostic patch.  Please continue to run
tests on system F74.

You do not need to run any more tests on D34 unless we find an error on F74.
We do not expect the information gathering patch to solve the problem and
now we must wait until we have a data transfer failure on F74.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Thu, 21 Jan 88 3:04:14 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Thu, 21 Jan 88 2:47:35 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 21 JAN 88 02:22:18 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42689@Ontyme.Tymnet 
Subject: F74 Problem/Trials on 21-Jan-88 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/21  19:20 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Problem/Trials on 21-Jan-88  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
On today's trials, we can not find any problem on both hosts.    
Where does the problem go!!   
     
Anyway the result is ... 
     
On F74    
======    
     
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
    34. 21-Jan-88 14:50       X                  X           X   
    35.           15:10       X                  X           X   
    36.           15:50       X                  X           X   
    37.           16:50       X                  X           X   
    38.           17:30       X                  X           X   
     
     
   The date & time is indicated in JST. 
     
On D34    
======    
     
     
Start Date &                           HSA  Async          Error 
time for trial        BIONIC  BIONIK  4800   2400  OK  NG  File  
     
 8. 21-Jan-88 09:20      X               X          X  
 9.           10:00      X               X          X  
10.           10:30      X               X          X  
11.           10:45      X               X          X  
12.           11:15      X               X          X  
13.           11:30      X               X          X  
14.           11:45      X               X          X  
15.           13:50      X               X          X  
16.           14:20      X               X          X  
17.           16:10      X               X          X  
18.           16:30      X               X          X  
19.           17:10      X               X          X  
     
     
The date & time is indicated in JST.    
     
     
     
What is the next step to find out the hidden beetle ?  
I think that without appearing the problem your trap on F74 does not work well. 
We will continue the trials tomorrow. If you need another idea on the trials,   
please let me know. 
     
Thanks and regards, 
Makoto
From: Carl A Baltrunas <Carl> 
Date: Thu, 21 Jan 88 3:38:07 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet,
	NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet,
	NIS.OGURA@Ontyme.Tymnet, Joe Smith <JMS>, Osman Guven <Osman> 
Subject: Re: F74 Problem/Trials on 21-Jan-88 
In-reply-to: M42689@Ontyme.Tymnet of 21 JAN 88 02:22:18

Makoto,
  At this point, I would like you to continue testing, only on F74.  My
trap appears to have caught something two times, indicating that the
condition that I thought might happen has occurred.  I have made a fast
revision to the trap and need to verify the repeatability.

  As you say the problem has not occurred, and my trap caught two times,
I believe that someone else (not your test) caught an error.  I am stopping
at the data center to review the trap output and will report to you the
results before tomorrow.

  Please continue testing on F74, so that I may gather more data.  Thank
you again for your help in tracking this problem.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Fri, 22 Jan 88 2:04:10 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Fri, 22 Jan 88 1:59:04 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 22 JAN 88 01:26:15 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M42913@Ontyme.Tymnet 
Subject: F74 problem/Trials 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/22  18:24 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 problem/Trials
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Today, we conducted only 5 trials. Because our file transfer device(MY unit)    
was occupied for the customer operation in all day.    
     
     
Anyway, we found no problem in the trials.   
The result is ....  
     
     
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
    39. 22-Jan-88 09:30       X                  X           X   
    40.           11:20       X                  X           X   
    41.           13:00       X                  X           X   
    42.           13:20       X                  X           X   
    43.           17:30       X                  X           X   
     
     
   The date & time is indicated in JST. 
     
Regarding the detected errors in your trap yesterday, I checked NIS'  
customer  who sent a file yesterday evening, however no NIS customer  
had the problem.    
     
This evening, by this moment,  no user reports the problem. 
     
Tomorrow, I will try few trials.   
     
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Sat, 23 Jan 88 1:15:18 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Sat, 23 Jan 88 1:07:26 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 23 JAN 88 00:37:43 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M43131@Ontyme.Tymnet 
Subject: F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/23  17:35 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Problem  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Today, I made 6 trials on F74, however no problem was appeared.  
     
     
The result is ....  
     
     
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
    44. 23-Jan-88 12:59       X                  X           X   
    45.           15:20       X                  X           X   
    46.           16:40       X                  X           X   
    47.           16:50       X                  X           X   
    48.           17:00       X                  X           X   
    49.           17:15       X                  X           X   
     
     
   The date & time is indicated in JST. 
     
How was your trap ?  What is the condition that you thought that might happen,  
mentioned in A53164 dated 21-Jan-88.    
     
Anyway, I will continue the trials the next week. 
     
Thaks and regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Mon, 25 Jan 88 1:44:16 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 25 Jan 88 1:31:33 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 25 JAN 88 01:20:14 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M43185@Ontyme.Tymnet 
Subject: F74 problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/25  18:18 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 problem  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Followings are the result of today's trial on F74.
     
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
    50. 25-Jan-88 09:30       X                  X           X   
    51.           09:55       X                  X           X   
    52.           10:20       X                  X           X   
    53.           10:40       X                  X           X   
    54.           11:05       X                  X           X   
    55.           11:20       X                  X           X   
    56.           13:00       X                  X           X   
    57.           13:20       X                  X           X   
    58.           13:40       X                  X           X   
    59.           14:10       X                  X           X   
    60.           14:25       X                  X           X   
    61.           15:00       X                  X           X   
    62.           15:30       X                  X           X   
    63.           15:50       X                  X           X   
    64.           16:05       X                  X           X   
    65.           17:15       X                  X           X   
     
     
   The date & time is indicated in JST. 
     
In past few days, no problem appeared. Did someone change something ? 
     
Best regards,  
Makoto
From: Carl A Baltrunas <Carl> 
Date: Tue, 26 Jan 88 0:44:03 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Subject: Re: F74 problem 
In-reply-to: M43185@Ontyme.Tymnet of 25 JAN 88 01:20:14

To:  Makoto Ogura

From: Carl Baltrunas

Re: F74 trap

Makoto,
  I am concerned about your testing.  Our patch has printed many lines
on the system console indicating that various users have received bad
data (according to the patch) from time to time, and yet your tests say
there have been no problems.

I have not obtained a paper copy of the system console output to compare
with the dates and times of your testing.  I will do that in the next day
or two.  The two usernames which I see that may be your customers were
(MFOOD) and (MFUDO) both running the program (UPLKT)BIONIK.  User (OHTA)
has also appeared in the trap information.

According to my trap-patch, the data bytes that prove that the user received
bad data will be a series of "UUUU" in either ASCII or KATAKANA modes.  If
you could check your data files for any occurrances of these 4 bytes, then
we can confirm that the problem we have detected via the patch is really
the same problem that is affecting your customers.

We will also be making another patch which will gather more information
including a copy of the entire buffer so that we can pinpoint the entire
sequence of bytes which we believe is in error.

I will send additional mail with dates & times in JST for when the errors
were trapped.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Tue, 26 Jan 88 3:38:19 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 26 Jan 88 3:31:40 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 26 JAN 88 03:14:32 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M43435@Ontyme.Tymnet 
Subject: F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/26  20:12 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Problem  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Today, we conducted 10 trials as follows, however no problem was appeared. 
And past few days, no user complaint us about the matter.   
     
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
    66. 26-Jan-88 10:25       X                  X           X   
    67.           11:00       X                  X           X   
    68.           11:25       X                  X           X   
    69.           13:10       X                  X           X   
    70.           13:50       X                  X           X   
    71.           14:25       X                  X           X   
    72.           15:00       X                  X           X   
    73.           15:50       X                  X           X   
    74.           16:25       X                  X           X   
    75.           17:15       X                  X           X   
     
     
   The date & time is indicated in JST. 
     
Where did the problem went out ?   
Again, do you know someone changed something on the F74 ?   
     
     
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Tue, 26 Jan 88 5:17:33 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 26 Jan 88 5:07:34 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 26 JAN 88 04:54:43 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M43441@Ontyme.Tymnet 
Subject: F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/26  21:52 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Problem  
            Ref A54786   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
This is just a short note.    
The usernames, MFUDO & MFOOD, are used by our customers. But they did not  
inform us about their error finding. I'm afraid that they missed finding   
the error out of their check. Anyway I will check it tomorrow.   
     
And (OHTA) is just the username which we are trying on F74 everyday.  
However, on today's trial nothing was appeared.   
     
Anyway, thanks for your working.   
Regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Wed, 27 Jan 88 2:24:12 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 27 Jan 88 2:23:27 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 27 JAN 88 01:54:37 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M43628@Ontyme.Tymnet 
Subject: F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/27  18:52 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Problem  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Today, we coducted following trials, and found no problem.  
     
     
     
     
    Start Date &                               HSA  Async              Error    
    time for trial          BIONIC  BIONIK    4800   2400   OK  NG     File
     
    76. 27-Jan-88 10:00       X                  X           X   
    77.           11:00       X                  X           X   
    78.           14:45       X                  X           X   
    79.           15:30       X                  X           X   
    80.           16:00       X                  X           X   
    81.           16:40       X                  X           X   
    82.           17:20       X                  X           X   
     
     
   The date & time is indicated in JST. 
     
How was your trap ?  Please let me know the date and time of your
trapped data for OHTA, MFUDO, and MFOOD.
     
Best regards,  
Makoto
From: Carl A Baltrunas <Carl> 
Date: Wed, 27 Jan 88 18:14:30 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet,
	NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet,
	Joe Smith <JMS>, Osman Guven <OSMAN> 
Subject: Re: F74 Problem 
In-reply-to: M43628@Ontyme.Tymnet of 27 JAN 88 01:54:37


Makoto,
  At this point, I do not expect that your testing will uncover anything
more.  I suggest that we stop the testing until the problem occurs again.
My trap has uncovered a potential problem with information passed from the
PDP-10 Base to the host with the wrong byte count.  I believe that it may
be caused when the base is overloaded.  I have attempted to overload the
base a few times since last week to trap the condition and we have trapped
three (3) times for certain, and numerous other times we suspect but are
not certain.

  I will leave the current trap in system F74 until we decide that a fix
has been found for the problem.  I will have resources verify which other
hosts use BIONIC or BIONIK and will install the trap on those systems as
well.  I believe that the problem we are seeing is not limited to system
F74, and may occur when the base is overloaded and some other conditions
exist at the same time.  At present, we cannot reliably re-create the
problem.

  As for your customers... if they report a problem, please see if they
can keep the erroneous data long enough to compare with a re-transmission
so that we can check our trap.  Their good data should be replaced with
a multiple of four (4) bytes of the ascii character "U" (octal 125, hex 55).
This same value will be found both in ascii text and ktakana text files
due to the nature of how block-io input is stored in memory.

  Thank you again for all the testing that you have done.  I will send
you a copy of the "suspicious" traps with username, program and times that
we saw a possible transmission failure.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Thu, 28 Jan 88 4:04:17 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Thu, 28 Jan 88 3:47:26 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 28 JAN 88 02:46:47 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M43881@Ontyme.Tymnet 
Subject: F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/01/28  19:44 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Problem  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your OnTyme, and I will stop making trials by your suggestion.  
     
And please send your suspicious trap data, I will check it. 
     
Best regards,  
Makoto
Received: from F74.Tymnet by D35.Tymnet; Tue, 2 Feb 88 6:41:09 PST
Return-path: <OPER@F74.Tymnet> 
From: OPER@F74.Tymnet 
Date: Tue, 2 Feb 88 6:36:25 PST 
To: OPER, BILLF, CARL, JMS, DANIELSR, MARCOTTE, OSMAN, SRA, MIKEBELL,
	RICHARDSON, CROMWELL 
Subject: "F74/DDD RECEIVED THE FOLLOWING"... 

F74/DDD RECEIVED THE FOLLOWING OUTPUT TWICE AT 00:48:40 AND
00:48:45:

?INFO STOPCODE 'BIOBAS' AT 02-FEB-1988 00:48:40
F74, HARDWARE DDD, KL-1354, BASE 6722, F74-P035/C10-1 M02450
FRAME 9 TTY127 MFOOD[35406,365745] AT F74
RUNNING (UPLKT)BIONIK[23036,304122]
[CONTINUING STYSTEM]

FREMONT OPERATIONS/ ERICK
Received: from F29.Tymnet by D35.Tymnet; Mon, 15 Feb 88 19:01:09 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Mon, 15 Feb 88 18:54:35 PST
Return-path: <NIS.K/WATANABE@EMSTXS.Ontyme.Tymnet> 
From: NIS.K/WATANABE@EMSTXS.Ontyme.Tymnet 
Date: 15 FEB 88 18:28:34 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet,
	NIS.OGURA@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet, NIS.TC@Ontyme.Tymnet 
Message-id: M47138@Ontyme.Tymnet 
Subject: F74 PROBLEM 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/02/16  09:52 (JST)  
     
Attn      : Carl Baltrunas    
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Shuichi Inoue   (NIS.OSAKA) 
            Kuni Kamoi      (NIS.KAMOI) 
            Makoto Ogura    (NIS.OGURA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Kazuo Watanabe  (NIS.TC)    
     
Subject   : F74 PROBLEM  
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Dear Mr.Baltrunas,  
this is the first time for me to sent you a mail. First I'd like to   
introduce myself, my name is Kazuo Watanabe, Application System  
Dept. in NIS. I have some customers on host F74.  
     
By the way, the F74's problem was returned to our customers. They have
sent  files on to F74, and the sent files had a problem. About the timing  
of the problem, following 5 cases are reported.   
     
     
 JST    01-Feb-88   evening      (Username: MPPC) 
        09-Feb-88   evening      (Username: MPPC) 
        12-Feb-88   evening      (Username: MPPC) 
        12-Feb-88   evening      (Username: MFOOD)
        15-Feb-88   18:13        (Username: MPPC) 
     
     
Please investigate again, and let me know result. I will try to test, 
if necessary.  
     
Best regards.  
K/Watanabe
Received: from F29.Tymnet by D35.Tymnet; Sat, 27 Feb 88 22:24:13 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Sat, 27 Feb 88 22:07:22 PST
Return-path: <NIS.OHKURO@EMSTXS.Ontyme.Tymnet> 
From: NIS.OHKURO@EMSTXS.Ontyme.Tymnet 
Date: 27 FEB 88 21:54:44 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.NS@Ontyme.Tymnet,
	TYMPLN.HQ@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet 
Message-id: M49361@Ontyme.Tymnet 
Subject: Serious Problem on F74 
SeriousProblemonF74: 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/02/28  14:47 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : See  Distribution 
     
From      : Mike Tanabe     (NIS.HQ)    
     
Subject   : Serious Problem on F74 
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
     
1. We have been facing very serious problem of character change  
   ( including digit change ) of customers' data in TYMCOM-X
   service between input, storage and output since Dec. 87. 
     
2. We would like to ask you so urgent solution of the problem    
   as soon as possible.  
   Because we will be in a position to lose customers' reliability    
   by the nature of the problem.   
     
3. The following are blief history of communications and actions 
   between your and our people.    
     
     
        About F74 problem
        =================
     
        04 Jan  Makoto Ogura of NIS sent a report to Rick Daniels regarding
                - Some user program could not work normally.
                - I/O tools like BIONIK, SPOOL could not work normally.    
     
        04      Rick replied and mentioned that it came from a hardware problem 
                and was already repaired at that time. Also he informed the F74 
                has been running on a spare hardware after the middle of Dec 87.
     
        07      NIS reported to Rick about data garbling on F74 after solving   
                the hardware problem on 4th Jan.  
     
        13      Ken Bedell sent an OnTyme to Makoto Ogura and mentioned you
                were working for the problem.
     
        15      F74 went back to it's home hardware.   
     
        21      You mentioned that you caught something which you beleave  
                someone else caught the error. You found it from your trap 
                observation.  
     
        From 12nd Jan 88 to 28th Jan, NIS conducted 88 trials on F74 and 19
        trials ob D34 for your traps and checking, however, unfortunately, the  
        problem appeared a few times after your trap setting. The problem on our
        trials did not appeare after 20th Jan.    
     
        28      You suggested to stop making trials for F74 by NIS, and the trap
                on F74 was still continued to check by you. Also you mentioned  
                you guess the cause of the problem was overload of the Base.    
     
     
We would like to hear your response in earlier opportunity. 
     
Best regards.  
     
Mike Tanabe    
Senior Managing Diretor of NIS
     
     
     
     
     
Distribution   
============   
     
     
     
Neil Sullivan   (ENS.NS) 
Ron Bamberg     (TYMPLN.HQ)   
Ken BeDell      (ENS.K/BEDELL)
Rick Daniels    (IPC.R/DANIELS)    
Chris Chen      (ENS.C/CHEN)  
Lisa Heinzel    (ENS.L/HEINZEL)    
Jan Krivanec    (IPC.J/KRIVANEC)   
Kei Suzuki      (NIS.HQ) 
Kuni Kamoi      (NIS.KAMOI)   
Makoto Ogura    (NIS.OGURA)   
Shuichi Inoue   (NIS.OSAKA)
Received: from F29.Tymnet by D35.Tymnet; Sat, 27 Feb 88 23:24:11 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Sat, 27 Feb 88 23:07:21 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 27 FEB 88 22:27:42 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.TC@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M49362@Ontyme.Tymnet 
Subject: Again, F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/02/28  15:25 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
            Hideo Nakano    (NIS.TC)    
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : Again, F74 Problem
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
One month has been passed since we talked each other. How are you doing.   
     
Now, we are facing te F74 problem which is the same as we found on Jan., again. 
     
  - At the end of the last week, one of our customers called me and complained  
    about the problem. He mentioned that he had experienced to it on 6 files    
    during Feb. The garbled file were sent from San Jose and London HSA node    
    to the host.    
    Also, other users reported the problem during the last week. 
     
  - So, 26th Feb., we made 6 trials in the same manner which we conducted it in 
    Jan., and found 2 error files which were renamed as ERR.05 and ERR.06 for   
    your reference. Please check (OGURA:74)74.FIL for trials log.
     
  - I've reviewed the problem, and found that at the address which is replaced  
    string address - approx. 400 charas, you can find the same string image.    
    In other word, when the problem appeared, some string (maybe 12 charas)
    is overwritten at the address which is the original address pluse approx.   
    400 bytes. 
    The exact figure about the overwritten (including CR LF count) seemes to    
     be depending on it's file record length as follows. .  
                                        ... We can't understand why ...    
     
        Rec length      The figure 
     
                80           405   
               162           403   
     
    This manner is found in both ASCII/KANA files. And in one file, the relative
    figure is only one.  
     
    So, I also guess some problem appeared at the line interface portion in the 
    Base for F74, as you mentioned. Because I think in the host, the data  
    handling method for ASCII/KANA is different (ASCII: 5chars/word, KANA: 4chars    
    /word).    
     
  - You mentioned in your Ontyme at the end of Jan., the problem might come
    from the overload of the Base. 
     
    And now, in Japan, the problem is becoming very critical.    
     
        So, what is the counter plan of such overload problem,   
        who can take place it,
        who is responsible on it ? 
     
  - Please check your traps every day and let me know the usernames and time    
    if you find error log.    
    (We did not get the list of usernames and times for Jan's error, which 
     your trap found.)   
     
  - Please let me know the best way to solve this problem   
     
Best regards,  
Makoto
From: Carl A Baltrunas <Carl> 
Date: Mon, 29 Feb 88 14:50:41 PST 
To: Makoto Ogura <NIS.OGURA@Ontyme> 
Cc: Mike Tanabe <NIS.HQ@Ontyme>, Ken BeDell <ENS.K/BeDell@Ontyme>, Chris Chen
	<ENS.C/Chen@Ontyme>, Rick Daniels <IPC.R/Daniels@Ontyme>,
	<NIS.OSAKA@Ontyme>, <NIS.TC@Ontyme>, Monitor Group <Carl>, Osman Guven
	<Osman>, Joe Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: F74 Interim solution 


TO:     Makoto Ogura

Copies: Mike Tanabe
        Ken BeDell
        Rick Daniels

From:   Carl A Baltrunas


Re:     A temporary solution to F74's problem

================================================================

Makoto,
    So sorry for the delay in answering messages from NIS in the past
week.  We have been investigating the problem further and working on
a solution.

    The problem as we currently understand it is caused by a flaw in
the implementation of the high-speed BLOCK-IO input from the network
base to the PDP-10.  The KL-10 hardware uses special cache memory to
increase the processor speed by only reading physical memory when it
is absolutely necessary.  The network base writes BLOCK-IO input into
physical memory and then notifies the PDP-10 when data is available.
If portions of the BLOCK-IO buffer still exist in the hardware cache
the old memory contents are passed to the user instead of the new data
from physical memory.  This problem did not exist on the KI-10 cpu and
was apparently overlooked when the monitor was modified to run on the
newer KL-10 cpu.

    A final solution will have to be made as part of our next cycle
of development on the operating system, however we have worked out a
temporary solution of forcing the BLOCK-IO input buffers to be read
directly from physical memory.  We expect to finish the testing of
this fix this afternoon and will make it available for system F74 as
soon as possible.

    My only question at this time concerns what other PDP-10 systems
will we need to apply this fix.  On what other systems do you and your
customers use the BIONIC or BIONIK programs?

    In regards to the list of usernames found in our traps... we have
determined that the trap caught many more events than actually occured
and we could not depend on any of them.  What happenned was that the
trap detected an event when the base message passed BLOCK-IO to the
operating system because cache had not been updated, but by the time
the operating system passed the data to the user, the cache data was
correct.  This is why we thought we trapped an error, yet you and your
customers found no errors in late January.

    Now, we are sure the problem is due to cache references and have
disabled the trapping while we work on the solution.

    I will send you another message at the time we are ready to reload
system F74 with the "fix" version of the operating system.

/Carl
Received: from F29.Tymnet by D35.Tymnet; Tue, 1 Mar 88 3:04:25 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Mar 88 2:58:54 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 01 MAR 88 00:53:13 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M49728@Ontyme.Tymnet 
Subject: The Solution for F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/03/01  17:51 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Mike Tanabe     (NIS.HQ)    
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : The Solution for F74 Problem
            Ref A67304   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your working about the matter.    
     
Please let me know about followings.    
     
- AS you mentioned "the problem was apparently overlooked when the    
  monitor was modified to run on the newer KL-10 cpu", and I think it was  
  a sometime of the last autumn. So please let me know exact time at which 
  the newer KL-10 was installed and run for F74.  
     
- From the time when I mentioned above, the KL-10 had the problem.    
  However, we, and our customers, found it at the middle of 
  the last December. Why did it appeared suddenly at that time ? 
  Was any changes for environment of CPU, network made at that time ? 
  Or under what kind of user condition, was it appeared ?   
  What was the user's facter for it ?   
     
- At this moment, we and our customers make an access to F74 and D34. 
  However, I don't know D34 has such kind of problem to be solved.    
     
- Please let me know the exact time when the 'fix' version was/will be
  installed for F74. We will conduct test trials to make sure.   
     
- We must report to some customers about the problem.  
  So if possible, please let me know more details about followings.   
     
        1. the cause of the problem.... more detail    
        2. As I mentioned on above, user conditions which leeds the problem
        3. Your counter plan for the fixing. 
     
     
Again thank you for your support on the matter.   
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Wed, 2 Mar 88 0:38:17 PST
Return-path: <OPER@F29.Tymnet> 
From: OPER@F29.Tymnet 
Date: Wed, 2 Mar 88 0:37:49 PST 
To: OPER, BILLF, CARL, JMS, DANIELSR, OSMAN, SRA, RICHARDSON,
	FSC.R/DONAHUE@ONTYME 
Subject: "F29/JJJ APR: 1081 STOPCODE CRASH"... 

F29/JJJ APR:  1081 -- STOPCODE - CRASH
DATE:  03-01-88   DOWN:  1807   ANS:  1814
STOPCODE TYPE:  HALT   NAME:  IME   M NUMBER:  M02467
LOADED P035/D FROM DISK.  SYSTEM CHOSE FAST DSKCLN AT 1808.
MEMORY ONLINE: 1024K   BUSS MODE:  4   INTERLEAVE
CRASH FILE:  CRA005

   EXEC PARITY ERROR-HALT STOPCODE IME
   SYSTEM RESTARTED FROM LOC 147, BOOTS
   LOADED /D AND BROUGHT ITSELF
   BACK UP.

FREMONT OPERATIONS...MS
Received: from F29.Tymnet by D35.Tymnet; Wed, 2 Mar 88 3:04:15 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 2 Mar 88 2:47:25 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 02 MAR 88 02:35:21 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M50004@Ontyme.Tymnet 
Subject: F74, Urgent !! 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/03/02  19:33 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Mike Tanabe     (NIS.HQ)    
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74, Urgent !!    
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your support on the current problem.   
     
Now, my customer, whom I mentioned in my previous letter, is very irretating    
about no announcement of the fixing. Because, as I mentioned before, his   
bussiness was stopped by unstability of the host system. So he is waiting it    
and the situation is becoming more critical for NIS.   
So please let me know about the expected timing of the "fix" implementation
for F74. Or if you have already do it, please let me know the exact time & 
date of it.    
     
One more problem.....    
     
The customer, which I mentioned above, has sent a file from HSA node of San Jose
at 1st Mar (in JST). And the file had some strange pattern in it's format. 
The file is (HAL:74)SHAMK2.121, I have already copied for you it as (HAL:74)    
SHAMK2.NIS, and the file record format is 80 chars record + CR LF.    
In each record, the last 8 chars are for the 8 digit sequencial record number.  
However, 1837th and 1838th records are concatinated in one line, just as the    
1837th record, with 161 char + CR LF. If the CR LF were replaced by the current 
F74's problem, the record length should be 162. This is very strange.....  
     
Anyway, the customer was afraid that was indication of another problem.    
     
So please check it and let me know the cause of it came from the same root 
of the current F74 problem or it is another problem.   
     
Tomorrow morning, I must reply to the customer about the situation of the F74   
availability. So please send information by the next morning in JST.  
     
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Tue, 1 Mar 88 3:04:25 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Mar 88 2:58:54 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 01 MAR 88 00:53:13 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M49728@Ontyme.Tymnet 
Subject: The Solution for F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/03/01  17:51 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Mike Tanabe     (NIS.HQ)    
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : The Solution for F74 Problem
            Ref A67304   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your working about the matter.    
     
Please let me know about followings.    
     
- AS you mentioned "the problem was apparently overlooked when the    
  monitor was modified to run on the newer KL-10 cpu", and I think it was  
  a sometime of the last autumn. So please let me know exact time at which 
  the newer KL-10 was installed and run for F74.  
     
- From the time when I mentioned above, the KL-10 had the problem.    
  However, we, and our customers, found it at the middle of 
  the last December. Why did it appeared suddenly at that time ? 
  Was any changes for environment of CPU, network made at that time ? 
  Or under what kind of user condition, was it appeared ?   
  What was the user's facter for it ?   
     
- At this moment, we and our customers make an access to F74 and D34. 
  However, I don't know D34 has such kind of problem to be solved.    
     
- Please let me know the exact time when the 'fix' version was/will be
  installed for F74. We will conduct test trials to make sure.   
     
- We must report to some customers about the problem.  
  So if possible, please let me know more details about followings.   
     
        1. the cause of the problem.... more detail    
        2. As I mentioned on above, user conditions which leeds the problem
        3. Your counter plan for the fixing. 
     
     
Again thank you for your support on the matter.   
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Tue, 1 Mar 88 3:04:25 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Mar 88 2:58:54 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 01 MAR 88 00:53:13 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M49728@Ontyme.Tymnet 
Subject: The Solution for F74 Problem 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/03/01  17:51 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Mike Tanabe     (NIS.HQ)    
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : The Solution for F74 Problem
            Ref A67304   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your working about the matter.    
     
Please let me know about followings.    
     
- AS you mentioned "the problem was apparently overlooked when the    
  monitor was modified to run on the newer KL-10 cpu", and I think it was  
  a sometime of the last autumn. So please let me know exact time at which 
  the newer KL-10 was installed and run for F74.  
     
- From the time when I mentioned above, the KL-10 had the problem.    
  However, we, and our customers, found it at the middle of 
  the last December. Why did it appeared suddenly at that time ? 
  Was any changes for environment of CPU, network made at that time ? 
  Or under what kind of user condition, was it appeared ?   
  What was the user's facter for it ?   
     
- At this moment, we and our customers make an access to F74 and D34. 
  However, I don't know D34 has such kind of problem to be solved.    
     
- Please let me know the exact time when the 'fix' version was/will be
  installed for F74. We will conduct test trials to make sure.   
     
- We must report to some customers about the problem.  
  So if possible, please let me know more details about followings.   
     
        1. the cause of the problem.... more detail    
        2. As I mentioned on above, user conditions which leeds the problem
        3. Your counter plan for the fixing. 
     
     
Again thank you for your support on the matter.   
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Tue, 1 Mar 88 17:18:52 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Tue, 1 Mar 88 17:15:17 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 01 MAR 88 16:52:05 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M49967@Ontyme.Tymnet 
Subject: F74 Fixing Timing 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/03/02  09:47 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Mike Tanabe     (NIS.HQ)    
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74 Fixing Timing 
            Ref M49728   
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
I'm still waiting your reply, especially information about fixing time.    
     
Because, one of F74's customers, who is handling a rom data on the host and
the current situation is becoming very critical, has stopped to  
use the host and is waiting your fixing announcement to re-use the host.   
     
So please confirme the exact timing of the fixing, as soon as possible.    
     
Best regards,  
Makoto
Received: from F29.Tymnet by D35.Tymnet; Wed, 2 Mar 88 3:04:15 PST
Received: from EMSTXS.Ontyme.Tymnet by F29.Tymnet; Wed, 2 Mar 88 2:47:25 PST
Return-path: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
From: NIS.OGURA@EMSTXS.Ontyme.Tymnet 
Date: 02 MAR 88 02:35:21 
To: TXS.C/BALTRUNAS@EMSTXS.Ontyme.Tymnet 
Cc: TXS.C/BALTRUNAS@Ontyme.Tymnet, ENS.K/BEDELL@Ontyme.Tymnet,
	IPC.R/DANIELS@Ontyme.Tymnet, ENS.C/CHEN@Ontyme.Tymnet,
	ENS.L/HEINZEL@Ontyme.Tymnet, IPC.J/KRIVANEC@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet,
	NIS.OSAKA@Ontyme.Tymnet, NIS.OGURA@Ontyme.Tymnet 
Message-id: M50004@Ontyme.Tymnet 
Subject: F74, Urgent !! 

     
     
        Network Information Service          OnTyme  NIS.TC 
                                             Phone   [-81] (3) 551 6115    
                                             Fax     [-81] (3) 551 6355    
Date      : 88/03/02  19:33 (JST)  
     
Attn      : Carl Baltrunas  (TXS.C/BALTRUNAS)
     
Copies    : Ken BeDell      (ENS.K/BEDELL)   
            Rick Daniels    (IPC.R/DANIELS)  
            Chris Chen      (ENS.C/CHEN)
            Lisa Heinzel    (ENS.L/HEINZEL)  
            Jan Krivanec    (IPC.J/KRIVANEC) 
            Mike Tanabe     (NIS.HQ)    
            Kei Suzuki      (NIS.HQ)    
            Kuni Kamoi      (NIS.KAMOI) 
            Shuichi Inoue   (NIS.OSAKA) 
     
From      : Makoto Ogura    (NIS.OGURA) 
     
Subject   : F74, Urgent !!    
     
- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -  
     
Carl,
     
Thanks for your support on the current problem.   
     
Now, my customer, whom I mentioned in my previous letter, is very irretating    
about no announcement of the fixing. Because, as I mentioned before, his   
bussiness was stopped by unstability of the host system. So he is waiting it    
and the situation is becoming more critical for NIS.   
So please let me know about the expected timing of the "fix" implementation
for F74. Or if you have already do it, please let me know the exact time & 
date of it.    
     
One more problem.....    
     
The customer, which I mentioned above, has sent a file from HSA node of San Jose
at 1st Mar (in JST). And the file had some strange pattern in it's format. 
The file is (HAL:74)SHAMK2.121, I have already copied for you it as (HAL:74)    
SHAMK2.NIS, and the file record format is 80 chars record + CR LF.    
In each record, the last 8 chars are for the 8 digit sequencial record number.  
However, 1837th and 1838th records are concatinated in one line, just as the    
1837th record, with 161 char + CR LF. If the CR LF were replaced by the current 
F74's problem, the record length should be 162. This is very strange.....  
     
Anyway, the customer was afraid that was indication of another problem.    
     
So please check it and let me know the cause of it came from the same root 
of the current F74 problem or it is another problem.   
     
Tomorrow morning, I must reply to the customer about the situation of the F74   
availability. So please send information by the next morning in JST.  
     
Best regards,  
Makoto
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Mar 88 13:53:58 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.OGURA@Ontyme.Tymnet, Monitor Group <Carl>, Osman Guven <Osman>, Joe
	Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: Re: F74, Urgent !! 
In-reply-to: M50004@Ontyme.Tymnet of 02 MAR 88 02:35:21

To:    Makoto Ogura

CC:    Ken BeDell
       Rick Daniels
       Jan Krivanec
       Mike Tanabe
       Shuichi Inoue

From:  Carl Baltrunas

re:    F74 Patch installation

---------------------------------------------------------------

Makoto,

    Thank you for your patience.  We have concluded the testing of our
patch to the operating system and it was installed on system F74 this
morning.  Please let us know if there are any additional problems.

 -  System F74 was reloaded with the patched monitor F74-P035/D-1 on
    2-Mar-88 at 11:33 PST.

 -  There is some confusion with the meaning of "newer KL-10" cpu.  The
    KL-10 cpu is newer than the old KI-10 cpu which system 34 used to
    be when it was located in Cupertino.  System 74 has always been a
    KL-10 cpu.

 -  The problem you have been experiencing with BIONIC and BLOCK-IO has
    always existed on the KL-10 cpu.  However, since it has always been
    intermittant, it was never brought to our attention until December.
    It was thought to be a host-base interface problem due to a similar
    problem discovered 5 years ago on system D54.  Now, we understand
    that the problem on D54 was probably the same as F74.  The changes
    made to D54 5 years ago changed the timing of the memory references
    and the problem was never seen again.  This time, more research was
    done and the problem with the cache holding "old" information gives
    us the ability to duplicate the problem and provide a solution.

 -  Why the problem "suddenly" appeared is unknown.  Probably a subtle
    change in the operating system timing or the mix of applications on
    the system is the answer.  Also, it is clear that the problem may
    have been present but undetected since September when the customer
    base of NIS was moved from system 34 to 74.

 -  So that you may provide an explanation of the problem to your own
    customers, here is the technical detail about the problem we have
    found and corrected with our patch to the system.

     o  The BIONIC and BIONIK programs both use a special high-speed
	communications protocol which allows large amounts of character
	data to be passed between the host and the network base without
	causing the host to process each data byte.  This is BLOCK-IO.

     o  BLOCK-IO utilizes multi-ported memory on the PDP-10 to place the
	data directly into buffers which the PDP-10 then passes directly
	to the user application (BIONIC).

     o  On the model KI-10 cpu all memory references were buffered by the
	hardware, but retrieved from physical memory, so all BLOCK-IO data
	coming in from the base was passed to the user application.

     o  On the model KL-10 cpu all memory references are still buffered by
	the hardware, but a second high-speed cache retains data recently
	referenced by the cpu and references to data stored in those memory
	addresses are retrieved from the cache whenever possible.

     o  Normal host-base messages are uncached and are always retrieved from
	physical memory.   BLOCK-IO data buffers currently reside in part of
	the dynamic memory pool which is cached for fast data access.  Since
	the BLOCK-IO buffer headers were referenced by the cpu to setup the
	data transfer, these memory addresses and some nearby addresses were
	stored in the cache.  After the transfer the cpu references the data
	to pass it to the user application and instead of retrieving all of
	the data from physical memory, some data is retrieved from the cache.

     o  Cache is filled in 4-word chunks.  The format of the BLOCK-IO block
	is 6-words of header and 100-words of data.  The header is always on
	a 4-word boundary and thus the last 2 words of the header and the
	first 2 words for the data are in the cache at the same time.  The
	last word of the header is the byte count and is always referenced
	prior to the transfer (pulling all 4 words into the cache).  Thus,
	the first 2 words of the data buffer are retrieved from the cache
	instead of physical memory for most of the transfers.

     o  Most of the time the cache data containing the above 4-word chunk is
	flushed or overwritten with a different 4-word chunk of addresses.
	That is why this problem is not repeatable upon demand.  In the few
	instances when the job mix on the system does not flush this 4-word
	block, the user application receives 2 words of "old" data.  Each
	word contains 4 bytes and that is why we see 8 data bytes with bad
	information when the problem occurs.

     o  The temporary solution for the problem is to mark the part of the
	dynamic memory pool used by BLOCK-IO buffers as uncached.  In this
	way we will achieve the same reliability that we had with BLOCK-IO
	on the model KI-10 cpu.

     o  The long-term solution will be to separate the BLOCK-IO data buffers
	from the rest of the dynamic memory pool and place them in a separate
	pool of uncached memory.  This will be done during our next monitor
	development cycle.

 -  The explanation above should answer any of the questions you may have
    had about the problem.  We have installed the temporary fix to system
    F74 at this time.  If you wish that we install the temporary fix to
    system D34, please let me know in your next message.

 -  The file (HAL:74)SHAMK2.NIS appears to be a victim of this same problem.
    BIONIC and BIONIK translate occurances of CR or LF in the data stream to
    CR + LF.  Therefore, if each record is transmitted as 80 characters + CR
    then the data file will contain 80 characters + CR LF, and if the 8 bytes
    including the CR are overwritten, we will see 80 + 80 + 1 + CR LF which
    is confirmed by the 161 characters + CR LF see in the output file.

Thank you again for your help in researching the problem and in testing
the modifications made to track down the source of the problem.  Please
let me know if the problem occurs again.

Best regards,

/Carl
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Mar 88 13:53:58 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.OGURA@Ontyme.Tymnet, Monitor Group <Carl>, Osman Guven <Osman>, Joe
	Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: Re: F74, Urgent !! 
In-reply-to: M50004@Ontyme.Tymnet of 02 MAR 88 02:35:21

To:    Makoto Ogura

CC:    Ken BeDell
       Rick Daniels
       Jan Krivanec
       Mike Tanabe
       Shuichi Inoue

From:  Carl Baltrunas

re:    F74 Patch installation

---------------------------------------------------------------

Makoto,

    Thank you for your patience.  We have concluded the testing of our
patch to the operating system and it was installed on system F74 this
morning.  Please let us know if there are any additional problems.

 -  System F74 was reloaded with the patched monitor F74-P035/D-1 on
    2-Mar-88 at 11:33 PST.

 -  There is some confusion with the meaning of "newer KL-10" cpu.  The
    KL-10 cpu is newer than the old KI-10 cpu which system 34 used to
    be when it was located in Cupertino.  System 74 has always been a
    KL-10 cpu.

 -  The problem you have been experiencing with BIONIC and BLOCK-IO has
    always existed on the KL-10 cpu.  However, since it has always been
    intermittant, it was never brought to our attention until December.
    It was thought to be a host-base interface problem due to a similar
    problem discovered 5 years ago on system D54.  Now, we understand
    that the problem on D54 was probably the same as F74.  The changes
    made to D54 5 years ago changed the timing of the memory references
    and the problem was never seen again.  This time, more research was
    done and the problem with the cache holding "old" information gives
    us the ability to duplicate the problem and provide a solution.

 -  Why the problem "suddenly" appeared is unknown.  Probably a subtle
    change in the operating system timing or the mix of applications on
    the system is the answer.  Also, it is clear that the problem may
    have been present but undetected since September when the customer
    base of NIS was moved from system 34 to 74.

 -  So that you may provide an explanation of the problem to your own
    customers, here is the technical detail about the problem we have
    found and corrected with our patch to the system.

     o  The BIONIC and BIONIK programs both use a special high-speed
	communications protocol which allows large amounts of character
	data to be passed between the host and the network base without
	causing the host to process each data byte.  This is BLOCK-IO.

     o  BLOCK-IO utilizes multi-ported memory on the PDP-10 to place the
	data directly into buffers which the PDP-10 then passes directly
	to the user application (BIONIC).

     o  On the model KI-10 cpu all memory references were buffered by the
	hardware, but retrieved from physical memory, so all BLOCK-IO data
	coming in from the base was passed to the user application.

     o  On the model KL-10 cpu all memory references are still buffered by
	the hardware, but a second high-speed cache retains data recently
	referenced by the cpu and references to data stored in those memory
	addresses are retrieved from the cache whenever possible.

     o  Normal host-base messages are uncached and are always retrieved from
	physical memory.   BLOCK-IO data buffers currently reside in part of
	the dynamic memory pool which is cached for fast data access.  Since
	the BLOCK-IO buffer headers were referenced by the cpu to setup the
	data transfer, these memory addresses and some nearby addresses were
	stored in the cache.  After the transfer the cpu references the data
	to pass it to the user application and instead of retrieving all of
	the data from physical memory, some data is retrieved from the cache.

     o  Cache is filled in 4-word chunks.  The format of the BLOCK-IO block
	is 6-words of header and 100-words of data.  The header is always on
	a 4-word boundary and thus the last 2 words of the header and the
	first 2 words for the data are in the cache at the same time.  The
	last word of the header is the byte count and is always referenced
	prior to the transfer (pulling all 4 words into the cache).  Thus,
	the first 2 words of the data buffer are retrieved from the cache
	instead of physical memory for most of the transfers.

     o  Most of the time the cache data containing the above 4-word chunk is
	flushed or overwritten with a different 4-word chunk of addresses.
	That is why this problem is not repeatable upon demand.  In the few
	instances when the job mix on the system does not flush this 4-word
	block, the user application receives 2 words of "old" data.  Each
	word contains 4 bytes and that is why we see 8 data bytes with bad
	information when the problem occurs.

     o  The temporary solution for the problem is to mark the part of the
	dynamic memory pool used by BLOCK-IO buffers as uncached.  In this
	way we will achieve the same reliability that we had with BLOCK-IO
	on the model KI-10 cpu.

     o  The long-term solution will be to separate the BLOCK-IO data buffers
	from the rest of the dynamic memory pool and place them in a separate
	pool of uncached memory.  This will be done during our next monitor
	development cycle.

 -  The explanation above should answer any of the questions you may have
    had about the problem.  We have installed the temporary fix to system
    F74 at this time.  If you wish that we install the temporary fix to
    system D34, please let me know in your next message.

 -  The file (HAL:74)SHAMK2.NIS appears to be a victim of this same problem.
    BIONIC and BIONIK translate occurances of CR or LF in the data stream to
    CR + LF.  Therefore, if each record is transmitted as 80 characters + CR
    then the data file will contain 80 characters + CR LF, and if the 8 bytes
    including the CR are overwritten, we will see 80 + 80 + 1 + CR LF which
    is confirmed by the 161 characters + CR LF see in the output file.

Thank you again for your help in researching the problem and in testing
the modifications made to track down the source of the problem.  Please
let me know if the problem occurs again.

Best regards,

/Carl
From: Carl A Baltrunas <Carl> 
Date: Wed, 2 Mar 88 13:53:58 PST 
To: <NIS.OGURA@EMSTXS.Ontyme.Tymnet> 
Cc: ENS.K/BEDELL@Ontyme.Tymnet, IPC.R/DANIELS@Ontyme.Tymnet,
	ENS.C/CHEN@Ontyme.Tymnet, ENS.L/HEINZEL@Ontyme.Tymnet,
	IPC.J/KRIVANEC@Ontyme.Tymnet, NIS.HQ@Ontyme.Tymnet,
	NIS.HQ@Ontyme.Tymnet, NIS.KAMOI@Ontyme.Tymnet, NIS.OSAKA@Ontyme.Tymnet,
	NIS.OGURA@Ontyme.Tymnet, Monitor Group <Carl>, Osman Guven <Osman>, Joe
	Smith <JMS>, Craig Fletcher <fletcherc> 
Subject: Re: F74, Urgent !! 
In-reply-to: M50004@Ontyme.Tymnet of 02 MAR 88 02:35:21

To:    Makoto Ogura

CC:    Ken BeDell
       Rick Daniels
       Jan Krivanec
       Mike Tanabe
       Shuichi Inoue

From:  Carl Baltrunas

re:    F74 Patch installation

---------------------------------------------------------------

Makoto,

    Thank you for your patience.  We have concluded the testing of our
patch to the operating system and it was installed on system F74 this
morning.  Please let us know if there are any additional problems.

 -  System F74 was reloaded with the patched monitor F74-P035/D-1 on
    2-Mar-88 at 11:33 PST.

 -  There is some confusion with the meaning of "newer KL-10" cpu.  The
    KL-10 cpu is newer than the old KI-10 cpu which system 34 used to
    be when it was located in Cupertino.  System 74 has always been a
    KL-10 cpu.

 -  The problem you have been experiencing with BIONIC and BLOCK-IO has
    always existed on the KL-10 cpu.  However, since it has always been
    intermittant, it was never brought to our attention until December.
    It was thought to be a host-base interface problem due to a similar
    problem discovered 5 years ago on system D54.  Now, we understand
    that the problem on D54 was probably the same as F74.  The changes
    made to D54 5 years ago changed the timing of the memory references
    and the problem was never seen again.  This time, more research was
    done and the problem with the cache holding "old" information gives
    us the ability to duplicate the problem and provide a solution.

 -  Why the problem "suddenly" appeared is unknown.  Probably a subtle
    change in the operating system timing or the mix of applications on
    the system is the answer.  Also, it is clear that the problem may
    have been present but undetected since September when the customer
    base of NIS was moved from system 34 to 74.

 -  So that you may provide an explanation of the problem to your own
    customers, here is the technical detail about the problem we have
    found and corrected with our patch to the system.

     o  The BIONIC and BIONIK programs both use a special high-speed
	communications protocol which allows large amounts of character
	data to be passed between the host and the network base without
	causing the host to process each data byte.  This is BLOCK-IO.

     o  BLOCK-IO utilizes multi-ported memory on the PDP-10 to place the
	data directly into buffers which the PDP-10 then passes directly
	to the user application (BIONIC).

     o  On the model KI-10 cpu all memory references were buffered by the
	hardware, but retrieved from physical memory, so all BLOCK-IO data
	coming in from the base was passed to the user application.

     o  On the model KL-10 cpu all memory references are still buffered by
	the hardware, but a second high-speed cache retains data recently
	referenced by the cpu and references to data stored in those memory
	addresses are retrieved from the cache whenever possible.

     o  Normal host-base messages are uncached and are always retrieved from
	physical memory.   BLOCK-IO data buffers currently reside in part of
	the dynamic memory pool which is cached for fast data access.  Since
	the BLOCK-IO buffer headers were referenced by the cpu to setup the
	data transfer, these memory addresses and some nearby addresses were
	stored in the cache.  After the transfer the cpu references the data
	to pass it to the user application and instead of retrieving all of
	the data from physical memory, some data is retrieved from the cache.

     o  Cache is filled in 4-word chunks.  The format of the BLOCK-IO block
	is 6-words of header and 100-words of data.  The header is always on
	a 4-word boundary and thus the last 2 words of the header and the
	first 2 words for the data are in the cache at the same time.  The
	last word of the header is the byte count and is always referenced
	prior to the transfer (pulling all 4 words into the cache).  Thus,
	the first 2 words of the data buffer are retrieved from the cache
	instead of physical memory for most of the transfers.

     o  Most of the time the cache data containing the above 4-word chunk is
	flushed or overwritten with a different 4-word chunk of addresses.
	That is why this problem is not repeatable upon demand.  In the few
	instances when the job mix on the system does not flush this 4-word
	block, the user application receives 2 words of "old" data.  Each
	word contains 4 bytes and that is why we see 8 data bytes with bad
	information when the problem occurs.

     o  The temporary solution for the problem is to mark the part of the
	dynamic memory pool used by BLOCK-IO buffers as uncached.  In this
	way we will achieve the same reliability that we had with BLOCK-IO
	on the model KI-10 cpu.

     o  The long-term solution will be to separate the BLOCK-IO data buffers
	from the rest of the dynamic memory pool and place them in a separate
	pool of uncached memory.  This will be done during our next monitor
	development cycle.

 -  The explanation above should answer any of the questions you may have
    had about the problem.  We have installed the temporary fix to system
    F74 at this time.  If you wish that we install the temporary fix to
    system D34, please let me know in your next message.

 -  The file (HAL:74)SHAMK2.NIS appears to be a victim of this same problem.
    BIONIC and BIONIK translate occurances of CR or LF in the data stream to
    CR + LF.  Therefore, if each record is transmitted as 80 characters + CR
    then the data file will contain 80 characters + CR LF, and if the 8 bytes
    including the CR are overwritten, we will see 80 + 80 + 1 + CR LF which
    is confirmed by the 161 characters + CR LF see in the output file.

Thank you again for your help in researching the problem and in testing
the modifications made to track down the source of the problem.  Please
let me know if the problem occurs again.

Best regards,

/Carl
 l.