Received: from B39.Tymnet by D35.Tymnet; Fri, 16 Dec 88 10:15:57 PST
Received: from tymix.Tymnet by B39.Tymnet; Fri, 16 Dec 88 10:34:52 PST
Received: by tymix.Tymnet (5.51/4.7) id AA20176; Fri, 16 Dec 88 09:49:23 PST
Received: by antares.Tymnet.com (3.2/SMI-3.2) id AA16448; Fri, 16 Dec 88
	02:30:17 PST
Return-path: <cbaltru@antares> 
From: cbaltru@antares (carl baltrunas) 
Date: Fri, 16 Dec 88 02:30:17 PST 
To: carl@d35 
Message-id: <8812161030.AA16448@antares.Tymnet.com> 
Subject: "Path:
	antares!tymix!oliveb!pyramid!decwrl!labrea!agate!garnet.berkeley.edu!maniac"...
	

Path: antares!tymix!oliveb!pyramid!decwrl!labrea!agate!garnet.berkeley.edu!maniac
From: maniac@garnet.berkeley.edu (George W. Herbert)
Newsgroups: rec.humor
Subject: the _NEW_ purity test...
Message-ID: <18156@agate.BERKELEY.EDU>
Date: 11 Dec 88 06:09:32 GMT
Sender: usenet@agate.BERKELEY.EDU
Organization: University of California, Berkeley
Lines: 821
Summary:here it is...
Followup-To:maniac@garnet.berkely.edu
Distribution:usa

-----------(cut here)-----------(cut here)-----------(cut here)-----------

-----------------------------------------------------------------------------
                   Brought to you by the Anti-Celibacy League
-----------------------------------------------------------------------------
                           THE UNISEX, OMNISEXUAL
                           P U R I T Y    T E S T
-----------------------------------------------------------------------------
                         Version 4.0 (400 questions)
                               Final Release
                             November 30, 1988
-----------------------------------------------------------------------------
Table of Contents:
	Title and related information
	Table of Contents
	Disclaimer of Liability
	Genesis and History of this version of the Purity Test
	Instructions for Use and Administration of the test

	1. Platonic Relations
	2. Auto-erotica and Mono-sexualism
	3. Legislative Misfits and Other Ethical Questions
	4. Drugs
	5. Non Platonic Relations
	6. Non Primary Choice Relations
	7. Alternate Choices
	8. Group Sexual Relations
	9. Extracurricular, deviant conduct
	     9.1. Non sentient objects
	     9.2. Locality
	     9.3. Style

	Scoring
	Warranty Information
	Footnotes
-----------------------------------------------------------------------------
Public domain;  no copyright.   Murphy's law on sex: Love is a matter of
chemistry;  sex is a matter of physics.   Virginity can be cured.

It should  not be inferred  that the authors/contributors  have actually
performed any of the actions described herein.
-----------------------------------------------------------------------------
                                  N O T I C E
Disclaimer of Liability
The authors/contributors are in no way, shape or form responsible for the
consequences of any actions or situations inspired as a result of reading
this document.   If you perform  any actions contained herein,  it's YOUR
own fault, not ours.
Warning: Some of the activities contained herein may be hazardous to the
         physical well-being of you or your partner(s).   Always consult
	 a doctor before attempting such activities.
-----------------------------------------------------------------------------
            Join the fight against celibacy... Just say YES!!!
-----------------------------------------------------------------------------
Genesis/History:
ver   last revise #-of-q  revision site/contributors
 1      -   -      100     MIT Baker House/anon
 1      -   -1982  100     Ported to CMU by ps
 2    Spring-1983  247     CMU/jb, pd, kr, ps, ts, mt, et al
 3    13-Apr-1985  400     CMU/da, fa, tc, no, dt, sv, rz, et al
 4    30-Nov-1988  400     Anti-Celibacy League/el, jb, tc, cc, sz,
				mlk, dtt, md, gwh, mtk, et al
-----------------------------------------------------------------------------
Instructions for Use:
This is a fairly long test consisting of four hundred questions.  It starts out
tame  and  gets  progressively  worse,  or better, depending on your viewpoint.
There are many ways of taking this test. You  can,  of  course, be  anti-social
and hide yourself in your room and take this test all by yourself.  However, we
feel that the best way to utilize this test is to hold a Purity Test Party. All
you need is  one copy  of the test,  and a bunch of friends.   (Lots of writing
implements and paper would be useful too.) The person with the copy of the test
will  be  the  test  administrator;  s/he will read the  questions out loud and
everybody else will  write down their answers,  or at least keep track of their
total "yes" or "no" answers, whichever is easier.  We have no definite rules as
to whether the participants are required to reveal their answers, that is up to
the group to decide; however, each person's purity score should be made  common
knowledge (The person with the highest score gets to be giggled at for the rest
of his/her life).  This works  great at  parties and  lets everyone  know who's
easy  and who isn't,  so  you'll know  who to go  home with.  Don't  leave home
without it (the test, that is).

All questions in this test pertain to events that occured after your weaning
and infancy.  Anything that may have happened  before that time shall not be
considered.

The term  mutual  masturbation refers  to someone  masturbating  you AND/OR you
masturbating  someone else,  not  exclusively someone  masturbating you AND you
masturbating them.

The term  sexual activity refers  to sexual intercourse,  oral sex,  and mutual
masturbation, but not necking or petting.

The term sexual  intercourse refers  to the act of intercourse.   Orgasm is not
necessary, penetration counts.

Numbers marked in <>'s are footnote numbers.  The footnotes are located at the
end of the text.

We would now like to bring to your attention  that  there  is  no  passing  nor
failing  score.  Therefore, one really shouldn't worry too much about getting a
high score, even if you do get giggled at for the rest of your life.

                       --- ALL TECHNICALITIES COUNT ---
-----------------------------------------------------------------------------
For this section, if you are mostly a:
         - heterosexual,  then your partner, often referred to as someone
           or partner, is to be someone of the opposite gender.
         - homosexual, then your partner, often referred to as someone
           or partner, is to be someone of your own gender.
         - 50-50 confirmed bisexual, then your partner, often referred to
           someone or partner, is to be someone of either gender.

1. Platonic Relations

             Have you ever done any of the following:

   1. kissed a friend or stranger on his/her hands, head, or neck as a
      friendly gesture?
   2. held hands with someone?
   3. had a date?
   4. had a date which lasted past 1 a.m.?
   5. dated someone on a regular basis?
   6. picked someone up?
   7. been picked up?
   8. gone steady?
   9. slow danced?
  10. had the symptoms of Russian <1> fingers?
  11. had the symptoms of Roman <2> hands?
  12. shared sleeping accommodations with someone without anything steamy
      happening?
  13. given a back or neck rub or massage with no ulterior motive?
  14. used tickling as a pick-up, get-to-know-you-better routine?
  15. directly asked someone whom you were not going out with and had
      never gone out with if they were a virgin?
  16. used physical strength, physical power, or any physical prowess, or
      prowesslessness as a factor in pick-up, get-to-know-you-better
      routine?
  17. secretly lusted after someone without that person knowing?
  18. dropped subtle hints to someone whom you liked/loved/wanted, hoping
      that they would pick up on it?
-----------------------------------------------------------------------------
Although this section is termed Auto-erotica and mono-sexualism, a situation
      should still count even if you were with someone else at the time.  It
      was so named because these activities,  like the harp, are essentially
      solo events.

2. Auto-erotica and Mono-sexualism
 Have you ever:
  19. had an arousing dream? (Wet dreams and the like)
  20. been sexually aroused?
  21. verbally expressed obscenities? (uttered, yelled, muttered, etc.)
  22. sexually fantasized about your long-term instructor, mentor, or someone
      who is superior to you? (One day skydiving teachers, or two hour ski
      instructors and the like do not count.)
  23. sexually fantasized about your lawyer, doctor, nurse, psychiatrist or
      someone with whom you are having a professional relationship?
  24. sexually fantasized about someone you know personally but not closely?
  25. sexually fantasized about anyone and masturbated at the same time?
  26. read or bought pornographic periodicals?
  27. read sexually explicit literature?
  28. gone skinny dipping alone?
  29. made obscene phone calls?
  30. phoned up any recorded phone sex numbers (this includes answering
      machines with "phone sex" material)?
  31. phoned up any live phone sex numbers (this includes any human with a
      phone, not just 976-type pay per call numbers)?
  32. stuffed your bra if you are female, or stuffed your pants if you are
      male?
  33. shaved your pubic hair?
  34. shaved your pubic hair on a fairly regular basis?
  35. masturbated?
  36. masturbated to orgasm?
  37. masturbated to orgasm at least five times in one twenty-four hour period?
  38. masturbated to orgasm on a fairly regular basis of no less than once
      a fortnight?
  39. masturbated to orgasm where you could have been discovered?
      (In a crowd, in public, gym/dorm/barracks showers, movie theater, etc.)
  40. masturbated to orgasm out in the wild or in nature with no nearby
      civilization?
  41. masturbated to orgasm while reading either pornographic or sexually
      explicit materials?
  42. masturbated to orgasm while driving a land vehicle?
  43. masturbated to orgasm while on the phone? (No kinky interpretations
      of on the phone.)
  44. masturbated to orgasm while in a bathroom of the opposite sex?
  45. masturbated to orgasm while watching an R or X-rated show?
  46. seen any burlesque show? (Rocky Horror counts)
  47. been to a peep show?
  48. been to a private showing of a pornographic movie?
  49. been to a public showing of a pornographic movie?  (i.e. X-rated
      movie house)
  50. walked around in your dwelling in the nude?  (Must be a serious walk;
      five minutes of going around trying to find your undies after a shower
      doesn't make it.)
  51. walked around in a public or semi-public area with a top (shirt,
      T-shirt, etc) but no bottoms (pants, shorts, etc)? (Dorm hallways,
      lobby areas, etc. are acceptable; however locker rooms and bathrooms
      and such place where this behavior is accepted does not count.)
  52. bought blatantly sexual objects? (This means that if you buy a bottle
      of Coke  and you use it as a dildo, it really doesn't count. Think:
      specific design for function.)
  53. owned any erotic art pieces?
  54. sculpted erotic/obscene artworks in food (predominantly bananas,
      carrots, apples...)?
  55. eaten any erotic food items? (Chocolate tits, banana dicks, etc.)
  56. sculpted erotic-obscene artworks in soap, wood, or any other
      carvable material (not food)?
  57. made an X or R-rated snowman or snow-woman?
  58. tasted your own orgasmic liquids?
  59. inserted your finger into your rectum?
  60. used anal beads <3>?
  61. performed oral sex on yourself? (Yes, this is possible.)
  62. willingly urinated on the garments that you were wearing? (In other
      words: piss in your pants; wet yourself; had an accident)
  63. willingly urinated on any part of your body?
  64. willingly defecated on the garments that you were wearing? (In other
      words: shit in your pants; had a serious accident.)
  65. willingly defecated on yourself? (In other words: sick.  Also very
      difficult.)
-----------------------------------------------------------------------------
3. Legislative Misfits and Other Ethical Questions
 Have you ever:
  66. administered (or are you in the process of administering) any version
      of the Purity Test?
  67. taken Purity Tests of any versions more than 5 times?
  68. lied on any previous Purity Tests?
  69. exaggerated about any sexual experiences?
  70. broken your word, or any promise or vow that you had made?
  71. written graffiti?
  72. plagiarized?
  73. shoplifted?
  74. stolen?
  75. written a check that bounced?
  76. committed breaking and entering?
  77. told someone that you loved them when you did not?
  78. told someone that you loved them strictly because you wanted to have
      sex with them?
  79. sexually fantasized about someone else other than your partner while
      you were engaged in sexual activity?
  80. intentionally listened in to other people performing sexual
      activities without their knowledge?
  81. used alcohol to lower someone else's inhibitions for the intent of
      sexual activity?
  82. used drugs to lower someone else's inhibitions for the intent of
      sexual activity?
  83. forced or coerced someone into performing sexual activities with you?
  84. had dates with multiple people in the same night while not all
      of your dates were aware of your actions?
  85. gone steady with multiple people at the same time without all of
      the people aware of what you were doing?
  86. gone steady with multiple people at the same time with all of them
      aware of your actions?
  87. urinated on someone else intentionally? (Piss fights!)
  88. urinated in any container that was not originally designed for such
      purpose (excepting urinalysis incidents)?
  89. urinated anywhere not generally accepted for urination?  (For instance:
      in the kitchen sink, or in the trunk of the family car)
  90. urinated from a height greater than the fifth floor, or equivalent
      height, above ground level (e.g. buildings, bridges, the Grand Canyon)?
  91. defecated anywhere not generally accepted for defecation? (Camping or
      hiking trips in without bathroom/outhouse access do not count.)
  92. stored any human excreta in your refrigerator, oven, or any food
      storage/preparation appliance?
  93. stored evacuated human excreta anywhere else in your room, apartment,
      house, habitation, office, etc?
  94. entered a bathroom of the opposite sex while you were not accompanied
      by someone of the opposite sex and were not involved in a search and/or
      rescue mission at the time?
  95. mooned or goosed <4> someone?
  96. streaked, flashed, or otherwise partially or totally exposed yourself
      in public before (or after) an informal, unofficial gathering of
      people?
  97. streaked, flashed, or otherwise partially or totally exposed yourself
      in public before a formal (official) gathering of people? (Such as
      for a function, stage performance, charity dinner, etc.)
  98. been arrested for any sexual, drug, or alcohol related offense?
      (Picture taken and all that wonderful, free stuff.)
  99. received money or some favor in exchange for sexual activities?
 100. given money or some favor in exchange for sexual activities?
 101. thought you might unintentionally have gotten pregnant or might have
      unintentionally caused a pregnancy?
 102. had or given someone an unwanted pregnancy?
 103. had sex while either you or your partner, but not both, were under the
      age of consent for the state that you were in?
 104. given a "sympathy fuck"?
 105. initiated sexual activities with someone for the sake of those
      activities only?
 106. willingly committed incest?
 107. been involved in adultery?
 108. stolen the underwear of someone you know for a purpose other than
      that of a practical joke or to just annoy the person? (A bunch of guys
      invading the women's dorm on a mission of panty raids does not count.)
 109. intentionally taken the underwear of someone you didn't know?
-----------------------------------------------------------------------------
4. Drugs
 Have you ever:
 110. had alcohol?
 111. been intoxicated?
 112. vomited due to excessive alcohol?
 113. passed out due to excessive alcohol?
 114. forgotten events that occurred while you were drunk?
 115. smoked tobacco?
 116. chewed tobacco?
 117. bought controlled substances in violation of the law?
 118. sold or re-sold controlled substances in violation of the law?
 119. taken stimulants (other than caffeine)?
 120. taken depressants (other than alcohol)?
 121. inhaled nitrous oxide (NO ) not administered for anesthesia during
      dental care?             2
 122. intentionally inhaled any other gases or fumes for purposes other
      than medical?
 123. taken valium other than for medical purposes?
 124. smoked marijuana/sensemilia?
 125. smoked marijuana/sensemilia more than four times?
 126. eaten marijuana/sensemilia?
 127. eaten marijuana or sensemilia more than four times?
 128. taken opiate in any form?
 129. taken opiate in any form more than twice?
 130. used cocaine?
 131. used cocaine more than four times?
 132. used any drugs for any purpose other than medical?
 133. used any one drug for any purpose other than medical more than twice?
 134. used PCP?
 135. used PCP more than twice?
 136. used lysergic acid diethylamide (LSD), peyote, or psilocybin?
 137. used LSD, peyote, or psilocybin more than twice?
 138. used LSD more than six times?
 139. deliberately injured yourself so as to obtain medication?
 140. played any games in which there was a mystery as to who would be
      getting drugs and who wouldn't, yet everybody plays in it? (e.g.
      Who's got the pill, where half the cups (of soda) would have LSD in
      it and the other half wouldn't and everybody picks a cup and drinks
      it and wonders who gets lucky.)1. had sexual intercourse while under the influence of cocaine?
 142. had sexual intercourse while under the influence of marijuana or
      sensemilia?
 143. had sexual intercourse while under the influence of LSD, peyote,
      or psilocybin?
-----------------------------------------------------------------------------
For this section, it you are mostly a:
         - heterosexual, then your partner, often referred to by the words
           someone or partner, is to be someone of the  opposite gender.
         - homosexual, then your partner, often referred to by the words
           someone or partner, is to be someone of your own gender.
         - 50-50 confirmed bisexual, then your partner, often referred to by
           the words someone or partner, is to be someone of either gender.

5. Non Platonic
 Have you ever:
 144. propositioned someone for necking or petting?
 145. propositioned someone for sexual activities?
 146. pinched or patted someone else's buttocks?
 147. french kissed?
 148. been kissed below the neck but not including arms or hands?
 149. kissed someone else below the neck but not including arms or hands?
 150. necked?
 151. petted above the waist?
 152. petted below the waist?
 153. kissed on the first date?
 154. necked on the first date?
 155. petted above the waist on the first date?
 156. petted below the waist on the first date?
 157. given a hickey?
 158. received a hickey?
 159. fondled or stroked someone else's clothed legs?
 160. fondled or stroked someone else's bare legs?
 161. fondled or stroked someone else's chest/torso?
 162. had your chest/torso fondled or stroked?
 163. been involved with pelvic thrusting while fully clothed?
 164. had your fingers licked or sucked?
 165. had your ear or ear region licked, breathed upon, sucked, or nibbled?
 166. licked, breathed on, sucked, or nibbled an ear or ear region?
 167. licked or sucked someone else's finger(s)?
 168. fondled someone who was asleep?
 169. given a back massage with ulterior motives?
 170. given a back massage that led to something steamier?
 171. seen someone else completely nude while the person was under good
      lighting conditions?
 172. been seen completely nude under good lighting conditions by
      someone else?
 173. been in someone's company while both of you were completely nude?
 174. bathed or showered with someone?
 175. let someone else wash you while you were perfectly capable of doing
      it yourself. (This means that it doesn't count if you were in the
      hospital with two broken arms and the nurse washed you, no matter
      how cute she is.)
 176. gone skinny dipping in mixed company?
 177. stroked or fondled a woman's clothed breast(s), or, if you are
      female, had your clothed breast(s) stroked or fondled?
 178. stroked or fondled a woman's bare breast(s), or, if you are female,
      had your bare breast(s) stroked of fondled?
 179. licked, sucked, or nibbled on someone else's nipple(s)? (Either one at
      a time, or, if you're really clever, both at the same time.)
 180. had your nipple(s) licked, sucked, or nibbled upon?
 181. petted, stroked, fondled, or otherwise handled someone else's  covered
      genitals?
 182. had your covered genitals petted, stroked, fondled, or otherwise
      handled?
 183. petted, stroked, fondled, or otherwise handled someone else's bare
      genitals?
 184. had your bare genitals petted, stroked, fondled, or otherwise  handled?
 185. had an orgasm while petting?
 186. given your partner an orgasm while petting?
 187. given or received finger scratch marks during sexual activity?
 188. performed oral sex?
 189. received oral sex?
 190. done sixty-nine <5>?
 191. performed mutual masturbation?
 192. had sexual intercourse?
 193. had sexual intercourse on the first date?
 194. had sexual intercourse without the use of birth control devices?
      (Rhythm, prayer, and hope methods do not count.)
 195. had sexual intercourse with a virgin? (Not yourself.)
 196. had sexual intercourse with a religious officiary. (Priest, nun,
      mother-superior, cardinal, pope, etc.)
-----------------------------------------------------------------------------
This section of the test deals with whether you have done things with people
      with whom  you may not  be altogether comfortable;  therefore in this
      section of the test, if you are mostly a:
         - heterosexual, then your partner, often referred to as someone or
           partner,  is to be someone of your own gender.
         - homosexual, then your partner, often referred to as someone or
           partner, is someone of the opposite gender.
         - 50-50 confirmed bisexual, then your partner, often referred to as
           someone or partner, is to be someone of either gender.

6. Non Primary Choice Relations
 Have you ever:
 197. held hands or otherwise displayed public affection?
 198. kissed someone on the lips?
 199. french kissed someone?
 200. necked?
 201. petted?
 202. received manual sex?
 203. given manual sex?
 204. received oral sex?
 205. given oral sex
 206. had sexual intercourse?
 207. had anal sex? (The use of fingers or any phallic objects in this
      case would also count.)
 208. done 69?
 209. propositioned someone for sexual activity?
 210. yielded willingly to a proposition from someone for sexual activity?
 211. been a participant in a who's-physically-better-equipped
      verification contest? (Contestants must be of same gender;
      spectators, judges, umpires, and verifiers may be of different
      gender.)
 212. gave money or favors for sexual activity?
 213. received money or favors for sexual activity?
 214. fondled someone who was asleep?
 215. attempted to seduce someone?
 216. allowed yourself to be seduced?
 217. had an orgasm while petting?
 218. gave your partner an orgasm while petting?
 219. had sexual activities with more than 10 people?
 220. stroked or fondled someone else's clothed legs?
 221. stroked or fondled someone else's bare legs?
 222. stroked or fondled someone else's clothed chest/torso region?
 223. stroked or fondled someone else's bare chest/torso region?
 224. stroked, fondled, or otherwise handled someone else's clothed genitals?
 225. stroked, fondled, or otherwise handled someone else's bare genitals?
 226. been in a menage-a-trois of people of the same sex?
-----------------------------------------------------------------------------
For  any  of the questions in this section, a yes answer is in order if the
      action/orientation is something that you do as an alternative to other
      sexual gratifications or as an aid and/or in conjunction with other
      means of sexual gratification, or in other words, have you done it in
      a serious basis? Trying it once to see what it's like does not count.

7. Alternate Choices
 Have you ever:
 227. been decidedly heterosexual?
 228. been decidedly homosexual?
 229. been decidedly bisexual?
 230. practiced bestiality <6>?
 231. practiced transvestism?
 232. practiced sadism <7>?
 233. practiced masochism <8>?
 234. practiced bondage?
 235. practiced domination?
 236. practiced submission?
 237. practiced sodomy <9>?
 238. practiced cocrophilia <10>?
 239. practiced frotteurism <11>?
 240. practiced klismaphilia <12>?
 241. practiced necrophilia <13>?
 242. practiced mysophilia <14>?
 243. practiced scoptophilia <15>?
 244. practiced urophilia <16>?
 245. owned a collection of underwear not your own?
 246. had a foot fetish to any degree?
 247. been a voyeur <17>?
 248. been an exhibitionist?
-----------------------------------------------------------------------------
This  section relates to what you have or have not done.  Accordingly, the
      group of people we are speaking of is of both genders.  In questions
      where groups of people are concerned, there must  be  at  least  one
      person in the group who is of the opposite gender.
8. Group Sexual Relations
 Have you ever:
 249. listened to dirty jokes in mixed company?
 250. told dirty jokes in mixed company?
 251. discussed masturbation? (Bringing up the topic of masturbation
      during Purity Testing does not cut it as "discussing masturbation".)
 252. played a game which may require you or others to disrobe?
 253. played a game which may require you or others to perform an
      action on another participant?
 254. been in intimate contact with more than one person at the same time
      while all of you were nude?
 255. had sexual intercourse with more than 10 people (not necessarily at
      the same time)?
 256. had sexual intercourse with more than 1 person in a 24 hour period?
 257. had sexual intercourse with persons of both genders in a 24 hour period?
 258. been in a bisexual/heterosexual menage-a-trois?
 259. engaged in sexual activities with a person and his/her parent?
 260. engaged in sexual activities, necking, or petting with a person and
      his/her sibling?
 261. been involved in a two (or more) in one?
 262. been involved in a gang bang?
 263. been in a circle jerk?
 264. been in a 69 circle?
 265. been to an oil party (cooking, baby, Wesson)?
 266. participated in a heterosexual orgy or been involved in group sex?
      (Four people or more; partners must be exchanged.)
 267. participated in a bisexual orgy or group sex? (Four people or more;
      partners must be exchanged.)
 268. participated in a fuck-a-thon?  (Where the object is to see how
      many times you can do it in a certain amount of time.)
-----------------------------------------------------------------------------
This  section  measures  your kinkiness. Therefore, the questions apply to
      both actions and events occurring while you were alone  as  well  as
      when you were with someone else.
9. Extracurricular, deviant conduct
9.1. Non sentient objects
 Have you ever:
 269. used a bowling pin, Coke bottle, or something along those general
      shapes for sexual purposes?
 270. masturbated using the aid of food?
 271. eaten that food after masturbation?
 272. eaten a lab dissection?
 273. inserted food into yours or someone else's anus?
 274. eaten that food after it was extracted/evacuated from yours or
      someone else's anus?
 275. received an enema for a purpose other than that of medical?
 276. used a basket, garbage can, or any other comparable sized receptacle
      for target practice masturbation?
 277. used a mechanical hand-held device in aiding or replacing
      masturbation? (Vibrator, massager, Dust-Buster, etc.)
 278. used a feather or any other device for the purpose of tickling during
      sexual activity?
 279. used ice for sexual purposes?
 280. used whipped cream for sexual purposes?
 281. used hot/melted wax for sexual purposes?
 282. placed anything edible on your partner's body and then eaten it?
 283. used any household syrup, sandwich spreading, oil, salad dressing,
      or any like substances for sexual purposes?
 284. used ropes, chains, cuffs or other similar device for bondage?
 285. used a whip, chain, cat-o-nine-tails, or something similar for pain?
 286. worn a leather, spandex or any other similar suit for sexual purposes?
 287. used an inflatable doll for sexual purposes?
 288. humped an inanimate object like a pillow, (dinner) liver, hole in
      the wall, sausages, bananas, etc?
 289. purchased sexually related objects throught the mail (not periodicals,
      but masks, suits, and other types of toys)?
 290. performed sexual activities with a dead person?
 291. inserted a small animal or creature (alive or dead) into your rectum?
 292. performed sexual activities with your (dead) dinner animal or creature?
 293. attempted to perform sexual activities with a live animal, but failed?
 294. performed sexual activities with a smallish animal?  (Dogs, cats,
      rabbits, lab rats, gerbils, etc.)
 295. performed sexual activities with a domesticated farm animal? (Cow,
      pig, chicken, sheep, etc.)
 296. mutilated any living animal or creature for your pleasures?
 297. had sexual intercourse with a live animal? (Any size.) [These three
      questions differ from those above in that ones above measure your
      variation in animal choice, and the questions down here measure what
      you do with the animals.]
 298. received oral sex from a live animal? (Any size.)
 299. given oral sex to a live animal? (Any size.)
 300. performed sexual activities with a single type of animal (alive or
      dead) more than once?
 301. had sexual activities with more than one kind of animal (alive or dead)?
 302. cross dressed in the undergarments of the opposite sex for sexual
      activities? (This means that school plays, initiations, and the such
      don't count.)
 303. stuffed your pants or bra while you were cross-dressed for sexual
      activities?
 304. had your head inserted into a urinal or toilet bowl willingly?
      (Doing this in a pristine, show-room model does not count.)
 305. worn a piece of lower-body underwear on your head? (Panties,
      jock-strap, etc.)
 306. eaten, sucked, licked, nibbled, or otherwise inserted unwashed, used
      crotch piece of underwear into your mouth while it was not being worn?
 307. deliberately sniffed or smelled the crotch piece of unwashed, used
      underwear while it was not being worn?
 308. played in or with shit?
 309. worn or used a condom, or any feminine hygiene contraption that has
      already been used?
-----------------------------------------------------------------------------
This  section  tries  to  figure  out how many places you have done it. It
      applies only to those situations in which you were with someone else.

9.2. Locality
 Have you ever:
 310. necked or petted in a place of religion? (Church, temple, altar,
      Grand Holy Cabbage Head Patch, etc.)
 311. engaged in sexual activities in a place of religion?
 312. necked or petted in a place of the dead? (Morgue, mortuary, etc.)
 313. engaged in sexual activities in a place of the dead?
 314. necked or petted in a contraption of the dead? (Coffin, hearse, etc.)
 315. engaged in sexual activities in a contraption of the dead?
 316. necked or petted in any moderately sized, road based vehicle not in
      excess of 30,000 pounds net unladen gross weight?
 317. engaged in sexual activities in any moderately sized, road based
      vehicle not in excess of 30,000 pounds net unladen gross weight?
 318. necked or petted in a road based vehicle in excess of 30,000 pounds
      net unladen gross weight? (Truck, tank, armored vehicle, etc.)
 319. engaged in sexual activities in a road based vehicle in excess of
      30,000 pounds net unladen gross weight?
 320. engaged in sexual activities in a land based, non road dependant
      vehicle? (Train, subway, roller-coaster, etc.)
 321. necked, petted, or engaged in sexual activities in a manually powered
      water based vehicle?  (Row boat, surfboard, floating bathtub, etc.
      In order for this question to be answered affirmatively, the vehicle
      must be in water at the time of the action.)
 322. necked, petted, or engaged in sexual activities in a non-manually
      powered water vehicle (PT boat, Yacht, sailboat, Cruise ship,
      aircraft carrier, nuclear submarine, battleship, etc.)
 323. necked, petted, or engaged in sexual activities in an academic arena
      (classroom, auditorium, stage, cafeteria, principal's office, etc.)?
 324. necked, petted, or engaged in sexual activities in an aircraft or
      spacecraft?  (Airplane, helicopter, hovercraft, balloon, zeppelin,
      flying carpet, flying saucer, etc.)
 325. performed sexual activities in a household room other than a bedroom?
 326. performed sexual activities on the floor (but not the roof)?
 327. performed sexual activities on any furniture that is indoors but is
      not predominantly used for sitting, or to be used as a table/desk?
      (i.e. non-flat surfaces such as the kitchen sink)
 328. performed sexual activities in a telephone booth, voting booth,
      automatic photograph takers, or any such small, non-moving enclosure
      that was not designed for such activities?
 329. performed sexual activities in an elevator, people-mover, escalator,
      or any other similar people moving device (ski lift, etc.)?
 330. performed sexual activities in a tree but not in a tree house or
      similar structure?
 331. performed sexual activites on the roof of a building taller than 5 floors?
 332. performed sexual activities inside any secluded, outdoor natural
      structure or enclosure? (cave, inside hedge, etc.)
 333. performed sexual activities in the snow? (Spring thaw acceptable.)
 334. performed sexual activities in a place where the air temperature
      was below the freezing point of water? (In a deep freeze, etc.)
 335. performed sexual activities where you could have been discovered?
 336. performed sexual activities in a body of water or water based
      environment? (bath-tub, hot tub, shower, running water (as in
      waterfalls, tropical, torrential downpour, monsoons, etc.), swimming
      pool, pond, lake lagoon, sea, ocean, etc.)?
 337. performed sexual activites in a desert or other arid, secluded area?
      (not in a house in the desert, but actually outside in the sand.)
 338. performed sexual activities in a bathroom of the opposite sex?
-----------------------------------------------------------------------------
9.3. Style
 Have you ever:
 339. watched someone else masturbate (not on video, has to be live)?
 340. had an orgasm on somebody?
 341. had an orgasm in somebody if you are a male or had someone orgasm in
      you if you are a female?
 342. used a penis as a leash or bludgeoning device?
 343. used oxygen deprivation for sexual enhancement? (Strangulation. sounds
      fun, eh?) (Nitrous oxide doesn't count.)
 344. willingly made video tapes or had pictures taken while engaged in
      sexual activities?
 345. willingly made audio recordings of sexual activities?
 346. talked dirty while performing sexual activities?
 347. intentionally made more noise than necessary while engaged in sexual
      activities so as to put on a good show for whoever may be listening in?
 348. had a family pet or domesticated animal walk over you or your
      partner while performing sexual activities?
 349. ignored any general emergency that arose while you were deeply
      engaged in sexual activities?  (Such as: house on fire, flash flood,
      private plane crash-lands in your dwelling...)
 350. engaged in sexual activities with someone who is 10 years older or
      younger than yourself?
 351. taken nude pictures of someone else?
 352. had nude pictures of you taken (this includes taking nude pictures of
      yourself in a mirror)?
 353. been involved in breast fucking?  (aka "The Hawaiian Muscle Fuck")
 354. participated in fist-fucking?
 355. had sexual intercourse continuously for more than three hours?
 356. been bruised while engaged in sexual activities?
 357. bruised someone else while engaged in sexual activities?
 358. been injured while engaged in sexual activities?
 359. orgasmed more than three times in one session of sexual intercourse?
 360. disturbed other people by making excessive noise while you and your
      partner were engaged in sexual activities?
 361. engaged in sexual activities while in formal costume (prom dress,
      wedding dress, tuxedo, ballroom gown, etc.)?
 362. had sexual intercourse doggie fashion?
 363. had sexual intercourse in the female superior position?
 364. had sexual intercourse sitting up or standing up?
 365. done vertical 69 (one person standing, the other hanging upside down)?
 366. had sexual intercourse upside-down (hanging from the cieling like bats,
      standing on your heads, etc.)?
 367. gone through multiple sexual positions without the need for re-entry?
 368. fell asleep while engaged in sexual activities?
 369. woken up to someone performing sexual activities with you?
 370. given or received a hickey on your upper, inner thigh?
 371. been on the receiving end of anal sex?
 372. been on the ramming end of anal sex?
 373. had sexual intercourse more than 10 times with 1 person?
 374. had sexual intercourse more than 5 times in a 24 hour period?
 375. had sexual intercourse more than 10 times in a 24 hour period?
 376. engaged in sexual activities while someone other than your partner
      was watching?
 377. engaged in sexual activities while one or both of you were playing
      a musical instrument, hacked, watched television, read, drawn or in
      other words were preoccupied with something other than sex and lust?
 378. engaged in oral sex after intercourse without washing or douching?
 379. kissed your partner on the lips after oral sex without brushing
      teeth, nor washing/gargling/rinsing out mouth?
 380. intentionally inflicted pain while performing sexual activities?
 381. drawn blood by biting while performing sexual activities? (Hickeys
      do not count as having drawn blood.)
 382. been involved in cunnilingus <18> during the woman's period?
 383. had sexual intercourse during the woman's period?
 384. foot masturbated someone?
 385. been foot masturbated?
 386. tongue bathed someone?
 387. been tongue bathed?
 388. licked or sucked on someone else's feet and/or toes?
 389. had your feet and/or toes licked or sucked by someone else?
 390. licked someone's anus?
 391. licked someone's anus while they were defecating?
 392. performed oral sex while the person was urinating?
 393. drunk your own urine?
 394. tasted or drunk someone else's urine?
 395. drunk human blood?
 396. tasted someone else's nasal mucous?
 397. been involved in golden showers?
 398. swallowed your partner's orgasmic secretions?
 399. used the Purity Test as a checklist of things you could do?
 400. participated in Purity Testing with an ulterior motive?
-----------------------------------------------------------------------------
Scoring

Congratulations,  you  are now the proud owner of a sheet of paper with lots of
itty-bitty answers to the Purity Test. Sworn to excellence of  workmanship,  we
now  give  you  directions  on  how  to  calculate your Purity score. There are
several methods; the calculator method works best. Of the easier ways: count up
all your "no" answers, then  divide  this  number  by  four.  This  gives  your
percentage  purity;  the  higher the number, the more pure you are; in the same
vein, the lower the  score,  the  more  of  a  sleaze-bag  you  are.  For  your
reference, we include calculator directions:
     For people with real calculators (HP):
               <#no ans.> [ENTER] 4 /
     For people with other (dinky) calculators:
               <#no ans.> / 4 =
-----------------------------------------------------------------------------
Warranty Information

We  hope that you have enjoyed this test. It does not come with a warranty, nor
does it guarantee that  it will get you laid or make  you somehow better in bed
or the haystack.

The makers of this test are not responsible  for  any  liabilities  or  damages
resulting  from  this  test, including but not limited to, paternity suits.

Propagate (this test) at will, even  without written  permission.

Not  recommended  for  children under twelve. Parental guidance discouraged and
frowned upon. Pencils, additional  paper,  and  batteries  not  included.  Some
assembly may be required.
-----------------------------------------------------------------------------
Drive carefully; 90% of the people in the world are caused by accidents.

The above is a public service announcement of this institution.
-----------------------------------------------------------------------------
Footnotes:

<1>  Rushin' fingers.
<2>  Roamin' hands.
<3>  They  come as a set of several balls strung together. These balls are
        inserted into the rectum of one of the participants before sex, and
        are yanked out, usually by the partner, during orgasm. I think it's
        supposed to feel good or something like that.
<4>  Goose: opposite of moon.
<5>  You must be at least 48 inches tall to be allowed on this ride.
<6>  Avec les animaux.
<7>  For clarification: a sadist likes to hurt others.
<8>  For clarification: a masochist likes to receive pain.
<9>  Anal sex.
<10> Marked interest in excrement; esp. use of feces or filth for sexual
        excitement.--Webster's Third New International Dictionary.
     An obsession with feces, varied in expression; it may involve the
        sight and sound of a person defecating.--The Book of Sex Lists,
        compiled by A. B. Gerber.  Ballantine Books, New York.  1981.
<11> 3: Masturbation by rubbing against another person.--Webster's.
     The need to rub against another stranger, especially in a tightly
        packed crowd.--Sex Lists.
<12> A dependency on being given an enema.--Sex Lists.
<13> Fascination  with the dead; specif: obsession with and usu. erotic
        attraction toward and stimulation by corpses typically evidenced by
        overt acts (as copulation with a corpse.)--Webster's.
<14> Abnormal attraction to filth.--Webster's.
     A dependency on something soiled or filthy, such as sweaty underwear
        or used menstrual pads.--Sex Lists.
<15> A desire to look at sexually stimulating scenes esp. as a substitute
        for actual sexual participation that constitutes a partial or
        component instinct often sublimated (as in a desire for
        learning).--Webster's.
     A dependency on looking at sexual organs and watching sexual activity
        openly.  It is not surreptitious as in voyeurism.--Sex Lists.
<16> Being dependently responsive to the smell or taste of urine or the
        sight and sound of someone urinating.--Sex Lists.
<17> 1: One whose sexual desire is concentrated upon seeing sex organs
        and sexual acts -- called also peeping tom.
     2: An unduly prying observer usu. in search of sordid acts or
        scandalous sights.--Webster's.
     Being dependently responsive to the risk of being caught while
        illicitly peering at another person or couple undressing or
        engaged in sexual activity.--Sex Lists.
<18> Vaginal oral sex.
 r EÆ