; 23-Mar-88  network routing map for the TXS lab
; Locations: South Bay Center (building D), and 135 Nicholson Lane
; Nodes: 552A, 554A, 2770, 6657, 6760, FOON, FRED
; Hosts: 14,15,16,17,62,95,118,897,930,934,4117,4284,4511,4525,4681
; Real hosts:
;   14 is KS2020-B on node 6760
;   17 is KS2020-A on node 6657
;  897 is VAX-11/750 on node 554A, visible to TYMNET on node 2770
;  930 is F3#5 on node FOON, visible to TYMNET on node 6760
;  934 is F3#6 on node FOON, visible to TYMNET on node 6760
; XRAY hosts:
;  XRAY:3984 is XRAY:ST@2770 (Tymnet interface in South Bay Center)
;  XRAY:4511 is XRAY:ST@6657 (X17's base)
;  XRAY:4681 is XRAY:ST@6760 (X14's base)
;  XRAY:5950 is on ND5566, neighbor to node 2770
;  XRAY:3732 is on ND5416, neighbor to nodes 6657 and 6760
;  XRAY:3734 is no ND5561, neighbor to nodes 6667 and 6760
; Alias hosts:
;    15 is on 6760 as alias for host 17
;    16 is on 6657 as alias for host 14
;    62 is on 6657 as alias for host 897
;  4117 is on 2770 as alias for TR@FRED, 10 hardwire + 2 modems
;  4284 is on 2770 as alias for TR@2770, 4 hardwire lines
;  4525 is on 2770 as alias for TR@554A, 4 hardwire lines (or TR@NICK)

.macro	ROUTE
		;There are 8 nodes and 5 real hosts plus TYMNET.
		;Each node needs 7 NPATH and 6 HPATH statements.

	NODE	552A			; X.25 to whatever in Nicholson
	  NPATH  554A,NICK
	  NPATH  2770,NICK
	  NPATH  6657,NICK
	  NPATH  6760,NICK
	  NPATH  NICK,NICK		; DRV11 #3
	  NPATH  FOON,NICK
	  NPATH  FRED,NICK
	 HPATH  TYMNET,NICK
	  HPATH  14,NICK		; KS on 6760
	  HPATH  17,NICK		; KS on 6657
	  HPATH  897,NICK		; VAX-11/750 in South Bay
	  HPATH  930,NICK		; F3 on FOON
	  HPATH  934,NICK		; F3 on FOON


	NODE	554A			; For VAX/750 in South Bay Center
	  NPATH  552A,FRED
	  NPATH  2770,FRED
	  NPATH  6657,FRED
	  NPATH  6760,FRED
	  NPATH  FOON,FRED
	  NPATH  FRED,FRED		; DRV11 #1
	  NPATH  NICK,FRED
	 HPATH  TYMNET,FRED
	  HPATH  14,FRED		; KS on 6760
	  HPATH  17,FRED		; KS on 6657
	  HPATH  897,*			; DUV11 #1 to VAX-11/750
	  HPATH  930,FRED		; F3 on FOON
	  HPATH  934,FRED		; F3 on FOON


        NODE	2770			; MDC link to TYMNET 5566:5950
	  NPATH  552A,FRED
	  NPATH  554A,FRED
	  NPATH  6657,FRED
	  NPATH  6760,FRED
	  NPATH  FOON,FRED
	  NPATH  FRED,FRED		; DRV11 #1
	  NPATH  NICK,FRED
	 HPATH  TYMNET,*,FRED		; DUV11 #1, default host
	  HPATH  14,FRED,TYMNET		; KS on 6760
	  HPATH  17,FRED,TYMNET		; KS on 6657
	  HPATH  897,FRED		; VAX-11/750 (SUP sees 897 here)
	  HPATH  930,FRED,TYMNET	; F3 on FOON
	  HPATH  934,FRED,TYMNET	; F3 on FOON


	NODE	6657			; Base to KS2020 host 17
	  NPATH  552A,NICK,6760
	  NPATH  554A,NICK,6760
	  NPATH  2770,NICK,6760
	  NPATH  6760,6760,NICK		; DRV11 #2
	  NPATH  FOON,6760,NICK
	  NPATH  FRED,NICK,6760
	  NPATH  NICK,NICK,6760		; DRV11 #3
	 HPATH  TYMNET,*,6760,NICK	; DUV11 (2 connections) default host
	  HPATH  14,6760,NICK,TYMNET	; KS on 6760
	  HPATH  17,*			; DRV11 #1 to KS2020
	  HPATH  897,NICK,6760,TYMNET	; VAX-11/750 on 554A
	  HPATH  930,6760,NICK,TYMNET	; F3 on FOON
	  HPATH  934,6760,NICK,TYMNET	; F3 on FOON


	NODE	6760			; Base to KS2020 host 14
	  NPATH  552A,NICK,6657
	  NPATH  554A,NICK,6657
	  NPATH  2770,NICK,6657
	  NPATH  6657,6657,NICK		; DRV11 #3
	  NPATH  FOON,FOON		; DRV11 #4
	  NPATH  FRED,NICK,6657
	  NPATH  NICK,NICK,6657		; DRV11 #2
	 HPATH  TYMNET,*,6657,NICK	; DUV11 (2 connections) default host
	  HPATH  14,*			; DRV11 #1 to KS2020
	  HPATH  17,6657,NICK,TYMNET	; KS on 6657
	  HPATH  897,NICK,6657,TYMNET	; VAX/750 on 554A
	  HPATH  930,FOON		; F3 on FOON (SUP sees 930 here)
	  HPATH  934,FOON		; F3 on FOON (SUP sees 934 here)


	NODE	FOON			; Base to F3 hosts 930 and 934
	  NPATH  552A,6760
	  NPATH  554A,6760
	  NPATH  2770,6760
	  NPATH  6657,6760
	  NPATH  6760,6760		; DRV11 #3
	  NPATH  NICK,6760
	  NPATH  FRED,6760
	 HPATH   TYMNET,6760
	  HPATH  14,6760		; KS on 6760
	  HPATH  17,6760		; KS on 6657
	  HPATH  897,6760		; VAX-11/750 on 552A
	  HPATH  930,*			; DRV11 #1 ==> F3 host
	  HPATH  934,*			; DRV11 #2 ==> F3 host


        NODE	FRED			; Terminals & modems in South Bay
	  NPATH  552A,NICK
	  NPATH  554A,554A		; DRV11 #2
	  NPATH  2770,2770		; DRV11 #1
	  NPATH  6657,NICK
	  NPATH  6760,NICK
	  NPATH  FOON,NICK		; 930 and 934 base
	  NPATH  NICK,NICK		; DUV11 #2
	 HPATH  TYMNET,2770		; (DUV11 #1 not connected to anything)
	  HPATH  14,NICK,2770		; KS on 6760
	  HPATH  17,NICK,2770		; KS on 6657
	  HPATH  897,554A		; VAX/750 on 554A
	  HPATH  930,NICK,2770		; F3 on FOON
	  HPATH  934,NICK,2770		; F3 on FOON


	NODE	NICK			; Terminals & modems in Nicholson
	  NPATH  552A,552A		; DRV11 #3
	  NPATH  554A,FRED
	  NPATH  2770,FRED
	  NPATH  6657,6657,6760		; DRV11 #1
	  NPATH  6760,6760,6657		; DRV11 #2
	  NPATH  FOON,6760,6657
	  NPATH  FRED,FRED		; DUV11 #2
	 HPATH  TYMNET,6657,6760,FRED
	  HPATH  14,6760,6657,FRED	; KS based on 6760
	  HPATH  17,6657,6760,FRED	; KS based on 6657
	  HPATH  897,FRED,6760,6657	; VAX-11/750 on 554A
	  HPATH  930,6760,6657		; F3 based on FOON
	  HPATH  934,6760,6657		; F3 based on FOON


.ENDM
