CTEST SETPROC
;CTEST ADDPROC LISTER=(MPL)TYPER
;CTEST ADDPROC TECO=(JMS)TECO
;CTEST ADDPROC MACRO=(FTSYS)REXMAC
;CTEST ADDPROC LOADER=(FTSYS)LINKER
CTEST SETDOLIST DEFAULT,LOG,(XEXEC),(MPL),(SPL),(UPL),(M33),(SYS)
CTEST ADDDOLIST (CARL),(JMS),(WRS),(DENCOFF)
;CTEST SETMAIL MAIL.BOX
CTEST MAKINI
R TC
RPG
:ESCAPE
