CONST
maxrw = 189;
max_rw_len = 20;

TYPE
token_kind =
(lparensy, rparensy, lbracketsy, rbracketsy, commentsy, dollarsy, colonsy, 
  semicolonsy, commasy, endfsy, dosy, ifsy, insy, lnsy, ofsy, orsy, tosy, 
  abssy, andsy, chrsy, cossy, divsy, endsy, eofsy, forsy, getsy, logsy, 
  maxsy, minsy, modsy, newsy, nilsy, notsy, oddsy, ordsy, ptrsy, setsy, 
  sinsy, sqrsy, tansy, ttysy, varsy, casesy, charsy, coshsy, datesy, elsesy, 
  eolnsy, exitsy, filesy, gotosy, loopsy, masksy, nexpsy, nilfsy, opensy, 
  orifsy, precsy, predsy, readsy, realsy, seeksy, sinhsy, sizesy, sqrtsy, 
  stopsy, succsy, tanhsy, textsy, thensy, timesy, truesy, typesy, withsy, 
  andifsy, arraysy, asciisy, beginsy, breaksy, clearsy, closesy, constsy, 
  cotansy, emptysy, falsesy, imagesy, indexsy, inputsy, io_oksy, labelsy, 
  read8sy, resetsy, retrysy, roundsy, truncsy, untilsy, whilesy, writesy, 
  arccossy, arcsinsy, arctansy, cursorsy, downtosy, eopagesy, extentsy, 
  lengthsy, modulesy, otherssy, outputsy, packedsy, publicsy, randomsy, 
  readlnsy, readrnsy, recordsy, repeatsy, returnsy, searchsy, seekoksy, 
  signalsy, staticsy, stringsy, substrsy, unmasksy, updatesy, verifysy, 
  write8sy, addresssy, booleansy, controlsy, disposesy, fortransy, forwardsy, 
  integersy, maximumsy, minimumsy, optionssy, pendingsy, programsy, 
  rewritesy, runtimesy, scratchsy, writelnsy, writernsy, allocatesy, 
  compdatesy, comptimesy, externalsy, filenamesy, functionsy, io_errorsy, 
  preservesy, attentionsy, dimensionsy, envmodulesy, exceptionsy, 
  extstatussy, file_namesy, getstringsy, io_statussy, lowercasesy, 
  proceduresy, putstringsy, ttyoutputsy, uppercasesy, datamodulesy, 
  lowerboundsy, mathstatussy, math_errorsy, upperboundsy, allconditionssy, 
  programstatussy, program_errorsy, special_errorsy, specialstatussy, 
  program_statussy, stack_overflowsy, storage_overflowsy, 
  exception_messagesy, etc);
VAR
nrw: array [1..21] of 1..190 :=
(1, 2, 10, 36, 69, 94, 124, 142, 151, 165, 171, 
  172, 173, 179, 182, 183, 185, 187, 188, 189, 190);
rw: ARRAY[1..189] OF STRING[20] :=
('', 'DO', 'IF', 'IN', 'LN', 'OF', 'OR', 'TO', '', 'ABS', 'AND', 'CHR', 
  'COS', 'DIV', 'END', 'EOF', 'FOR', 'GET', 'LOG', 'MAX', 'MIN', 'MOD', 
  'NEW', 'NIL', 'NOT', 'ODD', 'ORD', 'PTR', 'SET', 'SIN', 'SQR', 'TAN', 
  'TTY', 'VAR', '', 'CASE', 'CHAR', 'COSH', 'DATE', 'ELSE', 'EOLN', 'EXIT', 
  'FILE', 'GOTO', 'LOOP', 'MASK', 'NEXP', 'NILF', 'OPEN', 'ORIF', 'PREC', 
  'PRED', 'READ', 'REAL', 'SEEK', 'SINH', 'SIZE', 'SQRT', 'STOP', 'SUCC', 
  'TANH', 'TEXT', 'THEN', 'TIME', 'TRUE', 'TYPE', 'WITH', '', 'ANDIF', 
  'ARRAY', 'ASCII', 'BEGIN', 'BREAK', 'CLEAR', 'CLOSE', 'CONST', 'COTAN', 
  'EMPTY', 'FALSE', 'IMAGE', 'INDEX', 'INPUT', 'IO_OK', 'LABEL', 'READ8', 
  'RESET', 'RETRY', 'ROUND', 'TRUNC', 'UNTIL', 'WHILE', 'WRITE', '', 
  'ARCCOS', 'ARCSIN', 'ARCTAN', 'CURSOR', 'DOWNTO', 'EOPAGE', 'EXTENT', 
  'LENGTH', 'MODULE', 'OTHERS', 'OUTPUT', 'PACKED', 'PUBLIC', 'RANDOM', 
  'READLN', 'READRN', 'RECORD', 'REPEAT', 'RETURN', 'SEARCH', 'SEEKOK', 
  'SIGNAL', 'STATIC', 'STRING', 'SUBSTR', 'UNMASK', 'UPDATE', 'VERIFY', 
  'WRITE8', '', 'ADDRESS', 'BOOLEAN', 'CONTROL', 'DISPOSE', 'FORTRAN', 
  'FORWARD', 'INTEGER', 'MAXIMUM', 'MINIMUM', 'OPTIONS', 'PENDING', 
  'PROGRAM', 'REWRITE', 'RUNTIME', 'SCRATCH', 'WRITELN', 'WRITERN', '', 
  'ALLOCATE', 'COMPDATE', 'COMPTIME', 'EXTERNAL', 'FILENAME', 'FUNCTION', 
  'IO_ERROR', 'PRESERVE', '', 'ATTENTION', 'DIMENSION', 'ENVMODULE', 
  'EXCEPTION', 'EXTSTATUS', 'FILE_NAME', 'GETSTRING', 'IO_STATUS', 
  'LOWERCASE', 'PROCEDURE', 'PUTSTRING', 'TTYOUTPUT', 'UPPERCASE', '', 
  'DATAMODULE', 'LOWERBOUND', 'MATHSTATUS', 'MATH_ERROR', 'UPPERBOUND', '', 
  '', '', 'ALLCONDITIONS', 'PROGRAMSTATUS', 'PROGRAM_ERROR', 'SPECIAL_ERROR', 
  'SPECIALSTATUS', '', 'PROGRAM_STATUS', 'STACK_OVERFLOW', '', '', 
  'STORAGE_OVERFLOW', '', 'EXCEPTION_MESSAGE', '', '', '', '');
rwsym: ARRAY[1..189] OF token_kind :=
(etc, dosy, ifsy, insy, lnsy, ofsy, orsy, tosy, etc, abssy, andsy, chrsy, 
  cossy, divsy, endsy, eofsy, forsy, getsy, logsy, maxsy, minsy, modsy, 
  newsy, nilsy, notsy, oddsy, ordsy, ptrsy, setsy, sinsy, sqrsy, tansy, 
  ttysy, varsy, etc, casesy, charsy, coshsy, datesy, elsesy, eolnsy, exitsy, 
  filesy, gotosy, loopsy, masksy, nexpsy, nilfsy, opensy, orifsy, precsy, 
  predsy, readsy, realsy, seeksy, sinhsy, sizesy, sqrtsy, stopsy, succsy, 
  tanhsy, textsy, thensy, timesy, truesy, typesy, withsy, etc, andifsy, 
  arraysy, asciisy, beginsy, breaksy, clearsy, closesy, constsy, cotansy, 
  emptysy, falsesy, imagesy, indexsy, inputsy, io_oksy, labelsy, read8sy, 
  resetsy, retrysy, roundsy, truncsy, untilsy, whilesy, writesy, etc, 
  arccossy, arcsinsy, arctansy, cursorsy, downtosy, eopagesy, extentsy, 
  lengthsy, modulesy, otherssy, outputsy, packedsy, publicsy, randomsy, 
  readlnsy, readrnsy, recordsy, repeatsy, returnsy, searchsy, seekoksy, 
  signalsy, staticsy, stringsy, substrsy, unmasksy, updatesy, verifysy, 
  write8sy, etc, addresssy, booleansy, controlsy, disposesy, fortransy, 
  forwardsy, integersy, maximumsy, minimumsy, optionssy, pendingsy, 
  programsy, rewritesy, runtimesy, scratchsy, writelnsy, writernsy, etc, 
  allocatesy, compdatesy, comptimesy, externalsy, filenamesy, functionsy, 
  io_errorsy, preservesy, etc, attentionsy, dimensionsy, envmodulesy, 
  exceptionsy, extstatussy, file_namesy, getstringsy, io_statussy, 
  lowercasesy, proceduresy, putstringsy, ttyoutputsy, uppercasesy, etc, 
  datamodulesy, lowerboundsy, mathstatussy, math_errorsy, upperboundsy, etc, 
  etc, etc, allconditionssy, programstatussy, program_errorsy, 
  special_errorsy, specialstatussy, etc, program_statussy, stack_overflowsy, 
  etc, etc, storage_overflowsy, etc, exception_messagesy, etc, etc, etc, etc);