SV732A.IMG/IMG/B:1000,MP732A.MAP=CG732A.OBJ,RU732A.OBJ,
EXEC.OBJ,ERROR.OBJ,PKT1.OBJ,PKT2.OBJ,PKT3D.OBJ,
CMDTYM.OBJ,CMDS.OBJ,TRM.OBJ,TRMF.OBJ,TRMP.OBJ,
TRMT.OBJ,ZAPBUF.OBJ,STATUS.OBJ,
LNK1.OBJ,LNK2.OBJ,LNKF.OBJ,LNKF2.OBJ,
TYMA.OBJ,TYMB.OBJ,
LINA.OBJ,ONCE.OBJ,END.OBJ

