REPLACE
NO UPDATE
ONLC
(LPTSPL:32)AUXSPL.SAI,(JMS:14)AUXSPL.SAI
(LPTSPL:32)AUXSPL.SAV,(JMS:14)AUXSPL.SAV
(LPTSPL:32)AUXSPL.SAI,(JMS:17)AUXSPL.SAI
(LPTSPL:32)AUXSPL.SAV,(JMS:17)AUXSPL.SAV
QUIT
