:LOGFILE LINK10.LOG
:PARAMETERS P="P"	;May be set to "D" by ".PCOM LINK10 D"
ASSIGN DSK REL		;Using "\P\", P=Production, D=Debug version
DIRECT *.UNV
COMPILE/COMPILE @C1\P\LNK.CMD
COMPILE/COMPILE @C1\P\OVL.CMD
R LINK
@L1\P\LNK.CCL
RUN LINK
OVRLAY.REL/VALUE:%OVRLA
/EXIT
;*; DELETE LNK???.REL,PLT???.REL,PLTPRM.UNV,FORMSC.UNV,*.MAP
DIRECT *.REL,*.UNV,*.SHR,*.HLP
