LOWER=FTSASW+HEAD(XLR)+LOW+GOGOL+STRSER+IOSER+ARYSER+RECSER+NWORLD/NOLOAD/FAIL
NOTDDT=NOTDDT
%S%B
UPPER=FTSASW+HEAD(XLR)+UP+ORDER+GOGOL+STRSER+IOSER+ARYSER+RECSER+NWORLD+LEPRUN+WRDGET+SPARES/FAIL
