	TITLE	TECERR -- TECO 124 ERROR MESSAGE FILE

	LOC	0			; START AT 0
	RIM10				; OUTPUT ABSOLUTE ADDRESSES

MSGTBL:	XWD	TECSRH,'SRH'
	XWD	TECABS,'ABS'
	XWD	TECABT,'ABT'
	XWD	TECARG,'ARG'
	XWD	TECBAK,'BAK'
	XWD	TECBFS,'BFS'
	XWD	TECCOR,'COR'
	XWD	TECCOS,'COS'
	XWD	TECCRT,'CRT'
	XWD	TECDDR,'DDR'
	XWD	TECDDV,'DDV'
	XWD	TECDEX,'DEX'
	XWD	TECDFN,'DFN'
	XWD	TECDIR,'DIR'
	XWD	TECDPR,'DPR'
	XWD	TECEBD,'EBD'
	XWD	TECEBF,'EBF'
	XWD	TECEBO,'EBO'
	XWD	TECEBP,'EBP'
	XWD	TECEMA,'EMA'
	XWD	TECEMD,'EMD'
	XWD	TECEND,'END'
	XWD	TECENO,'ENO'
	XWD	TECENT,'ENT'
	XWD	TECEOA,'EOA'
	XWD	TECFNF,'FNF'
	XWD	TECFUL,'FUL'
	XWD	TECGCE,'GCE'
	XWD	TECIAB,'IAB'
	XWD	TECICE,'ICE'
	XWD	TECICG,'ICG'
	XWD	TECICT,'ICT'
	XWD	TECICV,'ICV'
	XWD	TECIDV,'IDV'
	XWD	TECIEC,'IEC'
	XWD	TECIEM,'IEM'
	XWD	TECIFC,'IFC'
	XWD	TECIFN,'IFN'
	XWD	TECILD,'ILD'
	XWD	TECILL,'ILL'
	XWD	TECILR,'ILR'
	XWD	TECINP,'INP'
	XWD	TECIPA,'IPA'
	XWD	TECIQC,'IQC'
	XWD	TECIQN,'IQN'
	XWD	TECIRB,'IRB'
	XWD	TECIRN,'IRN'
	XWD	TECISA,'ISA'
	XWD	TECITT,'ITT'
	XWD	TECMAP,'MAP'
	XWD	TECMEE,'MEE'
	XWD	TECMEF,'MEF'
	XWD	TECMEO,'MEO'
	XWD	TECMEQ,'MEQ'
	XWD	TECMEU,'MEU'
	XWD	TECMIQ,'MIQ'
	XWD	TECMLA,'MLA'
	XWD	TECMLP,'MLP'
	XWD	TECMRA,'MRA'
	XWD	TECMRP,'MRP'
	XWD	TECMUU,'MUU'
	XWD	TECNAE,'NAE'
	XWD	TECNAI,'NAI'
	XWD	TECNAL,'NAL'
	XWD	TECNAQ,'NAQ'
	XWD	TECNAU,'NAU'
	XWD	TECNAV,'NAV'
	XWD	TECNCS,'NCS'
	XWD	TECNFI,'NFI'
	XWD	TECNFO,'NFO'
	XWD	TECNLF,'NLF'
	XWD	TECNNQ,'NNQ'
	XWD	TECNTQ,'NTQ'
	XWD	TECNXD,'NXD'
	XWD	TECOCT,'OCT'
	XWD	TECODV,'ODV'
	XWD	TECOLR,'OLR'
	XWD	TECOUT,'OUT'
	XWD	TECPAR,'PAR'
	XWD	TECPDL,'PDL'
	XWD	TECPDQ,'PDQ'
	XWD	TECPOP,'POP'
	XWD	TECPRO,'PRO'
	XWD	TECPTL,'PTL'
	XWD	TECRNF,'RNF'
	XWD	TECRNO,'RNO'
	XWD	TECSAL,'SAL'
	XWD	TECSNA,'SNA'
	XWD	TECSNI,'SNI'
	XWD	TECSTC,'STC'
	XWD	TECSTL,'STL'
	XWD	TECTAG,'TAG'
	XWD	TECTAL,'TAL'
	XWD	TECTAV,'TAV'
	XWD	TECTMS,'TMS'
	XWD	TECTTL,'TTL'
	XWD	TECTTY,'TTY'
	XWD	TECUCA,'UCA'
	XWD	TECUCS,'UCS'
	XWD	TECUEY,'UEY'
	XWD	TECUFS,'UFS'
	XWD	TECUIN,'UIN'
	XWD	TECUIS,'UIS'
	XWD	TECUSR,'USR'
	XWD	TECUST,'UST'
	XWD	TECUTG,'UTG'
	XWD	TECUTT,'UTT'
	XWD	TECUTV,'UTV'
	XWD	TECUUO,'UUO'
	XWD	TECVOR,'VOR'
	XWD	     0,0		; END OF TABLE

;	MESSAGES HERE


TECSRH:	ASCIZ	\Cannot Find "17"
A search command not preceded by a colon modifier and not
within an iteration has failed to find the specified
character string "17".  If an S, FS, or any negative or
bounded search FAILS, the pointer is positioned as it was
before the search.  After an N or _ search fails the last
page of the input file has been input and, in the case of N,
output, and the buffer cleared.  If any ^Gi specifications
were used, the Q-registers involved may be examined using
a Qi= command to obtain the exact character string not found.
\

TECABS:	ASCIZ	\Ambiguous I/O switch abbreviation "/19"
The switch "/19" matches the initial parts of more than one
I/O switch.  More of the switch must be typed to make it
unique.  The only valid I/O switches are /APPEND, /R, /GENLSN,
/SUPLSN, /NOLSN, /NOIN and /NOOUT.
\

TECABT:	ASCIZ	\Ambiguous terminal abbreviation "19"
The abbreviation "19" matches the initial parts of more than
one terminal type.  More of the name must be typed to make it
unique.  The only valid terminals currently supported are 
20.
\

TECARG:	ASCIZ	\Improper Arguments
The following argument combinations are illegal:
1)      ,       (no argument before comma)
2)      m,n,    (where m and n are numeric terms)
3)      H,      (because H=B,Z is already two arguments)
4)      ,H      (H following other arguments)
\

TECBAK:	ASCIZ	\Cannot Delete Old Backup File
Failure in rename process at close of editing job initiated
by an EB command or a TECO command.  There exists an old
backup file 08.BAK with a protection <07> such that it
cannot be deleted.  Hence the input file 10 cannot be
renamed to "08.BAK".  The output file is closed with the
filename "01".  The RENAME UUO error code is 03.
\

TECBFS:	ASCIZ	\Bad file specification
The file specification used with any E-type command should
be in the general form
"dev:filename.extension<protection>[project,programmer,sfd1,sfd2,...]"
(<> and [] are interchangeable).  Other standard forms are
acceptable, but the filespec given was indecipherable.
\

TECCOR:	ASCIZ	\Storage Capacity Exceeded
The current operation requires more memory storage than TECO
now has and TECO is unable to obtain more core from the
monitor.  This message can occur as a result of any one of
the following things:
1)  command buffer overflow while a long command string is being typed,
2)  Q-register buffer overflow caused by an X or [ command,
3)  editing buffer overflow caused by an insert command or
    a read command.
\

TECCOS:	ASCIZ	\Contradictory Output Switches
The GENLSN and SUPLSN switches may not both be used with the
same output file.
\

TECCRT:	ASCIZ	\EV command not implemented
This version of TECO does not support special rubout handling
for CRT's.  It must be reassembled to include this feature if
needed.
\

TECDDR:	ASCIZ	\Double directory illegal
The file specification used with any E-type command should
be in the general form
"dev:filename.extension<protection>[project,programmer,sfd1,sfd2,...]"
(<> and [] are interchangeable).  Other standard forms are
acceptable, but the filespec given was indecipherable.
\

TECDDV:	ASCIZ	\Double device illegal
The file specification used with any E-type command should
be in the general form
"dev:filename.extension<protection>[project,programmer,sfd1,sfd2,...]"
(<> and [] are interchangeable).  Other standard forms are
acceptable, but the filespec given was indecipherable.
\

TECDEX:	ASCIZ	\Double extension illegal
The file specification used with any E-type command should
be in the general form
"dev:filename.extension<protection>[project,programmer,sfd1,sfd2,...]"
(<> and [] are interchangeable).  Other standard forms are
acceptable, but the filespec given was indecipherable.
\

TECDFN:	ASCIZ	\Double filename illegal
The file specification used with any E-type command should
be in the general form
"dev:filename.extension<protection>[project,programmer,sfd1,sfd2,...]"
(<> and [] are interchangeable).  Other standard forms are
acceptable, but the filespec given was indecipherable.
\

TECDIR:	ASCIZ	\Illegal character "00" in directory specification
The directory portion of a file specification should be in
any of the following forms:
	[project,programmer]
	[,programmer]		(logged-in project used)
	[project,]		(logged-in programmer used)
	[,]			(logged-in project-programmer used)
	[-]			(default directory path used)
All forms except the last may optionally have as many as five
sub-file directory names following the programmer number. For example:
	[project,programmer,sfd1,sfd2]    or
	[,,sfd1,sfd2,sfd3]
Project and programmer must be octal numbers.  The SFD's must be
alphanumeric names.  Brockets <> may be used in place of brackets [].
\

TECDPR:	ASCIZ	\Double protection illegal
The file specification used with any E-type command should
be in the general form
"dev:filename.extension<protection>[project,programmer,sfd1,sfd2,...]"
(<> and [] are interchangeable).  Other standard forms are
acceptable, but the filespec given was indecipherable.
\

TECEBD:	ASCIZ	\EB with Device 04 Is Illegal
The EB command and the TECO command may be specified only
with file structured devices, i.e., disk and DECtape.
\

TECEBF:	ASCIZ	\EB with Illegal File 02
The EB command and the TECO command may not be used with a
file having the filename extension ".BAK" or with a file
having the name "nnnTEC.TMP" where nnn is the user's job
number.  The user must either use an ER-EW sequence, or
rename the file.
\

TECEBO:	ASCIZ	\EN or EB before current EB job closed
An EN command may not be given while an EB command is in
progress.  Give an EF to close the files, or an EK to abort
the edit, if you wish to execute an EN.
\

TECEBP:	ASCIZ	\EB Illegal Because of File 02 Protection
The file 02[05] cannot be edited with an EB command or a
TECO command because it has a protection <07> such that it cannot
be renamed at close time.
\

TECEMA:	ASCIZ	\EM With Illegal Argument 06
The argument n in an nEM command must be greater than zero.
\

TECEMD:	ASCIZ	\EM With No Input Device Open
EM commands apply only to the input device, and so should be
preceded by an ER (or equivalent) command.  To position a
tape for output, that unit should be temporarily opened for
input while doing the EM commands.
\

TECEND:	ASCIZ	\EN with a device is illegal
Since it is not possible to rename across devices, there
must be no device specified in the EN command.  The device
is specified in the ER command which selected the file.
\

TECENO:	ASCIZ	\EN requires an open input file
EN commands apply to the file currently open for input.
You must execute an ER command to select the file to be RENAME'd
or deleted before executing an EN.
\

TECENT:	ASCIZ	\13
00Illegal Output Filename "02" ENTER UUO failure 0.
The filename "02" specified for the output file cannot be
used.  The format is invalid.
01Output UFD 04:[05] Not Found ENTER UUO failure 1.
The file 02[05] specified for output by an EE, EL, EW,
EA, EZ, or MAKE command cannot be created because there is no
user file directory with project-programmer number [05] on
device 04.
02Output Protection Failure ENTER UUO failure 2.
The file 04:02[05] specified for output by an
EE, EL, EW, EA, EZ, EB, MAKE, or TECO command cannot be created
either because it already exists and is write-protected against
the user, or because the directory it is to be entered into is
write-protected against the user.
03Output File Being Modified ENTER UUO failure 3.
The file 02[05] specified for output by an EE, EL, EW,
EA, EZ, EB, MAKE, or TECO command cannot be created because it is
currently being created or modified by another job.
06Output UFD or RIB Error ENTER UUO failure 6.
The output file 04:02[05]  cannot be created because
a bad directory block was encountered by the monitor while the
ENTER was in progress. The user may try repeating the EE, EL,
EW, EA, EB, or TECO command, but if the error persists, it
is impossible to proceed.  Notify your system manager.
14No Room or Quota Exceeded on 04:  ENTER UUO failure 14.
The output file 02 cannot be created because there is no
more free space on device 04:, or because the user's quota
is already exceeded there.
15Write Lock on 04:  ENTER UUO failure 15.
The outputfile 02 cannot be created because the output
file structure is write-locked.
16Monitor Table Space Exhausted ENTER UUO failure 16.
The output file 02 cannot be created because there is
not enough table space left in the monitor to allow the
ENTER.  The user may try repeating the EE, EL, EW, EA,
EB, or TECO command, but if the error persists he will have
to wait until conditions improve.
21Directory Already Exists ENTER UUO failure 21.
The output file 04:02[05] cannot be created because
a directory by that name already exists.
23Output SFD not Found ENTER UUO failure 23.
The output file 04:02[05] cannot be created
because the sub-file-directory on which it should be ENTERed
cannot be found.
24Search List Empty ENTER UUO failure 24.
The output file 02 cannot be created because the user's
file structure search list is empty.
25Output SFD Nested too Deeply ENTER UUO failure 25.
The output file 04:02[05] cannot be created
because the specified SFD path for the ENTER is nested too deeply.
26No Create for Specified SFD Path ENTER UUO failure 26.
The output file 04:02[05] cannot be created
because the specified SFD path for the ENTER is set for no creation.
ENTER Failure 03 on Output File 02.
The attempted ENTER of the output file 02 has failed and the
monitor has returned an error code of 03.  This error is not
expected to occur on an ENTER.  Please contact a systems programmer
and explain what you were doing.
\

TECEOA:	ASCIZ\06EO Argument Too Large
The argument 06 given with an EO command is larger than the
standard (maximum) setting of EO=16 for this version of
TECO.  This must be an older version of TECO than the user
thinks he is using;  the features corresponding to EO=06 do
not exist.
\

TECFNF:	ASCIZ	\13
00Input File 04:02[05] Not Found LOOKUP failure 0.
The file 02 specified for input by an ER, EB, EI, EP or
TECO command was not found on the input device 04.
01Input UFD 04:[05] Not Found LOOKUP UUO failure 1.
The file 02[05] specified for input by an ER, EB, EI,
EP or TECO command cannot be found because there is no User
File Directory with project-programmer number [05] on
device 04.
02Input Protection Failure LOOKUP UUO failure 2.
The file 04:02[05] specified for input by an
ER, EB, EI, EP or TECO command cannot be read because it is
read-protected against the user.
06Input UFD or RIB Error LOOKUP UUO failure 6.
The input file 02 cannot be read because a bad directory
block was encountered by the monitor while the LOOKUP was in
progress. The user may try repeating the ER, EB, EI, EP or TECO
command, but if the error persists all is lost.  Notify your
system manager.
16Monitor Table Space Exhausted LOOKUP UUO failure 16.
The input file 02 cannot be read because there is not enough
table space left in the monitor to allow the LOOKUP.  The
user may try repeating the ER, EB, EI, EP or TECO command,
but if the error persists he will have to wait until
conditions improve.
23Input SFD not Found LOOKUP UUO failure 23.
The input file 04:02[05] cannot be found
because the sub-file directory on which it should be looked
up cannot be found.
24Search List Empty LOOKUP UUO failure 24.
The input file 02 cannot be found because the user's file
structure search list is empty.
25Input SFD Nested too Deeply LOOKUP UUO failure 25.
The input file 04:02[05] cannot be found
because the specified SFD path for the LOOKUP is nested too deeply.
LOOKUP Failure 03 on Input File 02
The attempted LOOKUP on the input file 02 has failed and
the monitor has returned an error code of 03.  This error
is not expected to occur on a LOOKUP.  Please contact a
systems programmer and explain what you were doing.
\

TECFUL:	ASCIZ	\Device 04: Directory Full ENTER UUO failure 03.
The file 02 specified for output by an EW or MAKE command
cannot be created on DECtape 04 because the tape directory is full.
\

TECGCE:	ASCIZ	\Garbage Collector Error
While TECO was attempting to reclaim some wasted space in
core an internal error occurred.  Please report this problem
to your systems programmer.
\

TECIAB:	ASCIZ	\Incomplete <...> or (...) in Macro
A macro contained in a Q-register and being executed by an M
command contains an iteration that is not enclosed within
the Q-register by <...>, or a parenthetical expression that
is not closed within the Q-register by a ).
\

TECICE:	ASCIZ	\Illegal Control-E Command in Search Argument
A search argument contains a ^E command that is either not
defined or incomplete.  The only valid ^E commands in search
arguments are ^EA, ^ED, ^EV, ^EW, ^EL, ^ES, ^E<nnn>, and
^E[a,b,c,...].
\

TECICG:	ASCIZ	\Illegal Control-G Command in Text Argument
A text string contains a ^G command which is not followed by
a valid Q-register name (A thru Z, 0 thru 9, or *), or which
occurs in the middle of a ^E[....] specification.
\

TECICT:	ASCIZ	\Illegal Control Command 18 in Text Argument
In order to be entered as text in an insert command or
search command, all control characters (^@ - ^H and ^N - ^_)
must be preceded by ^R or ^T.  Otherwise they are
interpreted as commands.  The control character "18" is an
undefined text argument control command.
\

TECICV:	ASCIZ	\Illegal character "00" in EV specification
The characters used to specify a terminal type in an EV command
must be A-Z, 0-9, % or $.  The only terminals currently supported 
are 20.
\

TECIDV:	ASCIZ	\Input Device 04 Not Available
Initialization failure.  Unable to initialize the device 04
for input.  Either the device is being used by someone else
right now, or else it does not exist in the system.
\

TECIEC:	ASCIZ	\Illegal Character "00" After E
The only commands starting with the letter E are EA, EB, EC,
ED, EE, EF, EG, EH, EI, EK, EL, EM, EN, EO, EP, ER, ES, ET, EU,
EV, EW, EX, EY, and EZ.  When used as a command (i.e., not in a
text argument) E may not be followed by any character except
one of these.
\

TECIEM:	ASCIZ	\Re-init Failure on Device 04 After EM
Unable to re-initialize the device 04 after executing an EM
command on it.  If this error persists after retrying to
initialize the device with an ER command (or EW command if
output to the device is desired), consult your systems
programmer.
\

TECIFC:	ASCIZ	\Illegal Character "00" after F
The only commands starting with the letter F are FD, FS and
FN.  When used as a command (other than EF or in a text
argument) F may not be followed by any character other than
one of these.
\

TECIFN:	ASCIZ	\Illegal Character "00" in Filespec
File specifications must be of the form
dev:filename.extension<protection>[project,programmer,sfd1,sfd2,...]$
where dev, filename, extension and the sfd's are alphanumeric, and
protection, project and programmer are octal.  No characters other
than the ones specified may appear between the EA, EB, ED, EE, EI, EL,
EN, EP, ER, EW, or EZ command and the altmode terminator ($). (<> and
[] are interchangeable).
\

TECILD:	ASCIZ	\Illegal device 04:
Device 04:  cannot be used, because it is incapable of doing
the necessary I/O.  This may be because it cannot do input
(or output), or because it cannot handle the necessary I/O
mode, or (in the case of EA and EL) it cannot be appended
to.
\

TECILL:	ASCIZ	\Illegal Command 18
The character "18" is not defined as a valid TECO command.
\

TECILR:	ASCIZ	\Cannot Lookup Input File 10 to Rename It
Failure in rename process at close of editing job initiated
by an EB command or a TECO command.  Unab do a LOOKUP
on the original input file 04:10 in order to rename it
"08.BAK".  The output file is closed with the name "01".
The LOOKUP UUO error code is 03.
\

TECINP:	ASCIZ	\Input Error 11 on File 09
A read error has occurred during input.  The input file 09
has been released.  The user may try again to read the file,
but if the error persists, the user will have to return to
his backup file.  The input device error flags (status word
right half with bits 22-35 masked out) are 11 (14
01block too large).
02parity or checksum error).
03block too large and parity error).
04device error, data missed).
05block too large and device error).
06parity error and device error).
07block too large, parity error, and device error).
10improper mode).
11block too large and improper mode).
12parity error and improper mode).
13block too large, parity error, and improper mode).
14device error and improper mode).
15block too large, device error, and improper mode).
16parity error, device error, and improper mode).
17block too large, parity error, device error, and improper
mode).
\

TECIPA:	ASCIZ	\Illegal ^P or ^Y argument 06
The argument to a ^P or ^Y command is an absolute page
number in the file.  It must be greater than the current
page number.
\

TECIQC:	ASCIZ	\Illegal Command "00
The only valid " commands are "G, "L, "N, "E, "C, "A, "D,
"V, "W, "T, "F, "S, and "U.
\

TECIQN:	ASCIZ	\Illegal Q-register Name "00"
The Q-register name specified by a Q, U, X, G, %, M, W, [,
], ^G or * command must be a letter (A thru Z) or a digit (0
thru 9), OR an asterisk (*) for the EI and EP Q-register.
\

TECIRB:	ASCIZ	\Cannot Rename Input File 10 to 08.BAK
Failure in rename process at close of editing job initiated
by an EB command or a TECO command.  The attempt to rename
the original input file 10 to the backup filename "08.BAK"
has failed.  The output file is closed with the name "01".
The RENAME UUO error code is 03.
\

TECIRN:	ASCIZ	\Cannot Re-init Device 04 for Rename Process
Failure in rename process at close of editing job initiated
by an EB command or a TECO command.  Cannot reinitialize the
original input device 04 in order to rename the input file
10 to "08.BAK".  The output file is closed with the name
"01".
\

TECISA:	ASCIZ	\Illegal Argument with 00 Search
The argument preceding a search command must be either
  a) The number of times a match must be found before the
     search is considered successful, in which case it must
     be non-zero.  If it is negative, the search is
     performed in reverse.
  b) The boundaries of the search, in which case the first
     occurrence of the string therein is found.  If the
     second argument is greater than the first, the search
     is performed in reverse.
\

TECITT:	ASCIZ	\Illegal TTCALL type value 06
The extended TTCALL command must take the form
":arg1,arg2^T" where arg1 is the (optional) TTCALL argument
and arg2 is the TTCALL type in decimal.  The second argument
must be a legitimate TTCALL type, with 0-13 legal except for
3 (OUTSTR).  Type 8 (RESCAN) will do a RESCAN unless there
is an arg1, in which case it tests for CCL mode.  Other legal 
values of arg2 are -1 and -2, which serve to turn terminal
echoing on and off.
\

TECMAP:	ASCIZ	\Missing '
In attempting to execute a conditional skip command (a "
command whose argument does not satisfy the required
condition) no ' command closing the conditional execution
string can be found.  Note:  n"...' strings must be complete
within a single macro level.
\

TECMEE:	ASCIZ	\Macro Ending with E
A command macro being executed from a Q-register ends with
the character "E".  This is an incomplete command.  E is the
initial character of an entire set of commands.  The other
character of the command begun by E must be in the same
macro with the E.
\

TECMEF:	ASCIZ	\Macro Ending with F
A command macro being executed from a Q-register ends with
the character "F" (not an EF).  This is an incomplete
command.  F is the initial character of an entire set of
commands.  The other character of the command begun by F
must be in the same macro with the F.
\

TECMEO:	ASCIZ	\Macro Ending with Unterminated O Command
The last command in a command macro being executed from a
Q-register is an O command with no altmode to mark the end
of the tag-name argument.  The argument for the O command
must be complete within the Q-register.
\

TECMEQ:	ASCIZ	\Macro Ending with "
A command macro being executed from a Q-register ends with
the " character.  This is an incomplete command.  The "
command must be followed by one of the characters G, L, N,
E, C, A, D, V, W, T, F, S, or U to indicate the condition
under which the following commands are to be executed.  This
character must be in the Q-register with the ".
\

TECMEU:	ASCIZ	\Macro Ending with ^
A command macro being executed from a Q-register ends with
the ^ character.  This is an incomplete command.  The ^
command takes a single character text argument that must be
in the Q-register with the ^.
\

TECMIQ:	ASCIZ	\Macro Ending with 00
A command macro being executed from a Q-register ends with
the character "00".  This is an incomplete command.  The 00
command takes a single character text argument to name the
Q-register to which it applies.  This argument must be in
the same macro as the 00 command itself.
\

TECMLA:	ASCIZ	\Missing left angle bracket
There is a right angle bracket not matched by a left angle
bracket somewhere to its left.  (Note:  an iteration in a
macro stored in a Q-register must be complete within the
Q-register.)
\

TECMLP:	ASCIZ	\Missing (
Command string contains a right parenthesis that is not
matched by a corresponding left parenthesis.
\

TECMRA:	ASCIZ	\Missing right angle bracket
In attempting to exit from an iteration field with a ;
command (or to skip over an iteration field with a 0
argument) the < was not closed by a > command.  Note:
iteration fields must be complete within a single macro
level.
\

TECMRP:	ASCIZ	\Missing )
The command string contains, within an iteration field, a
parenthetical expression that is not closed by a right
parenthesis.
\

TECMUU:	ASCIZ	\Macro Ending with ^^
A command macro being executed from a Q-register ends with
control-^ or ^^.  This is an incomplete command.  The ^^
command takes a single character text argument that must be
in the Q-register with the ^^.
\

TECNAE:	ASCIZ	\No Argument Before =
The command n= or n== causes the value n to be typed.  The =
command must be preceded by either a specific numeric
argument or a command that returns a numeric value.
\

TECNAI:	ASCIZ	\No Altmode after nI
Unless the EO value has been set to 1, the numeric insert
command nI must be immediately followed by altmode.
\

TECNAL:	ASCIZ	\No altmode after nEL
The command nEL must be immediately followed by an altmode.
\

TECNAQ:	ASCIZ	\No Argument Before "
The " command must be preceded by a single numeric argument
on which the decision to execute the following commands or
skip to the matching ' is based.
\

TECNAU:	ASCIZ	\No Argument Before U
The command nUi stores the value n in Q-register i.  The U
command must be preceded by either a specific numeric
argument or a command that returns a numeric value.
\

TECNAV:	ASCIZ	\No altmode after EV
The commands nEV and n,mEV must be immediately followed by an
altmode.
\

TECNCS:	ASCIZ	\No Command String Seen Prior to * command
The * command saves the preceding command string in the
specified Q-register.  In this case no command string has
previously been given.
\

TECNFI:	ASCIZ	\No File for Input
Before issuing an input command (EY or A) it is necessary to
open an input file by use of an ER, EB, or TECO command.
\

TECNFO:	ASCIZ	\No File for Output
Before giving an output command (PW, P, ^P, N, EX, or EG) it
is necessary to open an output file by use of an EA, EB, EW,
EZ, MAKE, or TECO command.
\

TECNLF:	ASCIZ	\No log file open
When <arg>EL is used there must already be a log file open
\

TECNNQ:	ASCIZ	\Non-Numeric in Q-register 00
Q-register 00, specified by a Q or % command, does not
contain a number.
\

TECNTQ:	ASCIZ	\No Text in Q-register 00
Q-register 00, specified by a G, ^G, or M command, does not
contain text.
\

TECNXD:	ASCIZ	\Nonexistent device 04:
The device 0?~EQÙA;†