Received: from X32.Tymnet by X32.Tymnet; Sun, 25 Sep 88 22:48:09 PDT
Received: from B39.Tymnet by X32.Tymnet; Sun, 25 Sep 88 9:37:51 PDT
Received: from tymix.Tymnet by B39.Tymnet; Thu, 22 Sep 88 0:44:56 PDT
Received: by tymix.Tymnet (5.51/4.7) id AA12595; Thu, 22 Sep 88 00:47:15 PDT
Received: by antares.Tymnet.com (3.2/SMI-3.2) id AA23615; Thu, 22 Sep 88
	00:44:10 PDT
Return-path: <antares!jms@tymix.Tymnet> 
From: antares!jms (joe smith) 
Date: Thu, 22 Sep 88 00:44:10 PDT 
To: X32!Sally 
Message-id: <8809220744.AA23615@antares.Tymnet.com> 
Subject: "Path:
	antares!tymix!oliveb!ames!mailrus!tut.cis.ohio-state.edu!osu-cis!killer!jolnet!macman"...
	

Path: antares!tymix!oliveb!ames!mailrus!tut.cis.ohio-state.edu!osu-cis!killer!jolnet!macman
From: macman@jolnet.ORPK.IL.US (Rick George)
Newsgroups: rec.humor
Subject: Dave Barry stuff
Message-ID: <809@jolnet.ORPK.IL.US>
Date: 16 Sep 88 19:34:44 GMT
Reply-To: macman@jolnet.UUCP (Rick George)
Organization: Pangea Telecommunications Software
Lines: 50


	I myself am a big fan of Dave Barry,  just thought i would share
a neat little thing out of his book "Claw Your Way to the Top"


		WHILE YOU WERE OUT IN A MEETING

Mr./Mrs./Miss/
Ms./Rev./Massa/ _____________________________________________
				(name)

 Check One

( )	Telephoned.
( )	Did not Telephone.
( )	Thought about telephoning, but then
	changed his or her mind.
( )	Telephoned, but could not for the LIFE of
	him or her remember why.
( )	Telephoned, then hung right up, but I am
	certain it was him or her.
( )	Wants you to call and attempt to leave a
	message for him or her.
( )	Wants to fire you.
( )	Wants to reveal a sordid episode from his
	or her past involving a goat.
( )	Wants to end World Hunger in our lifetime.
( )	Wants your body.
( )	Wants for nothing.
( )	Wants to tell you the joke about the man
	who finds out that he has only eight hours to
	live, so he goes home and makes love
	with his wife once, twice, three times, and
	finally they fall asleep, and at 3 A.M. he
	tries to wake her up, and she says, "Not
	AGAIN! Some of us have to get up in the
	morning!"
( )	Ate paste as a child.
( )	Has the clap.


 - - - - - - - - - - - - - -[ CUT HERE ]- - - - - - - - - - - - - - - - - -

Just thought i would let you know that.  Haha

--
-------------------------------------------------------------------------------
Rick George					       macman@jolnet.ORPK.IL.US
		Pangea Telecommunications Software
-------------------------------------------------------------------------------
From: Sally Smith <SALLY@X930> (38725 Lexington St #247, Fremont CA 94536) 
Date: Sun, 25 Sep 88 22:49:01 PDT 
To: figmo@mica.berkeley.edu 
Subject: Test 

Hi Lynn,
This is a test to see if I can communicate with the world. Let me know if it 
arrives.

Sally
