;[CSM] B361LB.REL is on SYS:, not DSKB:[1,5]
;   0001  0	MODULE KERGLB (IDENT = '2.0.002'
;   0002  0			) =
;   0003  1	BEGIN
;   0004  1	
;   0005  1	SWITCHES LANGUAGE (COMMON);
;   0006  1	
;   0007  1	!<BLF/WIDTH:100>
;   0008  1	
;   0009  1	!++
;   0010  1	! FACILITY:
;   0011  1	!
;   0012  1	!	KERMIT common message processing global storage.
;   0013  1	!
;   0014  1	! ABSTRACT:
;   0015  1	!
;   0016  1	!	This module contains all of the global storage locations used
;   0017  1	!	by KERMSG.  These are in a separate module to make it possible
;   0018  1	!	to load the global storage into a common under P/OS.
;   0019  1	!
;   0020  1	! ENVIRONMENT:
;   0021  1	!
;   0022  1	!	TOPS-10, P/OS, VAX/VMS
;   0023  1	!
;   0024  1	! AUTHOR: Nick Bush, CREATION DATE: 21-December-1983
;   0025  1	!--
;   0026  1	
;   0027  1	%SBTTL 'Table of Contents'
;   0028  1	!
;   0029  1	! TABLE OF CONTENTS:
;   0030  1	!
;   0031  1	%SBTTL 'Revision History'
;   0032  1	
;   0033  1	!++
;   0034  1	!
;   0035  1	! 2.0.000	Extract this module from KERMSG.BLI.
;   0036  1	!
;   0037  1	! 2.0.001	By: Robert C. McQueen			On: 16-Feb-1984
;   0038  1	!		Move SEND%TIMEOUT from KERMSG to this module.
;   0039  1	!
;   0040  1	! 2.0.002	By: Nick Bush				On: 2-April-1984
;   0041  1	!		Add SRV%TIMEOUT from time between NAK's.
;   0042  1	!--
;   0043  1	
;   0044  1	%SBTTL 'Library files'
;   0045  1	!
;   0046  1	! INCLUDE FILES:
;   0047  1	!
;   0048  1	!
;   0049  1	! KERMIT common definitions
;   0050  1	!
;   0051  1	
;   0052  1	REQUIRE 'KERCOM';
;   0253  1	
;   0254  1	%SBTTL 'Global storage for KERMSG'
;   0255  1	
;   0256  1	GLOBAL
;   0257  1	!
;   0258  1	! Receive parameters
;   0259  1	!
;   0260  1	    RCV%PKT%SIZE,				! Receive packet size
;   0261  1	    RCV%NPAD,					! Padding length
;   0262  1	    RCV%PADCHAR,				! Padding character
;   0263  1	    RCV%TIMEOUT,				! Time out
;   0264  1	    RCV%EOL,					! EOL character
;   0265  1	    RCV%QUOTE%CHR,				! Quote character
;   0266  1	    RCV%SOH,					! Start of header character
;   0267  1	    RCV%8QUOTE%CHR,				! 8-bit quoting character
;   0268  1	!
;   0269  1	! Miscellaneous parameters
;   0270  1	!
;   0271  1	    SET%REPT%CHR,				! Repeat character
;   0272  1	!
;   0273  1	! Send parameters
;   0274  1	!
;   0275  1	    SND%PKT%SIZE,				! Send packet size
;   0276  1	    SND%NPAD,					! Padding length
;   0277  1	    SND%PADCHAR,				! Padding character
;   0278  1	    SND%TIMEOUT,				! Time out
;   0279  1	    SND%EOL,					! EOL character
;   0280  1	    SND%QUOTE%CHR,				! Quote character
;   0281  1	    SND%SOH,					! Start of header character
;   0282  1	    SEND%TIMEOUT,				! Time out
;   0283  1	!
;   0284  1	! Server parameters
;   0285  1	!
;   0286  1	    SRV%TIMEOUT,				! Amount of time between NAK's in server
;   0287  1	!
;   0288  1	! Statistics
;   0289  1	!
;   0290  1	    SND%TOTAL%CHARS,				! Total characters sent
;   0291  1	    RCV%TOTAL%CHARS,				! Total characters received
;   0292  1	    SND%DATA%CHARS,				! Total number of data characters sent
;   0293  1	    RCV%DATA%CHARS,				! Total number of data characters received
;   0294  1	    SND%NAKS,					! Total NAKs sent
;   0295  1	    RCV%NAKS,					! Total NAKs received
;   0296  1	    SND%COUNT,					! Count of total number of packets
;   0297  1	    RCV%COUNT,					! Count of total number packets received
;   0298  1	    SMSG%COUNT,					! Total number of packets sent
;   0299  1	    RMSG%COUNT,					! Total number of packets received
;   0300  1	    SMSG%TOTAL%CHARS,				! Total chars sent this file xfer
;   0301  1	    RMSG%TOTAL%CHARS,				! Total chars rcvd this file xfer
;   0302  1	    SMSG%DATA%CHARS,				! Total data chars this file xfer
;   0303  1	    RMSG%DATA%CHARS,				! Total data chars this file xfer
;   0304  1	    SMSG%NAKS,					! Total number of NAKs this file xfer
;   0305  1	    RMSG%NAKS,					! Total number of NAKs received
;   0306  1	    XFR%TIME,					! Amount of time last xfr took
;   0307  1	    TOTAL%TIME,					! Total time of all xfrs
;   0308  1	    						!  this file xfer
;   0309  1	    LAST%ERROR : VECTOR [CH$ALLOCATION (MAX%MSG + 1)],	! Last error message
;   0310  1	!
;   0311  1	! Misc constants.
;   0312  1	!
;   0313  1	    FILE%NAME : VECTOR [CH$ALLOCATION (MAX%FILE%NAME)],
;   0314  1	    FILE%SIZE,
;   0315  1	    SI%RETRIES,					! Send init retries to attempt
;   0316  1	    PKT%RETRIES,				! Number of retries to try for a message
;   0317  1	    DELAY,					! Amount of time to delay
;   0318  1	    DUPLEX,					! Type of connection (half or full)
;   0319  1	    PARITY%TYPE,				! Type of parity to use
;   0320  1	    DEV%PARITY%FLAG,				! True if output device does
;   0321  1	    						!  parity, false if we do it
;   0322  1	    CHKTYPE,					! Type of block check desired
;   0323  1	    ABT%FLAG,					! True if aborted file should be discarded
;   0324  1	    DEBUG%FLAG,					! Debugging mode on/off
;   0325  1	    WARN%FLAG,					! File warning flag
;   0326  1	    IBM%FLAG,					! Talking to an IBM system
;   0327  1	    IBM%CHAR,					! Turnaround character for IBM mode
;   0328  1	    ECHO%FLAG,					! Local echo flag
;   0329  1	    CONNECT%FLAG,				! Connected flag; True if
;   0330  1	    						!  terminal and SET LINE are
;   0331  1	    						!  the same
;   0332  1	    ABT%CUR%FILE,				! Abort current file
;   0333  1	    ABT%ALL%FILE,				! Abort all files in stream
;   0334  1	    TYP%STS%FLAG,				! Type status next message
;   0335  1	    TY%FIL,					! Type file specs
;   0336  1	    TY%PKT,					! Type packet info
;   0337  1	    FIL%NORMAL%FORM,				! Use normal form file names
;   0338  1	    GEN%1DATA : VECTOR [CH$ALLOCATION (MAX%MSG)],! Data for generic command
;   0339  1	    GEN%1SIZE,					! Size of data in GEN%1DATA
;   0340  1	    GEN%2DATA : VECTOR [CH$ALLOCATION (MAX%MSG)],! Second argument for generic command
;   0341  1	    GEN%2SIZE,					! Size of data in GEN%2DATA
;   0342  1	    GEN%3DATA : VECTOR [CH$ALLOCATION (MAX%MSG)],! Third arg for generic command
;   0343  1	    GEN%3SIZE;					! Size of data in GEN%3DATA
;   0344  1	%SBTTL 'End of KERGLB'
;   0345  1	END						! End of module
;   0346  1	
;   0347  0	ELUDOM


	TITLE	KERGLB
	TWOSEG


;[CSM]	.REQUEST  DSKB:B361AB.REL[1,5]
	.REQUEST  SYS:B361LB.REL	;[CSM]


	RELOC	0
RCV%PKT%SIZE::
	BLOCK	1
RCV%NPAD::
	BLOCK	1
RCV%PADCHAR::
	BLOCK	1
RCV%TIMEOUT::
	BLOCK	1
RCV%EOL::
	BLOCK	1
RCV%QUOTE%CHR::
	BLOCK	1
RCV%SOH::
	BLOCK	1
RCV%8QUOTE%CHR::
	BLOCK	1
SET%REPT%CHR::
	BLOCK	1
SND%PKT%SIZE::
	BLOCK	1
SND%NPAD::
	BLOCK	1
SND%PADCHAR::
	BLOCK	1
SND%TIMEOUT::
	BLOCK	1
SND%EOL::
	BLOCK	1
SND%QUOTE%CHR::
	BLOCK	1
SND%SOH::
	BLOCK	1
SEND%TIMEOUT::
	BLOCK	1
SRV%TIMEOUT::
	BLOCK	1
SND%TOTAL%CHARS::
	BLOCK	1
RCV%TOTAL%CHARS::
	BLOCK	1
SND%DATA%CHARS::
	BLOCK	1
RCV%DATA%CHARS::
	BLOCK	1
SND%NAKS::
	BLOCK	1
RCV%NAKS::
	BLOCK	1
SND%COUNT::
	BLOCK	1
RCV%COUNT::
	BLOCK	1
SMSG%COUNT::
	BLOCK	1
RMSG%COUNT::
	BLOCK	1
SMSG%TOTAL%CHARS::
	BLOCK	1
RMSG%TOTAL%CHARS::
	BLOCK	1
SMSG%DATA%CHARS::
	BLOCK	1
RMSG%DATA%CHARS::
	BLOCK	1
SMSG%NAKS::
	BLOCK	1
RMSG%NAKS::
	BLOCK	1
XFR%TIME::
	BLOCK	1
TOTAL%TIME::
	BLOCK	1
LAST%ERROR::
	BLOCK	24
FILE%NAME::
	BLOCK	33
FILE%SIZE::
	BLOCK	1
SI%RETRIES::
	BLOCK	1
PKT%RETRIES::
	BLOCK	1
DELAY:: BLOCK	1
DUPLEX::BLOCK	1
PARITY%TYPE::
	BLOCK	1
DEV%PARITY%FLAG::
	BLOCK	1
CHKTYPE::
	BLOCK	1
ABT%FLAG::
	BLOCK	1
DEBUG%FLAG::
	BLOCK	1
WARN%FLAG::
	BLOCK	1
IBM%FLAG::
	BLOCK	1
IBM%CHAR::
	BLOCK	1
ECHO%FLAG::
	BLOCK	1
CONNECT%FLAG::
	BLOCK	1
ABT%CUR%FILE::
	BLOCK	1
ABT%ALL%FILE::
	BLOCK	1
TYP%STS%FLAG::
	BLOCK	1
TY%FIL::BLOCK	1
TY%PKT::BLOCK	1
FIL%NORMAL%FORM::
	BLOCK	1
GEN%1DATA::
	BLOCK	24
GEN%1SIZE::
	BLOCK	1
GEN%2DATA::
	BLOCK	24
GEN%2SIZE::
	BLOCK	1
GEN%3DATA::
	BLOCK	24
GEN%3SIZE::
	BLOCK	1


FNM%NORMAL==:	    1
FNM%FULL==:	    2
FNM%UNTRAN==:	    4
PR%MIN==:	    0
PR%NONE==:	    0
PR%MARK==:	    1
PR%EVEN==:	    2
PR%ODD==:	    3
PR%SPACE==:	    4
PR%MAX==:	    4
GC%MIN==:	    1
GC%EXIT==:	    1
GC%DIRECTORY==:     2
GC%DISK%USAGE==:    3
GC%DELETE==:	    4
GC%TYPE==:	    5
GC%HELP==:	    6
GC%LOGOUT==:	    7
GC%LGN==:	    10
GC%CONNECT==:	    11
GC%RENAME==:	    12
GC%COPY==:	    13
GC%WHO==:	    14
GC%SEND%MSG==:	    15
GC%STATUS==:	    16
GC%COMMAND==:	    17
GC%KERMIT==:	    20
GC%JOURNAL==:	    21
GC%VARIABLE==:	    22
GC%PROGRAM==:	    23
GC%MAX==:	    23
DP%FULL==:	    0
DP%HALF==:	    1
CHK%1CHAR==:	    61
CHK%2CHAR==:	    62
CHK%CRC==:	    63
MAX%MSG==:	    140



	END

; Low  segment length:     167 words
; High segment length:       0 words






;			COMPILER INTERNAL TIMING

;	Phase	     Faults	  Cpu-time	Elapsed-time
;	LEXSYN	          0	   00:01.3	   00:02.5
;	FLOWAN	          0	   00:00.0	   00:00.0
;	DELAY	          0	   00:00.0	   00:00.0
;	TNBIND	          0	   00:00.0	   00:00.2
;	CODE	          0	   00:00.0	   00:00.0
;	FINAL	          0	   00:00.1	   00:00.1
;	Total	          0	   00:01.5	   00:02.8

; Compilation Complete

	END
     