

From: YEUX
Date: MAY 27,1981 0:32

**Caution**
You will be quite irritated at what is about to happen to VUE.
But, I feel obligated to tell you now so that you can calm down.
(At least you haven't had to learn/unlearn anything recently)

ALL VUE commands which are not in EMACS are no longer bound to keys.
If they are in EMACS, they will have the EMACS definitions.  (I will
explain in more detail later, but for now, that is enough.)  Some
normally used commands are about to disappear.  However, they will
be accessible through the Meta-X (extended command) method.
-Carl.

**Caution** Bear in room!

