From: Carl A Baltrunas <Carl@X930.Tymnet> 
Date: Sat, 31 Aug 85 14:36:03 PDT 
To: Carl A Baltrunas <Carl@X930.Tymnet>, Osman Guven <osman@X930.Tymnet>, Joe
	Smith <jms@X930.Tymnet> 
Cc: Craig Fletcher <fletcherc@X930.Tymnet> 
Subject: Hotline call - re: magnum on system D65 

I took a call, checked out the files on MAGNUM,FTMAGNUM and copied my
few magnum procedures over and they ran fine.  Without a "real" systems
problem I feel that we cannot do more for them.

I told them to contact Frank Siegel, or Dick Ouilette in the MAGNUM group
on Tuesday, or to contact BLDG C operations to see if they know of any
way to get ahold of the magnum people during the weekend.  If any of you
get another call... unless the customer has a bad file in his directory
there isn't much we can do.  Dallas OPS said they've seen no hardware
problems...

Nuff siad.  /Carl
From: Joe Smith <JMS@X930.Tymnet> (Liberty Street in Fremont 116-2512) 
Date: Fri, 15 Nov 85 0:56:11 PST 
To: Carl A Baltrunas <carl@X930.Tymnet>, Osman Guven <osman@X930.Tymnet>, Joe
	Smith <jms@X930.Tymnet> 
Cc: Craig Fletcher <fletcherc@X930.Tymnet> 
Subject: System 74's disk problem 

Around 11pm - got a call from Karen, the first attempt to copy the pack
bombed the system, had to start over.

Got on the system, ran full DSKCLN in check-out mode.  Only two files in
(TAPELIB) marked as bad, still had 24000 lost pages.

12:40am - Called data center, told them to deposit 1 in 30 and bring the
system up with a real FULL DSKCLN.  (Could not run TAKEIT because of network
problems.)

/JOE
From: Joe Smith <JMS@X930.Tymnet> (Liberty Street in Fremont 116-2512) 
Date: Sun, 17 Nov 85 21:20:28 PST 
To: Carl A Baltrunas <carl@X930.Tymnet>, Osman Guven <osman@X930.Tymnet>, Joe
	Smith <jms@X930.Tymnet> 
Cc: Craig Fletcher <fletcherc@X930.Tymnet> 
Subject: Hotline call for C57 

17-Nov-85 17:34/JMS
Contact:  Cupertino BLDG C, OPS, Karen, (408)446-7705, System C57

Symptom:  System dies in ONCE complaining about unit 15 off-line due to hardware
          errors, logical unit 5 missing from DSKB.  Operations called for
          software support in case problem was the same as "inconsistent pack
          set id".

Problem:  Advised them that problem sounded like hardware, and to try to the
          disk on a different drive.  Hardware called in.

Solution: Drive had a bad plug.  System answered at 18:49.


